### ISSUE TITLE
F5 Irules sourcetype is not being passed

### ISSUE THREAD

**Issue by kefrtelenor** [splunk/splunk-connect-for-syslog#1036]
Hi After we upgraded the SC4S to the newest version from version 1.56 to 1.62.2, it seems it is not able to pass the events as sourcetype=f5:bigip:ltm:http:irule but was passed as SC4S:unknown aka fallback sourcetype, after downgrading sc4s to 1.56 they were passed again as they should.
We have followed the guidelines in sending HSL aka syslogs from F5 in the documentation of the F5 addon https://docs.splunk.com/Documentation/AddOns/released/F5BIGIP/Setup

Also the splunk_metadata.csv also have the right attribute: f5_bigip_irule,index,f5

**Comment by rfaircloth-splunk** [comment]
Can you provide an example event for what does happen?

**Comment by kefrtelenor** [comment]
All LTM rules requests was not passed at all, but here is an example of an request which was not passed:
`<190>,f5_irule=Splunk-iRule-HTTP,src_ip=0.0.0.0,vip=0.0.0.0,http_method=GET,http_host=test.com:443,http_uri=/sharedfiles/upload/nav_files/ordrer/kontrakt/VerisOrderID_edit.asp?onlineOrdreID=3915860,http_url=test.com:443/testordre/testOrderID_edit.asp?onlineOrdreID=3915860,http_version=1.1,http_user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36",http_content_type=,http_referrer="https://test.com/testordre?OrdreID=3915860&CreateOrdre=True&KT=",req_start_time=2021/03/17 13:47:52,cookie="_ga _gid Kontrakter at_check TS2fb25577027 AMCV_32B74DE153EE86EE0A490D45%40AdobeOrg ASPSESSIONIDSQCQDDAQ TS01479295 s_cc utag_main _gcl_aw _gac_UA-63221604-1 AMCVS_32B74DE153EE86EE0A490D45%40AdobeOrg imp_st s_nr _fbp _scid s_ptc s_ppvl imp_sk test SB%5Ftest imp_uk actimo_app_sess imp_sl s_ppv s_vnum s_fid s_sq imp_nk dsv ADRUM",user=,virtual_server="/Legacy/test_Pool 0.0.0.0 80",res_start_time=2021/03/17 13:47:52,node=0.0.0.0,node_port=80,http_status=200,req_elapsed_time=20`

**Comment by rfaircloth-splunk** [comment]
this is misconfigured the host name should appear <190>$HOSTNAME,f5_irule
