### ISSUE TITLE
Docker Pull Rate Limit

### ISSUE THREAD

**Issue by I-Am-Buggy** [splunk/splunk-connect-for-syslog#1101]
This may be a podman/docker configuration issue, but since following the docs exactly led to this and it isn't mentioned anywhere I thought I would post here. I'm hitting a pull rate limit when trying to set this up on RHEL 8 using Podman:

Apr 09 10:19:35 <hostname> podman[41426]: Trying to pull docker.io/splunk/scs:latest...
Apr 09 10:21:46 <hostname> podman[41426]:   toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Apr 09 10:21:46 <hostname> podman[41426]: Error: Error initializing source docker://splunk/scs:latest: Error reading manifest latest in docker.io/splunk/scs: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Apr 09 10:21:46 <hostname> systemd[1]: sc4s.service: Control process exited, code=exited status=125
Apr 09 10:21:46 <hostname> systemd[1]: sc4s.service: Failed with result 'exit-code'.

I can login to docker using podman login docker and when running it manually according to the troubleshooting section the pulls all work and the system starts up correctly.  I cannot get it to perform the same way using the systemd unit file according to the directions found here: https://splunk-connect-for-syslog.readthedocs.io/en/master/gettingstarted/podman-systemd-general/

Any suggestions on a fix?

**Comment by rfaircloth-splunk** [comment]
This is an issue we should probably start raising in docs. While a sc4s deployment alone will never hit this limit all of the use of containers by your org with a common ip (nat) get a rate limit. The doc link shows the commands to "login" to docker hub moving you from the ip to the account limit even a free account resolves the limit as long as its not shared.

https://github.com/containers/podman/blob/master/docs/source/markdown/podman-login.1.md

**Comment by I-Am-Buggy** [comment]
That was the first thing I tried, which is how I got it to work correctly manually. It just doesn't work from systemd

[root@hostname ~]# podman login docker.io
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to docker.io

**Comment by rfaircloth-splunk** [comment]
The current containers are now published to ghcr.io which does not have a similar rate limit. The correct image reg is updated in docs
