### ISSUE TITLE
`SC4S_DEST_SPLUNK_INDEXED_FIELDS` is not honored 

### ISSUE THREAD

**Issue by abhinav-chittora** [splunk/splunk-connect-for-syslog#1125]
**Environment: -** 
```
docker version
Client:
 Version:           20.10.4
Server:
 Version:          20.10.4
```

**SC4S Version:** 
```
REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
splunk/scs   latest    8ec0fd765999   31 hours ago   520MB
```

**Issue:-** 
Even after setting SC4S_DEST_SPLUNK_INDEXED_FIELDS in env_file as follow, no additional indexed fields are visible in Splunk. 

**env_file:-** 
```
SPLUNK_HEC_URL=https://inputs-xxxxx.xxxxx.xxxx.cloud
SPLUNK_HEC_TOKEN=0ad2989a-xxxx-xxxx-xxxx-xxxxxxxxxxxx
#Uncomment the following line if using untrusted SSL certificates
SC4S_DEST_SPLUNK_HEC_DEFAULT_TLS_VERIFY=yes
SC4S_DEST_SPLUNK_HEC_TLS_VERIFY=1

#SC4S_DEST_SPLUNK_SC4S_METRICS_HEC=yes

SC4S_LISTEN_DEFAULT_TCP_PORT=514
#SC4S_LISTEN_DEFAULT_UDP_PORT=514
#SC4S_LISTEN_DEFAULT_RFC6587_PORT=601

### Section for TLS connections
#SC4S_SOURCE_TLS_ENABLE=yes
#SC4S_LISTEN_DEFAULT_TLS_PORT=6514
### Default TLS/TCP settings
SC4S_SOURCE_TCP_MAX_CONNECTIONS=2000
SC4S_SOURCE_TCP_IW_SIZE=20000000
SC4S_SOURCE_TCP_FETCH_LIMIT=2000
SC4S_IPV6_ENABLE=no

SC4S_DEST_GLOBAL_ALTERNATES=d_hec_debug
SC4S_DEST_SPLUNK_INDEXED_FIELDS=proto,destport
```

**Expected Output:-** 
After setting `SC4S_DEST_SPLUNK_INDEXED_FIELDS=proto,destport`, splunk should use 2 additional indexed fields. 

Do let me know if i need to add more details for debugging the issue.

**Comment by rfaircloth-splunk** [comment]
After replicating the config above I did see the additional fields however I noticed the default config is incorrect these should be enabled by default that will be in the next release.
![image](https://user-images.githubusercontent.com/35384120/115705127-2b9be600-a33a-11eb-8e36-9fc6e8837e60.png)

**Comment by rfaircloth-splunk** [comment]
Please confirm after restart this works
