### ISSUE TITLE
Request: support for Alsid for AD parser

### ISSUE THREAD

**Issue by dan-k-au** [splunk/splunk-connect-for-syslog#1128]
Requesting support for Alsid for AD syslog messages SC4S parser. There is a TA for Alsid for AD https://splunkbase.splunk.com/app/5173/ which should help.
Can someone kindly point me in the right direction to get this done and what you might need from me to make this happen? There is broad benefit to the community for this parser.

Can provide log samples if required.

**Comment by rfaircloth-splunk** [comment]
Yes log samples are always required

**Comment by dan-k-au** [comment]
Added 4 sample and de-sensitised syslog messages received using RAWMSG in SC4S: 

[Alsid_syslog.txt](https://github.com/splunk/splunk-connect-for-syslog/files/6431263/Alsid_syslog.txt)
