### ISSUE TITLE
Contributions: Correct Slack channel name

### ISSUE THREAD

**Issue by mkarlstrand-splunk** [splunk/splunk-connect-for-syslog#113]
https://github.com/splunk/splunk-connect-for-syslog/blob/master/CONTRIBUTING.md

Need to correct the Slack Channel name to use hyphens instead of underscores.

Project Discussion Forums
splunk-usergroups #splunk-connect-for-syslog

**Comment by rfaircloth-splunk** [comment]
Already fixed
