### ISSUE TITLE
Missing comma in spllunkfields.conf

### ISSUE THREAD

**Issue by labrown** [splunk/splunk-connect-for-syslog#1136]
I believe there is a missing comma character at this line:
https://github.com/splunk/splunk-connect-for-syslog/blob/2b30c711b4e53135444b485623bfc610ac2f19e2/package/etc/conf.d/conflib/_splunk/splunkfields.conf#L72

Should be:
                set("`meta_key`", value(".meta_key"));

I'd do a PR but I'm not allowed.

**Comment by rfaircloth-splunk** [comment]
oddly the comma here is optional. As a btw for a outside contributor to make a PR you need to first "fork" the repo then you can PR the project from the fork

**Comment by labrown** [comment]
Interesting.  I need to do more testing, and maybe I'm doing something not quite right, but my config files weren't working properly without the comma on that line.  I will test further and report back.

My "PR not allowed" issue isn't technical, but rather work policy.

**Comment by labrown** [comment]
You are correct sir. The comma is not required.  I must have had something else wrong in my config file when I ran across this not-a-bug.
