### ISSUE TITLE
Limit of 10 HEC destinations

### ISSUE THREAD

**Issue by back2root** [splunk/splunk-connect-for-syslog#1160]
It looks like, that SC4S is limited to 10 HEC destinations, even if more are specified.

If you have >10 Indexers and configure SC4S to directly send to the indexers for load balancing and performance reasons, you'll end in having max. 10 Indexers SC4S sending the data to.
As a result you'll have imbalanced data on your cluster.

**Comment by rfaircloth-splunk** [comment]
Beyond 10 indexes an actual load balancer should be used. SideKick is an excellent choice (free) or one of many other options

**Comment by back2root** [comment]
That sounds like an arbitrary unreasonable limit.
Adding a load balancer in between just adds additional complexity and latency.

I do not see an limit enforced by syslog-ng.

At least documentation must mention that limitation from sc4s.
