### ISSUE TITLE
Change default template to t_standard

### ISSUE THREAD

**Issue by kdorepos** [splunk/splunk-connect-for-syslog#1164]
The t_msg_only format strips the date/time and hostname from the syslog event. While this does decrease the size of the raw event, and thus reduces license usage, it has an unintended side effect of breaking some field extractions. While you can change the template for products, this does not work for custom IP/hostname filters when receiving on port 514. Changing the template to t_standard for all inputs keeps the integrity of the original event and reduces the likelihood of breaking field extractions.

**Comment by rfaircloth-splunk** [comment]
generally this indicates data that should be properly onboarded via an app_parser where this could be selected
