### ISSUE TITLE
Splunk SC4S with Palo Alto

### ISSUE THREAD

**Issue by Mopelola1** [splunk/splunk-connect-for-syslog#1184]
I have this issue with Sc4s to onboard Palo Alto logs. the logs were coming in well until recently when the logs started going to the scrc_fallback sourcetype. I need help with creating a custom filter for it. Thanks

**Comment by rfaircloth-splunk** [comment]
We need samples of the event from fallback the most common issue we have seen is misconfiguration where the source is changed to send ietf format to 514 instead of the 601 port

**Comment by Mopelola1** [comment]
Thanks. Here is the sample log:
**New Sample in sourcetype=fallback:**
PRI=13
MESSAGE=350 <14>1 2021-06-23T09:24:31-05:00 Panorama.xxxx.local - - - - 1,2021/06/23 09:24:31,000702285065,SYSTEM,monitoring,0,2021/06/23 09:24:31,,deviating-device, ,0,0,general,informational,"Deviating device: XXX-xxxxxxx-1, Serial: xxxxxxxxx6, Object: N/A, Metric: logging-rate, 
Value: 1",1647828,0x0,0,0,0,0,,Panorama,0,0,2021-06-23T09:24:31.000-05:00

**Old Sample in sourcetype=pan:system**
349 <14>1 2021-05-18T10:05:36-05:00 Panorama.xxxx.local - - - - 1,2021/05/18 10:05:36,000702285065,SYSTEM,monitoring,0,2021/05/18 10:05:36,,deviating-device, ,0,0,general,informational,"Deviating device: XXX-xxxxxxxxx-1, Serial: xxxxxxx1, Object: N/A, Metric: logging-rate, 
Value: 1",599191,0x0,0,0,0,0,,Panorama,0,0,2021-05-18T10:05:36.000-05:00

**Comment by rfaircloth-splunk** [comment]
This is a configuration issue on the palo side covered in docs. when using IETF (standard format) the port should be 601 not the legacy BSD 514 port

**Comment by Jaxjohnny** [comment]
hello.  
is this log the same? or a different issue?  all the logs are configured BSF format

the end of the message is after the beginning of the message

RAWMSG=255.255,,1,1,aged-out,1634,2411,2135,0,vsys1,FW04,from-policy,,,0,,0,,N/A,0,0,0,0,6d4f58b2-5528-474b-b85a-b371f6d82177,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-15T18:47:49.996+00:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 15 18:47:51 palo_alto_panarama_host 1,2022/08/15 18:47:51,012501003398,TRAFFIC,end,2561,2022/08/15 18:47:49,10.37.0.29,10.13.5.2,0.0.0.0,0.0.0.0,dns-services,local_domain\userone,,dns-base,vsys1,corp_trust,corp_dc,ae8.1852,ae8.1854,Panorama,2022/08/15 18:47:49,72223499,1,60737,53,0,0,0x19,udp,allow,317,92,225,2,2022/08/15 18:47:18,0,any,,7107085280655064783,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.
PRI=13
MESSAGE=255.255,,1,1,aged-out,1634,2411,2135,0,vsys1,FW04,from-policy,,,0,,0,,N/A,0,0,0,0,6d4f58b2-5528-474b-b85a-b371f6d82177,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-15T18:47:49.996+00:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 15 18:47:51 palo_alto_panarama_host 1,2022/08/15 18:47:51,012501003398,TRAFFIC,end,2561,2022/08/15 18:47:49,10.27.0.29,10.13.5.2,0.0.0.0,0.0.0.0,dns-services,local_domain\userone,,dns-base,vsys1,corp_trust,corp_dc,ae8.1852,ae8.1854,Panorama,2022/08/15 18:47:49,72223499,1,60737,53,0,0,0x19,udp,allow,317,92,225,2,2022/08/15 18:47:18,0,any,,7107085280655064783,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.
