### ISSUE TITLE
Documentation is missing info on how to set a proxy

### ISSUE THREAD

**Issue by orion84** [splunk/splunk-connect-for-syslog#1187]
As requested by Ryan on Slack, raising an issue for this.

I can't find in the docs how to set a proxy for SC4S to use for its outbound HTTP(S) traffic.

**Comment by rfaircloth-splunk** [comment]
syslog-ng uses the curl library add the following to  `env_file` to match your need
```
Without Authentication 
http_proxy="http://proxy.server:port"
https_proxy="https://proxy.server:port"

With Authentication 
 http_proxy="http://username:password@proxy.server:port"
 https_proxy="https://username:password@proxy.server:port"
```

Keep in mind the load over your proxy can be considerable monitoring your proxy is important if it becomes a key part of your logging infrastructure.
