### ISSUE TITLE
Splunk App for Infrastructure (SAI) is EOL

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#1188]
Splunk App for Infrastructure (SAI) is already End of Sale and is going EOL soon.

> To provide the best experience for Splunk users who want to monitor their infrastructure, Splunk is refocusing engineering efforts on our IT Essentials Work and IT Service Intelligence offerings. As a result, we will End Of Sale Splunk App for Infrastructure on April 30, 2021 and End of Life on August 14, 2022.

It is mentioned in [Getting Started/index](https://github.com/splunk/splunk-connect-for-syslog/blob/main/docs/gettingstarted/index.md#L62) along with the SAI add-on.

For new SC4S users it's probably not a good idea to recommend unsupported Splunk App and Add-ons that will require additional migration work in the near future.

For existing SC4S users a migration/upgrade path should be developed to move away from SAI.

**Comment by rfaircloth-splunk** [comment]
Thanks we just need to update docs the direct replacement for SAI is IT Essentials Work
