### ISSUE TITLE
unable to use stdout on centos8 baremetal

### ISSUE THREAD

**Issue by ora** [splunk/splunk-connect-for-syslog#1191]
Hello,

Running SC4S on baremetal CentOS.  It appears to be working fine, but Splunk catchall index is peppered with these errors and I can't figure out why.  Service starts up without errors and runs as root.  Followed install instructions to a tee.

`2021-07-09T15:43:31.743+00:00 sc4s syslog-ng 18199 - [meta sequenceId="59033"] Error opening file for writing; filename='/dev/stdout', error='No such device or address (6)'`

**Comment by rfaircloth-splunk** [comment]
The issue can be worked around by changing the file reference from stdout to a valid file stdout seems to be unavailable running from systemd
package/etc/conf.d/destinations/stdout.conf

**Comment by ora** [comment]
Can you elaborate .. changing it to what valid file?  What is it trying to write?  I get about 12k of these daily in the catch all index.  Thanks
