### ISSUE TITLE
Feature request: NetIQ to be part of Syslog-ng

### ISSUE THREAD

**Issue by raadheraadhe** [splunk/splunk-connect-for-syslog#1200]
Requesting support for new source for NETIQ Identity and Access Management syslogs. 
Sample raw logs have been attached.
[NetIQ_DEV.txt](https://github.com/splunk/splunk-connect-for-syslog/files/6827177/NetIQ_DEV.txt)

**Comment by rfaircloth-splunk** [comment]
This source appears to be sending non compliant syslog we need a pcap to resolve

**Comment by raadheraadhe** [comment]
[NetIQ_NovellAccessManager1.txt](https://github.com/splunk/splunk-connect-for-syslog/files/7018415/NetIQ_NovellAccessManager1.txt)

pcap is attached. thanks
