### ISSUE TITLE
Feature request: send Fortigate DLP events to "netdlp" index

### ISSUE THREAD

**Issue by obpedro** [splunk/splunk-connect-for-syslog#1201]
Fortigates have a DLP module to apply some DLP rules against data passing through the Fortigate. When enabled, these events look like the below:

`date=2021-07-15 time=13:04:15 devname="XXXXX" devid="XXXXX" eventtime=1626379456460651006 tz="-0700" logid="0954024577" type="utm" subtype="dlp" eventtype="dlp" level="notice" .......`

These events currently get (correctly) parsed with sourcetype=fgt_utm and go to index=netfw.

My request would be to add some type of config option to allow Fortigate events with subtype="dlp" to be stored in the "netdlp" index for easier searching and data segregation.

Thanks in advance,
Pedro

**Comment by rfaircloth-splunk** [comment]
you can use the compliance filter feature to do this use ```message('subtype="dlp"') as the filter condition
