### ISSUE TITLE
Any way to disable or reduce the stats from being logged?

### ISSUE THREAD

**Issue by ora** [splunk/splunk-connect-for-syslog#1210]
<html>
Hello, these come and are indexed in the fallback index every minute or more frequently, 80+ lines at a time.  Any way to reduce the frequency or disable these?

<body>

8/3/2112:20:34.000 PM | spl.sc4syslog.source.s_DEFAULT.processed=46183 spl.sc4syslog.src.network.s_DEFAULT0.0_0_0_0.processed=0 spl.sc4syslog.src.network.s_DEFAULT0.0_0_0_0.stamp=0 spl.sc4syslog.src.network.s_DEFAULT1.0_0_0_0.processed=0 spl.sc4syslog.src.network.s_DEFAULT1.0_0_0_0.stamp=0 spl.sc4syslog.src.network.s_DEFAULT2.0_0_0_0.processed=0 spl.sc4syslog.src.network.s_DEFAULT2.0_0_0_0.stamp=0 spl.sc4syslog.src.network.s_DEFAULT3.0_0_0_0.processed=44468 spl.sc4syslog.src.network.s_DEFAULT3.0_0_0_0.stamp=1627993232 spl.sc4syslog.center.received.processed=53504 spl.sc4syslog.filter.f_cisco_esa_authentication.matched=0 spl.sc4syslog.parser.p_leef_kv.discarded=0 spl.sc4syslog.filter.f_cisco_esa_http.matched=0 spl.sc4syslog.filter.f_cisco_esa_textmail.matched=0 spl.sc4syslog.parser.p_leef_devTime.discarded=0 spl.sc4syslog.parser.vendor_product_by_source.discarded=0 spl.sc4syslog.parser.p_cef_ts_rt.discarded=0 spl.sc4syslog.filter.f_msg_is_tcp_json.matched=0 spl.sc4syslog.src.syslog.s_DEFAULT5.0_0_0_0.processed=0 spl.sc4syslog.src.syslog.s_DEFAULT5.0_0_0_0.stamp=0 spl.sc4syslog.filter.f_is_rfc3164.matched=0 spl.sc4syslog.filter.f_cisco_parse_host.matched=0 spl.sc4syslog.parser.p_acs_event_time.discarded=0 spl.sc4syslog.parser.p_add_context_host.discarded=0 spl.sc4syslog.filter.f_cisco_esa_amp.matched=0
-- | --

</body>
</html>

**Comment by rfaircloth-splunk** [comment]
Yes https://splunk-connect-for-syslog.readthedocs.io/en/latest/sources/Splunk/#options switch to sending metrics as a metrics event rather than text event
