### ISSUE TITLE
Fireeye - Update filter for new source format

### ISSUE THREAD

**Issue by davidbattyJDS** [splunk/splunk-connect-for-syslog#1213]
Hi,

A new version of Fireeye is sending sylog in a different format to https://github.com/splunk/splunk-connect-for-syslog/pull/1049/files

Could you please update the filter to match this new format. (samples attached)

Thanks
[fireeye_samples.txt](https://github.com/splunk/splunk-connect-for-syslog/files/6936273/fireeye_samples.txt)

**Comment by rfaircloth-splunk** [comment]
This isn't new its just different the source can send CEF json and I think TSV (tab) of these the reliable format has been CEF the json format is often corrupt

**Comment by davidbattyJDS** [comment]
Thanks for the reply. The Fireeye SME has come back stating it needs to be kept json due to required additional fields that are not supported in CEF. 

Is it possible that existing parser can be amended to match on:

2021-07-26T09:47:48.965+00:00 10.00.000.00 fenotify-7752142.warning: {

**Comment by rfaircloth-splunk** [comment]
Yes this is something we can do I will put it on my list for the next week or so
