### ISSUE TITLE
Imperva Database Security event 

### ISSUE THREAD

**Issue by francly** [splunk/splunk-connect-for-syslog#1221]
Hi, I try to send the log from Imperva SecureSphere for database security, I have update it to forward to security index, however not happen.

`58 Aug  6 09:10 'Imperva Inc._SecureSphere'`

HEC debug log

`curl -k -u "sc4s HEC debug:$SC4S_DEST_SPLUNK_HEC_DEFAULT_TOKEN" "https://abc.com:8088/services/collector/event"
 -d '{"time":"1628237430.000","sourcetype":"imperva:waf","source":"sc4s","index":"netwaf","host":"localhost.localdomain","fields":{"sc4s_ven
dor_product":"Imperva Inc._SecureSphere","sc4s_syslog_format":"rfc3164","sc4s_syslog_facility":"local1","sc4s_proto":"TCP","sc4s_loghost":"
hosta","sc4s_fromhostip":"10.10.10.10","sc4s_destport":"514","sc4s_container":"8135dbe1d8a8","cef_version":"0","cef_severity":"High"
,"cef_name":"Custom Violation","cef_device_version":"13.5.0","cef_device_vendor":"Imperva Inc.","cef_device_product":"SecureSphere","cef_dev
ice_event_class":"Custom"},"event":"CEF: 0|Imperva Inc.|SecureSphere|13.5.0|Custom|Custom Violation|High|act=None…...........`

Splunk metadata csv

`cisco_ios,index,security

netwaf,index,security

nix_syslog,index,security`

**Comment by rfaircloth-splunk** [comment]
The first column of the config file is the vendor_product not the default name of the index so
```
Imperva Inc._SecureSphere,index,security
```
