### ISSUE TITLE
Request - Dell EMC Data Domain sourcetype

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1224]
Request assist for the sourcetype of above equipment as the log are appeared on the sc4s_fallback folder.
Any advice?
[2021-08-13R-hec.log](https://github.com/splunk/splunk-connect-for-syslog/files/6980827/2021-08-13R-hec.log)
[2021-08-12-hecR.log](https://github.com/splunk/splunk-connect-for-syslog/files/6980828/2021-08-12-hecR.log)

**Comment by rfaircloth-splunk** [comment]
Data domain is in these cases not sending syslog these events are simply the word "exit" This is improper from the source and would have very little value if mapped to a correct sourcetype. My suggestion is open a case with EMC to correct the issue at the source in this case. We often handle source side errors in sc4s in this case there is just very little to work with.
