### ISSUE TITLE
many http sessions, closed by server-reset

### ISSUE THREAD

**Issue by bennap** [splunk/splunk-connect-for-syslog#1233]
Statistics done on our environment (a SC4S on premise and a SplunkCloud instance) show us more than 1 billion a day of HTTP Sessions just for the flow between SC4S and SplunkCloud instance. Most of them are killed with Server-Reset in place of TCP-FIN.

If Server-reset seems to be on SplunkCloud side, is it possible to use longer HTTP Session to send data to our instance ? This is a lot of flow recorded in splunk for nothing.

**Comment by didier-splunk** [comment]
Hi Team,

I hope you are fine.

The issue is still going on version 1.92.1, is there any fixed coming?
