### ISSUE TITLE
Documentation:wrong Docker repository pointer

### ISSUE THREAD

**Issue by giraldomauricio** [splunk/splunk-connect-for-syslog#1243]
I noticed in the documentation, specifically for the service configuration, the Docker Repository points to:

ghcr.io/splunk/splunk-connect-for-syslog/container:1

Installing a recent SC4S, I noticed it was failing to start. Then I find out the repository is now:

splunk/scs

Changing it, fixed the issue, and let it start correctly.

**Comment by rfaircloth-splunk** [comment]
Is a firewall blocking this server?

**Comment by rfaircloth-splunk** [comment]
oh this was a facepalm moment, 1.91.18 fixes it
