### ISSUE TITLE
Silverpeak logs to SC4S-- help!

### ISSUE THREAD

**Issue by raventura** [splunk/splunk-connect-for-syslog#1246]
Hi All,

Has anyone ingested silverpeak logs into SC4S? can't seem to make it work to point events to destination index. We don't have silverpeak as sources that can be easily add the key, index/source, index/sourcetype name to spluink_metadata.csv. we used vendor_product_by_source.conf/csv to filter out snare logs to drop events and prevent it going to Splunk. tried this with silverpeak logs, but just can't direct the events to index.

![image](https://user-images.githubusercontent.com/89633109/131095924-2360de00-3d7a-43fa-a150-1f423f4b7e9c.png)

Thanks!

**Comment by rfaircloth-splunk** [comment]
We are happy to help onboard new sources but need to see the sources to help there is not enough data here to produce a app-parser which is required to enable vendor_product_by_source. Please get a pcap or capture the sc4s:fallback results from Splunk from a non prod system.

**Comment by jzcal8300** [comment]
I know this was 2 years old, was a parser created for this that could be shared? We are ingesting Silverpeak logs, but I don't believe I have the parser created correctly on SC4S.
