### ISSUE TITLE
two variable not align and document does not align

### ISSUE THREAD

**Issue by mshensg** [splunk/splunk-connect-for-syslog#1259]
found a minor error in code: 

conf.d/sc4slib/dest_hec/plugin.py line:45 & 47         **diskbuff_reliable** = True / False. 
However:
conf.d/sc4slib/dest_hec/plugin.jinja line:21         {%- if **reliable_diskbuff_enable** %}

so this feature will never been enabled as the difference in code. 

Also, in document (https://splunk.github.io/splunk-connect-for-syslog/main/) , it says SC4S_DEST_SPLUNK_HEC_DISKBUFF_DISKBUFSIZE however, the code takes SC4S_DEST_SPLUNK_HEC_{ group }_DISKBUFF_DISKBUFSIZE so it should be SC4S_DEST_SPLUNK_HEC_DEFAULT_DISKBUFF_DISKBUFSIZE assuming the group is DEFAULT. These other similar configurations should have the same effect. 

Also, from the code, it appears to be SC4S_DEST_SPLUNK_HEC_{ group }_DISKBUFF_MEMBUFSIZE is default as 163840000
SC4S_DEST_SPLUNK_HEC_{ group }_DISKBUFF_MEMBUFLENGTH is default as 60000
SC4S_DEST_SPLUNK_HEC_{ group }_DISKBUFF_DISKBUFSIZE is default to be volume space - 5GB and if the volume is smaller than 5GB, it will use 5GB. which means if volume space is 6GB, it will use 1GB. 

Hope this can help the user better configure the system.

**Comment by Jo-Ng** [comment]
This explained why it still growth to 14GB even when it configured to use max of 10GB space.
Hope to see this been correct by the team.

**Comment by rjha-splunk** [comment]
We will fix it in next release.
