### ISSUE TITLE
Configuration file format is newer than the current version config-version='3.34'

### ISSUE THREAD

**Issue by ora** [splunk/splunk-connect-for-syslog#1277]
Updated to 1.93.2 and now see this on startup:
syslog-ng-config: [2021-09-29T20:55:16.357143] WARNING: Configuration file format is newer than the current version, please specify the current version number (3.32) in the @version directive. syslog-ng will operate at its highest supported version in this mode; config-version='3.34'

Appears to be working fine so far.

 [meta sequenceId="2"] syslog-ng starting up; version='3.32.1'

**Comment by rfaircloth-splunk** [comment]
fixed in next release
