### ISSUE TITLE
disk buffer size limit not working

### ISSUE THREAD

**Issue by francly** [splunk/splunk-connect-for-syslog#1297]
Hi, I try to limit the disk buffer on 10GB  by configuring on env file however it's not working, currently 10GB and still growing, any idea?

env file
`SC4S_DEST_SPLUNK_HEC_DISKBUFF_ENABLE=yes
SC4S_DEST_SPLUNK_HEC_DISKBUFF_RELIABLE=yes
SC4S_DEST_SPLUNK_HEC_DISKBUFF_DISKBUFSIZE=10737418240
`

`@[DEV][_data] $ pwd
/path/volumes/splunk-sc4s-var/_data
[DEV][_data] $ du -hs syslog-ng*
1.2G    syslog-ng-00000.qf
1.2G    syslog-ng-00001.qf
1.2G    syslog-ng-00002.qf
1.2G    syslog-ng-00003.qf
1.3G    syslog-ng-00004.qf
1.2G    syslog-ng-00005.qf
1.2G    syslog-ng-00006.qf
1.2G    syslog-ng-00007.qf
1.2G    syslog-ng-00008.qf
1.2G    syslog-ng-00009.qf
0       syslog-ng.ctl
16K     syslog-ng.persist
4.0K    syslog-ng.pid

**Comment by francly** [comment]
This is the mount I use 

-v splunk-syslogconnect-var:/var/lib/syslog-ng -v /apps/syslogconnect/local:/etc/syslog-ng/conf.d/local:z -v /apps/syslogconnect/archive:/var/lib/syslog-ng/archive:z -v /apps/syslogconnect/tls:/etc/syslog-ng/tls:z -p 2514:514 -p 2514:514/udp -p 6514:6514 --env-file=/apps/syslogconnect/env_file --name syslogconnect ghcr.io/splunk/splunk-connect-for-syslog/container:1.99.0

**Comment by spccsp** [comment]
` 
#/opt/sc4s/env_file
#SC4S_DEST_SPLUNK_HEC_WORKERS=6
#Uncomment the following line if using untrusted SSL certificates
SC4S_DEST_SPLUNK_HEC_TLS_VERIFY=no
SC4S_DEST_SPLUNK_HEC_DISKBUFF_ENABLE=yes
SC4S_DEST_SPLUNK_HEC_DISKBUFF_RELIABLE=no
#SC4S_DEST_SPLUNK_HEC_DISKBUFF_MEMBUFSIZE=10241024 
#bytes

SC4S_DEST_SPLUNK_HEC_DISKBUFF_MEMBUFLENGTH=15000
SC4S_DEST_SPLUNK_HEC_DISKBUFF_DISKBUFSIZE=1024
#bytes
`

Tested with Splunk HEC disabled.

Trying to reduce the HEC workers with this parameter does not work. There are still 10 *.qf files created.
SC4S_DEST_SPLUNK_HEC_WORKERS=6

SC4S_DEST_SPLUNK_HEC_DISKBUFF_DISKBUFSIZE=1024
This above configuration seems to be ignored. With the above setting, it should be limited to 1MB max per qf (buffer) file. But the observation was that the disk buffer continued to grow beyond the 5MB per qf file mark in my test.  I am unable to test based on the default limit of 50GB per file.

I though it may have been the additional data that is in the Memory buffer and hence have set the following:
SC4S_DEST_SPLUNK_HEC_DISKBUFF_MEMBUFSIZE=10

The buffer continues to grow beyond the 1MB limit per file. (Over 5MB pef qf file)

**Comment by rfaircloth-splunk** [comment]
Resolved in V2 we will now use a 10GB default size and require specific choice by the admin to increase the size preventing conflict between queues when more than one destination is in use
