### ISSUE TITLE
Custom Ingestion Schemas

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#1299]
Feature request: We are interested in two new schemes for non OOB sourcetypes on SC4S. The new source types would be Raritan and Cisco Video Expressway. Trying to perform custom config of syslog data ingestion on SC4S for these source types.

Cisco Expressway server:
Model: EXPWY-1200-K9
Software version: X12.5.9

Raritan Model and firmware information.
Model: DSX2-8
Hardware Revision: 0x83
Firmware Version: 2.2.0.5.2131

Model: DSX2-16
Hardware Revision: 0x85
Firmware Version: 2.2.0.5.213

**Comment by rfaircloth-splunk** [comment]
The pcap attached was a word summary of packets not the actual data can you try again with -w to generate a pcap file

**Comment by rfaircloth-splunk** [comment]
For cisco express, this appears to be another packaging for cisco telepresence which is currently supported. The logs match our current samples if you find corner cases or additional events we need to handle we would be happy to address that. https://splunk.github.io/splunk-connect-for-syslog/main/sources/Cisco/#product-cisco-telepresence-video-communication-server-tvcs
