### ISSUE TITLE
Tanium log goes to fallback source

### ISSUE THREAD

**Issue by francly** [splunk/splunk-connect-for-syslog#1321]
Why the supported vendor tanium goes to fallback?

`PRI=13
MESSAGE=1197 <134>1 2021-11-03T07:56:46.784+00:00 HOSTA Tanium 27902 - [Tanium-Audit-Source@017472 object_id="97" audit_row_id="9998409" details="User: tanium; Session ID: 9662771; Authentication Type: User; Originated from SOAPPluginScheduler" creation_time="2021-11-01T00:36:52" modification_time="2021-11-01T00:36:52" last_modified_by="none" modifier_user_id="0" mod_user="{"id":0,"name":"none","domain":"","display_name":"","as_persona":null,"mod_persona":null,"group_id":null,"effective_group_id":null,"track_computer_id_flag":null,"track_computer_id_interval_seconds":null,"deleted_flag":null,"last_login":null,"modification_time":null,"creation_time":null,"active_session_count":null,"local_admin_flag":null,"locked_out":null,"owned_object_ids":null,"permissions":[],"personas":[],"roles":[],"metadata":[],"content_set_roles":[],"effective_content_set_privileges":[],"omitBlacklist":["roles","effective_group_id","content_set_roles","effective_content_set_privileges","owned_object_ids"],"omitWhitelist":[]}" mod_persona="null" type="0" object_name="" object_type_name="authentication_audit" type_name="CreateObject" audit_type="authentication_audit" Question="Tanium-Audit-Source"]`

**Comment by rfaircloth-splunk** [comment]
This is correctly formated RFC 5424 with IETF framing. Standard RFC5424 syslog uses port 601 while legacy BSD syslog uses 514. Change the port to 601 and it should work
