### ISSUE TITLE
Filter for Cisco Expressway

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#1324]
The Cisco TelePresence Video Communication Server Expressway data is falling into the sc4s fallback. I created a previous ticket, and the events are not being captured under the Cisco TelePresence Video Communication Server (TVCS) filter. Provided the sourcetypes and setup configurations below. PCAP file attached

Cisco Expressway server:
Model: EXPWY-1200-K9
Software version: X12.5.9

- vendor_product_by_source.csv
f_cisco_tvcs,sc4s_vendor_product,"cisco_tvcs"

-  vendor_product_by_source.conf
filter f_cisco_tvcs {
    #host("*cisco_tvcs*" type(glob))
    netmask(xxxxxxxxxx/xx)
};

 - splunk_metadata.csv
cisco_tvcs,index,xxxx-nw
cisco_tvcs,sourcetype,cisco:tvcs
[CiscoExpressway.zip](https://github.com/splunk/splunk-connect-for-syslog/files/7478553/CiscoExpressway.zip)

**Comment by techsystems-unix** [comment]
Good Afternoon,
Can someone please review this ticket to determine if its a in fact a bug? Per my ticket #1299, Cisco TelePresence Video Communication Server Expressway data logs match our current samples for the supported vendor, Cisco TelePresence Video Communication Server (TVCS). However, the data is in the fallback.

**Comment by rfaircloth-splunk** [comment]
Sorry for the delay on this I reviewed the pcap and have two findings. The events sent from the device are not syslog they are missing the required PRI from the beginning of the message. Second they are truncated at the udp packet boundary. I suggest changing from udp to tcp first, which may resolve the issue. With TCP grab a new pcap and open in wireshark if the (unknown) is still flagged please open a cisco support case
![image](https://user-images.githubusercontent.com/35384120/143028648-dee234a7-a94c-4e33-b5ae-0fae763428aa.png)

**Comment by techsystems-unix** [comment]
[ciscoexpressway2.zip](https://github.com/splunk/splunk-connect-for-syslog/files/7628606/ciscoexpressway2.zip)
We fixed Cisco syslog format issue. However, Splunk is not capturing error or warning logs from Splunk. We run mutiple failed login attempts and Splunk did not capture these logs. I have attached a new pcap file.

**Comment by techsystems-unix** [comment]
Any update?

**Comment by rfaircloth-splunk** [comment]
Thanks for the pcap it always helps in the .89.6 pcap the data is not syslog formatted see the missing PRI
![image](https://user-images.githubusercontent.com/35384120/145444452-20f606cd-25a7-4f64-ac6f-76fe9e5b4128.png)

In the working pcap you see correct syslog formatting
![image](https://user-images.githubusercontent.com/35384120/145444590-9b956777-333a-414b-ba72-2b9b208335ae.png)

when sending non syslog traffic to a syslog server the behavior is undefined this specific type of malformation will most likely result in data drops. Please work with cisco to identify why the one device is not conforming

**Comment by techsystems-unix** [comment]
Thank you. I will send this information out to the appropriate team now

**Comment by techsystems-unix** [comment]
Issue has been resolved with one of the servers not in syslog format. However, in the pcap file provided above "expresswayerror.zip", the issue is now related errors not being captured. In the pcap, the error is captured by the tcpdump. However, Splunk does not capture that error severity.

**Comment by techsystems-unix** [comment]
Hello. Is there anyone available to look at the pcap file provided below? In the pcap, the error is captured by the tcpdump. However, Splunk does not capture that error severity. Only informational severities are being flagged. 
[expresswayerror.zip](https://github.com/splunk/splunk-connect-for-syslog/files/7785420/expresswayerror.zip)

**Comment by techsystems-unix** [comment]
Hello. Is there anyone available to look at the pcap file provided below? In the pcap, the error is captured by the tcpdump. However, Splunk does not capture that error severity. Only informational severities are being flagged.
