### ISSUE TITLE
No documentation around custom log_paths

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-connect-for-syslog#1326]
Hi,
Awhile trying to setup custom log paths I'm not able to find any documentation around how to do this even though SC4S says its a native functionality.  Maybe I'm missing it but i've searched the repo and docs pretty throughly.

**Comment by rfaircloth-splunk** [comment]
Added doc in v2 branch
https://splunk.github.io/splunk-connect-for-syslog/next-major/destinations/
