### ISSUE TITLE
Request - Scality sourcetype

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1327]
Request assist for the sourcetype of above application as the log are appeared on the sc4s_fallback folder.
Any advice?

[Scality_Supervisor_v2.txt](https://github.com/splunk/splunk-connect-for-syslog/files/7503358/Scality_Supervisor_v2.txt)
[Scality_Node_v2.txt](https://github.com/splunk/splunk-connect-for-syslog/files/7503359/Scality_Node_v2.txt)

**Comment by Jo-Ng** [comment]
ANy suggestion or instruction document that I could DIY to temporary get it into correct path?

**Comment by rfaircloth-splunk** [comment]
Scality is a container based solution and should not be logging via syslog the Splunk Docker driver or the Splunk Connect for k8s are the better paths forward. If Scality was to log via syslog it would need to use structured 5424 format to be useful.

**Comment by Jo-Ng** [comment]
The current structure (RFC 3164) that Scality use need to run on "MicroK8s + Linux" or "Docker Compose"?
Alternative is use "RFC 5424" to run on "Podman + systemd"?
Is this correct?

**Comment by rfaircloth-splunk** [comment]
Scality is a a containerized solution using docker its improper to log from docker using syslog at all but especially improper to use RFC3164 which is "obsolete" docker is nearly 25 years more recent than this standard and 10 years more recent than RFC5424 which replaced 3164. Docker can log directly however sc4s will accept correctly formatted syslog what is being sent is not

**Comment by Jo-Ng** [comment]
@rfaircloth-splunk  Is this means even the events resided in "sc4s_fallback", it not necessary able to identifier by SC4S that configured run in Podman?

**Comment by rfaircloth-splunk** [comment]
The source is not sending valid syslog, and its architecturally wrong to use syslog from this source. Push back hard on the vendor
