### ISSUE TITLE
Alternative HEC destinations

### ISSUE THREAD

**Issue by realburns** [splunk/splunk-connect-for-syslog#1329]
Hi folks,

I dicovered some undocumented issues when I need to implement two or more alternative HEC destination. The first one is that you need to configure the follow variables with the complete setup of the HEC-URL e.g.:

SC4S_DEST_SPLUNK_HEC_FIRSTALT_URL=https://hec-host:8088/services/collector/event

That deviates from the definition of "SC4S_DEST_SPLUNK_HEC_DEFAULT_URL". Here you only need the definition of host and port.

The second problem is, that on some version in between the typo of d_hec_SOMEDESTINATION changed to lowercase d_hec_somedestination.

In the documentation it is mentinoned that you have to configure alternative destinations like this, d_hec_FOO:

SC4S_DEST_GLOBAL_ALTERNATES=d_hec_FIRSTALT,d_hec_SECONDALT
SPLUNK_HEC_ALT_DESTS=FIRSTALT,SECONDALT

SC4S_DEST_SPLUNK_HEC_FIRSTALT_URL=https://hec-host:8088/services/collector/event
SC4S_DEST_SPLUNK_HEC_FIRSTALT_TOKEN=cc3f96ac-ea43-4f87-b0b2-dd56ad5cc43b

SC4S_DEST_SPLUNK_HEC_SECONDALT_URL=https://hec-host:8088/services/collector/event
SC4S_DEST_SPLUNK_HEC_SECONDALT_TOKEN=f5af6abf-7d8f-4e54-bbe7-69fc93e6767c

#and if you need to use filtered alternative destinations you need that too:

SC4S_DEST_FOO_ALT_FILTER=f_nixtoprod
SC4S_DEST_FOO_FILTERED_ALTERNATES=d_hec_FIRSTALT

SC4S_DEST_FOO2_ALT_FILTER=f_nixtotest
SC4S_DEST_FOO2_FILTERED_ALTERNATES=d_hec_SECONDALT

BUT inside the container the configuration says:

destination d_hec_firstalt{
    http(
        url("https://hec-host:8088/services/collector/event")
        method("POST")
        log-fifo-size(180000000)
        workers(10)
        batch-lines(5000)
        batch-bytes(4096kb)
        batch-timeout(300)
        timeout(30)
        user_agent("sc4s/1.0 (events)")           
        headers("Authorization: Splunk cc3f96ac-ea43-4f87-b0b2-dd56ad5cc43b", "Connection: close")    
        persist-name("splunk_hecFIRSTALT")
        response-action(400 => drop, 404 => retry)   
        disk-buffer(
            mem-buf-length(6000)
            reliable(no)
            disk-buf-size(2510356428)            
        )
        tls(
            peer-verify(yes)
        )
        use-system-cert-store(yes)
        body('$(template t_splunk_hec_event_legacy)')
    );
};

destination d_hec_secondalt{
    http(
        url("https://hec-host:8088/services/collector/event")
        method("POST")
        log-fifo-size(180000000)
        workers(10)
        batch-lines(5000)
        batch-bytes(4096kb)
        batch-timeout(300)
        timeout(30)
        user_agent("sc4s/1.0 (events)")           
        headers("Authorization: Splunk f5af6abf-7d8f-4e54-bbe7-69fc93e6767c", "Connection: close")    
        persist-name("splunk_hecSECONDALT")
        response-action(400 => drop, 404 => retry)   
        disk-buffer(
            mem-buf-length(6000)
            reliable(no)
            disk-buf-size(2510356428)            
        )
        tls(
            peer-verify(yes)
        )
        use-system-cert-store(yes)
        body('$(template t_splunk_hec_event_legacy)')
    );
};

So d_hec_FIRSTALT and d_hec_SECONDALT are not known destinations and you have to lowercase them in the env_file.

I used the version 1.100.2 of SC4S.

Best regards

realburns

**Comment by rfaircloth-splunk** [comment]
Ressolved in v2 branch
