### ISSUE TITLE
null_queue events are going to sc4s:fallback

### ISSUE THREAD

**Issue by tomaschase** [splunk/splunk-connect-for-syslog#1330]
Hi, I found an issue at a customer when trying to null_queue events in order to reduce what is getting sent to Splunk. These events are ending up in the default index with the sourcetype of sc4s:fallback.

compliance_meta_by_source.conf
filter f_cisco_asa {
    "${fields.sc4s_vendor_product}" eq "cisco_asa"
    and message('419002: Duplicate TCP SYN')
};
filter f_cisco_ios {
    "${fields.sc4s_vendor_product}" eq "cisco_ios"
    and message('Duplicate TCP SYN')
};

compliance_meta_by_source.csv
f_cisco_asa,fields.sc4s_vendor_product,"null_queue"
f_cisco_ios,fields.sc4s_vendor_product,"null_queue"

**Comment by rfaircloth-splunk** [comment]
a new method of dropping events has been added to v2 that will be easier to use
