### ISSUE TITLE
Request - Tanium sourcetype

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1331]
Request assist for the sourcetype of above application as the log are appeared on the 

- sc4s_fallback when configured from Tanium Portal as Syslog RFC 5424
- sc4s_generic_json when configured from Tanium Portal as JSON format

Any advice?
[tanium_json_v2.txt](https://github.com/splunk/splunk-connect-for-syslog/files/7525720/tanium_json_v2.txt)
[tanium_rfc_v2.txt](https://github.com/splunk/splunk-connect-for-syslog/files/7525721/tanium_rfc_v2.txt)

**Comment by rfaircloth-splunk** [comment]
This one sat for a while without being looked at we need not get a pcap of this data
