### ISSUE TITLE
"sc4_container" is not properly extracted

### ISSUE THREAD

**Issue by ora** [splunk/splunk-connect-for-syslog#1337]
Config  "--name SC4S" seems to have no impact on sc4_container which shows the short hostname regardless of the container name.

**Comment by rfaircloth-splunk** [comment]
can you show your full env file. This seems to work in my lab

**Comment by ora** [comment]
I am probably misunderstanding something here ..  changing SC4SHOST to a static name seems to have no impact on the name "sc4s_container."

```
ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment SC4SHOST=MYNAME"

ExecStart=/usr/bin/podman run \
        -e "SC4S_CONTAINER_HOST=${SC4SHOST}" \
        -v "$SC4S_PERSIST_MOUNT" \
        -v "$SC4S_LOCAL_MOUNT" \
        -v "$SC4S_ARCHIVE_MOUNT" \
        -v "$SC4S_TLS_MOUNT" \
        --env-file=/opt/sc4s/env_file \
        --health-cmd="/healthcheck.sh" \
        --health-interval=10s --health-retries=6 --health-timeout=6s \
        --network host \
        --name SC4S \
        --rm $SC4S_IMAGE
```

**Comment by rfaircloth-splunk** [comment]
yes the "SC4SHOST" is mapped to the indexed field sc4s_loghost
the --name SC4S is the value used for sc4s_container

the "container" name is generally not unique for podman/docker deployments but is unique in k8s deployments
