### ISSUE TITLE
sc4s_syslog_severity not being send by default

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#1338]
Events do not have the field `sc4s_syslog_severity` set unless this field is statically set in `SC4S_DEST_SPLUNK_INDEXED_FIELDS=`.

Per the [documentation](https://splunk.github.io/splunk-connect-for-syslog/main/configuration/#splunk-hec-destination-configuration) this field should be sent by default.

**Comment by rfaircloth-splunk** [comment]
Fixed in 1.100.1
