### ISSUE TITLE
Support Arista Switches

### ISSUE THREAD

**Issue by olivierpas** [splunk/splunk-connect-for-syslog#1344]
Hello,

Can you please add arista switches as sourcetype on SC4S ? : 
Some logs as example : 

`2021-11-25T16:52:18+01:00 SWITCHNAME.domain.com Acl: %ACL-6-IPACCESS: list acl-internet Ethernet1 denied tcp xxx.xx.xx.xx(63751) -> xxx.xx.xx.xx(445)`

`2021-11-25T16:52:19+01:00 SWITCHNAME.domain.com IgmpSnooping: %IGMPSNOOPING-6-NO_IGMP_QUERIER: No IGMP querier detected in VLAN XXX. IGMP report received from xxx.xx.xx.36 on Port-ChannelX for xxx.xx.xx.109`

`2021-11-25T16:52:19+01:00 SWITCHNAME.domain.com IgmpSnooping: %IGMPSNOOPING-6-NO_IGMP_QUERIER: No IGMP querier detected in VLAN XXX. IGMP report received from xxx.xx.xx.36 on Port-ChannelX for xxx.xx.xx.109`

`2021-11-25T16:52:19+01:00 SWITCHNAME.domain.com Acl: %ACL-6-IPACCESS: list acl-xxx-1 Ethernet1 denied tcp xxx.xx.xx.xx(43167) -> xxx.xx.xx.xx(8750)`

`2021-11-25T16:52:19+01:00 SWITCHNAME.domain.com Acl: %ACL-6-IPACCESS: list acl-xxx-2 Ethernet5 denied tcp xxx.xx.xx.xx(1204) -> xxx.xx.xx.xx(5501)`

`2021-11-25T16:52:19.802098+01:00 SWITCHNAME.domain.com PortSec: %ETH-4-HOST_FLAPPING: Host 00:xx:xx:00:00:00 in VLAN XXX is flapping between interface Port-ChannelXX and interface Port-ChannelXX`

`2021-11-25T16:52:19+01:00 SWITCHNAME.domain.com PortSec: %ETH-4-HOST_FLAPPING: Host 00:xx:xx:00:00:00 in VLAN XXX is flapping between interface Port-ChannelXX and interface Port-ChannelXX`

Thank you in advance,

Regards,

**Comment by rfaircloth-splunk** [comment]
Release on next-major (beta) branch
