### ISSUE TITLE
Read the doc website is missing steps for creating microk8 cluster

### ISSUE THREAD

**Issue by rabrahamsplunk** [splunk/splunk-connect-for-syslog#1355]
On the following link https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/k8s-microk8s/ on the values.yaml config it does not explain how to expose the services to outside of the cluster. i.e if the documentation is followed we get to the point where SC4S is accessible from the Kubernetes server only (Telnetting clusterIP from kubernetes cluster). it is not accessible from outside of the cluster. Please make amendments to the doc so that we can setup kubernetes cluster and is accessible from everwhere on the network. 
Thanks

**Comment by rjha-splunk** [comment]
The documentation is updated for microk8s cluster, if you still notice the issue please raise/reopen the issue.
