### ISSUE TITLE
Require modify the Splunk Host field for Fortinet syslog integration

### ISSUE THREAD

**Issue by lgodoys** [splunk/splunk-connect-for-syslog#1356]
I was implemented SC4S to get all Fortinet appliances logs from syslog. But, by our side, we have implemented the Splunk Host field from Fortianalyzer, and, now, we have implemented over SC4S because of Splunk Senior Engineer to solve a randomly dropped logs. But, this new integration writes the host field with extracted devname from logs, and it's not possible to overwrite this field using a customized field.

I was trying to overwrite with these two filters, trying to find which one will overwrite the field, but none of these works

```
filter f_forti_host_fix_1 {
    host(<devname from logs>") or
    devname("<devname from logs>")
};

filter f_forti_host_fix_2 {
    netmask(<IP address from syslog event>)
```
I appreciate if it's possible to get some help to that

Kind regards

**Comment by rfaircloth-splunk** [comment]
Not sure I follow, can you show me a data sample with what is wrong?

**Comment by rfaircloth-splunk** [comment]
Closing issue, can reopen with more details

**Comment by rfaircloth-splunk** [comment]
could you attach a PCAP with a few messages that show the problem?
