### ISSUE TITLE
alternative syslog forward possibilities

### ISSUE THREAD

**Issue by fpereszlenyi** [splunk/splunk-connect-for-syslog#1359]
Hi,

I looked through the documentation, but found no way to send incoming syslog messages to an alternate syslog server in addition to Splunk HEC forwarding...
Is this possible to solve this somehow, can you please add  this feature?

Thx!

**Comment by obivon** [comment]
Does creating a 2nd destination (EX: d_syslog-forwarder) then adding both destinations to your log path not work?  I haven't tried that with SC$S, but sending messages to multiple destinations is a basic feature of syslog-ng.

**Comment by rfaircloth-splunk** [comment]
Additional ease of use for forwarding have been added to the v2 beta. Take a look at the pre-release doc
https://splunk.github.io/splunk-connect-for-syslog/next-major/destinations/
