### ISSUE TITLE
PaloAlto Firewall Filters pan:config

### ISSUE THREAD

**Issue by Mosstrow** [splunk/splunk-connect-for-syslog#1382]
Hello,

We are sending logs from Panorama using syslog method to SC4S. 
But its not able to parse Host information correctly when an audit comment in a firewall rule is added for sourcetype pan:config
SC4S detect the comment as hostname.

Sample payload:
These don't work and match the Host: mosstrow-21012022-rule1
```
1,2022/01/21 13:04:07,000702964134,CONFIG,1,13836,2022/01/21 13:04:07,192.168.10.1,,audit-commit,Mosstrow,Web,Succeeded, device-group  VS-TEST pre-rulebase security rules  RULE1,100380,0x8000000000000000,0,0,0,0,,PALOALTO,14,Mosstrow-21012022-rule1,0,2022-01-21T13:04:07.000+01:00
1,2022/01/21 12:52:14,000702964134,CONFIG,0,0,2022/01/21 12:52:14,192.168.10.1,,edit,Mosstrow,Web,Succeeded, device-group  VS-TEST pre-rulebase security rules  RULE1,100363,0x8000000000000000,0,0,0,0,,PALOALTO,14,Mosstrow-21012022-rule1 ,0,2022-01-21T12:52:14.000+01:00
```

This one works well:
`1,2022/01/21 13:03:13,000702964134,CONFIG,0,0,2022/01/21 13:03:13,192.168.10.1,,commit-and-push,Mosstrow,Web,Succeeded,,100379,0x8000000000000000,0,0,0,0,,PALOALTO,0,,0,2022-01-21T13:03:13.000+01:00`

Thanks

**Comment by rfaircloth-splunk** [comment]
The event format you have does not appear to match the documentation here I belive it can be customized perhaps it has been or is using an older default. https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/config-log-fields.html 

Please converse with palo support and share anything you learn

**Comment by rfaircloth-splunk** [comment]
Thanks once we know the proper way to handle this we can update
