### ISSUE TITLE
Feature Request: Use a Secret for HEC Token

### ISSUE THREAD

**Issue by kurtismullins** [splunk/splunk-connect-for-syslog#1404]
This is a two-part feature request related to the security of the HEC Token:

1. The token should be stored in a secret. It can be mounted from the StatefulSet as an environment variable by simply referencing the secret.
2. Allow referencing your own secret. Storing the token using plain-text in `values.yaml` and then committing it to a git repository has potential security implications.

If I am overlooking something or there is an obvious work-around, then feel free to share that information and close this issue.

Thanks!

**Comment by rfaircloth-splunk** [comment]
Agree will look at this post 2.0

**Comment by satellite-no** [comment]
@kurtismullins 
Work around would be using CI/CD pipeline with the secret as a variable in the pipeline. This way when its deployed the text is replaced, sanitary git repo and yet its auto included in the CD pipeline.

**Comment by kurtismullins** [comment]
@satellite-no 

This may be a valid work-around for some environments, agreed. Thank you for that suggestion!

Unfortunately, we don't have a good place in our pipeline to inject a token from a vault. Even if we did, I would feel much more comfortable storing this token as a Kubernetes Secret than as plain-text within a ConfigMap.
