### ISSUE TITLE
Issue with Receive Buffer in Kubernetes

### ISSUE THREAD

**Issue by kurtismullins** [splunk/splunk-connect-for-syslog#1406]
I have deployed SC4S. Upon startup, the container logs show the follow messages:

```
The kernel refused to set the receive buffer (SO_RCVBUF) to
the requested size, you probably need to adjust buffer related kernel
parameters; so_rcvbuf='17039360', so_rcvbuf_set='425984'
```

[This document suggests changing that on the host side](https://github.com/splunk/splunk-connect-for-syslog/blob/1ab884efc6a123b2baec2eae9e438f829bf1b548/docs/troubleshooting/troubleshoot_SC4S_server.md#sc4skernel-udp-input-buffer-settings).

Personally, I don't want to modify anything on the host-side if at all possible due to the way we configure our fleet of clusters. I also assume that most who use Kubernetes through cloud providers (e.g. GKE, AWS, etc...) cannot make this change to begin with.

Instead, is it possible to reduce that value through the helm chart?

**Comment by rfaircloth-splunk** [comment]
Its not possible to reduce the size in the helm chart today and avoid the warning however the buffer in use will be the max as limited by the OS a small buffer does limit the ability to handle bursts of udp data which may cause drops

**Comment by kurtismullins** [comment]
I wouldn't mind it if it it was simply a warning. Feel free to double-check me, but I believe it was causing the container to fail to startup completely / health-checks passing.

**Comment by rfaircloth-splunk** [comment]
Sorry missed the response but this is just a warning if it's failing to start it's something else
