### ISSUE TITLE
For Syslog port number openssl command is not showing the certificates 

### ISSUE THREAD

**Issue by uthaya26** [splunk/splunk-connect-for-syslog#1425]
We have configured the splunk with ssl enabled and properly certificate mapped.  Then when we enable syslog with TCP port number (e.g.7100), it configured and start listening. When we try to connect using openssl command its not showing the certificate which we configured on the splunk server. 

Below command ran on the same box.  It shows connected, but the certs are not showing. 
openssl s_client -connect 192.168.10.214:7100 -showcerts

**Comment by rfaircloth-splunk** [comment]
please share config with sensitive values masked
