### ISSUE TITLE
Support Cyber Ark Enterprise Password Vault

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-connect-for-syslog#143]
Samples Needed

**Comment by perditi0nspam** [comment]
Here is a sample from the CyberArk website:

[CyberArk PIM syslog format](https://docs.mcafee.com/bundle/enterprise-security-manager-data-sources-configuration-reference-guide/page/GUID-9295FD11-6C92-4878-85CE-4DE34CF5A011.html)
