### ISSUE TITLE
Add Juniper junos switch

### ISSUE THREAD

**Issue by olivierpas** [splunk/splunk-connect-for-syslog#1430]
Hello,

Can you please add juniper:junos:switch as sourcetype on SC4S ? :
Some logs as example :

`mgd[71026]: UI_NETCONF_CMD: User 'myusername' used NETCONF client to run command 'get-lldp-neighbors-information'`
`mgd[75048]: UI_LOGOUT_EVENT: User 'myusername' logout`
`mgd[75048]: UI_JUNOSCRIPT_CMD: User 'myusername' used JUNOScript client to run command 'get-software-information'`

`dot1xd[1877]: DOT1XD_USR_AUTHENTICATED: Custom_log MAC-RADIUS User 001b4f6f728c logged in MacAddress 00:1b:4f:6f:72:8c interface ge-4/0/16.0 vlan telephone-net`

`2022-02-03T22:20:14.714Z MySWITCHNAME1 dot1xd[1877] Custom_log MAC-RADIUS User 001b4f6f7496 logged in MacAddress 00:1b:4f:6f:74:96 interface ge-5/0/41.0 vlan telephone-net`

`dot1xd[1877]: DOT1XD_USR_AUTHENTICATED: Custom_log MAC-RADIUS User 001b4f6f7496 logged in MacAddress 00:1b:4f:6f:74:96 interface ge-5/0/41.0 vlan telephone-net`

`rpd[1848]: RPD_IFD_NOTIFICATION: EVENT <Bandwidth UpDown> ge-0/0/6 index 1306 <Up Broadcast Multicast> address #0 88.d9.8f.89.f6.9`

`rpd[1848]: RPD_IFL_NOTIFICATION: EVENT <UpDown> ge-0/0/6.0 index 1103 <Up Broadcast Multicast> address #0 88.d9.8f.89.f6.9

`mcsnoopd[1879]: RPD_IFD_NOTIFICATION: EVENT <Bandwidth UpDown> ge-0/0/6 index 1306 <Up Broadcast Multicast> address #<0> <00:01:07:01:06:01>`

`mcsnoopd[1879]: RPD_IFL_NOTIFICATION: EVENT <UpDown> ge-0/0/6.0 index 1103 <Up Broadcast Multicast> address #<0> <00:01:07:01:06:01>`

`dot1xd[1877]: DOT1XD_USR_AUTHENTICATED: Custom_log MAC-RADIUS User f434f0e4b418 logged in MacAddress f4:34:f0:e4:b4:18 interface ge-0/0/6.0 vlan employee-vlan-0517`

`rpd[1848]: RPD_IFL_NOTIFICATION: EVENT <UpDown> ge-0/0/6.0 index 1103 <Broadcast Multicast> address #0 88.d9.8f.89.f6.9`

`dot1xd[1877]: DOT1XD_USR_SESSION_DISCONNECTED: Dot1x User f434f0e4b418 session with MacAddress f4:34:f0:e4:b4:18 interface ge-0/0/6.0 vlan (null) disconnected`

`dot1xd[1877]: DOT1XD_AUTH_SESSION_DELETED: Dot1x User f434f0e4b418 session with MacAddress f4:34:f0:e4:b4:18 interface ge-0/0/6.0 vlan (null) deleted`

`mcsnoopd[1879]: RPD_IFL_NOTIFICATION: EVENT <UpDown> ge-0/0/6.0 index 1103 <Broadcast Multicast> address #<0> <00:01:07:01:06:01>`

`rpd[1848]: RPD_IFD_NOTIFICATION: EVENT <UpDown> ge-0/0/6 index 1306 <Broadcast Multicast> address #0 88.d9.8f.89.f6.9`

`mcsnoopd[1879]: RPD_IFD_NOTIFICATION: EVENT <UpDown> ge-0/0/6 index 1306 <Broadcast Multicast> address #<0> <00:01:07:01:06:01>`

`dot1xd[1877]: DOT1XD_USR_AUTHENTICATED: Custom_log MAC-RADIUS User f434f0e4b418 logged in MacAddress f4:34:f0:e4:b4:18 interface ge-0/0/6.0 vlan employee-vlan-0517`

`2022-02-03T22:20:03.550Z MySWITCHNAME1 dot1xd[1877] Dot1x User No User session with MacAddress 98:10:e8:f2:8d:2d interface ge-3/0/1.0 vlan (null) deleted`

`2022-02-03T22:20:03.545Z MySWITCHNAME1 dot1xd[1877] MAC-RADIUS User 9810e8f28d2d session with MacAddress 98:10:e8:f2:8d:2d interface ge-3/0/1.0 vlan 28 disconnected`

`2022-02-03T22:20:02.256Z MySWITCHNAME1 dot1xd[1877] Custom_log MAC-RADIUS User d47856b41719 logged in MacAddress d4:78:56:b4:17:19 interface ge-6/0/39.0 vlan telephone-net`

`2022-02-03T22:20:02.253Z MySWITCHNAME1 dot1xd[1877] Custom_log MAC-RADIUS User 3cb15b4b5fd2 logged in MacAddress 3c:b1:5b:4b:5f:d2 interface ge-3/0/29.0 vlan telephone-net`

For example mgd[71026] get the sourcetype nix:log

Thank you in advance,

Regards,

**Comment by rfaircloth-splunk** [comment]
It looks like some of these may be used by other juniper products such as "UI_JUNOSCRIPT_CMD" is also used by the router/firewall is there a strong need for two source types or can we use the main juniper source type "juniper:junos:firewall:structured" I realize this means its more than firewall but seems appropriate

**Comment by olivierpas** [comment]
TCPDUMP result using structured format :
` Msg: 1 2022-02-07T09:01:32.077Z MySWITCHNAME1 rpd 14783 RPD_IFD_NOTIFICATION [junos@2636.1.1.1.4.63.9 state="UpDown" interface-name="ge-5/0/43" interface-index="803" message="<Up Broadcast Multicast> address #0 88.d9.8f.89.d3.4e"] EVENT <UpDown> ge-5/0/43 index 803 <Up Broadcast Multicast> address #0 88.d9.8f.89.d3.4e
`

` Msg: 1 2022-02-07T09:01:38.024Z MySWITCHNAME1 dot1xd 14788 DOT1XD_USR_AUTHENTICATED [junos@2636.1.1.1.4.63.9 user-type="MAC-RADIUS" username="54ec2f359a90" mac-address="54:ec:2f:35:9a:90" interface-name="ge-2/0/0.0" vlan-name="employee-vlan-0000"] Custom_log MAC-RADIUS User 54ec2f359a90 logged in MacAddress 54:ec:2f:35:9a:90 interface ge-2/0/0.0 vlan employee-vlan-9999`

` Msg: 1 2022-02-07T09:01:07.105Z MySWITCHNAME1 dot1xd 1872 DOT1XD_USR_SESSION_DISCONNECTED [junos@2636.1.1.1.2.63 user-type="MAC-RADIUS" username="509a4c4b4b6d" mac-address="50:9a:4c:4b:4b:6d" interface-name="ge-6/0/20.0" vlan-name="235"] MAC-RADIUS User 509a4c4b4b6d session with MacAddress 50:9a:4c:4b:4b:6d interface ge-6/0/20.0 vlan 235 disconnected`

**Comment by rfaircloth-splunk** [comment]
fixed on v2 branch
