### ISSUE TITLE
Pan Threat logs are getting misparsed to sourcetype=ubnt - Probably useragent field issue

### ISSUE THREAD

**Issue by Rajkumar-talion** [splunk/splunk-connect-for-syslog#1438]
Hello,

We are sending logs to SC4S from Palo alto and then to Splunk cloud.
I can see there are events being misparsed into sourcetype=ubnt, they are Paloalto THREAT logs.
Below are the 2 logs which captured the SC4S host.

====================================

<14>Feb  4 09:59:53 ASD.xxx.com 1,2022/02/04 09:59:52,0123456,THREAT,url,2560,2022/02/04 09:59:33,172.16.8.52,204.79.197.219,198.101.98.202,204.79.197.219,Inside to Outside xxx and xxx - xxx,domain\user,,ssl,vsys1,Inside,Outside,ethernet1/3,ethernet1/1,Log-Forward-Profile,2022/02/04 09:59:33,36336,1,52305,443,49719,443,0x40f400,tcp,alert,"edge.microsoft.com/",(9999),computer-and-internet-info,informational,client-to-server,649741951,0xa000000000000000,172.16.0.0-172.31.255.255,United States,,,0,,,0,,,,,,,,0,504,385,0,0,,hostname1,,,,,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,4294967295,,"computer-and-internet-info,low-risk",7e8737f3-4ceb-426b-9fa3-c3cc09f06179,0,,0.0.0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2022-02-04T09:59:33.223-06:00,,,,encrypted-tunnel,networking,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no
<14>Feb  4 09:59:53 ASD.xxx.com 1,2022/02/04 09:59:52,0123456,THREAT,url,2560,2022/02/04 09:59:33,172.16.6.221,17.253.17.205,198.101.98.202,17.253.17.205,Inside to Outside xxx and xxx - xx,,,web-browsing,vsys1,Inside,Outside,ethernet1/3,ethernet1/1,Log-Forward-Profile,2022/02/04 09:59:33,45359,1,50079,80,33451,80,0x40f000,tcp,alert,"captive.apple.com/hotspot-detect.html",(9999),computer-and-internet-info,informational,client-to-server,649741952,0xa000000000000000,172.16.0.0-172.31.255.255,United States,,text/html,0,,,1,CaptiveNetworkSupport-418.80.2 wispr,,,,,,,0,504,385,0,0,,hostname1,,,,get,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,4294967295,,"computer-and-internet-info,low-risk",7e8737f3-4ceb-426b-9fa3-c3cc09f06179,0,,0.0.0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2022-02-04T09:59:33.849-06:00,,,,internet-utility,general-internet,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,web-browsing,no,no

====================================

The 1st event gets parsed properly and sourcetyped to pan: threat
The 2nd is getting misparsed and sourcetyped to ubnt.

I observed that there is space in the user agent ( 43rd field in the raw event ), I removed the space and sent it to SC4S again, this time both events got parser properly. Below is the sample ( basically i just removed the space of the 2nd event in the above sample )

====================================

<14>Feb  4 09:59:53 ASD.xxx.com 1,2022/02/04 09:59:52,0123456,THREAT,url,2560,2022/02/04 09:59:33,172.16.8.52,204.79.197.219,198.101.98.202,204.79.197.219,Inside to Outside xxx and xxx - xxx,domain\user,,ssl,vsys1,Inside,Outside,ethernet1/3,ethernet1/1,Log-Forward-Profile,2022/02/04 09:59:33,36336,1,52305,443,49719,443,0x40f400,tcp,alert,"edge.microsoft.com/",(9999),computer-and-internet-info,informational,client-to-server,649741951,0xa000000000000000,172.16.0.0-172.31.255.255,United States,,,0,,,0,,,,,,,,0,504,385,0,0,,hostname1,,,,,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,4294967295,,"computer-and-internet-info,low-risk",7e8737f3-4ceb-426b-9fa3-c3cc09f06179,0,,0.0.0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2022-02-04T09:59:33.223-06:00,,,,encrypted-tunnel,networking,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no
<14>Feb  4 09:59:53 ASD.xxx.com 1,2022/02/04 09:59:52,0123456,THREAT,url,2560,2022/02/04 09:59:33,172.16.6.221,17.253.17.205,198.101.98.202,17.253.17.205,Inside to Outside xxx and xxx - xx,,,web-browsing,vsys1,Inside,Outside,ethernet1/3,ethernet1/1,Log-Forward-Profile,2022/02/04 09:59:33,45359,1,50079,80,33451,80,0x40f000,tcp,alert,"captive.apple.com/hotspot-detect.html",(9999),computer-and-internet-info,informational,client-to-server,649741952,0xa000000000000000,172.16.0.0-172.31.255.255,United States,,text/html,0,,,1,CaptiveNetworkSupport-418.80.2wispr,,,,,,,0,504,385,0,0,,hostname1,,,,get,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,4294967295,,"computer-and-internet-info,low-risk",7e8737f3-4ceb-426b-9fa3-c3cc09f06179,0,,0.0.0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0,2022-02-04T09:59:33.849-06:00,,,,internet-utility,general-internet,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,web-browsing,no,no

====================================

Also, when I ingested the data directly without removing the space in the user agent field, I can see the events are getting parsed properly. The parsing issue happens only when we are sending the logs to SC4S.

PA Addon Version - 7.0.3
https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields.html

Thanks,
Raj

**Comment by rfaircloth-splunk** [comment]
investigating

**Comment by Rajkumar-talion** [comment]
Thanks for the input. port-level changes require effort from a different team. I will check whether that can be done.
But, out of curiosity, I passed 2 events in this bug, if this is related to the leading zero in the Syslog header for the time format, could you please let me know, how SC4S was able to parse the 1st event properly not the 2nd one.

**Comment by rfaircloth-splunk** [comment]
the trigger for the bug is the date plus failing to match a regex, with the correct data it won't hit that code path. I did confirm it works on v2 beta where we have modified the entry to the parsing logic to be a bit "safer" when formats are variable
