### ISSUE TITLE
Add netscout Arbor Edge Defense (aed)

### ISSUE THREAD

**Issue by Mosstrow** [splunk/splunk-connect-for-syslog#1443]
Hello,

Can you please add netscout:aed as sourcetype on SC4S ?
Documentation: https://github.com/arbor/TA_netscout_aed

Some logs as example :

CEF Mode (recommended in TA AED docs): 
`<25>Feb  8 12:00:30 DeviceDDOS01 CEF:0|NETSCOUT|Arbor Edge Defense|6.8.1.0|Invalid Packets|Blocked Host|5|rt=1644318030000 src=101.132.187.47 dpt=0 cn2=114 proto=TCP dst=8.8.8.8 spt=0 cs2Label=Protection Group Name cn2Label=Protection Group ID cs2=Test_VPN
`
`<25>Feb  8 12:00:30 DeviceDDOS01 CEF:0|NETSCOUT|Arbor Edge Defense|6.8.1.0|Blocked Countries|Blocked Host|5|rt=1644318030000 src=122.165.221.3 dpt=5001 cn2=84 proto=TCP dst=8.8.8.8 spt=46865 cs2Label=Protection Group Name cn2Label=Protection Group ID cs2=Test2_VPN
`
`<25>Feb  8 12:00:30 DeviceDDOS01 CEF:0|NETSCOUT|Arbor Edge Defense|6.8.1.0|Change Log|Change Log|5|msg=Username: User2, Subsystem: Notification Sets, Message: Edited the syslog notification for destination 8.8.8.8.
`
`<25>Feb  8 12:07:30 DeviceDDOS01 CEF:0|NETSCOUT|Arbor Edge Defense|6.8.1.0|TCP Connection Limiting|Blocked Host|5|rt=1644318450000 src=190.178.81.126 dpt=25 cn2=109 proto=TCP dst=8.8.8.8 spt=8477 cs2Label=Protection Group Name cn2Label=Protection Group ID cs2=Test_MAIL
`
sourcetype detected = cef

Legacy Mode:
`<25>Feb  8 11:43:30 DeviceDDOS01  arbor-networks-aps:Blocked Host: Blocked host 111.80.42.119 at 11:43 by Invalid Packets using TCP/22 (SSH) destination 8.8.8.8 source port 33239,EPOCH: 1644317010,PGID: 9,PGNAME: Default Protection Group,URL: https://DeviceDDOS01/summary/
`
`<25>Feb  8 11:43:30 DeviceDDOS01  arbor-networks-aps:Blocked Host: Blocked host 81.150.125.45 at 11:43 by Blocked Countries using UDP/8081 (TPROXY) destination 8.8.8.8 source port 1796,EPOCH: 1644317010,PGID: 94,PGNAME: Test_GENERIC,URL: https://DeviceDDOS01/summary/
`
`<25>Feb  8 11:49:30 DeviceDDOS01  arbor-networks-aps:Blocked Host: Blocked host 32.81.35.6 at 11:48 by Malformed HTTP Filtering using TCP/80 (HTTP) destination 8.8.8.8 source port 40629,EPOCH: 1644317310,PGID: 9,PGNAME: Default Protection Group,URL: https://DeviceDDOS01/summary/
`
sourcetype detected =  nix:syslog

Here a screenshot of log configuration
![Arbor2](https://user-images.githubusercontent.com/47419739/152976761-c7914c96-1cbe-4ef8-a7eb-491a050f77b3.JPG)

Thank you in advance,

Regards,

**Comment by rfaircloth-splunk** [comment]
Released on v2 branch

**Comment by Mosstrow** [comment]
Hello,

The regex of the stanza [syslog_headers] in the transforms.conf of netscout TA doesn't match with the log due to first fields removed by SC4S
https://github.com/arbor/TA_netscout_aed/blob/master/default/transforms.conf

Here is a sample of logs:
`<25>Apr 26 08:48:30 HOSTDDOS01 CEF:0|NETSCOUT|Arbor Edge Defense|6.8.1.0|Blocked Countries|Blocked Host|5|rt=1650955710000 src=27.198.9.1 dpt=81 cn2=53 proto=TCP dst=8.8.8.8 spt=60661 cs2Label=Protection Group Name cn2Label=Protection Group ID cs2=PROTECTION_GENERIC`

Splunk RAW message:
`0|NETSCOUT|Arbor Edge Defense|6.8.1.0|Blocked Countries|Blocked Host|5|rt=1650955710000 src=27.198.9.1 dpt=81 cn2=53 proto=TCP dst=8.8.8.8 spt=60661 cs2Label=Protection Group Name cn2Label=Protection Group ID cs2=PROTECTION_GENERIC`

Netscout Regex:
`REGEX = (?<device_hostname>\b\S+(?=\s\w{3,4}:\d))\s+(?<syslog_format>\b(CEF|LEEF)\b)\:(?<syslog_format_version>\d+|\d+\.\d+)\|(?<device_vendor>\bNETSCOUT\b)\|(?<device_product>\w+\s+\w+\s+\w+)\|(?<device_product_version>[^\|]+)\|(?<device_event_class_id>[^\|]+)(\|(?<alert_type>[^\|]+)\|(?<severity>\d{1,2}))?\|(?<msg>(rt=|msg=).+)$`

Could you please adapt SC4S side to match with netscout TA ?

Temporary fix, I replaced the regex in netscout TA to:
`(?<syslog_format_version>\d+|\d+\.\d+)\|(?<device_vendor>\bNETSCOUT\b)\|(?<device_product>\w+\s+\w+\s+\w+)\|(?<device_product_version>[^\|]+)\|(?<device_event_class_id>[^\|]+)(\|(?<alert_type>[^\|]+)\|(?<severity>\d{1,2}))?\|(?<msg>(rt=|msg=).+)$`

Thanks
