### ISSUE TITLE
New Source: HP - Software: 7.1.070 Release 5106p03

### ISSUE THREAD

**Issue by gbecker-splunk** [splunk/splunk-connect-for-syslog#1451]
Vendor: HP
Software: 7.1.070 Release 5106p03
Software Company: comware

<189>Jan 27 14:13:39 2022 Glas_2ndFlr_HP1950-SW8 (Stack) %%10WEB/5/LOGIN: admin-af@tii.local logged in from 10.176.11.78.

**Comment by rfaircloth-splunk** [comment]
this was included in v2.0.0
