### ISSUE TITLE
New Source: APC - Software APC Schneider Electric Firmware: ID18UPS 09.3

### ISSUE THREAD

**Issue by gbecker-splunk** [splunk/splunk-connect-for-syslog#1453]
Vendor: APC
Firmware: ID18UPS 09.3
Software: APC Schneider electric

<40>01/27/2022 14:21:31 172.16.150.21 APC: Test Syslog.

**Comment by rfaircloth-splunk** [comment]
this was already supported in 1.x note the apc test syslog events do not match normal events please see doc for setup
