### ISSUE TITLE
New Source: Buffalo - Software Buffalo Terastation Firmware: 4.82-0.08

### ISSUE THREAD

**Issue by gbecker-splunk** [splunk/splunk-connect-for-syslog#1454]
Vendor: Buffalo
Firmware: 4.82-0.08
Software: Buffalo Terastation

<134>Jan 27 14:29:26 nasapi[19090] - buffalo_jsonrpc2 - update_lastedit_time - INFO- last-edit time updated by "log.set_config"

**Comment by rfaircloth-splunk** [comment]
this was included in v2.0.0
