### ISSUE TITLE
New Source: Aruba - Software HP Owned Firmware: 8.6.0.9_79813

### ISSUE THREAD

**Issue by gbecker-splunk** [splunk/splunk-connect-for-syslog#1455]
Vendor: Aruba
Firmware: 8.6.0.9_79813
Software company: HP Owned

<140>Jan 27 14:43:50 2022 172.16.150.41 AP:Glas_1stFlr_AR515-TECH <172.16.150.41 FC:7F:F1:C1:39:CA> awc[5503]: wsc: wsc_service_wd_fd(1889), poll write, sevice fd 14

**Comment by rfaircloth-splunk** [comment]
this was already supported in 1.x
