### ISSUE TITLE
New Source: HPE - Software VMWare 6.7.0 Update 3 (Build 17499825)

### ISSUE THREAD

**Issue by gbecker-splunk** [splunk/splunk-connect-for-syslog#1456]
Vendor: HPE 
ProLiant DL380 Gen9
Software: VMWare 6.7.0 Update 3 (Build 17499825)

<78>2022-01-27T20:00:00Z HPE-HC-USE713BBHL.tii.local crond[2099184]: USER root pid 11997105 cmd /usr/lib/vmware/vmksummary/log-heartbeat.py

**Comment by rfaircloth-splunk** [comment]
this is already supported in 1.x
