### ISSUE TITLE
New Source: HPE - Software hp enterprise ilo : 2.78 Apr 28 2021

### ISSUE THREAD

**Issue by gbecker-splunk** [splunk/splunk-connect-for-syslog#1457]
Vendor: HPE 
ProLiant DL380 Gen9
ILO HP Enterprise based ilo
Software version for the hp enterprise ilo : 2.78 Apr 28 2021

<134>1 2022-01-27T19:51:46Z ILOUSE713BBHL #ILO4 - - - Browser login: Administrator - 10.176.11.78(ITLAPTOPAF.TII.local).

**Comment by rfaircloth-splunk** [comment]
this was included in v2.0.0
