### ISSUE TITLE
Incorrect naming of newly supported Cisco CMS source

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#1480]
Hello,

Issue #736 has been recently closed. The issue requested CMS (Cisco Meeting Server) support.
The latest 2.1.0 SC4S release calls this "CMC", or "Communications Management Controller" 
([feat: Support Cisco CMC](https://github.com/splunk/splunk-connect-for-syslog/commit/accc0268c0e7a525aff565cb5ca4983b1447707a)

The product is called CMS and not CMC. In fact, there is no Cisco Communications Management Controller. 
test_cisco_cmc.py does seem to test the provided syslog example from the case, so this is likely just a naming issue.

**Comment by rfaircloth-splunk** [comment]
I wasn't even close on that one....Fix PR is on the way
