### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#1484]
Hello, the documentation for Tenable and Varonis have spaces and capitalized letters in the index configuration code. Is this an error? When importing the index configurations under vendor_product_by_source.conf, the container fails.

Feb 16 07:57:05 servername docker[36247]: 100         host("Thycotic Software_Secret Server" type(glob))
Feb 16 07:57:05 servername docker[36247]: 101         #or netmask(xxx.xxx.xxx.xxx/xx)
Feb 16 07:57:05 servername docker[36247]: 102     };
Feb 16 07:57:05 servername docker[36247]: syslog-ng documentation: https://www.syslog-ng.com/technical-documents/list/syslog-ng-open-source-edition
Feb 16 07:57:05 servername docker[36247]: contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng
Feb 16 07:57:05 servername docker[36247]: [2022-02-16T12:57:05.857221] Error parsing filters of rule engine; filename='/etc/syslog-ng/conf.d/local/context/vendor_product_by_source.conf'
Feb 16 07:57:05 servername docker[36247]: [2022-02-16T12:57:05.857239] Error initializing message pipeline; plugin_name='add_contextual_data', location='/etc/syslog-ng/conf.d/enrich/vendor_product_by_source.conf:9:17'
Feb 16 07:57:06 servername docker[36247]: syslog-ng failed to start; exiting...

https://splunk-connect-for-syslog.readthedocs.io/en/latest/sources/Thycotic/
Sourcetype and Index Configuration
key	sourcetype	index	notes
Thycotic Software_Secret Server	thycotic:syslog	netauth	none

https://splunk-connect-for-syslog.readthedocs.io/en/latest/sources/Varonis/
Index Configuration
key	sourcetype	index	notes
Varonis Inc._DatAdvantage	varonis:ta	main

**Comment by rfaircloth-splunk** [comment]
In vendor_product_by_source.conf there is a missing ; most likely prior to Thycotic_Software_Secret_Server

**Comment by techsystems-unix** [comment]
A ";" isn't missing. Tthe documentation online does not reflect Thycotic_Software_Secret_Server.
It has spaces and is reflected as Thycotic Software_Secret Server. I have to add the underscores to the sourcetype for sc4s to work properly.

**Comment by techsystems-unix** [comment]
Any update on this?

**Comment by rfaircloth-splunk** [comment]
Sorry I lost track of this one.
Thycotic is CEF based so no need to use vendor_product_by_source
in splunk_metadata
```
Thycotic Software_Secret Server,index,newindex
```
