### ISSUE TITLE
Alternate Destinations - URI issue

### ISSUE THREAD

**Issue by iopsmon** [splunk/splunk-connect-for-syslog#1490]
If you configure or add another destination, there is an issue with the URI. 

You do not recieve any data

The issue is the uri for anything other than default needs to be "complete" https://splunk:8088/services/collector/event

For now the workaround is like the example below

SC4S_DEST_SPLUNK_HEC_BACKUP_URL=https://SPLUNK_SERVER:8088/services/collector/event

**Comment by rfaircloth-splunk** [comment]
confirmed issue
