### ISSUE TITLE
Feature Request: Kaspersky Security Center Parser

### ISSUE THREAD

**Issue by Zakk220** [splunk/splunk-connect-for-syslog#1512]
Hello, 
Can you create a parser for Kaspersky Security Center? Right now it is using sourcetype= sc4s:fallback. Below are links to two Kaspersky addons for Splunk. The addons do have some information for event extraction and parsing on the indexer in case they are able to provide useful information. I've also attached a few logs from a packet capture. Please let me know if you need more information.

https://apps.splunk.com/app/4661/#/details
https://apps.splunk.com/app/4656/#/details
[kaspersky_export.zip](https://github.com/splunk/splunk-connect-for-syslog/files/8164583/kaspersky_export.zip)

**Comment by rfaircloth-splunk** [comment]
The export attached is the RFC5424 format however the Splunk add-ons were developed for leef or cef format. I have a PR to support the samples provided please open a new issue with a CEF capture
