### ISSUE TITLE
Support Cisco ACS

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-connect-for-syslog#152]

**Comment by s-koniarz** [comment]
Same as other sourcetypes.  I will check with my management if we can share logs out.  Also, according to my network admins ACS is EOL but is replaced by Cisco ISE so they would be ISE logs.

**Comment by rfaircloth-splunk** [comment]
Yes this is certainly EOL but its going to hold on for quite some time for a number of reasons. I see plenty of customers with ACS and ISE that moved to ISE for wifi/wan network auth but continue to use ACS for admin auth to hardware

**Comment by perditi0nspam** [comment]
[ACS sample logs.txt](https://github.com/splunk/splunk-connect-for-syslog/files/3855806/ACS.sample.logs.txt)

Here are some sample syslogs for ACS 5.8

**Comment by rfaircloth-splunk** [comment]
This is a great start do you have any that show an authentication activity?

**Comment by perditi0nspam** [comment]
Here are some more samples.

![IMG_20191210_221203](https://user-images.githubusercontent.com/57867844/70566202-46821600-1b9c-11ea-9d95-441d33f048ba.jpg)
![IMG_20191210_221309](https://user-images.githubusercontent.com/57867844/70566208-4c77f700-1b9c-11ea-822f-a3fbc2b251a5.jpg)
![IMG_20191210_221329](https://user-images.githubusercontent.com/57867844/70566219-4eda5100-1b9c-11ea-91a7-9a2484589bb4.jpg)

CRLF are newlines. ACS logs can arrive as either UDP or TCP based syslogs.
