### ISSUE TITLE
Need a way to set "auto_extract_timestamp" at Splunk HEC URL endpoint "services/collector/event"

### ISSUE THREAD

**Issue by rvsoni** [splunk/splunk-connect-for-syslog#1525]
Need a way to set a "auto_extract_timestamp" at Splunk URL end point "services/collector/event"

Currently, there is no way to set the URL query parameter "auto_extract_timestamp" at HEC endpoint

Pl. refer to HTTP Event Collector REST API endpoints documentation.
https://docs.splunk.com/Documentation/Splunk/8.2.2/Data/HECRESTendpoints

**Comment by rfaircloth-splunk** [comment]
Timestamp extraction is handled in sc4s along with many other things this would create unpredictable and unsupportable behavior. If there is a source with a specific issue please open an issue with that source.
