### ISSUE TITLE
Documentation Broken Link

### ISSUE THREAD

**Issue by stevermc** [splunk/splunk-connect-for-syslog#1526]
https://splunk.github.io/splunk-connect-for-syslog/main/sources/base/cef/ has a broken link titled "Unique Listening Ports" https://splunk-connect-for-syslog.readthedocs.io/en/develop/sources/#unique-listening-ports

**Comment by mkarlstrand-splunk** [comment]
Hi @stevermc thank you for the comment. SC4S is a community project so please feel free to directly open a PR for fixes like this. Thanks :)
https://splunk.github.io/splunk-connect-for-syslog/main/sources/#unique-listening-ports

**Comment by mateuszpierzchala-splunk** [comment]
Mentioned link is working, probably fixed in some previous release. I will close this issue.
