### ISSUE TITLE
Feature Request: Defining CEF index

### ISSUE THREAD

**Issue by stevermc** [splunk/splunk-connect-for-syslog#1527]
Can we make it so indexes can be defined in the splunk_metadata file for CEF like syslog?

**Comment by rfaircloth-splunk** [comment]
This is already a feature https://splunk.github.io/splunk-connect-for-syslog/main/sources/base/cef/

**Comment by stevermc** [comment]
How? I looked through that webpage and only see where to change sourcetype. The only mention I see of index is main.
