### ISSUE TITLE
Splunk_cooked does not work with certain data

### ISSUE THREAD

**Issue by mshensg** [splunk/splunk-connect-for-syslog#1531]
1. it appears some multiline events cannot be processed properly. Only the first line is taken in.
2. Some data is not properly processed. 1 line is process in normal approach while the other is processed using splunk_cooked.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/61037055/157677330-066082e1-b358-44ea-807d-1fb880f07e88.png">
3. as Splunk_cooked has lower priority than other parsers, once the content (especially if the content is generated from a none standard data source), the event might not be able to reach to the parser. suggest to rename the file name to 1_splunk_cooked so to ensure it is the first parser.

**Comment by mshensg** [comment]
Can you share me the splunk side configuration? I am not using mock up Python script, I am testing in a real splunk environment. 
I can see _introspection got truncated, multiline event got truncated, and stash collected events may be processed wrongly (I actually thinking give all program based parser a p prefix, all regex based parser a r prefix so to ensure all program based parser will be executed on top of regex based. )

**Comment by rfaircloth-splunk** [comment]
yes this is here. I need to get this into a doc page
https://gist.github.com/rfaircloth-splunk/fe0f051fbedfefd13c5f56dfeb0a8b3b

**Comment by mshensg** [comment]
I performed some test (using tcpout, did not test UDP syslog out yet). I found Windows event (in traditional mode), _internal log, and _inspection log arrives successfully while I did not count whether there is any missing. However, the other logs including the data I send to certain index using collect command did not arrive: Instead, there are a lot of error messages reported by sc4s. 

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/61037055/157997822-8631b096-0847-41fe-8661-d8d97e5d2299.png">

**Comment by rfaircloth-splunk** [comment]
UDP would limtit the event to about 1200 bytes its just unusable only tcp can really be used

**Comment by rfaircloth-splunk** [comment]
Also I could use a pcap of an event that produces the invalid frame header

**Comment by mshensg** [comment]
so far as we tested, UDP limits on 65KB data which Windows Perform MultiKV will need to change to singleKV and nix add-on ps.sh will need to be updated to avoid being exceeding the limit. Using this approach is majorly before the connection does not have TCP (like data diode) so only UDP can be used. 
I will try disable HTTPS and then do a pcap and see if can find any clues. will post with updates

**Comment by rfaircloth-splunk** [comment]
is the splunk host linux or windows?

**Comment by mshensg** [comment]
AWS Linux 2. And Centos 7. No Splunk Enterprise on Windows. Only UF for Windows to collect Event Logs and forward via 9997

**Comment by rjha-splunk** [comment]
Any more update here ?

**Comment by rjha-splunk** [comment]
As there is no update on the issue we are closing it.
