### ISSUE TITLE
Feature Request: Kaspersky CEF

### ISSUE THREAD

**Issue by Zakk220** [splunk/splunk-connect-for-syslog#1561]
Attached is a few logs that covers most of our events. I had to remove a lot of information since it contained usernames so I wasn't able to upload a packet capture. Please let me know if more information is needed. Thank you!

[kasp.txt](https://github.com/splunk/splunk-connect-for-syslog/files/8307304/kasp.txt)

**Comment by rfaircloth-splunk** [comment]
No problem for CEF format I don't normally need more than the header fields

**Comment by rfaircloth-splunk** [comment]
This is also released
