### ISSUE TITLE
Dest configuration for UDP causes startup error

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-connect-for-syslog#1581]
[2022-03-18T15:06:55.424615] Unknown value specified in the transport()
option, no such LogProto plugin found; transport='udp '

**Comment by rfaircloth-splunk** [comment]
Solved "space" in user config.

**Comment by kamikaze2393** [comment]
Recently, started seeing this error.

podman[721641]:   File "/etc/syslog-ng/conf.d/destinations/dest_syslog/plugin.py", line 76, in <module>
podman[721641]:     transport=transport,
podman[721641]: NameError: name 'transport' is not defined
podman[721641]: [2022-03-24T09:17:47.202231] confgen: Generator program returned with non-zero exit code; reference='/etc/syslog-ng/conf.d/destinations/dest_sys>
podman[721641]: Error parsing config, syntax error, unexpected LL_ERROR, expecting end of file in /etc/syslog-ng/conf.d/destinations/dest_syslog/plugin.conf:3:1>

**Comment by kamikaze2393** [comment]
No changes done.
