### ISSUE TITLE
SC4S dtparse error Fortimail

### ISSUE THREAD

**Issue by stevermc** [splunk/splunk-connect-for-syslog#1582]
The new fortimail feature is working great so far!

I am seeing the below log when searching fortimail events in Splunk in the sc4s_error field:

dtparse: Expected: '%Y-%m-%d:%H:%M:%S%z', '%Y-%m-%d:%H:%M:%S' ; Actual: 2022-03-23:12:26:20.949

If you need anything else please let me know

**Comment by rfaircloth-splunk** [comment]
can you show me the event fields
date
time
eventtime (or a varient with epoch)

**Comment by stevermc** [comment]
No eventtime field 

date: 2022-03-23
time: 13:36:45.653
sc4s_recv_time: 1648060605.656
_time:  2022-03-23T13:36:45.656-05:00

**Comment by rfaircloth-splunk** [comment]
is there no other time field that looks like a 9/10 digit number?

**Comment by stevermc** [comment]
no other time fields than the ones given above
