### ISSUE TITLE
Internal events from the SC4S are written into console

### ISSUE THREAD

**Issue by harnhbn** [splunk/splunk-connect-for-syslog#1589]
Post installing 2.19.3, all the Internal events are being written directly on the console (linux server ssh console and it is very annoying ) This was not appearing in the previous version.
Please advise how to disable this

**Comment by rfaircloth-splunk** [comment]
can you screenshot the events ?

**Comment by rfaircloth-splunk** [comment]
try updating to the next build I think I already fixed this

**Comment by harnhbn** [comment]
I did update to v2.20.0, however it is still the same

**Comment by rfaircloth-splunk** [comment]
May have found the issue update again please
