### ISSUE TITLE
Dell RSA vendor / Product miss alignment

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-connect-for-syslog#1613]
Noticed the Dell RSA vendor product definitions are off.  I'm not sure if the code should match the docs or if the docs should match the code. 

Issue: 
  Docs indicate the below vendor product with the key of `dell_rsa_secureid`.  However they actually log with a key of `dell-rsa_secureid` (notice dash vs underscore).  

Docs:
```text
vendor('dell')
product('rsa_secureid')
```

Reality:
```text
vendor('dell-rsa')
product('secureid')
```

Does it make since to change it the the below so code matches docs with the addition of the class field for v2 conformity? 

Proposed solution:
```text
vendor('dell')
product('rsa')
class('secureid')
```

Reference:
[dell rsa docs](https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Dell/rsa_secureid/)

**Comment by rjha-splunk** [comment]
The doc is updated to show the real key.
