### ISSUE TITLE
Issue when installing sc4s on microk8s

### ISSUE THREAD

**Issue by michaelw2009** [splunk/splunk-connect-for-syslog#1617]
Hi,

I'm currently running microk8s with a few pods for sck and sc4snmp. I'm trying to install sc4s but getting the following result.
I believe the default sc4s yaml is not enough and lack of metallb configuration, but I cant find anywhere in the doc.

Here's the error message:

$ microk8s helm3 install sc4s sc4s/splunk-connect-for-syslog -f values_sc4s.yaml --namespace=sc4s --create-namespace
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/3052/credentials/client.config
Error: template: splunk-connect-for-syslog/templates/service.yaml:86:25: executing "splunk-connect-for-syslog/templates/service.yaml" at <.Values.usemetallb>: nil pointer evaluating interface {}.usemetallb

This is my sc4s yaml file:
splunk:
    hec_url: "http://192.168.1.50:8088/services/collector/event"
    hec_token: "eac3c683-438b-4afd-8b59-c4eff3476730"
    hec_verify_tls: "no"

Appreciate if you can provide a clear guide on how to install sc4s in a shared microk8s node.

rgds,
Michael

**Comment by rjha-splunk** [comment]
The instructions are updated.
