### ISSUE TITLE
SC4S booting issue

### ISSUE THREAD

**Issue by Saurabhharyan** [splunk/splunk-connect-for-syslog#1621]
Hello Team,

We are receiving following error post rebooting the SC4S machine. SC4s was working fine, post reboot the mount point(/var/lib/container) got unmounted. We have unmounted again but we coulne start the SC4S as expected.

Need your valuable time and support to resolve these issue.

systemctl status sc4s
Error: remount /var/lib/containers/storage/overlay, flags: 0x40000: invalid argument
![image](https://user-images.githubusercontent.com/95883185/161542237-dfbad42b-07a7-443d-8faf-2a00bdd63a19.png)

Regards,
Saurabh

**Comment by rfaircloth-splunk** [comment]
it looks like the volume is corrupt
```
podman volume rm splunk-sc4s-var
podman volume create splunk-sc4s-var
 
```
