### ISSUE TITLE
Typo on PANOS Document Page

### ISSUE THREAD

**Issue by kdiasSPL** [splunk/splunk-connect-for-syslog#1636]
There is a Type on the page: https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/PaloaltoNetworks/panos/
Attaching Screen shot to show location.  I know this is small, but thought it might help other people out
<img width="582" alt="Screen Shot 2022-04-07 at 3 10 01 PM" src="https://user-images.githubusercontent.com/103217411/162282882-12357b92-84c5-43b8-a5e7-4583a76a6979.png">
.

**Comment by mkarlstrand-splunk** [comment]
Hi @kdiasSPL SC4S is a community project. Please fee free to directly create a PR for fixes like this. Thank you :)

**Comment by mateuszpierzchala-splunk** [comment]
Closed by #1770
