### ISSUE TITLE
Entrypoint is not copying all context files

### ISSUE THREAD

**Issue by ehlo550** [splunk/splunk-connect-for-syslog#1639]
Not all context files are copied from the configmap mount point to the config directory.
For details see: https://github.com/splunk/splunk-connect-for-syslog/issues/1576

Regards

**Comment by rjha-splunk** [comment]
Other configmaps files are deprecated in v2 , the code needs to be corrected to remove the empty files and document will be revised , now the way to implement this feature is by using a .conf file in local/config/app_parsers/<filename>.conf, we will update it soon.
