### ISSUE TITLE
Docs: Clarify UDP recomendation

### ISSUE THREAD

**Issue by mkarlstrand-splunk** [splunk/splunk-connect-for-syslog#1657]
Update the UDP vs TCP docs section to include the full context of the recommendation contained in the blog post.

https://splunk.github.io/splunk-connect-for-syslog/main/architecture/
https://www.rfaircloth.com/2020/05/21/performant-and-reliable-syslog-udp-is-best/

**Comment by rjha-splunk** [comment]
@nandinivij can you please update this.

**Comment by rjha-splunk** [comment]
@mateuszpierzchala-splunk Can you please take a look?

**Comment by mateuszpierzchala-splunk** [comment]
@rjha-splunk sure, np

**Comment by mateuszpierzchala-splunk** [comment]
closed by #1801
