### ISSUE TITLE
Vendor Request: Oracle ZS7-2 Storage Appliance

### ISSUE THREAD

**Issue by mattweber78** [splunk/splunk-connect-for-syslog#1660]
Would it be possible to include Oracle Storage Appliance to a future version of SC4S?  There is no Splunk TA for it.  I have attached a small sample of log data to this request.  The systems these logs were pulled from are Oracle ZS7-2 Storage Appliances running on Oracle Solaris 11.4. 

[oracle_event_export.txt](https://github.com/splunk/splunk-connect-for-syslog/files/8533826/oracle_event_export.txt)

**Comment by mattweber78** [comment]
Any updates on this?

**Comment by rjha-splunk** [comment]
Hi , i reviewed the attached text sample, can you attach pcap/sanitized log after processing it in wireshark, as the documentation claim to have RFC5424 format but the attached log is not.

**Comment by bparmar-splunk** [comment]
@mattweber78,
We have not heard anything from you on this issue.
Closing this issue for now.

Please let us know in case of further queries.
