### ISSUE TITLE
A new filter support for the attached zsclater log

### ISSUE THREAD

**Issue by amulay26** [splunk/splunk-connect-for-syslog#1670]
[drive-download-20220426T202028Z-001.zip](https://github.com/splunk/splunk-connect-for-syslog/files/8566855/drive-download-20220426T202028Z-001.zip)

These seem to be Zscaler metrics log and need a filter for it.

**Comment by rjha-splunk** [comment]
@amulay26 Can you please attach pcap/sanitised log, the attached file is not able to provide right format for the parser

**Comment by amulay26** [comment]
[zscale_145_IF3L.txt](https://github.com/splunk/splunk-connect-for-syslog/files/8717583/zscale_145_IF3L.txt)
[zscale_145_IF2L.txt](https://github.com/splunk/splunk-connect-for-syslog/files/8717584/zscale_145_IF2L.txt)

**Comment by rjha-splunk** [comment]
The parsing works as it should , tested with the raw sampl
<img width="1104" alt="Screenshot 2022-05-20 at 13 24 08" src="https://user-images.githubusercontent.com/90039710/169518299-a23dce61-5cd8-41f0-85a0-ff765d7d1008.png">
e
