### ISSUE TITLE
CISCO SD WAN filter

### ISSUE THREAD

**Issue by gshahspl** [splunk/splunk-connect-for-syslog#1671]
Need a filter created for this vendor (not known) data is being logged with sourcetype:fallback

Cisco ASR1002-X router running IOS version 17.3.4a

metafile:
EXPOSE 1515/udp
cisco_sd_wan,index,firewall_sdwan
cisco_sd_wan,sourcetype,netflow-vs9

**Comment by nandinivij** [comment]
@gshahspl Can you please add redacted raw logs here

**Comment by bparmar-splunk** [comment]
@gshahspl,
We didn't hear anything from you on this issue.
We are closing this issue for now.

Feel free to reach out in case of any further queries.
