### ISSUE TITLE
Add a new filter for QUANTUM Scalar

### ISSUE THREAD

**Issue by olivierpas** [splunk/splunk-connect-for-syslog#1672]
Hello,

Can you please add a new filter for Quantum scalar technology ?

log sample :
```
PRI=13
MESSAGE=Scalar-i6000[2080]: [LMC SN='9999999' USER='admin' ROLE='Admin' COMMAND='Login' DATE='2022-04-28 13:53:53 +0200' FROM='192.168.2.67' DESCRIPTION='' ]
```

**Comment by bparmar-splunk** [comment]
@olivierpas,
Could you please send sanitized log to validate?

**Comment by bparmar-splunk** [comment]
@olivierpas,
We have not heard anything from you on this issue.
We are closing this issue.

Please let me know in case of any further queries.
