### ISSUE TITLE
Nutanix Prisim Data Filter 

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#1674]
Feature request: 
We are interested in a new data ingestion scheme for Nutanix Prism. The sourcetype would be Nutanix.
I have attached a pcap report from our Nutanix server. The logs are in syslog format.
Nutanix Prism version: 5.20.3
[nutanix.zip](https://github.com/splunk/splunk-connect-for-syslog/files/8586113/nutanix.zip)

**Comment by techsystems-unix** [comment]
Any updates on this ticket?

**Comment by rjha-splunk** [comment]
we are working on it, it should be released in few days after testing.

**Comment by techsystems-unix** [comment]
ok thank you
