### ISSUE TITLE
Cisco IOS-XR ASR9k syslog being sourced as nix:syslog

### ISSUE THREAD

**Issue by haydenseitz** [splunk/splunk-connect-for-syslog#1698]
Using version 2.28.4, I am seeing the same issues as described here: #1340

Our raw messages look like this:
```
<147>1102: lab-9k1 RP/0/RSP0/CPU0:2022 May 18 18:11:05.263 : SSHD_[65817]: %SECURITY-SSHD-3-ERR_GENERAL : Failed to receive User authentication request
```

In Splunk they show sourcetype=nix:syslog

![image](https://user-images.githubusercontent.com/17074342/169181079-a5c881b7-ff9f-4e5d-93df-01a6052e5e00.png)

The original issue was resolved here https://github.com/splunk/splunk-connect-for-syslog/pull/1343, but it seems the code structure and parsing for Cisco IOS has changed since then.

I tried to debug what part of the parser is not matching, but have not had any luck so far (I tried turning on syslog-ng tracing... _yikes_). I have everything set up in lab, so if anyone is willing to help, let me know what other info I can provide

**Comment by rjha-splunk** [comment]
Thanks for reporting , let me check and get back.

**Comment by rjha-splunk** [comment]
For now i will suggest to create following file:/opt/sc4s/local/config/filters/app-postfilter-ios_splunk.conf
```
block parser app-dest-rewrite-ios_syslog-postfilter() {    
 channel {
        rewrite {
            r_set_splunk_dest_default(
                index('netops')
                sourcetype('cisco:ios')
                vendor('cisco')
                product('ios')
            );               
        };
    };
};
application app-dest-rewrite-ios_syslog-postfilter[sc4s-postfilter] {
    filter {
        message(': %' type(string) flags(substring))
        ;
    };     

    parser { app-dest-rewrite-ios_syslog-postfilter(); };   
};
```

**Comment by haydenseitz** [comment]
Hi @rjha-splunk, thanks for the help. I added that filter and now those messages have `index`, `sourcetype`, `vendor`, and `product ` correct 👏. However, the message format doesnt match other cisco:ios, and it has some fields that the nix:syslog sourcetype typically has, like `program`. 

I assume it's still being parsed as nix:syslog initially, but the new filter is rewriting the fields listed above?

![image](https://user-images.githubusercontent.com/17074342/169351423-70417972-911a-4baa-a409-aca580989fb5.png)

**Comment by rjha-splunk** [comment]
yes you are right , as it post filter,you can unset the program as well 
`        rewrite{
            unset(value('PROGRAM'));
            };  `

**Comment by rjha-splunk** [comment]
Work around provided as the log format is different than supported type, we can work on it in next version.

**Comment by haydenseitz** [comment]
sounds good. I took a few other settings from `app-almost-syslog-cisco_syslog.conf` to get the message format to match other Cisco events. [Here ](https://pastebin.com/2Tdd7GbU) is the full config i'm using now. thanks again for the help!

**Comment by haydenseitz** [comment]
Is there a good way for me to check if there has been a patch for this issue?

**Comment by rjha-splunk** [comment]
We will review and update.
