### ISSUE TITLE
VMWare vCenter Source is missing  vcenter-server program type

### ISSUE THREAD

**Issue by harv-qq** [splunk/splunk-connect-for-syslog#1699]
can you add  vcenter-server as a program type for the vmware_vsphere_vc key so that the sourcetype is vmware:vclog:${PROGRAM} e.g. vmware:vclog:vcenter-server

**Comment by rjha-splunk** [comment]
Can you please attach a sample sanitised log to test it ? @harv-qq

**Comment by harv-qq** [comment]
- - vcenter-server - - [Originator@6876 vmw_cluster="blah blah" vmw_datacenter="blah blah" vc_event_type="com.vmware.vim25.TaskEvent" vmw_object_id="host-blah" vc_username="blah blah" vmw_vcenter="blah blah" vmw_vcenter_id="blah blah" env="blah blah" vc_vm_name="blah blah" vmw_vr_ops_id="blah blah"][meta sequenceId="-11111111"]Task: Create virtual machine snapshot

**Comment by harv-qq** [comment]
- - vcenter-server - - [Originator@6876 vmw_cluster="blah blah" vmw_datacenter="blah blah" vc_event_type="com.vmware.vim25.TaskEvent" vmw_object_id="host-blah" vc_username="blah blah" vmw_vcenter="blah blah" vmw_vcenter_id="blah blah" env="blah blah" vc_vm_name="blah blah" vmw_vr_ops_id="blah blah"][meta sequenceId="-11111111"]Task: Create virtual machine snapshot
