### ISSUE TITLE
debug not working

### ISSUE THREAD

**Issue by francly** [splunk/splunk-connect-for-syslog#1701]
Hi, any idea the same config on version 1.x working but not work on 2.x? That no debug file in archive directory.

`SC4S_DEST_GLOBAL_ALTERNATES=d_hec_debug
`

`SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=main for sourcetype=sc4s:fallback...
SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=main for sourcetype=sc4s:events...
syslog-ng checking config
sc4s version=2.28.4
starting goss
starting syslog-ng
`

**Comment by rjha-splunk** [comment]
The feature is deprecated , we will update the docs
