### ISSUE TITLE
syslog messages do not parse correctly when IPv4 addresses are in process name

### ISSUE THREAD

**Issue by RaygunDuck** [splunk/splunk-connect-for-syslog#1718]
Example of the issue
This line parses fine:
<14>Mar 25 19:08:39 ServerName conman[1324]: INFO     conman - lhvpn-10.194.1.45-nodes-86 is now running successfully

This does not, and is sent to the sc4s:fallback sourcetype
<29>Mar 25 19:08:39 ServerName 10.192.1.45.nodes-86[4035]: Options error: --ca fails with '/etc/config/lhvpn/10.192.1.45.nodes-86.ca': No such file or directory (errno=2)

I have observed this from multiple servers and log types.

**Comment by ryanfaircloth** [comment]
This is incorrect and not allowed in BSD format syslog. What is the source product have you communicated the defect to the vendor?

**Comment by rjha-splunk** [comment]
sc4s fallback is for the sourcetypes which are not identified by the parsers and thats why it adds PRI and message.

**Comment by RaygunDuck** [comment]
Regardless, SC4S is still providing less functionality than syslog-ng writing out files are picked up by a monitor input

**Comment by rjha-splunk** [comment]
All the supported vendors are documented , if something is breaking please feel free to share the sample sanitised log and we will try to fix it.

**Comment by RaygunDuck** [comment]
I have provided this. What additional information do you require?

**Comment by rjha-splunk** [comment]
source product for example.

**Comment by rjha-splunk** [comment]
I understand your concern, we will keep this issue open and discuss internally.

sc4s was designed to work in the said way and it is working as designed, we will check what we can do here and keep posted.

**Comment by ryanfaircloth** [comment]
The log format is not bsd formatted. In a unconfigured syslog-ng instance no processing other than logging the raw message occurs sc4s performs complex processing on the structured data for multiple use cases using syslog-ng. I'm sure splunk would be happy to help as they have with hundreds of non compliant sources. They need some help from you or the vendor. They need enough message samples from a packet capture to see all the defects in the source and they need to know the vendor and product to document the support.

**Comment by RaygunDuck** [comment]
So, won't fix. Got it.

**Comment by ryanfaircloth** [comment]
To be very specific its not a fix because its not wrong. However sc4s is designed to handle these conditions by forcing a developer to make correct choices. If you interested in the enhancement you just to to answer the rather simple questions asked. Your interactions imply you are more interested in this not being resolved than seeing a resolution for non technical reasons.  (Not a Splunker)

**Comment by RaygunDuck** [comment]
I have provided the required information in order to fix/enhance/(insert your preferred term here) however the responses that I continue to receive are difficult to interpret as anything other than being deliberately obtuse in order to avoid resolving the stated issue.

**Comment by ryanfaircloth** [comment]
@RaygunDuck the handling outliers can be tricky you could help by being specific with the source vendor and product to allow proper documentation for dealing with this non standard format and testing for regression in future releases. "syslog" is defined in RFC5424 as a standard, your incorrectly relying on rfc3164 which is not a standards track document. More than one sample is useful in many cases when source products are not following the standard there is more than one defect and the defects are not consistent its common to need a packet capture to find all the potential issues.  SC4S is extensible you can add the parser support yourself as well. Another valid choice is to refer the issue back to the origin and ask them to send   standard syslog

**Comment by rjha-splunk** [comment]
As per the current guidelines if the problem is with metadata and nonstandard RFC formats, we suggest to write custom parsers , splunk_metadata.csv to correct it.
