### ISSUE TITLE
Symantec (Broadcom) DLP - incorrect sourcetype

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#1724]
The [SC4S docs](https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Broadcom/dlp/) and [add-on docs](https://docs.splunk.com/Documentation/AddOns/released/SymantecDLP/Sourcetypes) both mention sourcetype of `symantec:dlp:syslog`, but the app-parser is setting it `symantec:dlp:system`.

**Comment by zyphermonkey** [comment]
Also worth noting that the docs mention this going to the `netauth` index when it actually goes into `netdlp`.

**Comment by rjha-splunk** [comment]
It is working as expected for the symantec:dlp:system , if the log has "Incident Id" in the message it will be symantec:dlp:syslog, the index mentioned is wrong in doc , thanks for pointing it out, we will fix it shortly.
