### ISSUE TITLE
splunk_sc4s_fallback in wrong index

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1727]
According to https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Splunk/sc4s/, the splunk_meradata.csv need to changed to included “splunk_” in front of sc4c_Fallback/ events and metrics

Noticed that when executed below, the output showed difference in Splunk Index
**Changed the metadata.csv to below**
$ cat /apps/sc4s/local/context/splunk_metadata.csv
#Auto recognize syslog type, index, custom index name to override the default
splunk_sc4s_fallback,index,sc4s_multi_sec_int_gdc-w
splunk_sc4s_events,index,sc4s_multi_sec_int_gdc-w
splunk_sc4s_metrics,index,sc4s_multi_sec_int_gdc-w 

Output on podman logs showed the index=main not index=” sc4s_multi_sec_int_gdc-w” as defined
$ podman logs SC4S
SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to **index=main for sourcetype=sc4s:fallback.**..
SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=sc4s_multi_sec_int_gdc-w for sourcetype=sc4s:events...
syslog-ng checking config
sc4s version=2.30.0
starting goss
starting syslog-ng

But the Splunk Index showing it parked into “sc4s_multi_sec_int_gdc-w” instead of main as indicated in the podman logs. Which is correctly part as what metadata defined
Refer to "splunk_index_fallback_OK" jpg

**IF changed the splunk_metadata.csv without the “splunk_” that use in version 1.**

#Auto recognize syslog type, index, custom index name to override the default
sc4s_fallback,index,sc4s_multi_sec_int_gdc-w
splunk_sc4s_events,index,sc4s_multi_sec_int_gdc-w
splunk_sc4s_metrics,index,sc4s_multi_sec_int_gdc-w 

Output on podman logs showed the index=” sc4s_multi_sec_int_gdc-w “ which is corrected as defined in splunk_meradata.csv

$ podman logs SC4S
SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to **index=sc4s_multi_sec_int_gdc-w for sourcetype=sc4s:fallback**...
SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=sc4s_multi_sec_int_gdc-w for sourcetype=sc4s:events...
syslog-ng checking config
sc4s version=2.30.0
starting goss
starting syslog-ng

But the Splunk Index reported differently, it was in the “main” instead of “sc4s_multi_sec_int_gdc-w “
Refer to "splunk_index_fallback" jpg  

Is the code error or something do wrongly from my end?

_Environment_

- Podman: 3.0.1
- SC4S: version 2.30.0

**Comment by rjha-splunk** [comment]
The key should be splunk_sc4s_fallback etc. , thanks for bringing it to out attention that podman logs are not reporting it correct , we will fix it.
