### ISSUE TITLE
SC4S: Can’t recognize vmware_exsi

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1728]
Detail: Podman 3.0.1
SC4S: v2.30.0
Index file:
$ cat /apps/sc4s/local/context/splunk_metadata.csv | grep vmwa
vmware_vsphere_esx,index,sc4s_multi_sec_int_gdc-w
vmware_vsphere_nsx,index,sc4s_multi_sec_int_gdc-w
vmware_vsphere_nsxfw,index,sc4s_multi_sec_int_gdc-w
vmware_vsphere_vc,index,sc4s_multi_sec_int_gdc-w

Search key: "(accessible, configured)" & "Lun Id"
Rsyslog recognize the both events as “sourcetype = vmware:esxi” (refer to splunk_vmware_esxi_rsyslog /splunk_vmware_esxi_rsyslog_LunID.JPG ), 
SC4S put into “sourcetype = sc4s:fallback” (refer to splunk_vmware_esxi_sc4s.JPG / splunk_vmware_esxi_sc4s_LunID.JPG).

### Rsyslog vm_ware_exsi sourcetype
attached together with
splunk_vmware_esxi_rsyslog	sample for rsyslog with "(accessible, configured)" 
![splunk_vmware_esxi_rsyslog](https://user-images.githubusercontent.com/84378190/176099238-71e22986-7e3e-4e32-b0e6-74f06615a651.JPG)
splunk_vmware_esxi_rsyslog_LunID.JPG	sample for rsyslog with "Lun Id"
![splunk_vmware_esxi_rsyslog_LunID](https://user-images.githubusercontent.com/84378190/176099228-8689b5ce-276d-40cc-b3d4-cc939bb914d7.JPG)

### SC4S Fallback sourcetype
splunk_vmware_esxi_sc4s.JPG	sample for sc4s with"(accessible, configured)" 
![splunk_vmware_esxi_sc4s](https://user-images.githubusercontent.com/84378190/176100354-bef01edb-6685-43d0-89bb-afed54eceef6.JPG)

splunk_vmware_esxi_sc4s_LunID		sample for sc4s with "Lun Id"
![splunk_vmware_esxi_sc4s_LunID](https://user-images.githubusercontent.com/84378190/176099221-6fc22c50-6922-4ea8-b98c-29dd19f6be6e.JPG)
splunk_vmware_index.JPG		Splunk index with vmware
![splunk_vmware_index](https://user-images.githubusercontent.com/84378190/176099213-99f84359-c73d-43f4-bc26-3c1427c3bf84.JPG)

**- echo can't be simulate due to below error**
 $ echo “2022-06-28T10:00:18.951604+08:00 test.com --> SCSI PE, ID (host: n test.com VVold: a.624a937028822838c36e41a7000113eb, vasa: naa.624a937028822838c36e41a7000113eb) (accessible, configured)” > /dev/udp/10.198.212.246/514

_-bash: syntax error near unexpected token `('_

**- pcap can't be capture as can't filter ONLY selected events**

**Comment by rjha-splunk** [comment]
The sourcetype you are not able to find ( the log is sourcetyped as sc4s:fallback ) as it is not supported log type, as a workaround please create a conf file in `/opt/sc4s/local/config/app_parsers/filters\app-syslog-vmware_esxi.conf`
```block parser app-dest-rewrite-vmware_esxi-postfilter() {
    channel {
        rewrite {
            r_set_splunk_dest_default(
                index("infraops")
                sourcetype('vmware:esxi')
                vendor("vmware")
                product("esxi")
                template('t_msg_only')
            );
        };
    };
};
application app-dest-rewrite-vmware_esxi-postfilter[sc4s-postfilter] {
        filter {
            match("accessible, configured" value("MESSAGE")) or
            match("Lun Id" value("MESSAGE"));
    };
    parser { app-dest-rewrite-vmware_esxi-postfilter(); };
};
```
Use the index as you required, don't overuse this way as it will impact the performance.
