### ISSUE TITLE
Host IP can’t be resolved to FQDN on same device on same sourcetype

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1742]
Noticed that same device but it was reported with IP & FQDN in same sourcetype.
The *.*.228.23 and FQDN *003 is a same device (esxi_IP_lookup.JPG). Where it given IP & FQDN in sourcetype=nix:syslog. This same goes with “vmware:esxi” (after parser implementation.)
![esxi_IP_lookup](https://user-images.githubusercontent.com/84378190/177309123-34085018-9ff4-4b2b-a82e-7d8a5b4c179a.JPG)

* Attached the events from the same device.(Refer to nix_syslog_228.23.csv / nix_syslog_003a.csv)
[nix_syslog_003a.csv](https://github.com/splunk/splunk-connect-for-syslog/files/9045610/nix_syslog_003a.csv)
[nix_syslog_228.23.csv](https://github.com/splunk/splunk-connect-for-syslog/files/9045611/nix_syslog_228.23.csv)

Before implement the parser, the *.*.228.23 reported on “sourcetype: sc4s: fallback”. After implemented the parser as provided on case  #1728 & #1732  with filter below:-

_$ cat app-syslog-vmware_esxi.conf
block parser app-dest-rewrite-vmware_esxi-postfilter() {
    channel {
        rewrite {
            r_set_splunk_dest_default(
                index('sc4s_multi_sec_int_gdc-w')
                sourcetype('vmware:esxi')
                vendor('vmware')
                product('esxi')
                template('t_standard')
            );
        };
    };
};
application app-dest-rewrite-vmware_esxi-postfilter[sc4s-postfilter] {
        filter {
        host(x.x.228.23)
        and match("14" value("PRI")) or match("166" value("PRI"))
    };
    parser { app-dest-rewrite-vmware_esxi-postfilter(); };
};_

Events in the fallback has successful registered into “sourcetype= vmware:esxi” but with FQDN and IP. Refer to “parser_esxi.JPG”
Attached with the events log for above “parser_003a.csv / parser_228.23.csv”
[parser_228.23.csv](https://github.com/splunk/splunk-connect-for-syslog/files/9045614/parser_228.23.csv)
[parser_003a.csv](https://github.com/splunk/splunk-connect-for-syslog/files/9045615/parser_003a.csv)
![parser_esxi](https://user-images.githubusercontent.com/84378190/177309331-cff52559-7f1f-4aed-80f9-8ead684bf09e.JPG)

Question: It is same device, why it recorded as FQDN & IP? Where could be goes wrong?
* Please don’t close the case after provide advise, as it may not resolve

**Comment by rjha-splunk** [comment]
Also try enabling SC4S_USE_NAME_CACHE=yes in your env file, check if that helps.

**Comment by Jo-Ng** [comment]
@rjha-splunk Thanks for the suggestion. It resolved the IP issues descripted early and now the IP replaced with the FQDN name on the fallback sourcetype

Unfortunately noticed it trigged another issues. That large numbers of “packet receive errors” after the service start up after  Enabled the “SC4S_USE_NAME_CACHE=yes” 
Before enable the cache “232140697” packet receive errors
![without_cache_enable](https://user-images.githubusercontent.com/84378190/179789255-8a2d3810-4d35-4331-b7fc-e9cdf7335381.JPG)

Modified the env_file with Enable the  “SC4S_USE_NAME_CACHE=yes” 
![env_file](https://user-images.githubusercontent.com/84378190/179789412-f1db72bd-1a76-4040-9ca6-e08eaa69af5e.JPG)

After enabled the cache  “233345468” packet receive errors
![with_cache_enable](https://user-images.githubusercontent.com/84378190/179789455-14c2c206-8853-4b67-9f52-37b96b140c45.JPG)

In 10 min around “1,204,771‬” packets lost where lot of events are missing at the Splunk Indexes. As we use of “loggen” to test where events are missing of half or more when the Cache enabled during test.

Any hints what could be goes wrong? No packets dropped IF without ENABLE the cache
Thanks and look forward for suggestion

**Comment by rjha-splunk** [comment]
i will increase rcfbuff and sockets to fix this, tuning is required.
