### ISSUE TITLE
SC4S: Can’t recognise TrendMicro Sourcetype

### ISSUE THREAD

**Issue by anupammandal** [splunk/splunk-connect-for-syslog#1748]
The TrendMicro DeepSecurity events are not recognized by SC4S. Attached are the screenshot from UI and the raw logs. Let me know if further information is needed
<img width="1435" alt="Trend_AWS" src="https://user-images.githubusercontent.com/12557069/178420777-33383d22-db61-468a-ba9e-a2864bea8244.png">
<img width="1449" alt="Trend_Cloud_one" src="https://user-images.githubusercontent.com/12557069/178420807-d793e895-0274-47dd-b4de-18e371c7197b.png">
[Trend_AWS.txt](https://github.com/splunk/splunk-connect-for-syslog/files/9089985/Trend_AWS.txt)
[Trend_Cloud_one.txt](https://github.com/splunk/splunk-connect-for-syslog/files/9089987/Trend_Cloud_one.txt)
.

**Comment by rjha-splunk** [comment]
The messages attached it after getting parsed by sc4s , we will be needing raw messages ( either captured by pcap) or anonymise it and paste here, it will be added to enhancement request.
