### ISSUE TITLE
mcafee_nsp app_parser not setting source

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#1749]
I don't see anything in the [app_parser](https://github.com/splunk/splunk-connect-for-syslog/blob/main/package/etc/conf.d/conflib/syslog/app-syslog-mcafee_nsp.conf) that sets source, but the add-on and the [docs](https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/McAfee/nsp/) show the need for `mcafee:nsp:*`

**Comment by zyphermonkey** [comment]
> I will check and review this, will be released next week.

Sounds good. Thanks!

**Comment by rjha-splunk** [comment]
Hi, I checked the source code of sc4s and TA and source is set by TA not sc4s here ,check the transforms.conf of TA.

**Comment by zyphermonkey** [comment]
Thanks that fixed it. 

I've been incorrectly reading the add-on docs that say if you have to install it on the indexer.
<br>

> Not required if you use heavy forwarders to monitor McAfee NSP logs.  

I've been making the incorrect assumption that SC4S was acting as a HF and of course that's not the case. Doh!
