### ISSUE TITLE
Netapp OnTap Data Scheme Issue

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#1750]
Hello,

 This may be a possible bug. We are unable to ingest any data from Netapp. I have attached the pcap which shows the packets are being received in syslog format. However, the data is not appearing within Splunk. We have done all of the proper configuration required as well. Can you please review the pcap file?
Netapp OnTap Version 9.10.1p5
[NetApp.zip](https://github.com/splunk/splunk-connect-for-syslog/files/9115381/NetApp.zip)

**Comment by rjha-splunk** [comment]
We will review and update.

**Comment by techsystems-unix** [comment]
Hello,
Any updates regarding this ticket?

**Comment by mateuszpierzchala-splunk** [comment]
Hi, this has been fixed in https://github.com/splunk/splunk-connect-for-syslog/pull/1759. I will close this ticket.
