### ISSUE TITLE
Retention Policy

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#1760]
We are ingesting about 70G a day of data on our syslog server. In the documentation is states set the SC4S_DEST_SPLUNK_HEC_DISKBUFF_DISKBUFSIZE within the env_file. We set the disk buffer size to 80G and our var partition has over 600G allocated. However, from yesterday at 1PM to today 8:10AM, it has increased by 87G in less than 24 hours. Is there a configuration variable to adjust or add to modify retention policies?

**Comment by rjha-splunk** [comment]
https://splunk.github.io/splunk-connect-for-syslog/main/configuration/#disk-buffer-variables all the variables are documented here.

**Comment by rjha-splunk** [comment]
Can you please let us know what is the issue here, looks like sc4s is working as designed, the databuffer will be what you will set in env file.

**Comment by ryanfaircloth** [comment]
Input is overrunning output that can be a lot of things one of them is the
splunk hec endpoint is not scaled for your workload or network constraints

**Comment by techsystems-unix** [comment]
This issue can be closed. The data was being kept in cache and overrunning the server due to missing custom and default indexes missing from the input.conf file under sc4s_hec directory.
