### ISSUE TITLE
TLS 3rd party forwarding not working for legacy BSD

### ISSUE THREAD

**Issue by davidbattyJDS** [splunk/splunk-connect-for-syslog#1767]
This is similar to syslog forwarding issue https://github.com/splunk/splunk-connect-for-syslog/pull/1756

env_file

SC4S_DEST_BSD_PALANTIRZSNSS_HOST=XXXXX
SC4S_DEST_BSD_PALANTIRZSNSS_PORT=XXXXX
SC4S_DEST_BSD_PALANTIRZSNSS_TRANSPORT=tls
SC4S_DEST_BSD_PALANTIRZSNSS_TLS_VERIFY=no
SC4S_DEST_BSD_PALANTIRZSNSS_MODE=SELECT

error message:
Jul 26 13:59:24 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: [2022-07-26T03:59:24.153194] Error initializing message pipelin>
Jul 26 13:59:24 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: syslog-ng failed to start; exiting...
Jul 26 13:59:24 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: Handling exit 1 and restarting
Jul 26 13:59:24 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: starting syslog-ng
Jul 26 13:59:26 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: [2022-07-26T03:59:26.246687] transport(tls) was specified, but >
Jul 26 13:59:26 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: [2022-07-26T03:59:26.246718] Error initializing message pipelin>
Jul 26 13:59:27 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: syslog-ng failed to start; exiting...
Jul 26 13:59:27 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: Handling exit 1 and restarting
Jul 26 13:59:27 dlu201016145426.obm.nix.srv.westpac.com.au podman[3058]: starting syslog-ng

**Comment by rjha-splunk** [comment]
We will check this and update the code.

**Comment by mateuszpierzchala-splunk** [comment]
closed by #1776
