### ISSUE TITLE
Extract HOST from non standard CEF

### ISSUE THREAD

**Issue by lucalopreiato** [splunk/splunk-connect-for-syslog#1768]
Hello,
i have many CEF logs like:

<13>Jul  6 00:50:02 alfanumeric/alfanumeric CEF:0|

host is not extracted at all, any suggestions on how to fix it?

**Comment by rjha-splunk** [comment]
Can you please share the complete anonymised message/pcap to test this.

**Comment by lucalopreiato** [comment]
<13>Jul  6 00:00:02 xxyy1234/xxyy1234 CEF:0|XXX|AT 00012345||Security|Login successful|25|externalId=ID1234567890123456789012345678 suser=12345678 rt=2022-07-05 23:50:04 src=123.123.123.123 dst=123.123.123.123 cnt=1

**Comment by mateuszpierzchala-splunk** [comment]
@lucalopreiato can you provide details about device that generates this log event so we ca create new custom filter?

**Comment by lucalopreiato** [comment]
sorry, it is custom made by a customer, i don't have any info about the device

**Comment by mateuszpierzchala-splunk** [comment]
the part hidden under bold XXX is the device vendor, I think it does not have to be anonymised, if you can provide it we can build new filter on top of this property
<13>Jul 6 00:00:02 xxyy1234/xxyy1234 CEF:0|**XXX**|AT 00012345||Security|Login successful|25|externalId=ID1234567890123456789012345678 suser=12345678 rt=2022-07-05 23:50:04 src=123.123.123.123 dst=123.123.123.123 cnt=1

**Comment by mateuszpierzchala-splunk** [comment]
I guess that we can create filter specific for this vendor if format is the same for various devices. Most probably it will be ready on Monday.

**Comment by mateuszpierzchala-splunk** [comment]
Thanks a lot for your responses.

**Comment by lucalopreiato** [comment]
thanks for your help! :)

**Comment by mateuszpierzchala-splunk** [comment]
Hi, one more question- in this case you expect the host to be `xxyy1234/xxyy1234` or `xxyy1234` ?

**Comment by lucalopreiato** [comment]
> Hi, one more question- in this case you expect the host to be `xxyy1234/xxyy1234` or `xxyy1234` ?

hello, sorry for the late response, host can be either `xxyy01234/xxyy01234` or `xxyy01234` or ip address; i must add that the numeric part of hostname can contain zeroes, i noticed that right now the regex takes only 1-9 digits, can you please fix that? thank you very much

Luca

**Comment by mateuszpierzchala-splunk** [comment]
@lucalopreiato Hi, I fixed this here https://github.com/splunk/splunk-connect-for-syslog/pull/1795

**Comment by lucalopreiato** [comment]
@mateuszpierzchala-splunk perfect! thanks
