### ISSUE TITLE
BYOE Documentation Update/Clarification - Buffer Configuration

### ISSUE THREAD

**Issue by mattweber78** [splunk/splunk-connect-for-syslog#1771]
I have set the SC4S_DEST_SPLUNK_HEC_DEFAULT_DISKBUFF_DIR to a local directory on my SC4S machine and it does not seem to work.  Nothing ever gets cached there when SC4S cannot establish an HEC connection to Splunk.  Is there anywhere I can look to figure out what the issue is?

**Comment by rjha-splunk** [comment]
@mattweber78 thank you for pointing this out , we will check this, there is a possibility that there is a gap in doc and Code in BYOE ( as BYOE is still a work in progress), we will update as soon as possible.
