### ISSUE TITLE
Add Fields to McAfee Epo Filter

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#1777]
Hello,
This would be considered an enhancement request. FOr the McAfee epo filter, the event data is not being extracted/translated properly. Would it be possible to add additional event fields to be ingested into splunk? For instance, ip address, agent, and mac address would be relevant fields we would like to see.

Currently, only the host, source, and sourectype are available. Please refer to the attachment for a visual. Thank you.

<img width="346" alt="McAfee Fields in Splunk" src="https://user-images.githubusercontent.com/66375826/183126010-f22df905-0895-4dff-9dd9-f616ec56a7b8.PNG">

The pcap is encrypted FYI
[McafeeFile.zip](https://github.com/splunk/splunk-connect-for-syslog/files/9270632/McafeeFile.zip)

**Comment by rjha-splunk** [comment]
Hi , Please use props and transforms capability to create more fields in splunk , the metadata field we update using sc4s is limited to host,sourcetype and some sc4s related fields, there is way to create a local postfilter where more metadata can be added.
