### ISSUE TITLE
[BYOE] - Disk Buffer DIR Seemingly Not Working

### ISSUE THREAD

**Issue by kobz360** [splunk/splunk-connect-for-syslog#1785]
Hey Guys, 

I've observed this [this PR](https://github.com/splunk/splunk-connect-for-syslog/issues/1771) which seemingly fixed SC4S BYOE disk buffering, however, for the life of me, I can't seem to get the directory to update. No matter what I do, the events still buffer in the default /var/log/syslog-ng/ folder (RHEL-8). 

I've got the following varibales set:

- sc4s_dest...._diskbuff_dir=path_to_dir
- sc4s_dest...._diskbuff_reliable=yes
- sc4s_dest...._diskbuff_diskbuffsize=sizeset
- sc4s_dest...._diskbuff_diskbuff_enable=yes

I've even tried stopping the SC4S service, removing the persist file (as recommended), then restarting SC4S but the persist file is made in the same location and seemingly still points to /var/lib/syslog-ng instead of the _path_to_dir_ which I had set. 

Is there something I'm doing wrong? Cheers guys and hope you have an amazing day. 

Running sc4s v2.33.0, syslog-ng v3.36

**Comment by mattweber78** [comment]
I am seeing the same after updating to 2.33.0.

**Comment by rjha-splunk** [comment]
There was a gap in code commit , so it was not working, The released is already added to the PR, it will be released soon.
