### ISSUE TITLE
Palo Alto Broken Events

### ISSUE THREAD

**Issue by Jaxjohnny** [splunk/splunk-connect-for-syslog#1786]
most of our events are coming in perfectly from Palo Alto Panorama devices.  The log collector is used

the end of the message is after the beginning of the message

RAWMSG=255.255,,1,1,aged-out,1634,2411,2135,0,vsys1,FW04,from-policy,,,0,,0,,N/A,0,0,0,0,6d4f58b2-5528-474b-b85a-b371f6d82177,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-15T18:47:49.996+00:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 15 18:47:51 palo_alto_panarama_host 1,2022/08/15 18:47:51,012501003398,TRAFFIC,end,2561,2022/08/15 18:47:49,10.37.0.29,10.13.5.2,0.0.0.0,0.0.0.0,dns-services,local_domain\userone,,dns-base,vsys1,corp_trust,corp_dc,ae8.1852,ae8.1854,Panorama,2022/08/15 18:47:49,72223499,1,60737,53,0,0,0x19,udp,allow,317,92,225,2,2022/08/15 18:47:18,0,any,,7107085280655064783,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.
PRI=13
MESSAGE=255.255,,1,1,aged-out,1634,2411,2135,0,vsys1,FW04,from-policy,,,0,,0,,N/A,0,0,0,0,6d4f58b2-5528-474b-b85a-b371f6d82177,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-15T18:47:49.996+00:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 15 18:47:51 palo_alto_panarama_host 1,2022/08/15 18:47:51,012501003398,TRAFFIC,end,2561,2022/08/15 18:47:49,10.27.0.29,10.13.5.2,0.0.0.0,0.0.0.0,dns-services,local_domain\userone,,dns-base,vsys1,corp_trust,corp_dc,ae8.1852,ae8.1854,Panorama,2022/08/15 18:47:49,72223499,1,60737,53,0,0,0x19,udp,allow,317,92,225,2,2022/08/15 18:47:18,0,any,,7107085280655064783,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.

notice if I take the end of the message and place it at the beginning, the log is correct
It should look like this:

MESSAGE=<14>Aug 15 18:47:51 palo_alto_panarama_host 1,2022/08/15 18:47:51,012501003398,TRAFFIC,end,2561,2022/08/15 18:47:49,10.27.0.29,10.13.5.2,0.0.0.0,0.0.0.0,dns-services,local_domain\userone,,dns-base,vsys1,corp_trust,corp_dc,ae8.1852,ae8.1854,Panorama,2022/08/15 18:47:49,72223499,1,60737,53,0,0,0x19,udp,allow,317,92,225,2,2022/08/15 18:47:18,0,any,,7107085280655064783,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.255.255,,1,1,aged-out,1634,2411,2135,0,vsys1,FW04,from-policy,,,0,,0,,N/A,0,0,0,0,6d4f58b2-5528-474b-b85a-b371f6d82177,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-15T18:47:49.996+00:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0

**Comment by ryanfaircloth** [comment]
You have an invalid host name throwing off the parser host names can have -
but not _ per rfc

**Comment by rjha-splunk** [comment]
As @ryanfaircloth mentioned the issue is with the naming of the host( as per RFC).

**Comment by Jaxjohnny** [comment]
That was not the real hostname.  the actual hostnames do not have underbars in them  i changed the hostname so our internal name was not posted

**Comment by Jaxjohnny** [comment]
i changed the hostname so the internal name did not show up on this forum.  

here is a better example.  i replaced out internal name with HOSTNAME.domainname.local.  i also replaced the internal ip with bogus ip.  

RAWMSG=:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 17 13:40:10 HOSTNAME.domainname.local 1,2022/08/17 13:40:10,015557000011303,TRAFFIC,end,2561,2022/08/17 13:40:03,29.0.1.25,10.1.1.1,0.0.0.0,0.0.0.0,sp-infra-services-appid,,,dns-base,vsys1,COM.Corp.CustomerRAS,trusted,tunnel.301,ethernet1/2,Panorama,2022/08/17 13:40:03,2262754,1,65260,53,0,0,0x19,udp,allow,23,9,18,2,2022/08/17 13:39:31,0,any,,7107019966429982667,0x8000000000000000,United States,10.0.0.0-10.255.255.255,,1,1,aged-out,2491,2492,0,0,,prodhafw01,from-policy,,,0,,0,,N/A,0,0,0,0,09333c73-6433-433f-be8c-26613b48f10e,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-17T13:40:03.686+00
PRI=13
MESSAGE=:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 17 13:40:10 HOSTNAME.domainname.local 1,2022/08/17 13:40:10,015557000011303,TRAFFIC,end,2561,2022/08/17 13:40:03,29.0.1.25,10.1.1.1,0.0.0.0,0.0.0.0,infra-services-appid,,,dns-base,vsys1,COM.Corp.CustomerRAS,trusted,tunnel.301,ethernet1/2,Panorama,2022/08/17 13:40:03,2262754,1,65260,53,0,0,0x19,udp,allow,23,9,13,2,2022/08/17 13:39:31,0,any,,7107019966429982667,0x8000000000000000,United States,10.0.0.0-10.255.255.255,,1,1,aged-out,2491,2492,0,0,,prodhafw01,from-policy,,,0,,0,,N/A,0,0,0,0,09e33373-6330-453f-be8c-26613b48f10e,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-17T13:40:03.686+00
