### ISSUE TITLE
Palo Alto Broken Split events

### ISSUE THREAD

**Issue by Jaxjohnny** [splunk/splunk-connect-for-syslog#1789]
Apologies if this is a duplicate. 
most of our events are coming in perfectly from Palo Alto Panorama devices. The log collector is used

the end of the message is after the beginning of the message

i changed the hostname so the internal name did not show up on this forum.

here is a better example. i replaced out internal name with HOSTNAME.domainname.local. i also replaced the internal ip with bogus ip.

RAWMSG=:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 17 13:40:10 HOSTNAME.domainname.local 1,2022/08/17 13:40:10,015557000011303,TRAFFIC,end,2561,2022/08/17 13:40:03,29.0.1.25,10.1.1.1,0.0.0.0,0.0.0.0,sp-infra-services-appid,,,dns-base,vsys1,COM.Corp.CustomerRAS,trusted,tunnel.301,ethernet1/2,Panorama,2022/08/17 13:40:03,2262754,1,65260,53,0,0,0x19,udp,allow,23,9,18,2,2022/08/17 13:39:31,0,any,,7107019966429982667,0x8000000000000000,United States,10.0.0.0-10.255.255.255,,1,1,aged-out,2491,2492,0,0,,prodhafw01,from-policy,,,0,,0,,N/A,0,0,0,0,09333c73-6433-433f-be8c-26613b48f10e,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-17T13:40:03.686+00
PRI=13
MESSAGE=:00,,,infrastructure,networking,network-protocol,3,"used-by-malware,has-known-vulnerability,pervasive-use",dns,dns-base,no,no,0
<14>Aug 17 13:40:10 HOSTNAME.domainname.local 1,2022/08/17 13:40:10,015557000011303,TRAFFIC,end,2561,2022/08/17 13:40:03,29.0.1.25,10.1.1.1,0.0.0.0,0.0.0.0,infra-services-appid,,,dns-base,vsys1,COM.Corp.CustomerRAS,trusted,tunnel.301,ethernet1/2,Panorama,2022/08/17 13:40:03,2262754,1,65260,53,0,0,0x19,udp,allow,23,9,13,2,2022/08/17 13:39:31,0,any,,7107019966429982667,0x8000000000000000,United States,10.0.0.0-10.255.255.255,,1,1,aged-out,2491,2492,0,0,,prodhafw01,from-policy,,,0,,0,,N/A,0,0,0,0,09e33373-6330-453f-be8c-26613b48f10e,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-17T13:40:03.686+00

**Comment by rjha-splunk** [comment]
Can you attach the real message from tcpdump after redacting the sensitive data, the message is not very clear to me how it should look like and what is broken.

**Comment by Jaxjohnny** [comment]
I found a tcpdump sanitizer, but it only modifies the source and destination ip.

How do i remove sensitive data from a pcap?  I've searched for a way, but could not find one.  

Thank you so much

johnny

**Comment by rjha-splunk** [comment]
please download pcap , open it in wireshark > statistics > follow stream > copy it in text file, replace the sensitive data and attach the text file here.

**Comment by Jaxjohnny** [comment]
wow, thank you.  i'll get this done.

**Comment by Jaxjohnny** [comment]
Frame 9: 887 bytes on wire (7096 bits), 887 bytes captured (7096 bits)
Ethernet II, Src: Microsof_0a:d2:39 (2:8:8:0a:d2:39), Dst: Microsof_e5:5f:97 (00:0d:3a:e5:5f:97)
Internet Protocol Version 4, Src: 10.14.18.4, Dst: 10.14.6.44
User Datagram Protocol, Src Port: 48908, Dst Port: 514
 [truncated]Syslog message: USER.INFO: Aug 19 14:18:00 HOSTNAME.domain.local 1,2022/08/19 14:18:00,012501004608,TRAFFIC,end,2561,2022/08/19 14:18:00,10.2.10.27,52.17.23.13,10.8.7.1,5.17.23.13,Permit Outbound PaaS S
    0000 1... = Facility: USER - random user-level messages (1)
    .... .110 = Level: INFO - informational (6)
    Message [truncated]: Aug 19 14:18:00 HOSTNAME.domain.local 1,2022/08/19 14:18:00,012501004608,TRAFFIC,end,2561,2022/08/19 14:18:00,10.21.10.27,52.17.23.13,10.8.7.1,5.17.23.13,Permit Outbound PaaS Service,,,ssl,vsys4
        Syslog timestamp (RFC3164): Aug 19 14:18:00
        Syslog hostname: HOSTNAME.domain.local
        Syslog process id: 1
        Syslog message id [truncated]: ,2022/08/19 14:18:00,012501004608,TRAFFIC,end,2561,2022/08/19 14:18:00,10.21.150.27,5.17.223.13,170.88.7.1,52.147.223.103,Permit Outbound PaaS Service,,,ssl,vsys4,CO.PaaS.Trust,Internet,ae8.1858,ae7.28


<14>Aug 19 14:18:00 HOSTNAME.domain.local 1,2022/08/19 14:18:00,012501004608,TRAFFIC,end,2561,2022/08/19 14:18:00,10.20.34.15,5.17.23.13,10.88.7.9,5.17.23.13,Permit Outbound PaaS Service,,,ssl,vsys4,CO.PaaS.Trust,Internet,ae8.1858,ae7.2858,Panorama,2022/08/19 14:18:00,75872209,1,61842,443,7676,443,0x40047a,tcp,allow,29859,24319,5540,48,2022/08/19 14:15:26,150,computer-and-internet-info,,7107083029716908336,0x8000000000000000,10.0.0.0-10.255.255.255,United States,,29,19,tcp-rst-from-server,1634,2428,2429,0,PaaS,FW02,from-policy,,,0,,0,,N/A,0,0,0,0,6a4403ff-d389-411f-a118-e9c22726b656,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-19T14:18:00.190+00:00,,,encrypted-tunnel,networking,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no,0
<14>Aug 19 14:18:00 HOSTNAME.domain.local 1,2022/08/19 14:18:00,012501004608,TRAFFIC,end,2561,2022/08/19 14:18:00,10.110.129.60,10.164.8.147,0.0.0.0,0.0.0.0,GP.ToCorp-TrustedUser,COsecure\6075457,COglobal\ersol,ssl,vsys1,CO.Corp.EmployeeRAS,CO.Corp.Trust,tunnel.201,ae8.1851,Panorama,2022/08/19 14:18:00,68084939,1,51663,17472,0,0,0x10047a,tcp,allow,9816,2976,6840,22,2022/08/19 14:17:40,16,private-ip-addresses,,7107083029716908337,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.255.255,,11,11,tcp-fin,1634,2261,2101,0,vsys1,FW02,from-policy,,,0,,0,,N/A,0,0,0,0,3233341c-a133-4933-bd43-d75158f7aed5,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-08-19T14:18:00.190+00:00,,,encrypted-tunnel,networking,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no,0

**Comment by Jaxjohnny** [comment]
Seems these "truncated" events are not even populating in splunk fall back index

**Comment by Jaxjohnny** [comment]
interestingly enough, this only seem to happen with hostnames that come over with all capitals in the name

so hostname.domain.local is working but HOSTNAME.domain.local is not.

**Comment by rjha-splunk** [comment]
As mentioned "interestingly enough, this only seem to happen with hostnames that come over with all capitals in the name

so hostname.domain.local is working but HOSTNAME.domain.local is not." , as the hostname should be always capital as per RFC standards , it is not working , SC4S is working as expected and designed.

**Comment by Jaxjohnny** [comment]
Thank you
