### ISSUE TITLE
Support/Document custom listener like SC4S_LISTEN_VENDOR_PRODUCT_EXTRA_STRINGS_PROTO_PORT

### ISSUE THREAD

**Issue by jrehm-mmm** [splunk/splunk-connect-for-syslog#1792]
In the context of customizing LISTENers for existing VP sources...

I have discovered that adding additonal custom value(s) separated by _ allow us to help filter by source tags and still automatically assign the vendor and product.  It's a quirk of the regex parsing that is not caring what comes after <_PRODUCT_> and before _<PROTO>_<PORT>

**Example**
SC4S_LISTEN_**CISCO_ASA_CSM-GCA**_UDP_PORT=18514
sets 
- vendor=cisco
- product=asa
- tag = .source.s_CISCO_ASA_CSM-GCA

Ryan says this is a loophole not intended to work that way, but agrees it's a "neat trick" and suggested documentation.  In my case it will be quite handy because we want to have 5 different Cisco_ASA ports open and filter them to indexes based only on port.  This will allow me to get away from having to manage like 30+ filter rules related to naming conventions at a global company and DNS resolution inconsistancies.  I get at least 1 ticket or communication every week saying, "I don't see data for firewall X in index Y"...and it turns out that they didn't follow the global naming convention or there is a legacy DNS rule taking precidence.

If I were to use just SC4S_LISTEN_**CSM_GCA**_UDP_PORT, then it would set vendor=csm product=gca, and I'd need to use additional pre and/or post-filters adding significant complexities.

**MY REQEUST**
1) Is there anything you all can think of as to where this might not work as I expect?
2) Are you OK with accepting this an acceptable filtering utility?
3) If so, please document it so that
   a) users are aware of it
   b) developers don't intentionally or accidenly break how it works today. 

Thanks for your efforts!

**Comment by mateuszpierzchala-splunk** [comment]
Hi, I reviewed the code and potential use cases and I do not see any obstacles. I will prepare small documentation update on this. Thank for bringing that out!

**Comment by mateuszpierzchala-splunk** [comment]
closed by #1794
