### ISSUE TITLE
New Source: Trend Micro Apex Central

### ISSUE THREAD

**Issue by ehlo550** [splunk/splunk-connect-for-syslog#1793]
Hi,
It would be nice to get a new Sourcetype for TrendMicro Apex Central logs.

I was able to onboard via the normal cef workflow but there is an error with the time parsing from rt field in sc4s_error:

`dtparse: Expected: '%s.%f', '%s', '%b %d %T', '%b %d %T UTC', '%b %d %T %Z', '%b %d %Y %T', '%b %d %Y %T UTC', '%b %d %Y %T %Z', ; Actual: Aug 22 2022 12:10:12 GMT+00:00`

For testing:
`echo '<41>Aug 22 12:10:50 1.1.1.1 CEF:0|Trend Micro|Apex Central|2019|AV:File quarantined|Eicar_test_file|3|deviceExternalId=2 rt=Aug 22 2022 12:10:12 GMT+00:00 cnt=1 dhost=TESTAV02 TMCMLogDetectedHost=TESTAV02 duser=TEST\\abcdef act=File quarantined cn1Label=Pattern cn1=1771500 cn2Label=Second_Action cn2=4 cs1Label=VLF_FunctionCode cs1=Real-time Scan cs2Label=Engine cs2=21.600.1005 cs3Label=Product_Version cs3=14.0 cs4Label=CLF_ReasonCode cs4=virus log cs5Label=First_Action_Result cs5=Unable to clean file cs6Label=Second_Action_Result cs6=File quarantined cat=1703 dvchost=TESTAV02 cn3Label=Overall_Risk_Rating cn3=1 fname=eicar_test.com filePath=C:\\TEST\\TEST\\ dst=10.10.10.10 TMCMLogDetectedIP=10.10.10.20 fileHash=3395856CE81F2B7382DEE72602F798B642F14140 deviceFacility=Apex One ApexCentralHost=TESTAV03 devicePayloadId=000000000000-00000000-0000-0000-0000 deviceNtDomain=N/A dntdom=Testapex\\ ' | nc IP 514`

As far as I understand: 
`'%b %d %Y %T %Z%z',`
has to be added to https://github.com/splunk/splunk-connect-for-syslog/blob/fc1325b10bd57ffe413a9ad5ef379254a4bffacd/package/etc/conf.d/conflib/syslog/app-syslog-cef.conf

Regards

**Comment by rjha-splunk** [comment]
```
block parser app-cef-trendmicroapex() {
        channel {
              parser {
              date-parser-nofilter(format(
                          '%b %d %Y %T %Z%z',
                          )
                          template("${.values.rt}")
              );
          };
            rewrite {
                    r_set_splunk_dest_update_v2(
                        index('test_sc4s'),
                        sourcetype('apexcentralsyslog')
                    );
            };
            rewrite {
                    unset(value('fields.sc4s_error'));
        };
      };
    };

    application app-cef-trendmicroapex[sc4s-postfilter] {
      filter{
            "Trend Micro" eq "${fields.sc4s_vendor}"
            and "Apex Central" eq "${fields.sc4s_product}";
        };
        parser { app-cef-trendmicroapex(); };
    };
```

Please use above code in local conf to use local data parser using value in .rt field and it will drop the error.
