### ISSUE TITLE
Cisco FTD parsing issue

### ISSUE THREAD

**Issue by Mosstrow** [splunk/splunk-connect-for-syslog#1798]
Hello Support,

Could you please adapt the filter for Cisco Firepower (FTD) logs to match the Cisco TA estreamer ?

FTD-7-430001-> 430003 & 430005 should use the sourcetype "cisco:firepower:syslog"

Logs example:
`%FTD-7-430002: EventPriority: Low, DeviceUUID: 577d68c2-369f-11ec-bae3-f3adb6c2041c, FirstPacketSecond: 2022-08-31T14:56:13Z, ConnectionID: 0, AccessControlRuleAction: Block, SrcIP: 10.10.10.220, DstIP: 239.255.255.250, SrcPort: 60903, DstPort: 1900, Protocol: udp, IngressInterface: user, IngressZone: user, IngressVRF: VRF_USER, EgressVRF: USER, Endpoint Profile: Invalid ID, ACPolicy: IPS_LAN, AccessControlRuleName: FINAL_DROP, Prefilter Policy: PFP_ALLOW, InitiatorPackets: 0, ResponderPackets: 0, InitiatorBytes: 0, ResponderBytes: 0, NAPPolicy: USER_LAN_IPS`

Non-FTD with sourcetype "cisco:asa"
`%FTD-7-710005: UDP request discarded from 10.10.10.76/57798 to user:224.0.0.252/5355`

Thanks

**Comment by rjha-splunk** [comment]
Please implement following code in path and restart SC4S and it will exactly do as above 
`/opt/sc4s/local/config/filters/app-dest-cisco-ftd_selective-postfilter.conf`

```
block parser app-dest-cisco-ftd_selective-postfilter() {
    channel {
        rewrite {
            r_set_splunk_dest_default(
                sourcetype('cisco:firepower:syslog')
                vendor('cisco')
                product('firepower')
                class('syslog')
            );
        };
    };
};

application app-dest-cisco-ftd_selective-postfilter[sc4s-postfilter] {
    filter {
        message('\s*%FTD-\d-43000[1-3,5]')
    };
    parser { app-dest-cisco-ftd_selective-postfilter(); };
};
```
