### ISSUE TITLE
zscaler (nss-fw and nss-dns) not correctly setting timestamp

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#1799]
For both `sourcetype=zscalernss-dns` and `sourcetype=zscalernss-fw` the `_time` of the event is the time sc4s received the event(`sc4s_recv_time`) instead of the actual timestamp of the event (see attached screenshot).

![image](https://user-images.githubusercontent.com/22804652/187929282-3b3d5235-b93e-4d24-9ba1-fc16709b33bf.png)

P.S. I'm also in contact with the vendor about increasing the granularity of the timestamps to include milliseconds. This will most likely be done via a logging template update on the zscaler side. This might throw a wrench in automatically extracting the timestamp from the event so thought it worth mentioning.

**Comment by rjha-splunk** [comment]
There is extra "datetime" word in front which is breaking KV pair, Please use following to correct the time stamp 
`/opt/sc4s/local/config/filters/app-dest-rewrite-zscaler_dns_postfilter.conf` create this file and restart sc4s it will fix the timestamp.
```
block parser app-dest-rewrite-zscaler_dns_postfilter() {
    channel {
        if {
            parser {
                regexp-parser(
                    prefix(".tmp.")
                    patterns('^datetime=(?<timestamp>\w+\s*\w+\s*\d+\s*\d+\:\d+\:\d+\s*\d{4})\s*(?<message>.+)')
                    template("$MESSAGE")
                );
                date-parser-nofilter(format(
                          '%a %b %d %H:%M:%S %Y'
                          )
                          template("${.tmp.timestamp}")
              );
            };
           rewrite {
               set("${.tmp.timestamp} ${.tmp.message}" value("MESSAGE"));
            };
        };
    };
};
application app-dest-rewrite-zscaler_dns_postfilter[sc4s-postfilter] {
       filter{
            "dns" eq "${fields.sc4s_class}"
            and "nss" eq "${fields.sc4s_product}";
        };
    parser { app-dest-rewrite-zscaler_dns_postfilter(); };
};
```
