### ISSUE TITLE
Wrong sourcetype on Sonicwall + incorrect format

### ISSUE THREAD

**Issue by nbertram-splunk** [splunk/splunk-connect-for-syslog#1809]
package/etc/conf.d/conflib/syslog/app-syslog-dell_sonicwall-firewall.conf

Sourcetype needs to be changed to "dell:sonicwall" in order for it to work with the TA that the SC4S docs point to - https://splunkbase.splunk.com/app/6203/

Also, this source defaults to being sent in JSON format, which is not supported by the TA. Customers have to add "SC4S_DEST_DELL_SONICWALL-FIREWALL_SPLUNK_HEC_FMT=none" to have this work with the TA since it's expecting raw format, not JSON.

**Comment by rjha-splunk** [comment]
We need to understand if the requirement is to change the sourcetype, do you mind sharing the anonymised sample

**Comment by nbertram-splunk** [comment]
I don't have a sample (customer engagement ended) but if it helps you can download the TA you're linking in the documentation and in props.conf you'll see the sourcetype being set in app-syslog-dell_sonicwall-firewall.conf does not match.

**Comment by mateuszpierzchala-splunk** [comment]
Hi, thanks for reporting this issue. The sourcetype indeed should be fixed to match TA, but regarding JSON messages it is a documented feature that our clients are using so this will not be changed.

**Comment by mateuszpierzchala-splunk** [comment]
closed by #1821
