### ISSUE TITLE
Support delivery to Kafka

### ISSUE THREAD

**Issue by MadsRC** [splunk/splunk-connect-for-syslog#181]
It would be great if SC4S could deliver events directly to a Kafka topic, instead of sending it to the HEC. We have a use case for this where we do not wish to send it directly to Splunk, as we need to do stream analysis and archiving before it arrives to Splunk.

It seems that syslog-ng can already be used as a producer for Kafka, which should make it only a matter of configuration. I'm thinking of just sending the event, as it would be formatted when sending to the HEC, directly to a single topic.

Alternatively, messages for index A could be put into topic A and messages for index B could be put into topic B.

I'm gonna give it a shot and hopefully send back a PR!

**Comment by rfaircloth-splunk** [comment]
this is presently roadmapped for v2. The intention is to use gomplate to allow an env var to switch the output from hec to kafka globally or on a case by case basis. Splunk Connect for Kafka can take these events from the topic and push them to Splunk in the case

**Comment by rfaircloth-splunk** [comment]
For this PR we will need to do the following

- create a working Docker-compose with zookeeper, kafka, kafka-connect and latest splunk connect for kafka
- enhance circle CI to run a a test sequence that repeats all tests in the current build using kafka path
- provide a getting started document describing a deployment which may reference external docs

**Comment by rfaircloth-splunk** [comment]
This request is blocked by the librdkafka driver on centos8 the current confluent version is out of date

**Comment by rfaircloth-splunk** [comment]
Cleaning up tickets this was resolved around Jan of 2020 we failed to link and close the ticket
