### ISSUE TITLE
Customized syslog - anomalous header - timestamp and host extraction

### ISSUE THREAD

**Issue by lucalopreiato** [splunk/splunk-connect-for-syslog#1811]
Hello,

i have a customized syslog with an anomalous header, sc4s won't extract timestamp and host, can it be fixed?

<86>Original Address=123.123.123.123 Sep  6 10:32:40 host01name02 sshd[13721]: Accepted keyboard-interactive/pam for user001 from 123.123.123.123 port 54952 ssh2
<86>Original Address=123.123.123.123 Sep  6 14:30:43 host01name02 sshd[30999]: Accepted keyboard-interactive/pam for user002 from 123.123.123.123 port 59680 ssh2
<86>Original Address=10.239.7.21 Sep  6 14:30:45 host01name03 sshd[10676]: Accepted keyboard-interactive/pam for user002 from 123.123.123.123 port 59684 ssh2
<86>Original Address=123.123.123.123 Sep 13 10:39:46 host01name02 sshd[22853]: Accepted keyboard-interactive/pam for user002 from 123.123.123.123 port 53089 ssh2

thanks
Luca

**Comment by rjha-splunk** [comment]
```
block parser app-dest-rewrite-custom_postfilter() {
    channel {
        if {
            parser {
                regexp-parser(
                    prefix(".tmp.")
                    patterns('(?<address>[^ ]+)\s+(?<timestamp>\w+\s+\d{0,2}\s+\d{2}\:\d{2}\:\d{2})\s+(?<host>[^, ]+)(?: |,)\s*(?:[^ ])+\s+(?<msg>.+)')
                    template("$MESSAGE")
                );
                date-parser-nofilter(format(
                          '%b %d %H:%M:%S'
                          )
                          template("${.tmp.timestamp}")
              );
            };
           rewrite {
               set("${.tmp.msg}" value("MESSAGE"));
            };
           rewrite {
               set("${.tmp.host}" value("HOST"));
            };
        };
    };
};
application app-dest-rewrite-custom_postfilter[sc4s-postfilter] {
    parser { app-dest-rewrite-custom_postfilter(); };
};
```
This is how you can set host and timestamp for the event , you can use example to set index and  vendor, product and all

**Comment by ryanfaircloth** [comment]
This structure implies a poorly configured syslog relay which is a worst
practice. Forwarding in RFC5424 setting the original value as sdata is
considered proper.

The advice to use post filter here is incorrect. The right solution is use
the "almost-syslog" topic instead so normal processing can be applied for
the least cost

**Comment by rjha-splunk** [comment]
Yes i agree With @ryanfaircloth , i missed to consider the cost implications here, please use almost-syslog that will be better.
