### ISSUE TITLE
Cannot parse hostname containing "@" from BSD syslog format

### ISSUE THREAD

**Issue by rlai0013** [splunk/splunk-connect-for-syslog#1819]
Hi team,

I've set up some Dell EMC storage devices via the "simple log path by port" method.
I've run into a bug(?) with one of them (Unity storage) where the host and program fields aren't parsed from the logs. Have done a bit of testing and it seems to be because the message includes a hostname and serial number separated by an "@", e.g. "host-name_here@ABC0123456789".
This previously worked in older versions of SC4S - we upgraded from 1.107.1 to 2.33.0.

Sample log: 
<12>Sep 20 00:23:01 host-name_here@AZ0123456789 Mnsvc_unique[13255]:  "2022-09-20T00:23:01.942Z" "host-name_here@AZ0123456789" "Mnsvc_unique" "13255" "unix/spa/root" "WARN" "1:7D9" :: "Authentication session Session_25_1662702229: User my-user0123 failed to authenticate in authority LocalDirectory/Local" :: Category=Authentication Component=MnsvcServer TimeZone=UTC

In version 1.107.1, we would get:
- host = host-name_here@az0123456789
- source = program:Mnsvc_unique

In version 2.33.0, we get:
- host = \<source IP\>
- source = program:

Would love a fix/change to have the host parsed from the message as it was in previous versions.

Thanks!

**Comment by rjha-splunk** [comment]
@rlai0013 

```
block parser app-dest-rewrite-unix_postfilter() {
    channel {

        filter {
            match('Mnsvc' value("MESSAGE") flags(ignore-case));
        };
        if {
            parser {
                regexp-parser(
                    prefix(".tmp.")
                    patterns('(?<host>[^ ]+)\s*(?<message>(?:(?<prgm>.+)(?:\[\d+\]+))\:\s*(?:.+))')
                    template("$MESSAGE")
                );
            };
           rewrite {
               set("${.tmp.message}" value("MESSAGE"));
            };
           rewrite {
               set("${.tmp.host}" value("HOST"));
               set("${.tmp.prgm}", value(".PROGRAM"));
            };
           rewrite {
           r_set_splunk_dest_default(
                source('program:${.tmp.prgm}')
                sourcetype('dell_custom')
            );
          };
        };
    };
};
application app-dest-rewrite-unix_postfilter[sc4s-postfilter] {
    parser { app-dest-rewrite-unix_postfilter(); };
};
```

Please note following points:

1. The sourcetype is set to dell_custom, change it to as you feel right
2. Right now its filtering on Mnsvc , please feel free to change it to other strings
3. The hostname should be RFC compliant.

**Comment by rlai0013** [comment]
Thanks for your help @rjha-splunk
