### ISSUE TITLE
d_rawmsg debug destination doesn't work

### ISSUE THREAD

**Issue by cchantrey** [splunk/splunk-connect-for-syslog#1825]
Docs mention using a `d_rawmsg` destination to log raw messages locally in /opt/sc4s/archive by sourcetype. How to enable this isn't mentioned. Some info in Slack lead to adding `SC4S_DEST_GLOBAL_ALTERNATES=d_rawmsg` to the env_file, but this doesn't work and may be from a previous version. Confirmation of this functionality and instruction to enable it is needed.

**Comment by rjha-splunk** [comment]
For now it can be implemented using templating , GLOBAL_ALTERNATES are nearly deprecated, i am posting an example below how you can see the RAWMSG , it is not good practise to do it in this way , its very costly process.
```
block parser app-postfilter-cisco_asa_new_metadata() {
    channel {
       rewrite {
           r_set_splunk_dest_default(
               index("test_sc4s")
               template('t_fallback_kv')
           );
       };
   };
};
application app-postfilter-cisco_asa_new_metadata[sc4s-postfilter] {
    filter {
        'cisco' eq "${fields.sc4s_vendor}"
        and 'asa' eq "${fields.sc4s_product}"
    };    
    parser { app-postfilter-cisco_asa_new_metadata(); };
};
```
It will append all the cisco asa message with RAWMSG, please feel free to change it as per your usecase.
