### ISSUE TITLE
VMware vSphere Postfilters - Empty Vendor 

### ISSUE THREAD

**Issue by mikelaz** [splunk/splunk-connect-for-syslog#1826]
Hi,

I have recently discovered that several events from our VMware ESXi servers were being indexed on Splunk with no value on the sc4s.vendor field.
After reviewing our environment and configuration I reviewed the code and saw that on all the VMware related postfilter files there was the following line on the aggregation part of the code:
`value("fields.sc4s_vendor", "${fields.sourcetype}@1")`
Followeb by:
`value("fields.sc4s_product", "${fields.sc4s_product}@1") `

I modified the line to:
`value("fields.sc4s_vendor", "${fields.sc4s_vendor}@1")`
On each file and since then I have verified that no VMware event has an empty value on the sc4s_vendor field.

Thanks for your effort on developing this great solution!

Best regards

**Comment by rjha-splunk** [comment]
Thank you for pointing it out, we will release the fix shortly.
