### ISSUE TITLE
Gigamon SSL Session Syslog

### ISSUE THREAD

**Issue by cchansk** [splunk/splunk-connect-for-syslog#1833]
Recently, after restarting the service and updating to a new version (2.35.0), I started seeing having certain issues with my Gigamon SSL session logs where 8 different devices with different source IPs are showing up with host=sep. They host field used to show up with the source IP. I tried modifying the host.csv file and adding the SC4S_USE_REVERSE_DNS variable to see if I can manually change it to a name, but had no luck. Wanted to see if anyone knows why that'd be happening.

Below is what some events look like:

Wed CEF:0|Gigamon|HC1|5.15.01|1002|SESSION_DECRYPT|6|src=10.40.24.148 dst=138.113.112.18 spt=53699 dpt=443 vlan=100 dhost=newseu.cgtn.com cs1Label=Certificate Subject cs1=*.cgtn.com cs2Label=Certificate Issuer cs2=Zscaler Intermediate Root CA (zscloud.net) (t) cs3Label=Cipher Suite cs3=TLS_AES_256_GCM_SHA384 proto=TLS/SSL outbound GigamonIsslTLSVersion=TLSv1.3 GigamonIsslCertStatus=Valid

Wed CEF:0|Gigamon|HC1|5.15.01|1001|SESSION_NO_DECRYPT|6|src=10.40.200.62 dst=20.106.86.13 spt=63240 dpt=443 vlan=100 dhost=settings-win.data.microsoft.com proto=TLS/SSL reason=Policy

**Comment by rjha-splunk** [comment]
https://splunk.github.io/splunk-connect-for-syslog/main/experiments/ Use the property
SC4S_USE_NAME_CACHE=yes to fix it, We dont think its because of upgrade.

**Comment by cchansk** [comment]
The setting does not seem to have helped. Added it to the env_file, and restarted sc4s.

SC4S_DEST_SPLUNK_HEC_DEFAULT_URL=https://splunkreceiver.domain.com:8088
SC4S_DEST_SPLUNK_HEC_DEFAULT_TOKEN=<token>
#Uncomment the following line if using untrusted SSL certificates
SC4S_DEST_SPLUNK_HEC_DEFAULT_TLS_VERIFY=no
SC4S_LISTEN_SIMPLE_EXTREMEIQ_AEROHIVE_UDP_PORT=1514
SC4S_USE_NAME_CACHE=yes

**Comment by rjha-splunk** [comment]
The setting will help if it will send any event which is parsed correctly by sc4s.

**Comment by rjha-splunk** [comment]
also can you attached pcap and sanitized log with header so that we can see if you are receiving it on the wire and what is not working.

**Comment by cchansk** [comment]
Just an update - the host field changed to oct. I couldn't for the life of me figure out where it got sep from (I thought it was like an abbrv for some product), but I guess it's actually parsing the month into the host field.

**Comment by cchansk** [comment]
Just wanted to follow up to see if what I provided was enough.

**Comment by rjha-splunk** [comment]
Thanks it is enough for now, i will get back after reviewing all the provided input and attachment asap.

**Comment by cchansk** [comment]
Wanted to bump this

**Comment by mstopa-splunk** [comment]
Hi, I'm closing this issue due to the now outdated version of SC4S, but feel free to open a new issue if the problems persist on the latest release
