### ISSUE TITLE
Extra product description isn't working as expected

### ISSUE THREAD

**Issue by chrisengie** [splunk/splunk-connect-for-syslog#1834]
Hi,

Following our conversation in Slack (https://splunk-usergroups.slack.com/archives/CNV918JCQ/p1664459905826089), this is the issue:

Using the "Filtering by an extra product description" (docs https://splunk.github.io/splunk-connect-for-syslog/main/sources/#filtering-by-an-extra-product-description) with the listener below makes the parser of Infoblox not working. SC4S thinks it is vendor "isc" & product "bind":
SC4S_LISTEN_INFOBLOX_NIOS_CUSTOMTEST_TCP_PORT=30006

I tried to send the logs to the default UDP 514 and it is also being parsed as ISC BIND...

When I do :
SC4S_LISTEN_INFOBLOX_NIOS_TCP_PORT=30006
This works and get recognized as "infoblox:dns" with vendor "infoblox" and product "nios".

It looks like this feature "extra product description" breaks the parsing of infoblox (or more likely SC4S does not follow infoblox parser when there is this feature on).

Here are two screenshot from the Splunk GUI where you can see the result of ingesting infoblox data with the 2 listeners:

SC4S_LISTEN_INFOBLOX_NIOS_CUSTOMTEST_TCP_PORT=30006
![infoblox_notworking](https://user-images.githubusercontent.com/91262717/193070824-5e45bf1d-849a-41af-a001-c0d574a69d1f.jpg)

SC4S_LISTEN_INFOBLOX_NIOS_TCP_PORT=30006
![infoblox_working](https://user-images.githubusercontent.com/91262717/193070831-ae974c37-8548-4611-b0d4-f15d589d791e.jpg)

**Comment by rjha-splunk** [comment]
fixed in release 2.42.0
