### ISSUE TITLE
vmware_vsphere - esx multiple programs going to fallback 

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#1838]
I've found the following that aren't accurately being captured as `class=esx`. There could be more this is just over a 1hr period.

| source |
| --- |
| program:esxupdate |
| program:healthd |
| program:ConfigStore |
| program:crond |
| program:kmxa |
| program:crx-cli |
| program:backup.sh |
| program:configStoreBackup |
| program:heartbeat |

SC4S also appears to be injecting `[meta sequenceId="4330150"]` into events. Not sure if this is needed later for other Splunk apps, but wanted to bring it up because I don't think it is.

**RAW**  
`<166>2022-10-01T11:09:32.770Z hypervisor01 Hostd: info hostd[2100080] [Originator@6876 sub=Vimsvc.TaskManager opID=2e195085 user=vpxuser] Task Created : haTask--vim.InternalStatsCollector.queryLatestVmStats-2475465895`

**Splunk via SC4S**
`- - hostd 2100080 - [originator@6876 sub="Vimsvc.TaskManager" opID="2e195085" user="vpxuser"][meta sequenceId="4330150"]Task Created : haTask--vim.InternalStatsCollector.queryLatestVmStats-2475465895`

**Comment by mateuszpierzchala-splunk** [comment]
closed by #1884
