### ISSUE TITLE
Migrating Disk Buffer from one SC4S instance to another

### ISSUE THREAD

**Issue by kobz360** [splunk/splunk-connect-for-syslog#1843]
Hi Team, I had a question/scenario to pose to you: 

Let's say I was able to backup the my reliable disk buffering directory for SC4S and detach it from Instance 1. Would I be able to "plug and play" said directory/disk into a second instance, which would then read the buffer and send it to the HEC destination as normal? Or is this not really possible, likely due to much of the metadata and operations going on beneath the surface?

Thanks guys and hope you have an amazing day.

**Comment by mstopa-splunk** [comment]
Hi @kobz360 it's almost 2 years after your question but in case someone looks it up:

please start by reading this: https://axoflow.com/docs/axosyslog-core/chapter-routing-filters/concepts-diskbuffer/get-information-about-disk-buffer-files/diskb-proc-sep-sysl-inst/

Let us know if you have problems applying that to SC4S
