### ISSUE TITLE
Special F5 ASM format isn't parsed properly

### ISSUE THREAD

**Issue by chrisengie** [splunk/splunk-connect-for-syslog#1865]
Hi,

I've got F5 ASM logs going into fallback. Is there a way to parse it properly?

Here is an anonymized sample:

`f5_afm=Splunk-F5-AFM,source=mysource,acl_policy_name="/Common/DROP_EXTERNAL_STREAM",rule="DROP_TRAFIC",action="Drop",host="myhost",context_name="/Common/global-firewall-rules",date_time="Oct 13 2022 09:49:48",dest_ip="11.11.11.11",dest_port="8888",dest_port="9999",drop_reason="Policy",route_domain="0",src_ip="10.10.10.10",src_port="3000",src_zone="/Common/external"
`

Thanks

Here is the slack topic about it : https://splunk-usergroups.slack.com/archives/CNV918JCQ/p1665651684817379

**Comment by rjha-splunk** [comment]
Hi @chrisengie The message should be always with header (syslog) , please get it corrected from the vendor , although i am sharing you a way to get it done but i will not recommend it.
```
rewrite set_raw_f5_bigip_afm{
    set-tag("wireformat:raw_f5_bigip_norfc");
};
block parser app-syslog-f5_bigip_irule_afm() {
    channel {
        parser {
            regexp-parser(
                prefix(".tmp.")
                patterns('(?<message>(?<message_pre>f5_afm.*)\S+date_time="(?<timestamp>.+[^",])",dest_ip.*)')
            );
        };
        rewrite {
            set("${.tmp.message}", value("MESSAGE"));
        };
        parser {
            date-parser(
                format(
                    '%b %d %Y %H:%M:%S'
                )
                template("${.tmp.timestamp}")
            );
        };
        rewrite {
            r_set_splunk_dest_default(
                index("netwaf")
                sourcetype('f5:bigip:afm:syslog')
                vendor('f5')
                product('bigip')
                class("afm")
            );
        };
        #Note this should be RFC this tag is being set to allow routing to rfc destinations
        rewrite(set_raw_f5_bigip_afm);
        rewrite(r_set_source_identified);

   };
};
application app-syslog-f5_bigip_irule_afm[sc4s-raw-syslog] {
    parser { app-syslog-f5_bigip_irule_afm(); };
};
```
