### ISSUE TITLE
Logs catched incorrectly by app-almost-syslogz-hostnodate

### ISSUE THREAD

**Issue by mikelaz** [splunk/splunk-connect-for-syslog#1872]
Hi,

We have detected that audit logs from our Forcepoint WebProtect (only admin audit events, not the navigation events) are being catched by the app-almost-syslogz-hostnodate parser and therefore are being incorrectly parsed.

The issue is that the parser filter expects that the month in syslog logs come with the first letter in capitals followed by other 2 letters in lowercase but in this case (the audit events from Forcepoint), the month comes with the 3 letters in lowercase and it parses as Host-no-date events and the month is collected as hostname.

The current filter in app-almost-syslogz-hostnodate.conf is:

```
filter {
            not message('^\<\d+\> ?[A-Z][a-z]{2} ');
        };
```

An example of the events that we receive (anonimized):
`<156> oct 11 16:10:25 172.26.000.000 vendor=Forcepoint product=Security product_version=8.5.4 action=Log Off user={USER} reason={{Role:{_}},_{Type:{}},_{Element:{}},_{Values:{{Previous:_Source:10.0.0.0}{Current:_}}}}`

For this case and for us one solution would be change the filter to accept month names with the first letter in capitals as well as with all the letters in lowercase.

 ```
filter {
            not message('^\<\d+\> ?[A-Za-z][a-z]{2} ');
        };
```
Just in case you think that this change will not have any problem with another type of event.

Best regards,

Mikel

**Comment by bparmar-splunk** [comment]
@mikelaz,
Are you still facing this issue ?

**Comment by mikelaz** [comment]
Hi, we made some tests with the workaround that we were proposing without success and then we verified that the problem was that the audit logs came from a machine whose OS was in Spanish. As you can see on the following screenshot, even though the format was correct (%b for the month name) we were receiving the month names in lowercase:
 
![image](https://user-images.githubusercontent.com/16541558/213108963-4708d62a-5631-4482-abe6-e5886f0a5c6b.png)

The reason is that in Spanish the months are not named with the first letter in capitals and instead of receiving "Jan" for January we were receiving "ene" that is the abreviation of "enero".

We have finally deactivated the forwarding of these audit logs since they were not giving us relevant information.

Thanks a lot for your help.

**Comment by bparmar-splunk** [comment]
@mikelaz,
Thank you for the update.
We are closing this issue for now.

Please reach out in case of further queries.
