### ISSUE TITLE
New product name for Cisco ESA in CEF logs

### ISSUE THREAD

**Issue by mikelaz** [splunk/splunk-connect-for-syslog#1873]
Hi,

We have recently deployed one new Cisco ESA Appliance and we have discovered that the Device_Product field has been changed by Cisco in order to use the new commercial name of the solution:  Secure Email Gateway

We have created a new local conf file to recognize this new format using the following filter:

```
  filter{
        match("Cisco" value(".metadata.cef.device_vendor"))
        and match('C\d+V? Secure Email Gateway( Virtual)?' value(".metadata.cef.device_product"));
    };
```
It could be added to the current app-cef-cisco_esa.conf file and the new filter would be:

```
application app-cef-cisco_esa[cef] {
    filter{
        match("Cisco" value(".metadata.cef.device_vendor"))
        and ( 
            match('C\d+V? Email Security( Virtual)? Appliance' value(".metadata.cef.device_product"))
            or match('C\d+V? Secure Email Gateway( Virtual)?' value(".metadata.cef.device_product"))
        );
    };
    parser { app-cef-cisco_esa(); };
};

```
Best regards,

Mikel

**Comment by rjha-splunk** [comment]
Can you please attach an anonymised log so that we can add it out tests?

**Comment by mikelaz** [comment]
Hi,

Here you have two anonymised lines. I hope that will be useful for you.

CEF:0|Cisco|C300V Secure Email Gateway Virtual|14.2.0-620|ESA_CONSOLIDATED_LOG_EVENT|Consolidated Log Event|5|deviceExternalId=XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXX ESAMID=9999999 ESADCID=3333333 ESAAMPVerdict=NOT_EVALUATED ESAASVerdict=NOT_EVALUATED ESAAVVerdict=NOT_EVALUATED ESACFVerdict=NO_MATCH endTime=Fri Oct 21 11:05:36 2022 ESADLPVerdict=NOT_EVALUATED ESAGMVerdict=NOT_EVALUATED ESAMFVerdict=NOT_EVALUATED act=DELIVERED ESAOFVerdict=NOT_EVALUATED ESATLSOutCipher=ECDHE-RSA-AES256-GCM-SHA384 ESATLSOutConnStatus=Success ESATLSOutProtocol=TLSv1.2

CEF:0|Cisco|C300V Secure Email Gateway Virtual|14.2.0-620|ESA_CONSOLIDATED_LOG_EVENT|Consolidated Log Event|5|deviceExternalId=XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXX ESAMID=9999999 ESAICID=22222 ESADCID=3333333 ESAAMPVerdict=NOT_EVALUATED ESAASVerdict=NOT_EVALUATED ESAAVVerdict=NOT_EVALUATED ESACFVerdict=NO_MATCH endTime=Fri Oct 21 11:10:02 2022 ESADLPVerdict=NOT_EVALUATED dvc=172.26.0.0 ESAFriendlyFrom=mail@mail.com ESAGMVerdict=NOT_EVALUATED startTime=Fri Oct 21 11:10:02 2022 deviceOutboundInterface=OutgoingMail deviceDirection=1 ESAMailFlowPolicy=RELAY suser=mail@mail.com cs1Label=MailPolicy cs1=DEFAULT cs2Label=SenderCountry cs2=not enabled ESAMFVerdict=NOT_EVALUATED act=DELIVERED cs4Label=ExternalMsgID cs4='<635261e9.lFiApPMHkzd55Vmz%mail@mail.com>' ESAOFVerdict=NOT_EVALUATED duser=mail@mail.com ESAHeloDomain=machine.domain.net ESAHeloIP=10.0.0.0 cfp1Label=SBRSScore cfp1=not enabled sourceHostName=unknown ESASenderGroup=RELAYLIST sourceAddress=10.0.0.0 msg='MSG' ESATLSOutCipher=ECDHE-RSA-AES256-GCM-SHA384 ESATLSOutConnStatus=Success ESATLSOutProtocol=TLSv1.2
