### ISSUE TITLE
Where to put vendor parsers?

### ISSUE THREAD

**Issue by martynjlewis** [splunk/splunk-connect-for-syslog#1889]
Hi, my apologies if this isn't the right place to ask this question but I haven't been able to find a definitive answer anywhere else.
Can someone please advise where the config for the vendors should be placed? There are both the app-parsers and app_parsers directories but I'm not sure which to use.

**Comment by rjha-splunk** [comment]
Hi, please feel free to place your local configs any place inside /opt/sc4s/local/config/*/.conf , most of the folders are placeholder and it
will work in any of these folders if it has .conf extension.

**Comment by martynjlewis** [comment]
Wow, that was a really quick response. Thank you so much for clearing that up. Does this mean that the .csv files are no longer needed?

**Comment by rjha-splunk** [comment]
It is but if you have to place it in local/context/*.csv , splunk_metadata.csv is great for metadata override but i
will suggest to use .conf file for everything else in place of other csv files.

**Comment by martynjlewis** [comment]
That's brilliant. Thank you so much for your help.

**Comment by rjha-splunk** [comment]
@bparmar-splunk Please add it to FAQ.

**Comment by rjha-splunk** [comment]
FAQ added , thanks @bparmar-splunk
