### ISSUE TITLE
SC4S default indexes

### ISSUE THREAD

**Issue by artemrys** [splunk/splunk-connect-for-syslog#1893]
Can we have a file using which we can create all default indexes in one go?

**Comment by bparmar-splunk** [comment]
Hi @artemrys,
Thanks for reaching out.

Please check this [file](https://github.com/splunk/addonfactory-splunk_env_indexer/blob/ada106b38d886e18eecb8cf34dded12da51e5283/default/indexes.conf) which has all the indexes created in one shot.
For more information on this file, please refer [Splunk docs](https://docs.splunk.com/Documentation/Splunk/latest/admin/Indexesconf).

Also, above indexes.conf file has lastChanceIndex configured, please use it only if it fits your requirement. If not, then please discard the use of lastChanceIndex.

Thank you.

**Comment by bparmar-splunk** [comment]
Indexes.conf file added in this repo.(https://github.com/splunk/splunk-connect-for-syslog/pull/1910/commits/89fc862de94dece9e424e8097d6c5b9f3ad30629)
