### ISSUE TITLE
Vendor parser not working.

### ISSUE THREAD

**Issue by anupammandal** [splunk/splunk-connect-for-syslog#1896]
Hi Rahul,
I am trying to drop events based on "sc4s_vendor", "sc4s_product" and message, but the parser is not working. Below are the details - 
Parser location - **"/opt/sc4s/local/config/app_parsers/syslog/<file.conf>**
Attached are the snippets of configuration files and logs that I am trying to drop.

![Screenshot 2022-11-04 at 9 37 43 AM](https://user-images.githubusercontent.com/12557069/199886150-61a8ac83-50ed-4681-864b-37235777719e.png)
![Screenshot 2022-11-04 at 9 38 48 AM](https://user-images.githubusercontent.com/12557069/199886180-071d5f01-3ce8-4f6c-9c66-5e0727ba2a14.png)
<img width="1133" alt="Screenshot 2022-11-04 at 9 44 14 AM" src="https://user-images.githubusercontent.com/12557069/199886196-2f6522e5-fb32-4fd9-98bb-044e39b7a18f.png">
<img width="1156" alt="Screenshot 2022-11-04 at 9 44 31 AM" src="https://user-images.githubusercontent.com/12557069/199886203-14847b62-f1ee-40b5-bc14-a82721d075d4.png">

**Comment by rjha-splunk** [comment]
We will be needing anonymized preprocessed log sample to check this.

**Comment by anupammandal** [comment]
I will try to get them from the source but am I putting the conf file in the correct location and is the parser configuration correct?

**Comment by rjha-splunk** [comment]
everything else looks good , you need to check filter block , thats what can be a problem 

It can be placed anywhere in the subdirectories of /opt/sc4s/local/config/*/*.conf, also do you have any other postfilter for the same source ?

Example of Vendor and product matching 
```
filter{
            "dns" eq "${fields.sc4s_class}"
            and "nss" eq "${fields.sc4s_product}";
        };
```

**Comment by anupammandal** [comment]
No, that is the only config in that server. I will try to get the raw logs for you.

**Comment by bparmar-splunk** [comment]
@anupammandal,
We didn't hear anything from you on this issue.
We are closing this issue for now.

Feel free to reach out in case of any further queries.
