### ISSUE TITLE
dest_key did not do lower

### ISSUE THREAD

**Issue by mshensg** [splunk/splunk-connect-for-syslog#1897]
In code [splunk-connect-for-syslog](https://github.com/splunk/splunk-connect-for-syslog)/[package](https://github.com/splunk/splunk-connect-for-syslog/tree/main/package)/[etc](https://github.com/splunk/splunk-connect-for-syslog/tree/main/package/etc)/[conf.d](https://github.com/splunk/splunk-connect-for-syslog/tree/main/package/etc/conf.d)/[log_paths](https://github.com/splunk/splunk-connect-for-syslog/tree/main/package/etc/conf.d/log_paths)/[0](https://github.com/splunk/splunk-connect-for-syslog/tree/main/package/etc/conf.d/log_paths/0)/[lp_dest_filtered_alts_select](https://github.com/splunk/splunk-connect-for-syslog/tree/main/package/etc/conf.d/log_paths/0/lp_dest_filtered_alts_select)/plugin.py

it did not do dest_key lower so if we use this feature, we should not use upper case in env_file, or should be lower case. 

        dest_key = var.replace("SC4S_DEST_", "").replace("_FILTERED_ALTERNATES", "")
        dest_key_dests = os.environ[var].split(",")
        dest_filters = os.getenv(
            f"SC4S_DEST_{ dest_key }_ALT_FILTER", "f_is_nevermatch"
        ).split(",")

**Comment by rjha-splunk** [comment]
right now here , the dest key we are extracting from SC4S_DEST_X_Y_FILTERED_ALTERNATES and then checking in caps we have dest key in SC4S_DEST_<dest_key>_ALT_FILTER,so i think right now using this property comes with following:
1) vendor and product will set as CAPS
2) if you want the value to be set in lower case both of the above properties should be in lower case.

**Comment by mshensg** [comment]
What I am trying to say is not I would like it to be lower case. It is this env configuration cannot be upper case because the code forget to do tolower, if we use CAPS in env file, it will not work as SC4S vendor and product are always lower case. So either here add tolower or document says user need to use lower case instead.

**Comment by rjha-splunk** [comment]
Understood , we will test it and correct either the doc or code.

**Comment by mshensg** [comment]
thanks Rahul and maybe let me make it more clear. For example, I would like to filter on all SPLUNK SC4S system messages. it will be like below:

SC4S_DEST_SPLUNK_SC4S_ALT_FILTER = f_filter_sc4s
SC4S_DEST_SPLUNK_SC4S_FILTERED_ALTERNATES = d_archive

in the jinja template it is: 

'{{ dest_key }}' eq "${fields.sc4s_vendor}_${fields.sc4s_product}"

So the comparison will become:

'SPLUNK_SC4S' eq "splunk_sc4s"

as all the system sc4s_vendor and sc4s_product for that is lowercase. Then this feature actually does not work. I read the code for other Python files to use VENDOR + PRODUCT, they will do an tolower() so I assume here this is missed out inside of the corresponding python file to make it become 

'splunk_sc4s' eq "splunk_sc4s"

Otherwise, we will have to configure:  which will work also

SC4S_DEST_splunk_sc4s_ALT_FILTER = f_filter_sc4s
SC4S_DEST_splunk_sc4s_FILTERED_ALTERNATES = d_archive

**Comment by rjha-splunk** [comment]
Released it now it supports both lower case and upper case.
