### ISSUE TITLE
Some logs from Forcepoint not showing in events using SC4S.

### ISSUE THREAD

**Issue by kppathak** [splunk/splunk-connect-for-syslog#1901]
the customer has configured the Forcepoint email server with the help of SC4S setup.
https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Forcepoint/
 https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Forcepoint/webprotect/#sourcetype-and-index-configuration
mail-esg logs from the Forcepoint email server are no longer showing up in Splunk. Other logs from the server are working fine.
All logs are lending in this source type--> sourcetype=websense:cg:kv
Here's a snip of the test SIEM message. Also, if you notice when we send the test SIEM from Forcepoint we see it in the index=main. The last time the search worked was in the index=netproxy not main as per the customer input.
index=netproxy host=adstxfpmail-esg source=sc4s sourcetype=websense:cg:kv stopped working on December 15th 2021. --> Image attached.
The customer is not able to see the logs from the host of the mail server, Can someone please look into this issue?
I have attached the image and log file for further investigation.
![last log received on 15th dec 2021](https://user-images.githubusercontent.com/117859155/200921302-c6018ed1-a888-4c88-b907-ea70fea299ac.png)
[log level commands.txt](https://github.com/splunk/splunk-connect-for-syslog/files/9974415/log.level.commands.txt)
![SIEM integration image from where this log are genreating](https://user-images.githubusercontent.com/117859155/200921346-31996e50-3cc7-40b8-accc-70a8a2b0aa5a.png)
[Splunk_metdata.csv](https://github.com/splunk/splunk-connect-for-syslog/files/9974417/Splunk_metdata.csv)
![test msg](https://user-images.githubusercontent.com/117859155/200921359-df83f771-dff2-4d55-b87a-d2fa6f8f7012.png)

**Comment by rjha-splunk** [comment]
we will be needing pcap or raw anonymized sample to work, please attach the same.

**Comment by kppathak** [comment]
Thanks for the update, I have asked the customer to share the PCAP for the same.

**Comment by kppathak** [comment]
Hi, Please archive the issue for now. 
no further support is needed.

**Comment by bparmar-splunk** [comment]
> Hi, Please archive the issue for now. no further support is needed.

Closing this issue as per above [comment](https://github.com/splunk/splunk-connect-for-syslog/issues/1901#issuecomment-1331021987).
