### ISSUE TITLE
Need add custom filter created for a source not listed in the known vendor for SC4S

### ISSUE THREAD

**Issue by kppathak** [splunk/splunk-connect-for-syslog#1902]
We have a case where the customer wants to add a custom filter created for a source not listed in the known vendor for SC4S
Need to add Datadog which is not listed as a known vendor in SC4S.
1) Application Name = cisco:ios , DNS , sshd
2) Index = network
3) Sourcetype = cisco:ios , syslog
4) Port = 514
5) Protocol = UDP

I have asked the customer to share the **PCAP** file for this request.
Let me know if anything else is required for this request.

**Comment by kppathak** [comment]
Please find the PCAP file. Let me know the status.

[uploadsvc-32case3096836-11-14-2022-USER-0030b00002AOzqNAAT-datadog.pcap.zip](https://github.com/splunk/splunk-connect-for-syslog/files/10007239/uploadsvc-32case3096836-11-14-2022-USER-0030b00002AOzqNAAT-datadog.pcap.zip)

**Comment by rjha-splunk** [comment]
Please dont attach pcap file here, please feel free to share it over slack or a restricted access drive link.

**Comment by kppathak** [comment]
HI @rjha-splunk , PCAP shared over slack. Please check from your end.

**Comment by bparmar-splunk** [comment]
@kppathak,
Could you please help us with more information about this issue?
Please share your expectation.

**Comment by kppathak** [comment]
@bparmar-splunk This request is to add a custom filter in the known vendor for the SC4S.
Can you please tell me what else is required from my side?

**Comment by kppathak** [comment]
@rjha-splunk Thanks for clarifying the point, I have asked the customer to share the above-requested information.

**Comment by bparmar-splunk** [comment]
@kppathak,
We did not hear anything from you about this issue.
Closing this issue for now.
Feel free to reach out in case of any further queries.

Thank you.

**Comment by kppathak** [comment]
@bparmar-splunk Can you please share the update and let me know if anything is required from the customer end?

**Comment by bparmar-splunk** [comment]
@kppathak,
Could you please send us the link of Cisco documentation which specifies the format of log being sent from the respective devices

**Comment by kppathak** [comment]
@bparmar-splunk Please find the doc link.
https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html

**Comment by kppathak** [comment]
Hi @bparmar-splunk Please proceed with the issue closure as the customer will take care of this configuration internally in their team.
