### ISSUE TITLE
Parser conflict

### ISSUE THREAD

**Issue by lucalopreiato** [splunk/splunk-connect-for-syslog#1904]
Hello,
we have a custom parser placed in /opt/sc4s/local/config/app_parsers/syslog with a filter based on "netmask(ip_address/32)",
the parser assigns an index, a sourcetype and a timezone to data coming from the filtered ip address.

we noticed btw that some events are classified by SC4S as "nutanix" sourcetype because there are some specific text strings in the message.

questions:

is there a specific order in which the filters are applied? (i expected the sc4s/local conf to have precedence)
is it possible to have a more strict filter on nutanix parser?

thanks
Luca

**Comment by rjha-splunk** [comment]
The sc4s/local configs is last to get applied if sc4s-postfilter topic is used, we need to see 1) the sample message which is creating issue
2) The parser which is applied(local)
3) what exactly is not working.

**Comment by lucalopreiato** [comment]
1) `<13>Nov  9 08:45:37 s_esm@hostname AzReject hostname.domain.local [09/Nov/2022:08:45:35 +0100] "10.10.10.10 uid=14700270,ou=People,ou=ou,dc=applicazioni,dc=domain,dc=locale" "advancedauth_strong_agent_rz09 GET /arcotlogin/images/tim.svg?SMSESSION=-SM-kfgCTeIavWZw8YFVmcrlAtSXIXZusbo2%2bgbNdqS75Vk0k0JDWm2RSPzvZXQNicIOyfcXqJCrBYILx2NVNlJw1TWN7AXbLjdSiw2jwa1Z%2b6QWyPwTM3YeWzDaW4atJGC4%2b9tWXPMK4udD6lT6ajeTaYMNNGzXiZENTDevhjBujMGw1WWJoinYzBK9hfsUMTYQfSmNDA1Xk8%2f%2bDNkkGul1pwOcffuVzvvstdJL%2fu2B%2fEI2RjjO%2b6emXhHtEhXx7ChTA6IbkawNaeumM5uvYLZYEcXocco8JdVYcdiOEywhn2TmZNKNHJNvvY6doiG2UFrdAtYM34%2fTAObtsWEEjwOf9xlAlVzCDJ3p23N0JxkcHT%2bkPW3h13Iw3A5Q0w44QvQ2ndusoyJMKsHxYrIyjt6YxaeCD%2fTkp9KJCzEAPb90zL8vADDZl1CCdRnCch86wirL%2bR1m7Klf4vfzdu5BB%2fcqBVa6epg89kWmboIccR0WmPvUhzOKKCJD7Wh8Xltt3gkYIslOKYw%2fa%2bd9MPDB9i0Hpdjd%2fIxOVQ%2bUPdVnuMxJFznp0iRd500lXwlnd3jh42EYEKpE2%2fXHtmVX2J9R6MxRupqL0IuvPahJQ8q%2fOuvA5r3DoMSoMUHNU39xVz9vAsMsfTZk62AsrpBSbBfJ7LARGEPrKH%2b9UgGyiecgMjFtBFnHcU9hAWjf1VjqPKdwYGB3d%2bqU%2frb2mXXpRflsoXsT%2fqq5pCH8fF7Fp10Fwb3L3rAH4rZ8yC%2fdkWLwtsZnToDBC%2f74%2bzDB7BW2BMeMlBToNSYaQbAtLnCjgnfX%2biyEM348GOGbpioPcPxvQO0uo9TrwQeDrynG7pBW%2bZxPwAt2oiT4PdS2e0NCBamWHhHR8osLgSQ3fLYRvE%2fKqD20HTqCwI0dxf%2f43iP6LnmL88KNtnxfhpGzpHCVMiTe3KG5mu3Wp1Zd6JY8xPE1pzwUtEmDTugEFTxfyJ8TsAKsDjevFLAORAtzzw9MrMW1rhVBwhPg6EPGoibnvSDDk%2fu78iYG9ncEkTOirr1Wbd4kL7k3TUw%2bNUgoMgPzUxrsblKhY9NMajLrfcCYLlQEP9Lk7uUMaXSOaXQ%2b406OtqtIVV3GnxPnKiKlDYajnVV72DLnnj2YV8uZdnD30dDb%2fdH3Bxd5oO40XL5MBLmrPF7zHD2%2buCt3CW5L%2fE3NMjCzuRKj08joIMmaD6Y5vf1ZT8bUi3il8JDm5GJZ9N0e%2baMJfK1VlajlqMvhAXU%2b" [0000000000000000000000002542320a-ff75-636b5a9f-e7fff700-058f33bbfea8] [5] Session is not authorized for this security level [] []   
`
2) `block parser app-syslog-siteminder-pcsng() {
 channel {
        parser {
            kv-parser(prefix(".values.") template("$(template t_hdr_msg)"));
        };
        # inserire qui filtro
        filter {
				netmask(10.10.10.20/32) or
				netmask(10.10.10.30/32);
                };
        rewrite {
            r_set_splunk_dest_default(
                index('priority_2')
                sourcetype('siteminder')
                template('t_msg_only')
            );
            set("$(template t_hdr_msg)" value("MESSAGE"));
                        fix-time-zone("Europe/Rome");
        };
    };
};
application siteminder-pcsng[sc4s-syslog] {
        parser { app-syslog-siteminder-pcsng(); };
};`

3) syslog coming from the ip addresses specified in '2)' should go to index=priority_2 with sourcetype=siteminder nut some events, like the one in '1)' go to index=infraops with sourcetype=nutanix
