### ISSUE TITLE
entrypoint.sh issue

### ISSUE THREAD

**Issue by ChristophHerd** [splunk/splunk-connect-for-syslog#1908]
Hello!

After installing sc4s on microk8s following the documentation on https://splunk.github.io/splunk-connect-for-syslog/main/ the created pod does not start properly but keeps restarting with "CrashLoopBackOff".

In the log I found following error:

_[root@lab-1 ~]# microk8s kubectl logs sc4s-splunk-connect-for-syslog-0 
SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=main for sourcetype=sc4s:fallback...
SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=main for sourcetype=sc4s:events...
**kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
/entrypoint.sh: line 40: [: -ne: unary operator expected**_

I used the latest sc4s version 2.39.0:

_[root@lab-1 ~]# microk8s helm3 list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
sc4s                    default         3               2022-11-13 16:49:46.839043345 +0100 CET deployed        splunk-connect-for-syslog-2.39.0        2.39.0_     

I´m not sure if this error in entrypoint.sh is the main problem causing the restart loop, but I think this should be fixed.

Thank you!
Christoph

**Comment by rjha-splunk** [comment]
this is not the reason , why you are getting this error, the $PID value is NULL so the issue is populated like this, there is something else going inside.

**Comment by rjha-splunk** [comment]
We also have ansible method to install sc4s in microk8s can you please follow the same https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/ansible-mk8s/
