### ISSUE TITLE
Splunk Connect for Syslog F5 Log Ingestion

### ISSUE THREAD

**Issue by Csaboo77** [splunk/splunk-connect-for-syslog#1911]
Hi.

Data type other than sc4s:events and sc4s:fallback not getting ingested using SC4S (Multiple network interface)
Data is coming in only for source types sc4s: events and sc4s: fallback. There are multiple compatible devices like (f5 BIG IP) set up to send data via UDP 514 at the server and nothing is being sent to Splunk. Does anyone have any ideas on how to troubleshoot this? 

thx

**Comment by rjha-splunk** [comment]
looks like your f5 event is not following standard and the parser is not able to read the message, https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/F5/bigip/#sourcetypes , please check with echo command to send directly to sc4s and check the data.

**Comment by rjha-splunk** [comment]
please check the third last line it should be ");" not "};"

**Comment by Csaboo77** [comment]
> 

Yes, you right, we replaced it.
But the data still arrives on the fallback. 
Maybe the problem is that the f5 waf data that is coming in (f5:bigip:asm:syslog) is being routed via tcp on port 1514. While the bigip system data is trying to be sent over udp 514.
Is this related to sc4s:fallback? Should we switch to tcp sending?

thx

**Comment by rjha-splunk** [comment]
share a sample message , i will try to check.

**Comment by rjha-splunk** [comment]
pcap will be best, you can join our external usergroup and reach out to me on slack , or capture pcap, analyze in wireshark (statistics > conversation > follow stream) , anonymize sensitive data and share here.

**Comment by Csaboo77** [comment]
> share a sample message , i will try to check.

this is the wrong: f5 system datas comes to fallback (that one is attached).

![pic_2](https://user-images.githubusercontent.com/118187950/201688110-b064d2ff-f0cc-473a-8b1e-0cf719a45df4.PNG)

and the correct one:

The ASM waf is good, it comes in the right sourcetype.

**Comment by rjha-splunk** [comment]
Can you please share a raw sample and also let me know where it should end up , as i am bit confused :)

**Comment by Csaboo77** [comment]
> Can you please share a raw sample and also let me know where it should end up , as i am bit confused :)

Okay I am witing from that info from IT support, if u do not mind I will be back tomorrow.
Thank you very much so far.

**Comment by Csaboo77** [comment]
> > Can you please share a raw sample and also let me know where it should end up , as i am bit confused :)
Hi.

I have got the raw samples: 
![Névtelen](https://user-images.githubusercontent.com/118187950/201906901-f37354e6-8b8f-41c8-9a5c-12b10aa9727a.png)

(wher you can see the tool and just let you know the hidden are is a hostname).

**Comment by rjha-splunk** [comment]
i understand that, can you please edit the sensitive data and share it as a text ( are you sure it doesn't have pri as this doesn't look like RFC compliant message).

**Comment by Csaboo77** [comment]
> i understand that, can you please edit the sensitive data and share it as a text ( are you sure it doesn't have pri as this doesn't look like RFC compliant message).

[f5_ltm.log](https://github.com/splunk/splunk-connect-for-syslog/files/10012243/f5_ltm.log)

**Comment by Csaboo77** [comment]
> > i understand that, can you please edit the sensitive data and share it as a text ( are you sure it doesn't have pri as this doesn't look like RFC compliant message).
> 
> [f5_ltm.log](https://github.com/splunk/splunk-connect-for-syslog/files/10012243/f5_ltm.log)

Hi.
We changed from Remote HSL splunk type to Classic Remote Syslog Logging, and probably the problem solved.
