### ISSUE TITLE
Airwatch logs not parsing correctly

### ISSUE THREAD

**Issue by choovertx** [splunk/splunk-connect-for-syslog#1914]
We've added "vmware_airwatch,index,mdm" to the metadata file.  Do we also need a separate parser?  Logs look like the following:

host = [november]
source = [program:14]
sourcetype = [nix:syslog]

Happy to provide additional info.

**Comment by rjha-splunk** [comment]
Best will be providing a sample/pcap , key is always sc4s_vendor_sc4s_product( both values can be checked in gui).

**Comment by choovertx** [comment]
I've uploaded the pcap to the splunk case we have opened.  3098485

**Comment by rjha-splunk** [comment]
The issue resolved.
