### ISSUE TITLE
Zscaler logs going to main index

### ISSUE THREAD

**Issue by choovertx** [splunk/splunk-connect-for-syslog#1920]
We have noticed, there are logs from 2 hosts going to the main index.  All other zscaler logs are in correct index/sourcetype.
source = [sc4s]
sourcetype = [json]

**Comment by bparmar-splunk** [comment]
@choovertx,
Please share (on DM) the raw sample / pcap file to check the issue.

**Comment by choovertx** [comment]
pcap was emailed directly to @rjha-splunk when issue was opened.
