### ISSUE TITLE
Request to make SO_RCVBUFF and SOCKETS configurable by port_id and port type

### ISSUE THREAD

**Issue by jrehm-mmm** [splunk/splunk-connect-for-syslog#1924]
the enhancement needed is the port reuse number and buffer size should be specific the the port_id and  port type (TCP,UDP,TLS etc) and fall back to the current global value if not set more specifically

I've currently got 16 unique UDP listeners but only a few heavy data sources that need elevated buffer sizes or counts.  Would be helpful to be able to tune these individually and not have to open them all up to the max needed .

**Comment by rjha-splunk** [comment]
we will be checking and appending this feature next quarter.

**Comment by rjha-splunk** [comment]
With the recent EBPF and parallelize feature we dont think this feature is needed any more , we are open for suggestions/comment @jrehm-mmm
