### ISSUE TITLE
ESET and SC4S

### ISSUE THREAD

**Issue by Adpafer** [splunk/splunk-connect-for-syslog#1929]
Hi there, I would like my eset server to send syslog messages to SC4S but I know ESET is not supported product. Is it possible to configure SC4S the way that it receives syslogs from ESET?

Thanks for help, regards, pawelF

**Comment by rjha-splunk** [comment]
If server can send RFC compliant log sc4s will able to assign few of the metadata but will send to main or last chance index, the way to handle will be create either a dedicated port , spin a local config for sc4s to understand the data.

You can also share pcap/raw file to support ticket , if you need more help here, there are many examples of local config in docs and closed github issues.

**Comment by bparmar-splunk** [comment]
@Adpafer,
We have not heard any updates from you regarding this.
We are closing this issue for now.

Please let us know in case of further queries.
