### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by declan727** [splunk/splunk-connect-for-syslog#1939]
In the Runtime section of the documentation for installation it instructs you to create a /opt/sc4s/env_file and to add the following however it is blank and does not provide the values or any example. Please see the screen shot below. Thoughts?

Thank you

![image](https://user-images.githubusercontent.com/4894407/203613657-214eafd2-0433-4736-b281-e6415f2da19d.png)

**Comment by bparmar-splunk** [comment]
@declan727,
Thank you for bringing this up.

We will review on this as well as in other docs for blank content.
