### ISSUE TITLE
Palo Alto - Decryption Logs not being ingested

### ISSUE THREAD

**Issue by jajulius** [splunk/splunk-connect-for-syslog#1941]
We have Palo Logs being ingested into Splunk Cloud instance via Splunk HF's running SC4S and have followed the documentation to set it up.
All appears to be working apart from what appears to be Decryption logs.
These are coming into the Splunk CLoud with Sourcetype as SC4S:unknown.
There's this link from Palo detailing the format but nothing in the SC4S documentation about configuring it to ingest it properly.
https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/decryption-log-fields

Here's a sample of the log

=======================================================
1,2022/11/29 09:41:04,007957000278554,DECRYPTION,0,2561,2022/11/29 09:41:00,172.26.16.15,51.116.246.106,172.26.19.4,51.116.246.106,Azure-Sanctioned-APPs,,,ssl,vsys1,DATA-ALL,DATA-ALL,ethernet1/1,ethernet1/1,PANORAMA_LOGGING,2022/11/29 09:41:00,418284,1,39580,443,2714,443,0x400400,tcp,allow,N/A,,,,,241d1cf2-33e1-4b83-b46d-38dea4e367ef,Certificate,Certificate,TLS1.2,ECDHE,AES_256_GCM,SHA384,NO_DECRYPT,,None,trusted,Trusted,No Decrypt,33000001de1a8917657,643856ed9d2fce5408ca7ba627126996f20ceb0827f6ebd4fe7d80cea7a6a2c5,2022/06/30 18:59:16,2023/09/30 18:59:16,V3,2048,28,32,31,0,:::::RSA,*.events.data.microsoft.com,Microsoft Secure Server CA 2011,Microsoft Secure Server CA 2011,,,,,,,,,,2022-11-29T09:41:00.460+00:00,,,,,,,,,,,,,,,,,7075675525986786795,0x8000000000000000,32,33,0,0,,az-pa-pxy-we,1,encrypted-tunnel,networking,browser-based,4,"used-by-malware,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no

**Comment by rjha-splunk** [comment]
We need to see on the wire event( anonymised one) , as the message doesnt look like RFC compliant , it should be either RFC3164/RFC5424

**Comment by bparmar-splunk** [comment]
@jajulius,
We have not heard anything from you on this issue.
Closing this issue for now.

Please let us know incase of further queries.
