### ISSUE TITLE
Request to make SC4S_SOURCE_UDP_FETCH_LIMIT configurable

### ISSUE THREAD

**Issue by jrehm-mmm** [splunk/splunk-connect-for-syslog#1944]
The SC4S_SOURCE_UDP_FETCH_LIMIT configuration variable seems to have been skipped or missing.  After discussions with Baszi and Ryan, they agree that the default of 100 is likely not sufficient for all use cases.

**Comment by bparmar-splunk** [comment]
@jrehm-mmm,
Thanks for reaching out.

We will review about this change with internal team and will keep you posted.

Thank you.

**Comment by ehlo550** [comment]
Can you perhaps give an update on the status of this request?

**Comment by rjha-splunk** [comment]
Other properties are added in 2.49.0
