### ISSUE TITLE
sc4s writing data into terminal screen when it is started

### ISSUE THREAD

**Issue by harnhbn** [splunk/splunk-connect-for-syslog#1954]
We have installed the lates version of sc4s -  2.43.1 on RHEL8 Virtual machine and as soon as we start the sc4s, it is writing the messages into the terminal screen. any one has any idea on how to fix this.

2022 Dec 14 14:55:25 hostxxxx matched='filter(riverbed_syslog_stealconnect)=0', not_matched='filter(riverbed_syslog_stealconnect)=0', processed='source(s_startup_out)=1', processed='center(received)=25', matched='filter(syslog-vmware_vsphere-sdata)=0', not_matched='filter(syslog-vmware_vsphere-sdata)=0', processed='source(s_NW)=0', discarded='parser(p_cef_kv)=0', discarded='parser(p_leef_kv)=0', discarded='parser(p_cef_ts_rt)=0', discarded='parser(app-group-sc4s-raw)=0', discarded='parser(app-group-sc4s-syslog-pgm)=0', processed='src.file(s_startup_out#0,/var/lib/syslog-ng/log/syslog-ng.out)=1', stamp='src.file(s_startup_out#0,/var/lib/syslog-ng/log/syslog-ng.out)=1671029005', matched='filter(f_is_rfc3164)=0', not_matched='filter(f_is_rfc3164)=0', matched='filter(syslog-vmware_vsphere-esx-pgm)=0', not_matched='filter(syslog-vmware_vsphere-esx-pgm)=0', msg_size_max='src.file(s_startup_out#0,/var/lib/syslog-ng/log/syslog-ng.out)=19', discarded='parser(p_leef_devTime)=0', discarded='parser(vendor_product_by_source)=0', discarded='parser(app-group-sc4s-almost-syslog)=0', discarded='parser(p_acs_event_time)=0', discarded='parser(p_add_context_host)=0', discarded='parser(sb_alertext_kv)=0', matched='filter(f_is_rfc)=0', not_matched='filter(f_is_rfc)=0', matched='filter(f_is_rfc5424)=0', not_matched='filter(f_is_rfc5424)=0', matched='filter(f_cisco_esa_error_logs)=0', not_matched='filter(f_cisco_esa_error_logs)=0', matched='filter(f_cisco_esa_textmail)=0', not_matched='filter(f_cisco_esa_textmail)=0', matched='filter(f_cisco_esa_authentication)=0', not_matched='filter(f_cisco_esa_authentication)=0', matched='filter(f_is_source_identified)=0', not_matched='filter(f_is_source_identified)=0', discarded='parser(app-group-sc4s-syslog)=0', matched='filter(f_cisco_esa_antispam)=0', not_matched='filter(f_cisco_esa_antispam)=0', matched='filter(f_cisco_esa_http)=0', not_matched='filter(f_cisco_esa_http)=0', matched='filter(f_cisco_esa_system_logs)=0', not_matched='filter(f_cisco_esa_system_logs)=0', matched='filter(f_host_is_nil_or_ip)=0', not_matched='filter(f_host_is_nil_or_ip)=50', matched='filter(syslog-vmware_vsphere-nsx-pgm)=0', not_matched='filter(syslog-vmware_vsphere-nsx-pgm)=0', matched='filter(syslog-vmware_vsphere-vsan-pgm)=0', not_matched='filter(syslog-vmware_vsphere-vsan-pgm)=0', processed='src.network(s_DEFAULT#3,0.0.0.0)=0', stamp='src.network(s_DEFAULT#3,0.0.0.0)=0', eps_since_start='src.network(s_DEFAULT#1,0.0.0.0)=0', eps_since_start='src.network(s_DEFAULT#2,0.0.0.0)=0', processed='src.network(s_DEFAULT#0,0.0.0.0)=0', stamp='src.network(s_DEFAULT#0,0.0.0.0)=0', processed='src.network(s_DEFAULT#2,0.0.0.0)=0', stamp='src.network(s_DEFAULT#2,0.0.0.0)=0', msg_size_max='src.network(s_DEFAULT#3,0.0.0.0)=0', processed='src.syslog(s_DEFAULT#5,0.0.0.0)=0', stamp='src.syslog(s_DEFAULT#5,0.0.0.0)=0', matched='filter(syslog-netsource-vmware_vsphere-vcenter-pgm)=0', not_matched='filter(syslog-netsource-vmware_vsphere-vcenter-pgm)=0', processed='src.file(s_startup_err#0,/var/lib/syslog-ng/log/syslog-ng.err)=0', stamp='src.file(s_startup_err#0,/var/lib/syslog-ng/log/syslog-ng.err)=0', processed='source(s_DEFAULT)=0', msg_size_max='src.network(s_DEFAULT#0,0.0.0.0)=0', processed='src.network(s_DEFAULT#1,0.0.0.0)=0', stamp='src.network(s_DEFAULT#1,0.0.0.0)=0', matched='filter(f_cisco_esa_amp)=0', not_matched='filter(f_cisco_esa_amp)=0', msg_size_avg='src.network(s_DEFAULT#3,0.0.0.0)=0', processed='source(s_internal)=24', discarded='parser(p_add_context_splunk)=0', msg_size_max='src.file(s_startup_err#0,/var/lib/syslog-ng/log/syslog-ng.err)=0', processed='src.internal(s_internal#0)=24', stamp='src.internal(s_internal#0)=1671029695', discarded='parser(p_ise_event_time_multi)=0', processed='source(s_startup_err)=0', processed='destination(d_stdout)=25', msg_size_avg='src.network(s_DEFAULT#0,0.0.0.0)=0', msg_size_m

**Comment by bparmar-splunk** [comment]
@harnhbn,
Could you please share the configuration steps you followed to install sc4s?

**Comment by harnhbn** [comment]
I followed the steps mentioned in the link - https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/byoe-rhel8/ and we are using first option  to start the sc4s via the sc4s.service unit file 
1) the entrypoint.sh script (identical to that used in the container) can be run directly via systemd

**Comment by rjha-splunk** [comment]
I confirm the issue existed when we spin it with BYOE CENTOS 8, we need to check more to fix it, for now we recommend to use any container based solution,we will post update soon on this.
