### ISSUE TITLE
Dell EMC Unity app parser request

### ISSUE THREAD

**Issue by zyphermonkey** [splunk/splunk-connect-for-syslog#1955]
1. what is the source (what TA is associated to this sample)?
    > No related TA
1. What is the sourcetype of the message?
    > These are my best guess at a sourcetype.
    > `dell:emc:unity:syslog` OR `dell:unity:syslog` with or without the trailing `:syslog`
1. How customized is the sample , is there any documentation to refer to this sample to validate the RFC compliance?
    > Sample provided to @bparmar-splunk are default from the storage appliance.

**Comment by bparmar-splunk** [comment]
@zyphermonkey,
Could you please provide us an official doc link which we can refer for log format?

**Comment by bparmar-splunk** [comment]
@zyphermonkey,
This issue was earlier resolved by @rjha-splunk. Please refer #1819 for this issue resolution.
Please reach out in case of any queries.

Thank you.

**Comment by bparmar-splunk** [comment]
@zyphermonkey,
We are closing this issue for now.
Please reach out in case of further queries.

Thank you.

**Comment by zyphermonkey** [comment]
@bparmar-splunk 
Is there a reason to not add a permanent parser for this?

I was under the impression that we shouldn't use post-parsers in production due to performance issues.

**Comment by zyphermonkey** [comment]
Yea that is a problem, but that means that every current parser is only parsing 100% RFC compliant logs which just isn't true.

**Comment by zyphermonkey** [comment]
I don't think this is a very popular data source so the need/desire to ensure it's included in the package is low for me (and the community I believe.)

I'll work on implementing the postfilter and testing it.

Thanks for hearing me out.
