### ISSUE TITLE
docker-compose.md file broken (contains docker-compose-MacOS.md guts)

### ISSUE THREAD

**Issue by greggwoodcock** [splunk/splunk-connect-for-syslog#1956]
https://github.com/splunk/splunk-connect-for-syslog/blob/main/docs/gettingstarted/docker-compose.md
Is identical to
https://github.com/splunk/splunk-connect-for-syslog/blob/main/docs/gettingstarted/docker-compose-MacOS.md

**Comment by bparmar-splunk** [comment]
@greggwoodcock,
Thank you for bringing this up.
We have identified one difference that is in installation of Docker for Mac & Other systems. Rest all is managed in docker container.
We will review internally and will keep you posted.
