### ISSUE TITLE
Support VMware 

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#196]
At present VMware syslog messages are collected via a dedicated TA:
[https://splunkbase.splunk.com/app/3215/](url)

It would be great if these syslogs could be supported natively within SC4S for the much needed simplicity and performance.

**Comment by rfaircloth-splunk** [comment]
This one should not be very hard, we do need samples either as sourcetype=sc4s:fallback or pcap to verify we have the msg header correct and build a proper test case.

**Comment by perditi0nspam** [comment]
Here are samples for ESXi host syslogs:

![IMG_20191212_222128](https://user-images.githubusercontent.com/57867844/70746387-68130700-1d2e-11ea-971f-338926524a86.jpg)

These are sent from each ESXi host separately.

**Comment by perditi0nspam** [comment]
Here are samples from the VMware management appliance.

![IMG_20191212_222231](https://user-images.githubusercontent.com/57867844/70746515-a27ca400-1d2e-11ea-8073-0adc2a415e87.jpg)

![IMG_20191212_222406](https://user-images.githubusercontent.com/57867844/70746529-a8728500-1d2e-11ea-8c27-da37220921cb.jpg)
