### ISSUE TITLE
Secondary HEC output with SELECT mode does not work

### ISSUE THREAD

**Issue by chrisengie** [splunk/splunk-connect-for-syslog#1965]
Hi,

As talked on slack, here is the issue:
I have set up a secondary HEC destination output in the env file:

```
SC4S_DEST_SPLUNK_HEC_SPLUNKCLOUDPREPROD_URL=https://http-inputs.mystack-pp.splunkcloud.com
SC4S_DEST_SPLUNK_HEC_SPLUNKCLOUDPREPROD_TOKEN=xxxx
SC4S_DEST_SPLUNK_HEC_SPLUNKCLOUDPREPROD_TLS_VERIFY=yes
SC4S_DEST_SPLUNK_HEC_SPLUNKCLOUDPREPROD_MODE=SELECT
```

And added a filter to describe the "SELECT" mode in a parser:

```
application sc4s-lp-spectrum_alert_dest_fmt_SPLUNKCLOUDPREPROD[sc4s-lp-dest-select-d_fmt_hec_SPLUNKCLOUDPREPROD] {
    filter {
        tags(".source.s_SPECTRUM_ALERT_UTC_TZ");
    };
};
```

The filter here uses the tag referencing the listener which I set up also in the env file:

`SC4S_LISTEN_SPECTRUM_ALERT_UTC_TZ_TCP_PORT=10000
`

This configuration does not work, I receive no data on this secondary HEC output.
When switching to "global" instead of "select", it works.

**Comment by rjha-splunk** [comment]
Hi, I tested the scenario and it works , we found a gap in doc and we will fix it 

```
SC4S_DEST_SPLUNK_HEC_OTHER_URL=xxxx
SC4S_DEST_SPLUNK_HEC_OTHER_TOKEN=xxxx
SC4S_DEST_SPLUNK_HEC_OTHER_TLS_VERIFY=no
SC4S_DEST_SPLUNK_HEC_OTHER_MODE=SELECT
```

Created file in ```/opt/sc4s/local/config/app_parsers/selectors/<filename>.conf```

```
application sc4s-lp-cisco_ios_dest_fmt_other[sc4s-lp-dest-select-d_hec_fmt_other] {
    filter {
        'cisco' eq "${fields.sc4s_vendor}"
    };    
};
```

And it worked , the name of the topic should be in lower case "other" not "OTHER"
