### ISSUE TITLE
Nutanix filter matches on non Nutanix logs

### ISSUE THREAD

**Issue by ItsMrJeff** [splunk/splunk-connect-for-syslog#1970]
Found this while troubleshooting Palo Alto logs.  It appears that the seemingly random characters within these sourcetype=pan:* events happen to match the filter within app-syslog-nutanix.conf (package/etc/conf.d/conflib/syslog/app-syslog-nutanix.conf) multiple times a day.  It looks to be matching on:

filter {
match('ntnx' value("MESSAGE") flags(ignore-case)) and
match('cvm' value("MESSAGE") flags(ignore-case));

All of these specific Palo Alto events contain these characters and therefore are identified incorrectly as a nutanix:syslog sourcetype and routed accordingly.  Is it possible to improve the filter matching for Nutanix events?  Also looks like it could be related to this similar issue #1904.  

Obfuscated example of one of the events it labeled as sourcetype=nutanix:syslog:

1,2023/01/04 08:16:53,015,THREAT,url,2305,2023/01/04 08:16:53,172.11.11.11,172.2.111.111,1.1.1.1,172.2.111.111,User,t\t,,google-analytics,sys,Inside,Outside,ethernet1/5,ethernet1/6,Log_Export,2023/01/04 08:16:53,,1,11111,443,11111,443,,tcp,alert,"doubleclick.net/j/collect",(1111),web-advertisements,informational,client-to-server,,0,172.1.1.1-172.3.1.1,United States,0,text/plain,0,,,1,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0),,,"https://yiEpeRxtyh9oY5hV4JUk_m57FhFICqVm7vv1_wSmIr8NZRwCvmgjbdIJy4RQtKLHHDjJ7VXYFqDCoI3GdqSivOOF2J3NxCQHQlZ10VD-n2Hy4_eDEVksFm8hwxiNfhhf7vswj7w-hWVQygiSnTNxYmogtw7ys1iLlsro0Ddkc51IXNXsR3ADJ6UkPedlaoeM1C_CGT0HWTC5dFZiNpzESf5w3LFX8vlt80_MTQtw%26wn63130.jMmY4ZWQtNjE0MzMzLThjYmEtNDUwNjg4MjcyOGE4Yi00NDgyItYTBmZTkxMTMzNmI1&",,,,0,1,0,0,0,,primary,,,,post,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,,,"web-advertisements,low-risk",,0,

**Comment by Jaxjohnny** [comment]
Good morning.  This occurred for us today as well.  When will this move to production.  Thank you for correcting it.

**Comment by mstopa-splunk** [comment]
Hi @Jaxjohnny thank you for reporting, please provide a pcap file or a sample for us to validate and fix
