### ISSUE TITLE
Capture source IP

### ISSUE THREAD

**Issue by buzzard192** [splunk/splunk-connect-for-syslog#1972]
Is there a way for SC4S to capture the source IP and store it in a field?  I saw that in the "compliance_meta_by_source.csv" file you can use syslog-ng macros, and I saw that syslog-ng has a SOURCEIP macro, but I can not find an example of how to use a macro in the csv file.  Would the line needed just be:

f_test_test,fields.sourceIP,${SOURCEIP}

and that would add a field named "sourceIP" containing the IP of the sending device?

**Comment by marakji-splunk** [comment]
![image](https://github.com/user-attachments/assets/37fc63d0-e81a-49c5-97ca-768cb013f69b)

The source IP is captured and stored by default in **sc4s_fromhostip**

**Comment by rjha-splunk** [comment]
As mentioned by @marakji-splunk we are already capturing it.
