### ISSUE TITLE
Not getting syslog data from the Schneider with product APC Power Systems into Splunk

### ISSUE THREAD

**Issue by vrathod12** [splunk/splunk-connect-for-syslog#1974]
We are using SC4S to get syslog data from the known vendor of Schneider with product APC Power Systems. This is our first item to try to get into the SC4S server. The SC4S server is receiving the UDP packets as shown below in the tcpdump example but SC4S is not recognizing and processing the data.

Splunk Version: 8.2.9

tcpdump -v -# host \(starfire and ups1\) and port 514
dropped privs to tcpdump
tcpdump: listening on ens192, link-type EN10MB (Ethernet), capture size 262144 bytes
1 09:13:50.761791 IP (tos 0x0, ttl 63, id 1, offset 0, flags [none], proto UDP (17), length 115)
ups1.scdc.local.52598 > starfire.scdc.local.syslog: SYSLOG, length: 87
Facility syslog (5), Severity info (6)
Msg: Dec 30 09:13:49 10.100.157.111 Web user 'Court' logged in from 10.100.157.3. 0x0015
2 09:14:01.411472 IP (tos 0x0, ttl 63, id 1, offset 0, flags [none], proto UDP (17), length 79)
ups1.scdc.local.54390 > starfire.scdc.local.syslog: SYSLOG, length: 51
Facility syslog (5), Severity info (6)
Msg: Dec 30 09:14:00 10.100.157.111 APC:Test Syslog.
3 09:14:29.788718 IP (tos 0x0, ttl 63, id 1, offset 0, flags [none], proto UDP (17), length 116)
ups1.scdc.local.49711 > starfire.scdc.local.syslog: SYSLOG, length: 88
Facility syslog (5), Severity info (6)
Msg: Dec 30 09:14:28 10.100.157.111 Web user 'Court' logged out from 10.100.157.3. 0x001F

3 packets captured
13 packets received by filter
0 packets dropped by kernel

It does process the data from the NC test command below. That entry does go into Splunk in the main index as a fallback default. (See the attached file SPLUNK_SC4S_Test.png for the success results.)

echo 'APC:Test Syslog.' | nc -v starfire.scdc.local 514
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 10.205.5.38:514.
Ncat: 17 bytes sent, 0 bytes received in 0.09 seconds.

I have attached the following files that are associated with Schneider APC source.

/opt/sc4s/local/config/app_parsers/app-vps-schneider_apc.conf
/opt/sc4s/local/context/splunk_metadata.csv
/opt/sc4s/local/context/vendor_product_by_source.conf
/opt/sc4s/local/context/vendor_product_by_source.csv
/opt/sc4s/env_file

The system appears to be running without errors as seen by these commands:
systemctl restart sc4s
journalctl -b -u sc4s | tail -100

Dec 30 10:13:35 starfire.scdc.local systemd[1]: sc4s.service: Succeeded.
Dec 30 10:13:35 starfire.scdc.local systemd[1]: Stopped SC4S Container.
Dec 30 10:13:35 starfire.scdc.local systemd[1]: Starting SC4S Container...
Dec 30 10:13:35 starfire.scdc.local podman[2769221]: Trying to pull [ghcr.io/splunk/splunk-connect-for-syslog/container2](https://ghcr.io/splunk/splunk-connect-for-syslog/container2):2...
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Getting image source signatures
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:ff016e063047e2f414a33bbd6ba04bd625a400837373dd18d1fdecce79aedcef
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:8abc860612807800afc77e8631e844c183642c3fd7bf28098329a9a471c51bfa
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:754318b6a98e4d0225f824b1b1cca9a8111de0a1257162dbdc7a82d576f469da
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:98ac41c9b062ef668e72339124fa1e18401ceb18ae423475a6383145406b078f
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:d0f3ec825cc8f5c1e2b9a90ace26aebdebc55d25c527ba073e472ba8ea7cd01e
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:dc374660f36a34eca7d0010e39b79a17bb985b5904c2cbcafd8305c4f6985d17
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:66e5c90a532b718c6aaf27cd8dbcfa92c7b3fd2cf860ccfa185805fad8523391
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:90690fc0243bce6a4f0c4b7f49a33c439a3d9df371e1a4bc28a5549b2ca77087
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:900577f546c0ab4fd7e7b444ff184644ac6dbc52f17593b6df5732488f9270d1
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:1b9bc8f258ea3074352341db69be8773b66843f45cc7da9902039fc1df420cce
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:b0fb1f6f27092b5213bb43da997412f8296ac169d5ff6fe133eb30b2d57dd0ef
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:471039bc68a54a3616b160d0e5acbbedb6f19fc5fcfbf556a735c56c3bdd9ce6
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:bd89c56a724d3e9e76926c24dcda7634d590a7fe178d1e33f966fa65ea259c65
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:bb6251c72cb06f070f248950495768a918e62a0a4d8b29d0ab0fdffa8bdac78b
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:97f65c51aebaac9b5f24b139b49bcec65e85305e93170b2a884e2b1b7a8a04ac
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:7477dd34016dcca785b3449c8eafd20358557ca91f509bcfc5b655a6143824f5
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:9f4f7d4e45c46d328677fd73d10149ebdaa8985155b526f9c8de7c988be62a33
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:5dc58c328b393d64c7758d992018727b87f63bbfab0ad3793eb12ab98c5f27fd
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying blob sha256:e0a478082703b926e49fc36ab737ae7a74f1f0dcdd4f43ed2112156080dbadf7
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Copying config sha256:118d958e6dde9e466f1223d78c8b02ab32c544ab375891b568394e89b55990a3
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Writing manifest to image destination
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: Storing signatures
Dec 30 10:13:36 starfire.scdc.local podman[2769221]: 118d958e6dde9e466f1223d78c8b02ab32c544ab375891b568394e89b55990a3
Dec 30 10:13:36 starfire.scdc.local systemd[1]: Started SC4S Container.
Dec 30 10:13:37 starfire.scdc.local podman[2769251]: SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=main for sourcetype=sc4s:fallback...
Dec 30 10:13:37 starfire.scdc.local podman[2769251]: SC4S_ENV_CHECK_HEC: Splunk HEC connection test successful to index=main for sourcetype=sc4s:events...
Dec 30 10:13:41 starfire.scdc.local podman[2769251]: syslog-ng checking config
Dec 30 10:13:41 starfire.scdc.local podman[2769251]: sc4s version=2.43.2
Dec 30 10:13:43 starfire.scdc.local podman[2769251]: starting goss
Dec 30 10:13:45 starfire.scdc.local podman[2769251]: starting syslog-ng

Please help us get this going so we can understand what to do for the rest of our syslog data. 

Thank you.

**Comment by bparmar-splunk** [comment]
@vrathod12,
Could you please send the sanitized log to validate and the settings file?

**Comment by bparmar-splunk** [comment]
@vrathod12,
Could you please send sanitized log to validate and the conf files in DM ?

**Comment by vrathod12** [comment]
@bparmar-splunk 
The issue has been resolved after selecting the index.

**Comment by bparmar-splunk** [comment]
@vrathod12,
Thank you for the update.
We are closing this issue.

Please reach out in case of further queries.
