### ISSUE TITLE
SC4S Vulnerabilities

### ISSUE THREAD

**Issue by ryanoneil2** [splunk/splunk-connect-for-syslog#1987]
[twistlock_scans_splunk-connect-for-syslog_latest_01_20_23_08_39_38.xlsx](https://github.com/splunk/splunk-connect-for-syslog/files/10500577/twistlock_scans_splunk-connect-for-syslog_latest_01_20_23_08_39_38.xlsx)

See attached.  I'm trying to get SC4S added to an internal repository.  

Are these able to be remediated or explained?

**Comment by rjha-splunk** [comment]
we need to review this and get back.
