### ISSUE TITLE
SC4S not sending data to Splunk Cloud

### ISSUE THREAD

**Issue by vrathod12** [splunk/splunk-connect-for-syslog#1996]
We have Juniper Firewall appliances sending logs to our syslog server equipped with SC4S, however the logs are not flowing into Splunk Cloud.

All required details have been verified but not able to find the disconnect behind this.

Validated:
- Juniper generating the data, no port blockage, no overlapping IPs of device and SC4S
- getting data with tcpdump with tcp port 514
- SC4S instance is active and running also checked the result of journalctl -b -u sc4s | tail -100 command.

Please help in finding the root cause on this on priority basis as ingestion has been stopped since November 2022.

**Comment by rjha-splunk** [comment]
Capture pcap and echo the message to the port, what happened why data was stopped , if it was a disk
issue, was the sc4s cleaned and restarted.

**Comment by vrathod12** [comment]
We have tried sending the "echo “Hello SC4S” > /dev/udp/<SC4S_ip>/514" and getting the result in Splunk. 
Customer had an issue with the SC4S and to resolve performed below steps:
docker volume rm splunk-sc4s-var
docker volume create splunk-sc4s-var
docker system prune [--all]

After running above command tried starting the SC4S,
Dec 07 13:50:11 kmci4slg2005 systemd[1]: Starting SC4S Container...
Dec 07 13:50:11 kmci4slg2005 systemd[1]: Started SC4S Container.
Dec 07 13:50:11 kmci4slg2005 docker[22706]: /usr/bin/docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/d9f6a0345c1596976a4ef44c7154bbf2888cd3067c2f5a4a5f80edd2576dba96-init/merged: no such file or directory.
Dec 07 13:50:11 kmci4slg2005 docker[22706]: See '/usr/bin/docker run --help'.
Dec 07 13:50:11 kmci4slg2005 systemd[1]: sc4s.service: main process exited, code=exited, status=127/n/a
Dec 07 13:50:11 kmci4slg2005 systemd[1]: Unit sc4s.service entered failed state.
Dec 07 13:50:11 kmci4slg2005 systemd[1]: sc4s.service failed.

Due to above error, resized the overlay2 directory.

Even further, In sc4s.service file the ExecStartPre parameter commented due to that the docker was not able to pull the latest image from github not able to pull a simple hello-world docker image too, because it was trying the same mount point as defined for SC4S which were not being found and we were seeing the same error.

Post these changes ran below commands,
- systemctl daemon-reload
- systemctl enable sc4s
- systemctl start sc4s

**Comment by vrathod12** [comment]
There are 3 sources configured with the SC4S i.e. Juniper Firewall, Palo Alto & Cisco. The issue is only with Juniper rest are perfectly working fine. 

We have tried to validate the Juniper firewall ingestion by freshly configuring the SC4S on the separate standalone instance but issue remains same.

**Comment by rjha-splunk** [comment]
get the pcap captured , and slack me , we will see what is happening to log.

**Comment by bparmar-splunk** [comment]
Since there is no such update from reporter about this issue, we are closing this for now.
Please feel free to reach out in case of any queries.
