### ISSUE TITLE
SC4S: Add official support for AWS Fargate

### ISSUE THREAD

**Issue by splunkin** [splunk/splunk-connect-for-syslog#1997]
Customer has standardized on AWS Fargate and is requesting official support for SC4S with AWS Fargate.

**Comment by bparmar-splunk** [comment]
@splunkin,
Could you please elaborate more on this issue?
And please send relevant link references which helps us to add official support.

**Comment by rjha-splunk** [comment]
We dont support it now , we will update the community as soon as we will have the plan for it.

Closing it as duplicate request.
