### ISSUE TITLE
sourcetype cisco:wsa:l4tm documented, but not working

### ISSUE THREAD

**Issue by schose** [splunk/splunk-connect-for-syslog#1998]
Hi all,

In the [sc4s documentation](https://github.com/splunk/splunk-connect-for-syslog/blob/a8ecf03ea8e489d7e71db61fbc2fd8e4e2d195a5/docs/sources/vendor/Cisco/cisco_wsa.md?plain=1#L17) cisco:wsa:l4tm is listed as a usable sourcetype. [Splunk Docs](https://docs.splunk.com/Documentation/AddOns/released/CiscoWSA/Upgrade) also describe it: "to collect data for access logs, W3C logs, and L4TM logs for the Cisco Web Security Appliance, you must use Splunk Connect for Syslog." 

In Cisco [product documentation](https://www.cisco.com/c/en/us/td/docs/security/wsa/wsa11-0/user_guide/b_WSA_UserGuide/b_WSA_UserGuide_chapter_010111.html) "Traffic Monitor Logs | Records sites added to the L4TM block and allow lists. | No | Yes" is listed as "Supports Syslog Push?" -> "No"

On recent v14.5.1-008 there is still no option to send l4tm logs using syslog:  
![image](https://user-images.githubusercontent.com/12794820/217065179-07c2714a-5710-4935-a769-2f2f87030f5e.png)

can anybody help to clarify if this is a double documentation bug or any hints how to ingest cisco:wsa:l4tm using syslog?

Thanks for all in advance!

Andreas

**Comment by bparmar-splunk** [comment]
Hi @schose,
To ingest Cisco WSA logs, please refer this docs which helps you to configure your logs route to Splunk using SC4S.
Doc link: https://docs.splunk.com/Documentation/AddOns/released/CiscoWSA/Installationsteps

**Comment by schose** [comment]
Hi @bparmar-splunk ,

just to clarify, in Splunk docs it's stated that you can ingest Traffic Monitor Logs (cisco:wsa:l4tm) using syslog. The Vendor (Cisco) documents that this is not possible. I also try to show in the screenshot that ciscos documenation is right. 

My question is: is this is an mistake in your documentation? How do you ensure that sourcestypes listed below "known vendors" are really working?

best regards,

Andreas

**Comment by adri8n** [comment]
@schose Did you sort any of this out?  A bit long ago now I know.  I've been dealing with WSA v12.5 and the add-on and it doesn't work quite as the documentation suggests or as expected.  I can share my experience, and possibly help, but you may have already long since moved on.

**Comment by rjha-splunk** [comment]
Please open a support case for WSA TA team and they should be able to help.
