### ISSUE TITLE
cisco:ism:syslog PROGRAM being truncated in logs. 

### ISSUE THREAD

**Issue by phanTom-adarma** [splunk/splunk-connect-for-syslog#2001]
For cisco:ise:syslog sourcetype we are seeing truncation on the PROGRAM field to 32 characters.

OLD SYSLOG:
"date_stamp host CISE_Administrative_and_Operational_Audit message"

SC4S:
"CISE_Administrative_and_Operatio message"

I raised this on Slack at 10:44 GMT and was advised to raise this as a bug.

**Comment by rjha-splunk** [comment]
can you send pcap over slack or post here the sanitized sample to verify and validate.

**Comment by phanTom-adarma** [comment]
It's hard to grab from the wire due to no tcpdump enables or wireshark available and to do so would take time and approvals :/ 

Below is the _raw message as received by Splunk from rsyslog for the same thing:

2023-02-10T13:45:02+00:00 host1 CISE_Administrative_and_Operational_Audit 0000787078 1 0 2023-02-10 13:45:02.993 +00:00 0013144606 61026 NOTICE EAP-TLS: Shutdown secure connection with TLS peer, ConfigVersionId=94, AdminInterface=UNKNOWN, AdminIPAddress=0.0.0.0\, , OperationMessageText=Connection closed from 0.0.0.0:45598 to  0.0.0.0:5671, AcsInstance=another_host,

**Comment by phanTom-adarma** [comment]
@rjha-splunk 

This is an SC4S parsed event in the Splunk GUI:

CISE_Administrative_and_Operatio 0000016038 1 0 2023-02-10 14:59:33.211 +00:00 0000069104 61056 NOTICE System-Management: The federation link was down, ConfigVersionId=46, AdminInterface=UNKNOWN, OperationMessageText=From HOSTX To HOSTY\; Cause=\{tls_alert\,"unknown Ca"\},

**Comment by bparmar-splunk** [comment]
Closing this issue as there is no such update from reporter.
