### ISSUE TITLE
Pulse Secure Program Fix

### ISSUE THREAD

**Issue by phanTom-adarma** [splunk/splunk-connect-for-syslog#2002]
In my environment the ":" in **PulseSecure:** is not being extracted in the Program value so I have had to duplicate the parser, remove the ":" and add to to custom parsers to make it work.

**Comment by rjha-splunk** [comment]
Please feel to raise PR , we will review and merge it

**Comment by bparmar-splunk** [comment]
Closing this issue since there is no such update from reporter.
Please feel free to reach out in case of any queries.
