### ISSUE TITLE
Milliseconds in timestamp lost in translation

### ISSUE THREAD

**Issue by jbemmel** [splunk/splunk-connect-for-syslog#2005]
For a custom syslog parser I have the following input:
```
2023-02-16T20:50:45.106263+01:00 leaf2 sr_chassis_mgr: chassis|1172|1172|00122|W: Interface lag1 is now down for reason: standby-signaling
```

After processing in sc4s and splunk, this appears in the logs as
```
2023-02-16T19:50:45.000+00:00 leaf2 sr_chassis_mgr: chassis|1172|1172|00122|W: Interface lag1 is now down for reason: standby-signaling

    host = leaf2
    source = sc4s
    sourcetype = nokia:router
```

My parser uses template('t_everything') - what could be causing the loss of those 106ms?

**Comment by mateuszpierzchala-splunk** [comment]
@jbemmel can you please provide the parser in the comment? I will take a look.

**Comment by jbemmel** [comment]
The parser is at https://github.com/jbemmel/srl-splunk/blob/main/app-syslog-nokia_srlinux.conf

**Comment by jbemmel** [comment]
Thanks for looking into this, I'll try

**Comment by ikheifets-splunk** [comment]
Hello, @jbemmel !
Please let me know is it working for you?
