### ISSUE TITLE
Known Vendors Panos - pan:decryption

### ISSUE THREAD

**Issue by Jaxjohnny** [splunk/splunk-connect-for-syslog#2010]
We have a sourcetype showing up.  SC4S seems to recognize it, but there is not a key to direct the data to an index

The sourcetype is pan:decryption

Requesting a key to match pan:decryption sourcetype

1,2023/02/24 18:36:16,012501002896,DECRYPTION,0,2561,2023/02/24 18:36:01,10.1.3.11,18.1.1.26,17.8.19.2,18.1.1.2,Whitelist-AppId,,,incomplete,vsys1,Corp.Trust,Internet,ae8.1851,ae7.2851,Panorama,2023/02/24 18:36:01,34757090,1,64779,443,9386,443,0x1400000,tcp,allow,N/A,,,,,11d42847-c7bd-4432-95e4-de345c0683c8,Unknown,Client_Hello,TLS1.2,,,,decrytpme-3rd-categories,,Protocol,uninspected,Uninspected,Forward,,,,,V1,0,0,0,0,0,:::::NONE,,,,,General TLS protocol error,,,,,,,,2023-02-24T18:36:01.834+00:00,,,,,,,,,,,,,,,,,7107092619227871007,0x8000000000000000,1634,2261,1619,0,vsys1,AT1FW01,1,unknown,unknown,unknown,1,,,incomplete,no,no

**Comment by Jaxjohnny** [comment]
The good news is that SC4S recognizes the sourcetype, pan:decryption.  It places it in the lastchanceindex.

**Comment by bparmar-splunk** [comment]
@Jaxjohnny,
Please help us with latest raw messages to check and validate.
Also, as per pan [docs](https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/PaloaltoNetworks/panos/#sourcetype-and-index-configuration), below would be the values:
Key: **pan_panos_decryption**
Sourcetype: **pan:decryption**
Default Index: **netops**

Please confirm the above values

**Comment by bparmar-splunk** [comment]
@Jaxjohnny,
We have not heard anything from you. Hence we are closing this issue for now.
Please let me know in case of any further queries.

Thank you.

**Comment by Updog21** [comment]
@bparmar-splunk I believe this is still a persistent issue. The parser for the `DECRYPTION` is missing a number of key value pairs. I'm also running into this issue and get the following error when referencing the key (as you mentioned earlier):

`A filter referenced by the database is not found in the filters file; filter='“pan_panos_decryption`

Thanks you.
