### ISSUE TITLE
Incorrect documentation for Imperva SecureSphere

### ISSUE THREAD

**Issue by locose** [splunk/splunk-connect-for-syslog#2014]
Documentation seems to be incorrect for Imperva SecureSphere
 
https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Imperva/waf/#index-configuration

The Index key has spaces [**Imperva Inc._SecureSphere**]

**Comment by bparmar-splunk** [comment]
@locose,

I have tried to override the index using the same key mentioned above(including whitespace).
Key mentioned in documentation is correct as per this finding.

Please validate at your end with latest version of SC4S and let us know in case of any further queries.

**Comment by bparmar-splunk** [comment]
@locose,
We have not heard anything from you. Please let us know incase of any further queries.
Closing this issue for now.
