### ISSUE TITLE
HP ILO new log type still classified as dell powerswitch logs

### ISSUE THREAD

**Issue by dominion1-git** [splunk/splunk-connect-for-syslog#2027]
This is a followup from issue https://github.com/splunk/splunk-connect-for-syslog/issues/2012
Latest release still has issues parsing other iLO 5 syslogs

sc4s_product :: powerswitch
sourcetype :: dell:emc:powerswitch:n
sc4s_tags :: wireformat:rfc|wireformat:rfc5424|source_identified|.app.app-syslog-dell_switch_n|.source.s_DEFAULT

log snippet for reference:

`- - - - - [meta sequenceId="314250447"]56 Network: Ethernet 10/25Gb 2-port SFP88 XXXXX-ACHT Adapter Connectivity status changed to OK for adapter in slot 2, port 2 ACTION: If the connection is lost, then check the physical connection from the server to its destination device such as interconnect ,blade, switch etc, including any cables. Refer to the NIC issues flowchart in the Troubleshooting Guide for more information.`

**Comment by bparmar-splunk** [comment]
Hi @dominion1-git,
Below is the parser, place it in `/opt/sc4s/local/config/app_parsers/syslog` and restart SC4S.
```
block parser app-syslog-hpe_ilo() {
 channel {
        rewrite {
            r_set_splunk_dest_default(
                index("infraops")
                sourcetype('hpe:ilo')
                vendor("hpe")
                product("ilo")
                template('t_5424_hdr_sdata_compact')
            );
        };

   };
};

application app-syslog-hpe_ilo[sc4s-syslog-pgm] {
    filter {
        program('(#ILO|[iI][lL][oO])\d{1}+') or
        program('DenialofService' type(string)) or
        program('Network' type(string)) or
        match('iLO', value("MESSAGE")) or
        program('ci-audit-log' type(string));
    };

    parser { app-syslog-hpe_ilo(); };
};

application app-syslog-hpe_ilo_syslog[sc4s-syslog] {
    filter {
        message('fpc0' type(string) flags(prefix));
    };

    parser { app-syslog-hpe_ilo(); };
};
```

Please let us know in case of any further queries.

**Comment by rjha-splunk** [comment]
Reopening this issue as the fix was reverted , we will post the update today

**Comment by bparmar-splunk** [comment]
Issue was resolved and hence closing this issue.
