### ISSUE TITLE
Support McAfee EPO

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#203]
McAfee EPO is a very popular security orchestration platform found in various enterprises. At present there isn't support for it. For more details on syslog integration with EPO check out:
[https://kc.mcafee.com/corporate/index?page=content&id=KB87927](url)

Here is an example of the syslog format:
[https://community.mcafee.com/t5/image/serverpage/image-id/4083iC9D705170F9187D0/image-size/large?v=1.0&px=999](url)

It would be of great help if this was integrated into SC4S.
I should point out that the product requires syslog-tls, in case that has any bearing on integration.

**Comment by rfaircloth-splunk** [comment]
From the SC4S side this would be easy however there is not a Splunk TA using the syslog method yet so this may have limited value. We already have syslog-tls support and would need samples (raw text)  we could add it in now for use when the Splunk TA is updated in the future

**Comment by perditi0nspam** [comment]
Here are some EPO samples.

![IMG_20191210_221347](https://user-images.githubusercontent.com/57867844/70565710-551bfd80-1b9b-11ea-936a-ec5395ab551c.jpg)
![IMG_20191210_221404](https://user-images.githubusercontent.com/57867844/70565728-5b11de80-1b9b-11ea-8a5b-77b24ecbc0ad.jpg)
![IMG_20191210_221422](https://user-images.githubusercontent.com/57867844/70565732-5ea56580-1b9b-11ea-8b8f-9cb9f6342468.jpg)

CRLF are newlines. All syslogs from EPO must arrive via syslog-tls.

**Comment by mkarlstrand-splunk** [comment]
> Here are some EPO samples.
> 
> ![IMG_20191210_221347](https://user-images.githubusercontent.com/57867844/70565710-551bfd80-1b9b-11ea-936a-ec5395ab551c.jpg)
> ![IMG_20191210_221404](https://user-images.githubusercontent.com/57867844/70565728-5b11de80-1b9b-11ea-8a5b-77b24ecbc0ad.jpg)
> ![IMG_20191210_221422](https://user-images.githubusercontent.com/57867844/70565732-5ea56580-1b9b-11ea-8b8f-9cb9f6342468.jpg)
> 
> CRLF are newlines. All syslogs from EPO must arrive via syslog-tls.

Thank you very much for providing these. Is there any possibility you could provide these as a CSV?

**Comment by rfaircloth-splunk** [comment]
Feature ready for next release
