### ISSUE TITLE
HP Tandem server data is not getting sourcetyped correctly

### ISSUE THREAD

**Issue by ravi429** [splunk/splunk-connect-for-syslog#2031]
Hi Team,
Our application team is sending data from HP Tandem server to our sc4s endpoint and which then comes to Splunk cloud
We see that the data is going to main index and getting sourcetyped as sc4s:fallback

Team do not want to use xma on tandem server as it is using high CPU

Kindly help how fix this

**Comment by ravi429** [comment]
Below is the format of data coming in

PRI=10 MESSAGE=09 224234 10 ABC SYS5hgtgm1 5617xxxx0978 100 30SV 5000 0

Source=sc4s sourcetype=sc4s:fallback

**Comment by rjha-splunk** [comment]
will be needing raw anonymised message or raise a support case upload pcap or DM the pcap from external splunk usergroup
