### ISSUE TITLE
sc4s.service failure (exit-code)

### ISSUE THREAD

**Issue by skydandrear** [splunk/splunk-connect-for-syslog#2038]
Hi,
I am trying to configure sc4s on a Centos 9 machine following the following procedure in the documentation [Bring Your Own Environment](https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/byoe-rhel8/)
After following all the steps I got problems starting the sc4s service.Once enabled the service remains active for a few seconds and then fails.
I attach screen to better understand the problem.

![image](https://user-images.githubusercontent.com/126185104/230320738-5218f5ca-a060-4742-813e-68a114f3abca.png)

![image](https://user-images.githubusercontent.com/126185104/230320685-15e0a237-7104-4a24-a41c-fdb86df100d6.png)

Has anyone encountered a similar problem?

**Comment by mathiznogoud** [comment]
I might have a simmilar problem to you,
Can you share the details "journalctl -xeu sc4s.service" ?

**Comment by skydandrear** [comment]
![Screenshot 2023-04-19 at 14 38 29](https://user-images.githubusercontent.com/126185104/233077154-fab1758e-513d-4bbd-9c49-e04b10625ff8.png)

**Comment by rjha-splunk** [comment]
let me check it on priority today.

**Comment by rjha-splunk** [comment]
It will take 2-3 more days to validate and fix.

**Comment by rjha-splunk** [comment]
I looked into the issue closely, unfortunately we dont support syslog-ng 4.0 yet because of type issue and it will be fixed in 4.2 , we are working and testing syslog-ng 4.2 , you need to spin BYOE instance with 3.36 version now.
