### ISSUE TITLE
SC4S official support for Rubrik

### ISSUE THREAD

**Issue by fpunzohig** [splunk/splunk-connect-for-syslog#2040]
Hello SC4S team. My company uses Rubrik and we need to stream the logs it emits through SC4S into Splunk. Can you please add Rubrik as a supported vendor. I have attached the raw text (obfuscated) from a tcpdump we just did. Please contact me via email if you need anything else.  
[RubrikRawDataObfuscated.zip](https://github.com/splunk/splunk-connect-for-syslog/files/11223577/RubrikRawDataObfuscated.zip)

Thanks, 
Frank

**Comment by bparmar-splunk** [comment]
@fpunzohig,
Could you please answer following questions:

- What is the source (what TA is associated to this sample)?
- What is the sourcetype and index of the message?
- Is there any documentation to refer to this sample to validate the RFC compliance?

**Comment by fpunzohig** [comment]
@bparmar-splunk. Apologies, as it turns out this data is not specific to Rubrick, these are just Linux OS logs. We are going to get them ingested through SC4S using the nix_syslog key. Before I close this issue though, can I bother you for some instruction on how to ingest data into the nix_syslog key but have the data arrive on a non default port. We would like to have the data arrive via TCP rather then UDP 514 due to the added resiliency of TCP protocol. I have read through all the documentation but can't find anything telling me how to do that. 

Thanks in advance, 
Frank

**Comment by bparmar-splunk** [comment]
@fpunzohig,
You can copy below env variable to env_file.
`SC4S_LISTEN_DEFAULT_TCP_PORT=${SC4S_LISTEN_TCP_PORT}`

You can also make use of below parser to route your messages:
```
block parser app-syslog-rubrik() {
    channel {
        rewrite {
            r_set_splunk_dest_default(
                index("netops")
                sourcetype('rubrik:syslog')
                vendor("rubrik")
                product("syslog")
            )
        };
    };
};
application app-syslog-rubrik[sc4s-syslog-pgm] {
    filter {
        program('sudo'  type(string)  flags(prefix)) or
        match('rubrik' value('MESSAGE'));
    };	
    parser { app-syslog-rubrik(); };
};
```
Please validate your usecase and let us know in case of any queries.
