### ISSUE TITLE
Support for dell isilon

### ISSUE THREAD

**Issue by olivierpas** [splunk/splunk-connect-for-syslog#2047]
Hello,

Can you please add dell isilon as supported product ?

Please contact me on slack.

Regards,

**Comment by mateuszpierzchala-splunk** [comment]
Hi, please provide sanitised PCAP file so we can work on something.

**Comment by mateuszpierzchala-splunk** [comment]
Local post filter provided: `application app-dell-isiolion-postfilter[sc4s-postfilter] {
 filter {
        host("zxx*" type(glob)) or
        host("yyy*" type(glob))
        };
    parser { app-dell-isiolion-postfilter() };
};

block parser app-dell-isiolion-postfilter() {
     channel {
        rewrite {
            r_set_splunk_dest_default(
                index('netops')
                source('dell:isilion')
                sourcetype('dell:isilion:$(lowercase ${PROGRAM})')
                vendor("dell")
                product('isilion')
                template('t_5424_hdr_sdata_msg')
            );
        };
   };
};`
