### ISSUE TITLE
Custom TLS Connector for SC4S

### ISSUE THREAD

**Issue by pwickham** [splunk/splunk-connect-for-syslog#2056]
Hi 
Is it possible to create a simple port source with a custom TLS cert associated to it? We have a syslog source that  is trying to do TLS verify and it doesn't recognise our private CA that signed the TLS cert. The vendor has indicated that they have no way of introducing additional CAs into the product. (Don't ask!)

At this stage im thinking i can create a custom syslog-ng config for the port and point the cert option to the public cert we have acquired for this product but im not sure how i can add that config to SC4S. If this was standard Syslog-ng it would be very easy to do.

**Comment by rjha-splunk** [comment]
https://splunk.github.io/splunk-connect-for-syslog/main/configuration/#syslog-source-tls-certificate-configuration , we dont support multiple tls on different ports, we can explore to enhance it.

**Comment by bparmar-splunk** [comment]
@pwickham,
We have not heard from you since last two weeks. Please let us know in case of any further queries.
Closing this issue for now.
