### ISSUE TITLE
Log split into 2 line the new line start with PRI=13

### ISSUE THREAD

**Issue by jworapong** [splunk/splunk-connect-for-syslog#2073]
The raw log
May 17 22:00:16 wsa.domain.local Splunk-Web-Access: Info: 1684335615.707 39 172.20.43.210 TCP_DENIED/407 0 CONNECT tunnel://ts01-gyr-maverick.cloudsink.net:443/ - NONE/- - OTHER-NONE-DefaultGroup-NONE-NONE-NONE-NONE-NONE <"-",-,-,"-",-,-,-,-,"-",-,-,-,"-",-,-,"-","-",-,-,"-",-,"-","-","-","-","-","-","-",0.00,0,-,"-","-",-,"-",-,-,"-","-",-,-,"-",-,-> - - >timestamp: 1684335615.707 x-elapsed-time: 39 cs(Referer): - c-ip: 172.20.43.210 sc-result-code: TCP_DENIED sc-http-status: 407 sc-bytes: 0 cs-method: CONNECT cs-url: tunnel://ts01-gyr-maverick.cloudsink.net:443/ s-hostname: - cs-uri: - cs-username: - cs-mime-type: - x-acltag: OTHER-NONE-DefaultGroup-NONE-NONE-NONE-NONE-NONE cs(X-Forwarded-For): - c-port: 56218 s-computerName: ts01-gyr-maverick.cloudsink.net s-port: 443 cs-version: 1 x-webcat-code-abbr: - x-wbrs-score: - x-webroot-scanverdict: - x-webroot-threat-name: - x-webroot-trr: - x-webroot-spyid: - x-webroot-trace-id: - x-mcafee-scanverdict: - x-mcafee-filename: - x-mcafee-av-scanerror: - x-mcafee-av-detecttype: - x-mcafee-av-virustype: - x-mcafee-virus-name: - x-sophos-scanverdict: - x-sophos-scanerror: - x-sophos-file-name: - x-sophos-virus-name: - x-ids-verdict: - x-icap-verdict: - x-webcat-req-code-abbr: - x-webcat-resp-code-abbr: - x-wbrs-threat-type: - x-avc-app: - x-avc-type: - x-avc-behavior: - x-request-rewrite: - x-avg-bw: 0.00 x-bw-throttled: 0 user-type: - x-resp-dvs-threat-name: - x-resp-dvs-scanverdict: - x-resp-dvs-verdictname: - x-req-dvs-threat-name: - x-req-dvs-scanverdict: - x-req-dvs-verdictname: - x-amp-verdict: - x-amp-malware-name: - x-amp-score: - x-amp-upload: - x-amp-filename: - x-amp-sha: - cs(User-Agent): "CrowdStrike Falcon Sensor" cs-bytes: 138

**after sc4s parsing**
**First Line** index and sourcetype are correct
timestamp: 1686528000.000 x-elapsed-time: 39 cs(Referer): - c-ip: 172.20.43.210 sc-result-code: TCP_DENIED sc-http-status: 407 sc-bytes: 0 cs-method: CONNECT cs-url: tunnel://ts01-gyr-maverick.cloudsink.net:443/ s-hostname: - cs-uri: - cs-username: - cs-mime-type: - x-acltag: OTHER-NONE-DefaultGroup-NONE-NONE-NONE-NONE-NONE cs(X-Forwarded-For): - c-port: 56218 s-computerName: ts01-gyr-maverick.cloudsink.net s-port: 443 cs-version: 1 x-webcat-code-abbr: - x-wbrs-score: - x-webroot-scanverdict: - x-webroot-threat-name: - x-webroot-trr: - x-webroot-spyid: - x-webroot-trace-id: - x-mcafee-scanverdict: - x-mcafee-filename: - x-mcafee-av-scanerror: - x-mcafee-av-detecttype: - x-mcafee-av-virustype: - 

**Second Line** index and sourcetype are incorrect
PRI=13
MESSAGE=x-mcafee-virus-name: - x-sophos-scanverdict: - x-sophos-scanerror: - x-sophos-file-name: - x-sophos-virus-name: - x-ids-verdict: - x-icap-verdict: - x-webcat-req-code-abbr: - x-webcat-resp-code-abbr: - x-wbrs-threat-type: - x-avc-app: - x-avc-type: - x-avc-behavior: - x-request-rewrite: - x-avg-bw: 0.00 x-bw-throttled: 0 user-type: - x-resp-dvs-threat-name: - x-resp-dvs-scanverdict: - x-resp-dvs-verdictname: - x-req-dvs-threat-name: - x-req-dvs-scanverdict: - x-req-dvs-verdictname: - x-amp-verdict: - x-amp-malware-name: - x-amp-score: - x-amp-upload: - x-amp-filename: - x-amp-sha: - cs(User-Agent): CrowdStrike Falcon Sensor cs-bytes: 138

**Comment by bparmar-splunk** [comment]
@jworapong,
Could you please help us with pcap file or raw message with header?

**Comment by jworapong** [comment]
**Here is the raw including the syslog header.**

May 17 22:00:16 wsa.domain.local Splunk-Web-Access: Info: 1684335615.707 39 172.20.43.210 TCP_DENIED/407 0 CONNECT tunnel://ts01-gyr-maverick.cloudsink.net:443/ - NONE/- - OTHER-NONE-DefaultGroup-NONE-NONE-NONE-NONE-NONE <"-",-,-,"-",-,-,-,-,"-",-,-,-,"-",-,-,"-","-",-,-,"-",-,"-","-","-","-","-","-","-",0.00,0,-,"-","-",-,"-",-,-,"-","-",-,-,"-",-,-> - - >timestamp: 1684335615.707 x-elapsed-time: 39 cs(Referer): - c-ip: 172.20.43.210 sc-result-code: TCP_DENIED sc-http-status: 407 sc-bytes: 0 cs-method: CONNECT cs-url: tunnel://ts01-gyr-maverick.cloudsink.net:443/ s-hostname: - cs-uri: - cs-username: - cs-mime-type: - x-acltag: OTHER-NONE-DefaultGroup-NONE-NONE-NONE-NONE-NONE cs(X-Forwarded-For): - c-port: 56218 s-computerName: ts01-gyr-maverick.cloudsink.net s-port: 443 cs-version: 1 x-webcat-code-abbr: - x-wbrs-score: - x-webroot-scanverdict: - x-webroot-threat-name: - x-webroot-trr: - x-webroot-spyid: - x-webroot-trace-id: - x-mcafee-scanverdict: - x-mcafee-filename: - x-mcafee-av-scanerror: - x-mcafee-av-detecttype: - x-mcafee-av-virustype: - x-mcafee-virus-name: - x-sophos-scanverdict: - x-sophos-scanerror: - x-sophos-file-name: - x-sophos-virus-name: - x-ids-verdict: - x-icap-verdict: - x-webcat-req-code-abbr: - x-webcat-resp-code-abbr: - x-wbrs-threat-type: - x-avc-app: - x-avc-type: - x-avc-behavior: - x-request-rewrite: - x-avg-bw: 0.00 x-bw-throttled: 0 user-type: - x-resp-dvs-threat-name: - x-resp-dvs-scanverdict: - x-resp-dvs-verdictname: - x-req-dvs-threat-name: - x-req-dvs-scanverdict: - x-req-dvs-verdictname: - x-amp-verdict: - x-amp-malware-name: - x-amp-score: - x-amp-upload: - x-amp-filename: - x-amp-sha: - cs(User-Agent): "CrowdStrike Falcon Sensor" cs-bytes: 138

**Comment by jworapong** [comment]
I can fix the issue by changing the manual sending method to nc.
