### ISSUE TITLE
Github logging changes coming in Github Enterprise Server 3.9

### ISSUE THREAD

**Issue by adammike** [splunk/splunk-connect-for-syslog#2075]
https://docs.github.com/en/enterprise-server@3.9/admin/release-notes#3.9.0-rc.1-changes

# [3.9.0-rc.1: Changes](https://docs.github.com/en/enterprise-server@3.9/admin/release-notes#3.9.0-rc.1-changes)
Field names for some service logs on GitHub Enterprise Server have changed as part of GitHub's gradual migration to internal semantic conventions for [OpenTelemetry](https://opentelemetry.io/). Additional field names will change in upcoming releases. If any tooling or processes in your environment rely on specific field names within logs, or log entries in specific files, the following changes may affect you.

* level is now SeverityText.
* log_message, msg, or message is now Body.
* now is now Timestamp.
* Custom field names such as gh.repo.id or graphql.operation.name use semantic names.
* Log statements that the instance would previously write to auth.log, ldap.log, or ldap-sync.log now appear in containerized logs for github-unicorn if the statement originated from a web request, or in logs for github-resqued if the statement originated from a background job.

For a full list of mappings, download the [OpenTelemetry attribute mapping CSV](https://docs.github.com/assets/ghes-3.9-opentelemetry-attribute-mappings.csv).

**Comment by mateuszpierzchala-splunk** [comment]
@adammike hi, thanks for info. SC4S is not doing any extractions based on affected fields so this release should not affect us. We only assign index, source, sourcetype etc based on the message format.
