### ISSUE TITLE
Customer needs support for IBM MQ Logs

### ISSUE THREAD

**Issue by mchowdhury-splunk** [splunk/splunk-connect-for-syslog#2081]
Customer is looking to have support for IBM MQ Logs in SC4S. The MQ Appliance which is based on the Datapower appliances uses the RFC 3164 spec. Please see following documentation https://www.ibm.com/docs/en/mq-appliance/9.3?topic=targets-format-mq-logs-sent-log. They also provided pcap file for the logs. Appreciate I can be contacted here mchowdhury@splunk.com for the file.

**Comment by rjha-splunk** [comment]
Will continue the discussion on internal channels.

**Comment by rjha-splunk** [comment]
The solution is posted internally.

**Comment by aalisher-tmx** [comment]
the solution posted internally implemented but some of the logs goes into main index as well. How can we resolve it
