### ISSUE TITLE
create a new filter for raritan SX2

### ISSUE THREAD

**Issue by amalitol** [splunk/splunk-connect-for-syslog#2085]
Noticed SC4S supports raritan vendor sourcetype:dsx. 
I have a raritan SX II and all it logs fall into "sourcetype:fallback" 
I think I it could be great and simple to somekind of edit the current supported "sourcetype:dsx" and create a new one as "sourcetype:sx2" using the same vendor filter as a template. 

I was trying to edit and create the current Know Vendor Raritan "sourcetype:dsx" but I don't have enough experience. 

Thank you,

**Comment by mateuszpierzchala-splunk** [comment]
Hi, @amalitol please provide .pcap file or raw message.

**Comment by ikheifets-splunk** [comment]
Hello, @amalitol ! Can you please to provide us .pcap file? We need to know real log format that producing your device.

**Comment by amalitol** [comment]
Hi @ikheifets-splunk The .pcap file is on its way.
Thank you,

**Comment by amalitol** [comment]
Hi @ikheifets-splunk && @mateuszpierzchala-splunk 
.pcap attached in a .zip file as well as the raw messages in a note above. 
[myrarirancap.zip](https://github.com/splunk/splunk-connect-for-syslog/files/12001854/myrarirancap.zip)

I'm waiting for your comments.

Thank you,

**Comment by ikheifets-splunk** [comment]
Hello, @amalitol ! 

In your attachment I found 2 different formats of logs:

```
<14>[Port Disconnected]: Port 'ccserveraggsw1 - N9K- Top' disconnected by user 'admin' from host '10.20.70.46'.
```

```
<189>drnetappsw1: 2023 Jul  8 20:31:32.389 EDT: %VSHD-5-VSHD_SYSLOG_CONFIG_I: Configured from vty by securescan on [10.20.202.58](https://10.20.202.58/)@ssh.11396
```

Which of them I need to support?
 
P.S. More details on the bottom:
![Screenshot 2023-07-11 at 12 55 28](https://github.com/splunk/splunk-connect-for-syslog/assets/138466237/90d5e11c-26ec-4934-a7a5-85f90adc5fe5)

**Comment by amalitol** [comment]
I would say the first format.<14>…

**Comment by rjha-splunk** [comment]
@amalitol Kindly dont post pcap to open sourced space, from next time kindly use engineers email or support case, i have deleted the pcap from the comments.

**Comment by ikheifets-splunk** [comment]
Hello, @amalitol !

It's seems your device generating very generic message by this reason we're asking to use non-default port (custom) when sending logs from this device. Because for such generic messsaes there is only one way to identify the source (by device source port or device source hostname).

P.S. The same situation with Raritan DSX (that you mentioned), it's sending logs using 9001 port by TCP (instead of default port). because we can't indentify this device by another way. I can prepare Pull Request that will identify your device by some fixed port.

**Comment by amalitol** [comment]
Hi @ikheifets-splunk,  It makes sense to me. What to do next?

**Comment by ikheifets-splunk** [comment]
Hello, @amalitol !
You just need to send logs to 9001 port under TCP (same as Raritan DSX) and that already will work (it's didn't go to fallback) and your device would be identified as "Raritan DSX". If you need to separate DSX and DSX2 devices we can make pull request.
