### ISSUE TITLE
millisecond not getting generated and overriding timestamp for milliseconds not working

### ISSUE THREAD

**Issue by kavyavedika** [splunk/splunk-connect-for-syslog#2090]
We are in version 2.49.4. We have configured paloalto,tenable,f5 and a lot of devices to send data to sc4s. We are noticing couple of issues with respect to time zone and milliseconds.
1. All data coming to SC4S has no milliseconds in it. either it is 000 or a wrong millisecond for _time. We have tried using t_standard t_msg_only or t_everything. All have no milliseconds in them. We tried to override the props from HEC with custom time format and timezone but the HEC props are not making any difference. 
2. Time zone for a couple of hosts not getting mapped correctly and logging in future. We have set SC4S_DEFAULT_TIMEZONE to EUROPE/LONDON we see issues from paloalto hk region which is still logged in future. I have even tried sc4s_time_zone in compliance_meta_by_source.conf  - this havent made any difference. 
3. How can we override in sc4s timestamp from event. 

Need help in resolving these time issues and how can we parse data from SC4S. We need to understand why the receiving HEC layer props transforms are not making any difference does it mean that SC4S is already parsed and HEC props wont work? 
There is one last issue to report apart from timestamp. On tenable a few of its data are ignoring the compliance_meta_by_source filters and going to wrong index. out of 100 percent tenable data 90 percent of the data logging in to right index and 10 percent tenable data going to wrong index. 
Jul 04 09:03:43 server.org Tenable.ad[4]: "1" "1" "Global" "Global." "CN=ifnwie\, Engin,OU=Users,OU=UK,DC=global,DC=test,DC=org" "2749843" "" "msds-lastsuccessfulinteractivelogontime"=""2023-07-04T09:03:37.5209663Z""
sc4s_product ad
sc4s_vendor tenable

Example tenable data going to right index
Jul 04 12:36:25 server.org Tenable.ad[4]: "1" "1" "Global" "Global" "CN=SVC-APPDN,OU=Service Accounts,OU=Management,OU=UK,DC=global,DC=test,DC=org" "302494" "" "msds-lastsuccessfulinteractivelogontime"=""2023-07-04T12:35:31.9022696Z""
sc4s_product ad
sc4s_vendor tenable

**Comment by rjha-splunk** [comment]
Please file a support case and share the pcap file (anonymised log) , we need to see the real log to replicate and help here.

As well as you can share the anonymised log here as well.

**Comment by kavyavedika** [comment]
Please find the file attached. 3257331 there is already a case open.

**Comment by kavyavedika** [comment]
Any update on this? Do you need a call ?

**Comment by rjha-splunk** [comment]
we will be able to look into this soon,we will keep posted.

**Comment by rjha-splunk** [comment]
Yes lets have a call, kindly share your availability  @ rjha@splunk.com

**Comment by kavyavedika** [comment]
i have attached the details on the case with tar of the syslog-ng folder on
3257331. i am free today and tomorrow 5 to 8 IST.

Regards,
Kavya

**Comment by rjha-splunk** [comment]
Please ask assigned support person to schedule a call.

**Comment by kavyavedika** [comment]
ok

**Comment by ikheifets-splunk** [comment]
discussed this issue internally, in generally it's not a bug (original timestamp doesn't contains milliseconds)
