### ISSUE TITLE
Create a new filter for a10network thunders

### ISSUE THREAD

**Issue by amalitol** [splunk/splunk-connect-for-syslog#2094]
This is an ADC vendor. Behavior is similar to F5 BigIP. 
It has the following events (default): 
WAF (traffic)
SYSTEM and 
AUDIT
Any help, even showing how to create the filter from scratch would be appreciated since there is not too much information about it. 

Thank you,

**Comment by bparmar-splunk** [comment]
Hi @amalitol,

You can refer the [docs](https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/create-parser/).

**Comment by amalitol** [comment]
Hi @bparmar-splunk 

The documentation assumes you previously develop stuff for SC4S or you are an experienced developer, which I am not. Is there any other documentation (with practice examples) where I can create a specific parser for this vendor? 
If I could at least see how is the process. Step-by-step of creating a new source type? 

Thank you

**Comment by bparmar-splunk** [comment]
Hi @amalitol,
please capture .pcap file or raw message and sent it over mail or slack.

**Comment by amalitol** [comment]
I can provide a whole list of logs types:
[A10_4.1.4-GR1-P5_ELOG.pdf](https://github.com/splunk/splunk-connect-for-syslog/files/12134405/A10_4.1.4-GR1-P5_ELOG.pdf)

**Comment by bparmar-splunk** [comment]
@amalitol,
We have gone through the pdf provided above. There are examples but it seems it is of generic format.
We would need actual raw messages so that we can process events based on actual keywords.
Please send us raw messages on Slack DM or email.

**Comment by ikheifets-splunk** [comment]
Hello, @amalitol !
Can you please provide us .pcap file? We need examples of real logs, because lots of devices sending very similar logs and by this reason we wanna correctly identify your device and then use correct parser for your log message. 
In your pdf we can find different formats of logs (syslog, cef, leef). What of that your need to parse?

**Comment by amalitol** [comment]
Hi @ikheifets-splunk  
I'll be working in your request. Parse must be created for the cef logging. 
Thank you

**Comment by ikheifets-splunk** [comment]
Thanks a lot @amalitol !
Please send me it on email ikheifets@splunk.com . Because pcap file and your logs might contain sensitive information.

**Comment by amalitol** [comment]
I will.
But I have a question. @ikheifets-splunk, are you going to create a global parser for the whole a10network traffic or it's going to be just for my specific applications? I mentioned it because I only have this logging on to one virtual service. I you want to have the whole picture, I might need to enable the traffic of all the virtual services I want to monitor in an a10netwosks device. 

Thank you,

**Comment by amalitol** [comment]
Hi @ikheifets-splunk\,

I'm working with Roger Valencia, my a10networks SE to get all the information required.
There is a delay in getting the information but, I will have it sooner than later.

Thank you,

**Comment by amalitol** [comment]
Hi @ikheifets-splunk.
I have sent to you the .pcap file.

**Comment by amalitol** [comment]
Hi @ikheifets-splunk.
Please let me know if you need more information from the vendor or if the .pcap + .pdf was enough.

Thank you,

**Comment by ikheifets-splunk** [comment]
> I noticed the index created is netwaf. Does it include the audit and system logs?

It will work for all types of log if you proposed me correct logs.  CEF logs consists "vendor" and "product" inside the body. And we filtering by "vendor" and "product". You can see [here](https://github.com/splunk/splunk-connect-for-syslog/blob/main/tests/test_a10.py#L23) in your message A10 is "vendor" name vThunder is "product"

**Comment by amalitol** [comment]
Thank you for the update @ikheifets-splunk. So now I need to upgrade my current sc4s instance?

**Comment by amalitol** [comment]
Hi @ikheifets-splunk,
I have upgraded the cs4s to the latest version (3.3.0) and it seems the new parsing is not working. The logs I'm getting for [audit log] and [SYSTEM] appear as:
source = program:a10logd
sourcetype = nix:syslog
Do I need to do something else? 
Thank you,

**Comment by ikheifets-splunk** [comment]
@amalitol Can you provide me message that working incorrectly. I just remind you that you tell me parse CEF message and provided pcap file with CEF message

**Comment by amalitol** [comment]
Yes, Sr. 
Give me a couple of days and I will provide all the logs you need.

Thank you,

**Comment by amalitol** [comment]
I @ikheifets-splunk,
Hope you received the .pcap files I sent to you.
Thank you,
