### ISSUE TITLE
Docs: BYOE installation - "gomplate --help" doesn't return version

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#211]
The following states that "gomplate --help" can be used to determine that gomplate is the right version:
[](https://splunk-connect-for-syslog.readthedocs.io/en/master/gettingstarted/byoe-rhel7/)

The help command doesn't show the version, "gomplate --version" does.

**Comment by mepjad-k** [comment]
I included the full path, then worked.

**Comment by rfaircloth-splunk** [comment]
resolved in prior pr
