### ISSUE TITLE
Trusted TLS certificates no longer work with 3.0.0 due to RHEL -> Alpine change

### ISSUE THREAD

**Issue by lilyinstarlight** [splunk/splunk-connect-for-syslog#2116]
Due to the change from a RHEL-based container image to an Alpine-based container image in #2103, the RHEL commands for updating the CA trust in [`packages/sbin/entrypoint.sh`](https://github.com/splunk/splunk-connect-for-syslog/blob/v3.0.0/package/sbin/entrypoint.sh#L117-L126) no longer work

The bug can be reproduced by adding a `tls/trusted.pem` file and attempting to start the 3.0.0 container

Notably, it is a warning and not a fatal error that the entrypoint script failed, so I did not initially notice the problem until I found data was not getting forwarded despite SC4S running. You can see in the container logs that the CA certificate update failed, and in our environment we get a self-signed cert warning from curl and then SC4S says the HEC connection failed

The change should be a simple fix, though, so would I be able to PR this diff after testing? https://github.com/lilyinstarlight/splunk-connect-for-syslog/commit/8afb7043cc7ac180a0e267bef0f0e9aa632b0891

The contribution guide just mentions asking before making a PR. Thank you!

cc @mateuszpierzchala-splunk and @rjha-splunk (from #2103)

Some extra details on our setup:
* Red Hat Enterprise Linux 8.8
* Running via container with podman (unprivileged user)

**Comment by rjha-splunk** [comment]
Thank you, we will review and merge it.

We are still reviewing parts of it so the documentation is not updated for 3.x

**Comment by rjha-splunk** [comment]
we have merged the fix into main, it should release soon.

**Comment by lilyinstarlight** [comment]
I just got a chance to come back to this a bit ago, and I can now confirm that 3.0.1 works for us in testing. Thank you!
