### ISSUE TITLE
Documentation issue for .../sources/vendor/CyberArk/pta/

### ISSUE THREAD

**Issue by alasdairb** [splunk/splunk-connect-for-syslog#2127]
Document says the Vendor = Cyber-Ark Product=Vault
It should be Vendor = CyberArk Product=PTA

key	sourcetype	index	notes
Cyber-Ark_Vault	cyberark:pta:cef	main	none
CyberArk_PTA	cyberark:pta:cef	main	none

See in
https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/CyberArk/pta/

**Comment by mstopa-splunk** [comment]
Thank you for reporting, fixed: https://github.com/splunk/splunk-connect-for-syslog/blob/main/docs/sources/vendor/CyberArk/pta.md
