### ISSUE TITLE
NetApp OnTapp Update Support

### ISSUE THREAD

**Issue by techsystems-unix** [splunk/splunk-connect-for-syslog#2134]
Good Afternoon,

The latest version of Netapp Ontap is 9.12.1p5. Does Splunk SC4S support the latest version? We just want to proactively prepared prior to the upgrade to prevent loss in data ingestion.

Thanks,
Shaunice Yearwood

**Comment by mstopa-splunk** [comment]
Hi @techsystems-unix , thank you for reporting this. In your attached pcap file I can see mostly sshd events (https://www.strongdm.com/blog/view-ssh-logs) . We cannot classify them as Netapp OnTap based on the message format, but they can be still classified in the required way for example based on host or netmask. 

Can you please send NetApp OnTap events to test message-based filtering for this vendor?

**Comment by mstopa-splunk** [comment]
Closing the issue due to no response for more than 10 days; please refer to this thread in a new issue or request reopening in case of follow-up.
