### ISSUE TITLE
metallbsharingkey incorrect reference in service template

### ISSUE THREAD

**Issue by chipzzz** [splunk/splunk-connect-for-syslog#2136]
`metallbsharingkey` is under `service` in [values.yaml](https://github.com/splunk/splunk-connect-for-syslog/blob/9c06f97b28279b17def21d3b3e2854546438502a/charts/splunk-connect-for-syslog/values.yaml#L99-L102)

While in the [template ](https://github.com/splunk/splunk-connect-for-syslog/blob/9c06f97b28279b17def21d3b3e2854546438502a/charts/splunk-connect-for-syslog/templates/service.yaml#L7)

is referenced as ` .Values.metallbsharingkey` instead of  as `.Values.service.metallbsharingkey`

**Comment by mstopa-splunk** [comment]
Thank you for reporting, fixed: https://github.com/splunk/splunk-connect-for-syslog/pull/2151#issuecomment-1715396650
