### ISSUE TITLE
Please share the sc4s documentation for implementation

### ISSUE THREAD

**Issue by ashokreddy2** [splunk/splunk-connect-for-syslog#2142]
Please share the sc4s documentation for implementation.
sc4s in vm
sc4s in cloud foundry 
sc4s in container

**Comment by mstopa-splunk** [comment]
@ashokreddy2 please find SC4S documentation here: https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/

**Comment by mstopa-splunk** [comment]
Closing this issue due to lack of response over the past 10 days
