### ISSUE TITLE
feat - http compression

### ISSUE THREAD

**Issue by yaleman** [splunk/splunk-connect-for-syslog#2144]
** Feature Request description: **

Please include configuration/tests for HTTP compression when sending from syslog-ng to HEC now that syslog-ng/syslog-ng#4137 has been merged. This will allow for *significant* reductions in client traffic once implemented.

Reference: [docs here](https://github.com/therandomstring/syslog-ng/blob/b77018bb73b3be7a04ed4a54ae0c86677cc7cc66/news/feature-4137.md)

Below you can see a configuration example:

```
destination d_http_compressed{
	http(url("127.0.0.1:80"), content-compression("deflate"), accept-encoding("all"));
};
```

**Comment by ikheifets-splunk** [comment]
It seems HTTP compression was released in 3.9.0
