### ISSUE TITLE
pan_panos_userid missing in docs

### ISSUE THREAD

**Issue by ehlo550** [splunk/splunk-connect-for-syslog#2149]
**Describe the bug**
The key pan_panos_userid is missing from the docs [Sourcetype and Index Configuration](https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/PaloaltoNetworks/panos/#sourcetype-and-index-configuration)

**Comment by mstopa-splunk** [comment]
thank you for reporting, solved: https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/PaloaltoNetworks/panos/
