### ISSUE TITLE
Palo Alto logs are not recognized for one host

### ISSUE THREAD

**Issue by chrisengie** [splunk/splunk-connect-for-syslog#2155]
**Was the issue replicated by support?**
It is being done on slack

**What is the sc4s version ?**
2.43.2

**Is there a pcap available?**
Yes, I gave it to Rahul (rjha).

**Is the issue related to the environment of the customer or Software related issue?**
I'd say the software since all other palo alto devices are treated correctly.

**Is it related to Data loss, please explain ?**
Protocol? Hardware specs?
No
**Last chance index/Fallback index?**
There's a postfilter that avoids that but it is fallback sourcetype
**Is the issue related to local customization?**
No

**Do we have all the default indexes created?**
Yes

**Describe the bug**

Hello I've got a palo alto device that is not recognized as such by sc4s. I'm wondering why... It goes to fallback
here is an example of a sample that has been anonymized by the "scrub" splunk command:
1,2003/01/20 14:49:19,,TRAFFIC,end,2501,2003/01/20 14:49:19,109.131.000.210,010.16.00.240,010.16.14.240,00.11.010.13,Internet to Z0,,,ssl,khxk1,External Zone,Internal Zone,hneysdxa0/1,hneysdxa0/2,XjsxsKTGX,2003/01/20 14:49:19,47206,1,33003,232,34001,232,0h00022t,tcp,allow,6400,1020,2000,22,2003/01/20 14:48:57,1,any,,5042000103306432013,0b0,Lorenza,010.16.0.0-010.21.053.053,,01,01,tcp-fin,0,0,0,0,,MEE-SAUL-HF-KQ-OpCfa00,from-policy,,,0,,0,,N/A,0,0,0,0,32goq23t-1000-0010-y431-65y3v001e042,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2003-01-00B11:49:19.864+03:00,,,encrypted-tunnel,networking,browser-based,4,"used-by-rosaria,able-to-transfer-file,has-known-vulnerability,tunnel-other-application,pervasive-use",,ssl,no,no,0

sc4s_tags are :
wireformat:rfc\|wireformat:rfc3164\|.app.app-fallbackz-lastchance\|.app.app-fix-invalid-program-z_bsdconvention\|.source.s_PAN_PANOS_UTC_TZ\|.app.postfilter-paloaltonetworks_panos_utc

**To Reproduce**
Use the pcap to ingest the data to a custom port.

**Comment by rjha-splunk** [comment]
the problem is sc4s parser is expecting serial number in the message `1,2023/09/05 16:17:34,<here>,SYSTEM,`
```
application app-syslog-pan_panos[sc4s-syslog] {
	filter {
        "${PROGRAM}" eq ""
        and message('1,' type(string) flags(prefix))
        and message('^1,[^,]+,[^,]+,[A-Z]+\,')
        ;
    };	
    parser { app-syslog-pan_panos(); };
};
```
the regex is expecting some value here

**Comment by phamthanhsang-cs** [comment]
> the problem is sc4s parser is expecting serial number in the message `1,2023/09/05 16:17:34,<here>,SYSTEM,`
> 
> ```
> application app-syslog-pan_panos[sc4s-syslog] {
> 	filter {
>         "${PROGRAM}" eq ""
>         and message('1,' type(string) flags(prefix))
>         and message('^1,[^,]+,[^,]+,[A-Z]+\,')
>         ;
>     };	
>     parser { app-syslog-pan_panos(); };
> };
> ```
> 
> the regex is expecting some value here

Hi, i would like to know if there's any workaround on SC4S for this issue ?
