### ISSUE TITLE
Requesting custom parser for Axway

### ISSUE THREAD

**Issue by sursaini23** [splunk/splunk-connect-for-syslog#2164]
**What is the sc4s version ?** v3.4.1 SC4S

**Is there a pcap available?** Will share pcap on request

**What the vendor name?** Axway

**What's the product name?** Axway

** Feature Request description: ** Requesting custom parser for Axway logs

** Should it support TCP or UDP?** TCP

** Do you want to have it for local usage or prepare a github PR? ** github PR

**Comment by ikheifets-splunk** [comment]
Hello, @sursaini23 !
Can you please provide .pcap file with raw logs that producing Axway?

**Comment by ikheifets-splunk** [comment]
You can send me on my email - ikheifets@splunk.com

**Comment by ikheifets-splunk** [comment]
@sursaini23 Can you tell me please what the [product](https://www.axway.com/en/products) of Axway are you using?

**Comment by sursaini23** [comment]
Hello, I will get back to you shortly on the above queries. Thanks

**Comment by sursaini23** [comment]
axway secure transport is the product, I will share logs on email at earliest

**Comment by ikheifets-splunk** [comment]
Hello, @sursaini23 !
You sent me on email not a .pcap file. Please sent me a .pcap
