### ISSUE TITLE
ESXI VMware parser issue?

### ISSUE THREAD

**Issue by RyanKershawWhittle** [splunk/splunk-connect-for-syslog#2166]
Hi is this a sc4s parser error?

![image](https://github.com/splunk/splunk-connect-for-syslog/assets/101280607/8e93d10a-3383-4b15-9fb5-58c417cd5395)
 
 looks like event splitting is not done correctly? the program -- vpxa -- is replicated two times for one event?

**Comment by mstopa-splunk** [comment]
Hi @RyanKershawWhittle please check the raw message (https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/create-parser/#start-with-a-raw-log-message) and let me know if it's not replicated already there. At first glance I don't see message rewriting in SC4S vsphere config

**Comment by RyanKershawWhittle** [comment]
Will close this it looks fine... 

Looked like it wasnt splitting up events correctly i.e. 

- - Vpxd - - --vpxd--
