### ISSUE TITLE
Parser for Semperis DSP logs

### ISSUE THREAD

**Issue by muditrao82** [splunk/splunk-connect-for-syslog#2211]
**What is the sc4s version ?**
sc4s version=2.49.8
**Is there a pcap available?**
attached in log files.

**What the vendor name?**
Semperis DSP

**What's the product name?**
Semperis DSP

** Feature Request description: **
Logs parser for Semperis DSP

** Should it support TCP or UDP?**
UDP

** Do you want to have it for local usage or prepare a github PR? **
[demologs.txt](https://github.com/splunk/splunk-connect-for-syslog/files/12769703/demologs.txt)

**Comment by ikheifets-splunk** [comment]
@muditrao82 are you solved this issued already in splunk user group and I can close this issue?

**Comment by muditrao82** [comment]
@ikheifets-splunk this issue has not been resolved from Splunk user group. My main technical contact and SE at Splunk informed me that you were working on completing the parser for Semperis DSP logs. What is the current status and when will this be completed?

**Comment by ikheifets-splunk** [comment]
Hello, @muditrao82 !
I linked a pull request to this issue.
If you wanna test it before release you can pull development version [ghcr.io/splunk/splunk-connect-for-syslog/container3:pr-2259](ghcr.io/splunk/splunk-connect-for-syslog/container3:pr-2259)

**Comment by muditrao82** [comment]
Hello,

I have download the parser and it’s not parsing any of the fields. Only
source type is correct.

**Comment by ikheifets-splunk** [comment]
Hello, @muditrao82 !

Usually we not parsing such formats only identifying `vendor` and `product`. 
But after you mentioned that important for you, it I updated my PR and it's working like that:

![Screenshot 2023-11-13 at 23 23 27](https://github.com/splunk/splunk-connect-for-syslog/assets/138466237/ff2c594b-a4e8-45af-866d-4aac1afc44c6)

P.S. Hope that it would be okay for you
