### ISSUE TITLE
Cohesity: some logs are not detected by parser, filter needs to be updated

### ISSUE THREAD

**Issue by aalisher-tmx** [splunk/splunk-connect-for-syslog#2215]
**Was the issue replicated by support?**
No
**What is the sc4s version ?**
3.1.4
**Is there a pcap available?**
can share via email or via sales engineer 
**Is the issue related to the environment of the customer or Software related issue?**
Software
**Is it related to Data loss, please explain ?**
Protocol? Hardware specs?
cohesity is using port 514 (tcp) to ingest syslog
**Last chance index/Fallback index?**
Fallback
**Is the issue related to local customization?**

**Do we have all the default indexes created?**
Yes
**Describe the bug**
I have defined a custom index for the keys defined in https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/Cohesity/cluster/ in a metadata file. But some of the logs are still going to infraops and osnix indexes. Looks like filter is not detecting some of the source types.
**To Reproduce**

**Comment by ikheifets-splunk** [comment]
@aalisher-tmx Please don't forget mention this issue, when you will send .pcap file. Will wait your .pcap file

**Comment by ikheifets-splunk** [comment]
@aalisher-tmx I looked at your .pcap file. We identifying logs as `cohesity`  if logs produced by program `cluster_audit` or `dataprotection_events`. In your case logs producing mostly producing `sshd`. we can't identify your logs by `sshd` because it's a very generic and popular program. By this reason it's not a bug.

**Comment by ikheifets-splunk** [comment]
@aalisher-tmx As I already mentioned `ssh` logs might be produced by any vendor and device, we mostly skipping such logs and analysing only device-specific logs. I also will talk with another maintainers tomorrow about that, but it's seems that we wouldn't fix that.

If you really need to mark them ask them as `cohesity` then I can propose such approach. You need to ask tech support provide you custom local configuration that will identify logs as `cohesity` if hostname is equal to some hostname (constant name of device that producing this logs).

**Comment by ikheifets-splunk** [comment]
@aalisher-tmx if we talking about `api_audit ` please send me .pcap with that. In your .pcap I didn't find something similar.
If we talking about ssh, I already [described what to do on my previous comment](https://github.com/splunk/splunk-connect-for-syslog/issues/2215#issuecomment-1749380366)

**Comment by ikheifets-splunk** [comment]
please update SC4S on version [3.4.7](https://github.com/splunk/splunk-connect-for-syslog/releases) we added support of `api-audit`
