### ISSUE TITLE
Pure Storage: filter needs to be updated as some logs are going to wrong index

### ISSUE THREAD

**Issue by aalisher-tmx** [splunk/splunk-connect-for-syslog#2216]
**Was the issue replicated by support?**
No
**What is the sc4s version ?**
3.1.4
**Is there a pcap available?**
yes. Will share via email or via sales engineer
**Is the issue related to the environment of the customer or Software related issue?**
Software
**Is it related to Data loss, please explain ?**
Protocol? Hardware specs?
pure appliances are using port 514 (tcp) to ingest syslog
**Last chance index/Fallback index?**
fallback
**Is the issue related to local customization?**

**Do we have all the default indexes created?**
yes
**Describe the bug**
I have defined a custom index in the splunk metadata file for which most of the logs are getting ingested except few which are going to infraops and osnix indexes as well. Looks like filter needs to be updated to capture the logs being missed. Thanks.  (https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/PureStorage/array/)
**To Reproduce**

**Comment by mstopa-splunk** [comment]
hi @aalisher-tmx sure, please send a pcap through Salesforce support ticket or via sales engineer and mention my username so it gets passed to me

**Comment by mstopa-splunk** [comment]
hello @aalisher-tmx my apologies for the delay. We've started working on this issue but I can't find a sample message to reproduce the bug, all the messages that I tried from the provided pcap file worked correctly. Please send a sample message that is not parsed correctly

**Comment by mstopa-splunk** [comment]
fixed in 3.11.1
