### ISSUE TITLE
Request AS400 Device

### ISSUE THREAD

**Issue by shihab123** [splunk/splunk-connect-for-syslog#2238]
**What is the sc4s version ?**
4.3.1
**Is there a pcap available?**
Yes
**What the vendor name?**
AS400
**What's the product name?**
AS400
** Feature Request description: **
Onboard AS400 Device Data
** Should it support TCP or UDP?**
UDP
** Do you want to have it for local usage or prepare a github PR? **
local usage
[AS400_syslog_data.txt](https://github.com/splunk/splunk-connect-for-syslog/files/12886572/AS400_syslog_data.txt)

**Comment by ikheifets-splunk** [comment]
Hello, @shihab123 !

According to your CEF logs your device is "PowerTech Interact".  In this log format (CEF) vendor name and product name are embedded in message header.

Are you sure that this logs for AS400? As I understood you mean IBM device.

**Comment by shihab123** [comment]
Hello,

Vendor is IBM (ISeries)
Product is called Interact


Thanks,
________________________________

**Comment by ikheifets-splunk** [comment]
@shihab123 if it's okay if we will identify in splunk such device as "PowerTech Interact", because this vendor information was encoded in logs?

**Comment by ikheifets-splunk** [comment]
@shihab123 Cool, thanks!
Can you please also provide .pcap file with that logs (send me on my email: ikheifets@splunk.com)?
In your txt files hidden message headers like log date, hostname, etc. I need it because I wanna help you and also it can help me to doublecheck that parser working correctly.

**Comment by ikheifets-splunk** [comment]
@shihab123 Just give me a PCAP file and I will make PR on 1-2 days.

**Comment by ikheifets-splunk** [comment]
Hello @shihab123 ! You don't provided me pcap file :( By this reason it would be hard to test my [Pull Request](https://github.com/splunk/splunk-connect-for-syslog/pull/2248) for this feature.

Please test your logs on this development docker image of sc4s https://github.com/splunk/splunk-connect-for-syslog/pkgs/container/splunk-connect-for-syslog%2Fcontainer3/140155454?tag=pr-2248 . And tell is it working for you or not. If yes we will merge and it would be available on the next release version.

P.S. Please also tell me what index would be fluent for that logs. Currently it's going to netops

**Comment by ikheifets-splunk** [comment]
@shihab123 I created pull request for your issue, please test if it work for you, and if yes, I will merge it.
You just need to update your sc4s on that [development version of sc4s (docker image)](https://github.com/splunk/splunk-connect-for-syslog/pkgs/container/splunk-connect-for-syslog%2Fcontainer3/140155454?tag=pr-2248) to check your logs format.
