### ISSUE TITLE
Add a filter to support Sonic logs

### ISSUE THREAD

**Issue by mpaidela** [splunk/splunk-connect-for-syslog#2294]
**What is the sc4s version ?**
latest
**Is there a pcap available?**
NA
**What the vendor name?**
Sonic
**What's the product name?**
Sonic
** Feature Request description: **
Add a filter to support Sonic logs
** Should it support TCP or UDP?**
both
** Do you want to have it for local usage or prepare a github PR? **
Yes

**Comment by mpaidela** [comment]
attaching sample events here.
[Sonic_sample_logs.txt](https://github.com/splunk/splunk-connect-for-syslog/files/13686990/Sonic_sample_logs.txt)

**Comment by mstopa-splunk** [comment]
@mpaidela there are multiple vendors with matching name (Sonic, Dell Networking SONiC, Sonicwall, sonic-net). Please attach a link to vendor documentation.

**Comment by mpaidela** [comment]
@mstopa-splunk Here the links.

[https://www.dell.com/support/kbdoc/en-us/000215519/dell-networking-sonic-system-log-messages-and-audit-logs#:~:text=They%20include%20events%20such%20as,classified%20based%20on%20severity%20level](url)
 
[https://www.dell.com/support/kbdoc/en-us/000218235/dell-networking-sonic-how-to-configure-switch-to-send-logs-to-syslog-servers?lang=en](url)

**Comment by mpaidela** [comment]
@mstopa-splunk any update?

**Comment by mstopa-splunk** [comment]
@mpaidela PR https://github.com/splunk/splunk-connect-for-syslog/pull/2315 is ready and should be merged by the end of the week. 
In the meantime please read staging documentation for this vendor: https://splunk.github.io/splunk-connect-for-syslog/2315/sources/vendor/Dell/sonic/ and notice that this vendor's logs have no distinguishable parts of logs, so you have to either use a Vendor Product by Source (vps) parser.

Let me know if that's new for you and I will attach links to the documentation.
You can test it with image `ghcr.io/splunk/splunk-connect-for-syslog/container3:pr-2315`

**Comment by mstopa-splunk** [comment]
Support for Dell SONiC has been added in  SC4S v.3.19.0
