### ISSUE TITLE
Add Aviatrix as a Known Vendor

### ISSUE THREAD

**Issue by wozzies** [splunk/splunk-connect-for-syslog#2332]
**What is the sc4s version ?**
3.19.0

**Is there a pcap available?**
yes

**What the vendor name?**
Aviatrix

**What's the product name?**
Aviatrix Gateway
Aviatrix Controller

** Feature Request description: **
Add Aviatrix to the known vendors list

** Should it support TCP or UDP?**
Both

** Do you want to have it for local usage or prepare a github PR? **
Included in next upgrade

**Comment by ikheifets-splunk** [comment]
Hello, @wozzies !
Can you share pcap file with logs that producing your device?
You can send it on email: ikheifets@splunk.com

**Comment by ikheifets-splunk** [comment]
Hello, @wozzies !
I've got email, but your pcap file not consist syslog messages at all.
Please open your file using WireShark and check it. 
I need a pcap with syslog messages that producing your device.

**Comment by ikheifets-splunk** [comment]
Hello, @wozzies !
I've got email **2 weeks ago**, but your pcap file not consist syslog messages at all.
You didn't response on my previous message. We can't implement parser for your message if you can't provide log message format.
