### ISSUE TITLE
A new parser for Dell Avamar logging

### ISSUE THREAD

**Issue by RichardHEB** [splunk/splunk-connect-for-syslog#2341]
**What is the sc4s version ?**
pr-2259
**Is there a pcap available?**
Yes
**What the vendor name?**
Dell
**What's the product name?**
Avamar
** Feature Request description: **
Need a parser created for Avamar logs
** Should it support TCP or UDP?**
UDP
** Do you want to have it for local usage or prepare a github PR? **
local and github PR

**Comment by ikheifets-splunk** [comment]
Hello, @RichardHEB !

> What is the sc4s version ?
> pr-2259

Please use release version (for example `3.19.0` or `latest`), we asking customer use dev version only for test is Pull Request working before release :) 

> Is there a pcap available?
> Yes

Please send me on email: ikheifets@splunk.com

**Comment by ikheifets-splunk** [comment]
Hello, @RichardHEB !
Haven't got pcap from you!

**Comment by RichardHEB** [comment]
Hi @ikheifets-splunk I had asked Andre (Splunk) to send it to you. He's had it since day one, I can email it to your Splunk email, do not want to posted open in public here. Am checking with Andre as well.

**Comment by ikheifets-splunk** [comment]
@RichardHEB finally received it, Andre shared with me.

**Comment by RichardHEB** [comment]
Hi Ilya, any updates on this one?

**Comment by ikheifets-splunk** [comment]
Hello, @RichardHEB !
During next few hours will make build for your that you can take for test ;)

**Comment by ikheifets-splunk** [comment]
Hello, @RichardHEB !
Please upgrade on our dev version to test is it working for you:
`docker pull ghcr.io/splunk/splunk-connect-for-syslog/container3:pr-2393`

We parsed your log message (sensitive data like ip, emails anonymized):
```
<141> Apr 05 18:19:55 MCS:BS::BACKUP::EDIT: <Code> 22555 <Type> AUDIT <Severity> PROCESS <Category> SECURITY <User> email@my.com <HwSource> amavar <Summary> Changed backup expiration. <path> /clients/Dev-Cert/Windows/test.com <createtime> 2024-02-03 02:32:09 CST <plugin> 3001 <labelnum> 388 <expiration> 2024-02-16 <requestor> <requestor domain="/" host="1.1.1.1" product="test" role="Administrator" user="email@my.com"/>
```

Will look at Splunk like this:
<img width="1727" alt="Screenshot 2024-04-05 at 18 58 47" src="https://github.com/splunk/splunk-connect-for-syslog/assets/138466237/7cf7f2a1-25fa-4132-ab14-62c3ff46246c">

**Comment by ikheifets-splunk** [comment]
Hello, @RichardHEB !
I've got your email that is working for you and question about release. If we talking about official release 7-10 days, because we have a process of review and release.

If you need it today and don't want to wait, please [embed parser that provided on PR](https://github.com/splunk/splunk-connect-for-syslog/blob/b159c19f3dbbecb5e85e995ef2225e81691f05fd/package/etc/conf.d/conflib/syslog/app-syslog-dell_avamar.conf) as local parser. 

For that:
1. Use latest SC4S version
2. place parser that I mentioned here `/opt/sc4s/local/config/app-parser`
3. check that you mounting to docker container this folder `/opt/sc4s/local/config`

**Comment by RichardHEB** [comment]
Ilya, we tested as instructed above and also ran a load test, everything is working as it should with the latest SC4S version 3.22.3; we put the parser in this folder:` /opt/sc4s/local/config/app-parsers` and our docker is mounted to `/opt/sc4s/local` 
Let me know when it is merged with main and in the latest version. Thanks Richard

**Comment by ikheifets-splunk** [comment]
@RichardHEB It will be released during 24h

**Comment by RichardHEB** [comment]
@ikheifets-splunk Hi Ilya,  any word? I still don't see it merged to main and we were hoping to deploy to cert then prod today. Thanks!

**Comment by ikheifets-splunk** [comment]
It has been released https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v3.23.0
