### ISSUE TITLE
Documentation conflict regarding load balancers

### ISSUE THREAD

**Issue by splaarmy** [splunk/splunk-connect-for-syslog#2358]
**Describe the bug**
SC4S documentation mentions not using load-balancers in a few places, such as https://splunk.github.io/splunk-connect-for-syslog/main/lb/, however on the page linked below seems to list a load-balancer as a prerequisite:

`A network load balancer (NLB) configured for round-robin. Note: Special consideration may be required when more advanced products are used. The optimal configuration of the load balancer will round-robin each http POST request (not each connection).`

https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/getting-started-runtime-configuration/

**To Reproduce**
1. Go to https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/getting-started-runtime-configuration
2. Item in question is currently the second paragraph in the Prerequisite section.

**Comment by fyodorr** [comment]
The loadbalancers in this case have different usages. 

The loadbalancer that's recommended is the load balancer for balancing the http (HEC) traffic to indexers.

The loadbalancer that's not recommended is the load balancer that's placed infront of the syslog server (SC4S).

**Comment by rjha-splunk** [comment]
We are working on documentation , we will update the sections to make it more clear cc: @mstopa-splunk

**Comment by rjha-splunk** [comment]
The clarification documentation is merged.
