### ISSUE TITLE
Parser de Squid Proxy

### ISSUE THREAD

**Issue by JosepSirt** [splunk/splunk-connect-for-syslog#2359]
**What is the sc4s version ?**
3.21.0

**Is there a pcap available?**
Yes

**What the vendor name?**
Squid

**What's the product name?**
Squid Proxy

** Feature Request description: **
When I configured the events of a SquidProxy to be sent to an SC4S and from there to send them to my Splunk Cloud, I realized that they arrive in sc4s_fallback format. 

** Should it support TCP or UDP?**
Support both TCP & UDP

** Do you want to have it for local usage or prepare a github PR? **
github PR

**Comment by mstopa-splunk** [comment]
hi @JosepSirt can you send a pcap file through Splunk support or to mstopa@splunk.com?

**Comment by mstopa-splunk** [comment]
@JosepSirt if the vendor has docs with description and examples we can start with that also while waiting for raw messages. If not, can we close this issue and reopen when the customer provides the events?

**Comment by JosepSirt** [comment]
Yes, we are going to close the case.

The client is no longer interested in integrating Squid into Splunk.

Thank you very much for the help.
