### ISSUE TITLE
All Sophos Logs go to netdlp Index

### ISSUE THREAD

**Issue by jungleboogie75** [splunk/splunk-connect-for-syslog#2395]
**What is the sc4s version ?**
3.22.2

**Describe the bug**
All of the data for Sophos is sent to the netdlp index rather than being routed to more logical destinations. My customer only had a few sourcetypes from Sophos, but these are the overrides I used:

sophos_xg_content_filtering,index,netproxy 
sophos_xg_event,index,netauth 
sophos_xg_firewall,index,netfw 
sophos_xg_waf,index,netwaf

**Comment by mstopa-splunk** [comment]
hi @jungleboogie75 I added `sophos_xg_firewall,index,netfw` to `splunk_metadata.csv` and it worked.

![image](https://github.com/splunk/splunk-connect-for-syslog/assets/139441697/e2d980e2-ed5c-4769-b83a-366e90441ea6)

![image](https://github.com/splunk/splunk-connect-for-syslog/assets/139441697/ada31b5d-ab2e-4fbf-8dcf-1e2fc91144da)

For enhancement/bug fix issues please open a new github issue and refer to this one, for support please open a Splunk support ticket
