### ISSUE TITLE
Docs: TLS_PORT not detailed, even though it exists in code for various sources

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#244]
Within the different templates for various sources, the code checks for a TLS_PORT. For example:
SC4S_LISTEN_CISCO_ISE_TLS_PORT

When looking over existing docs (index.md), it never mentions these variables but rather regular UDP and TCP options.

**Comment by rfaircloth-splunk** [comment]
Fixed in docs
