### ISSUE TITLE
Documentation sample mismatches

### ISSUE THREAD

**Issue by geoffmartin** [splunk/splunk-connect-for-syslog#2463]
On the documentation page for destinations it seems the code for examples 5 and 6 (for "asa" and "epo" respectively) are inverted.

Example 5 is supposed to be ASA but code filters for "mcafee" and "epo"
Example 6 is supposed to be EPO but code filters for "cisco" and "asa"

https://splunk.github.io/splunk-connect-for-syslog/main/destinations/

**Comment by rjha-splunk** [comment]
@cwadhwani-splunk Kindly check and correct this.

**Comment by cwadhwani-splunk** [comment]
A PR has already been raised to update the destination.md file.
PR link: https://github.com/splunk/splunk-connect-for-syslog/pull/2470

**Comment by rjha-splunk** [comment]
PR raised and will be merged.
