### ISSUE TITLE
Fix InfoBlox NIOS DNS for CIM compliance

### ISSUE THREAD

**Issue by jnudell** [splunk/splunk-connect-for-syslog#2483]
As per current documentation (https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/InfoBlox/) InfoBlox NIOS DNS data is not CIM compliant and the current recommendation is to use Splunk Stream (which has not been updated in over a year).

I would like to request that the SC4S team fix the InfoBlox NIOS DNS data to be CIM compliant.

**Comment by rjha-splunk** [comment]
We will review this, SC4S provides metadata for sourcetype, source and addon.

**Comment by jnudell** [comment]
Hi @rjha-splunk, do you have any updates on this?  Do you have more technical details regarding why InfoBlox NIOS DNS data is not CIM compliant at this time?

Thanks!

**Comment by rjha-splunk** [comment]
Hi @jnudell what do you mean by CIM compliance here, SC4S prepares metadata to handover to TAs.

Can you please elaborate it in detail?

**Comment by rjha-splunk** [comment]
The issue is fit for Sales and Support ticket,Unfortunately SC4S team can't extend help here.

**Comment by jnudell** [comment]
Splunk support directed me to post the issue here on GitHub.  Are you indicating that this issue, which is called out in the SC4S notes (https://splunk.github.io/splunk-connect-for-syslog/main/sources/vendor/InfoBlox/) will never be resolved by the SC4S team?

**Comment by rjha-splunk** [comment]
hi @jnudell , i think there is a misunderstanding , the CIM compliance as i mentioned earlier is taken care not by SC4S team but other teams in Splunk, we just provide metadata to the TAs.

We are not sure what is needed to be fixed here, from SC4S side we are preparing data as documented, Please mention the ticket number i will look into and talk to support and as well please let me know your CSM.

**Comment by jnudell** [comment]
Ok, we have spoken and I will pursue this via the TA teams.
