### ISSUE TITLE
Referencing field values in postfilter parser

### ISSUE THREAD

**Issue by rucete** [splunk/splunk-connect-for-syslog#2493]
Hi, 

I'm trying to implement a block parser for for fortigate events. Pretty straightforward:

```
block parser fortinet_fortios_logid-postfilter() {
channel {
	rewrite(r_set_dest_splunk_null_queue);
	};
};

application fortinet_fortios[sc4s-postfilter] {
filter {
	"${fields.sc4s_vendor}" eq "fortinet" and
	"${fields.sc4s_product}" eq "fortios" and
	"${.values.action}" eq "allowed";
	};		
	parser { fortinet_fortios_logid-postfilter(); };
};
```

The thing is I cannot seem to find documentation on how to correctly reference this value: 

`"${.values.action}" eq "allowed";`

I'm just trying to filter out allowed traffic. I know the rest of the parser works because without that ".values.action" line, it drops all events. No errors are reported in the sc4s logs. 

I'm not just looking to resolve this issue, but a link to the documentation where this is explained (besides SC4S's docs on github, which I've read) is also appreciated. 

Thank you.

**Comment by rjha-splunk** [comment]
The fields are not available to sc4s to filter , the main fields to filter is usually start with sc4s_* fields , Best will using regexes based on MATCH() and MESSAGE()

[](https://syslog-ng.github.io/admin-guide/110_Template_and_rewrite/001_Modifying_messages/008_Custom_SDATA_fields)

[](https://axoflow.com/docs/axosyslog-core/chapter-parsers/sdata-parser/_print/?highlight=sdata#prefix)

Official document to read about what is implemented.

**Comment by cwadhwani-splunk** [comment]
@rucete 
Since we have not heard back, I am closing this issue. Feel free to reopen or create a new issue if you have further queries.

**Comment by rucete** [comment]
Hi, sorry for the late response. In case it helps someone, this was the correct answer for me:

```
# file: /opt/sc4s/local/config/app_parsers/rewriters/fortinet_fortios_action-postfilter.conf

block parser action_allowed_fortinet-postfilter() {
channel {
                rewrite(r_set_dest_splunk_null_queue);
        };
};

application action_allowed_fortinet-postfilter[sc4s-postfilter] {

filter {
                "${fields.sc4s_vendor}" eq "fortinet" and
                "${fields.sc4s_product}" eq "fortios" and
                message("^.*action=\"(pass|passthrough|log-only|detected|allowed|accept|close|dns|ip-conn|allow|server-rst|client-rst)\".*$")
                ;
        };

        parser { action_allowed_fortinet-postfilter(); };
};
```

And this is the test event I am working with:
```
date=2024-05-27 time=11:18:26 devname="FRW009" devid="FG800FT977652098" eventtime=1719479003329404637 tz="+0200" logid="0000000013" type="traffic" subtype="forward" level="notice" vd="IT" srcip=172.20.108.91 srcname="ASSE483" srcport=64328 srcintf="BUILD" srcintfrole="lan" dstip=8.8.8.8 dstport=443 dstintf="VLAN01" dstintfrole="lan" srcuuid="ffff203c-ffff-ffff-ffff-c9ffff0bffff" dstuuid="ffff203c-ffff-ffff-ffff-ffffffff3455" srccountry="Reserved" dstcountry="Italy" sessionid=933058694 proto=6 action="client-rst" policyid=6 policytype="policy" poluuid="bfffff0c-ffff-ffff-ffff-24ffffffffff" policyname="HTTP_Corporate" service="HTTPS" trandisp="noop" duration=5 sentbyte=2477 rcvdbyte=867 sentpkt=9 rcvdpkt=7 vwlid=2 vwlquality="Seq_num(1 VLAN01), alive, selected" vwlname="INTERNET" appcat="unscanned" osname="Windows" srcswversion="11 / 2020" unauthuser="anonymous" unauthusersource="kerberos" mastersrcmac="00:00:00:00:59:7f" srcmac="00:00:00:00:59:7f" srcserver=0 dsthwvendor="Advantech" dstdevtype="Router" masterdstmac="00:00:00:00:c1:78" dstmac="00:00:00:00:c1:78" dstserver=0
```

 I had some trouble understanding how to escape the "" and finding out which ```vendor_action``` corresponded to the actual ```action``` that got parsed in Splunk by the forti addon so that **all** the allowed traffic was dropped, and not only the one marked as allowed in the forti side, as Splunk parses several vendor actions (the ones in the regex) as ```action="allowed"```.

Thank you for your help.
