### ISSUE TITLE
Parser for Aruba SilverPeak events

### ISSUE THREAD

**Issue by jzcal8300** [splunk/splunk-connect-for-syslog#2529]
**What is the sc4s version?**
3.27.0
**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?**
Yes, I currently have a case opened for a parser and have uploaded logs to this case.
**What the vendor name?**
Aruba
**What's the product name?**
SilverPeak
**If you're requesting support for a new vendor, do you have any preferences regarding the default index and sourcetype for their events?**
I currently have logs going to silverpeak index with sdwan sourcetype, but the parsing is not right.

**Do you have syslog documentation or a manual for that device??**
https://www.silver-peak.com/sites/default/files/userdocs/orchestrator_operators_guide.pdf

**Feature Request description:**
Parser for Aruba SilverPeak logs.
**Do you want to have it for local usage or prepare a github PR?**
local and public as I would think more might benefit for this parser, but I would like to get my logs parsed correctly as soon as possible.

**Comment by jzcal8300** [comment]
Sounds good. Let me know if you need the Splunk ticket and I can send that via email. Thanks.

**Comment by cwadhwani-splunk** [comment]
Yes, please provide me the ticket link.

**Comment by jzcal8300** [comment]
What's your splunk email and I can send it over?

**Comment by cwadhwani-splunk** [comment]
Here is the email: cwadhwani@splunk.com

**Comment by jzcal8300** [comment]
I sent the ticket information over yesterday. Thanks!

**Comment by cwadhwani-splunk** [comment]
Thanks @jzcal8300 
We have received the ticket and the attached files.

**Comment by wojtekzyla** [comment]
Solved in #2537

**Comment by wojtekzyla** [comment]
Solved in #2537
