### ISSUE TITLE
Juniper sourcetype

### ISSUE THREAD

**Issue by n0068702** [splunk/splunk-connect-for-syslog#2544]
**What is the sc4s version?**
version = "3.4.2"

**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?**
?

**What the vendor name?**
Juniper

**What's the product name?**
firewall

**If you're requesting support for a new vendor, do you have any preferences regarding the default index and sourcetype for their events?**

index = juniper_admin 
sourcetypes = juniper:junos:admin
                         junos:firewall

**Do you have syslog documentation or a manual for that device??**

**Feature Request description:**

Need to add these sourcetypes to sc4s vendor

**Do you want to have it for local usage or prepare a github PR?**

**Comment by n0068702** [comment]
I already had a case open with splunk
3533537<https://splunk.my.site.com/customer/5005a0000313kAoAAI>
Remind me how to run a pcap


Donald McNeill
Senior Infrastructure Engineer
Global Digital Services – Service Management and Delivery

From: cwadhwani-splunk ***@***.***>
Date: Monday, August 5, 2024 at 1:57 AM
To: splunk/splunk-connect-for-syslog ***@***.***>
Cc: McNeill, Don ***@***.***>, Mention ***@***.***>
Subject: Re: [splunk/splunk-connect-for-syslog] Juniper sourcetype (Issue #2544)

Hi @n0068702<https://urldefense.com/v3/__https:/github.com/n0068702__;!!JJ-tOIoKdBzLSfV5jA!pVsCi01bHHBC9MtHKMvahlb0iLeuFbWhqWk4UjqZbfuG-HOetel4Wx_BTUxGVxNCmKPOjFEP63d_CirkEQBWHprlgHezlY-q$>
Could you please create a support ticket and share the sample logs or the pcap file over that ticket? This will help us move forward with this case.

Thanks.

**Comment by cwadhwani-splunk** [comment]
Hi @n0068702 
Here are a couple of links that can help you to get the raw logs/pcap file:

- https://splunk.github.io/splunk-connect-for-syslog/main/create-parser/#procure-a-raw-log-message-using-tcpdump
- https://splunk.github.io/splunk-connect-for-syslog/main/troubleshooting/troubleshoot_resources/#obtain-raw-message-events

Please feel free to reach out to support if you need any further help with the PCAP file.

**Comment by n0068702** [comment]
Can we do a call?

Donald McNeill
Senior Infrastructure Engineer
Global Digital Services – Service Management and Delivery

From: cwadhwani-splunk ***@***.***>
Date: Wednesday, August 7, 2024 at 2:12 AM
To: splunk/splunk-connect-for-syslog ***@***.***>
Cc: McNeill, Don ***@***.***>, Mention ***@***.***>
Subject: Re: [splunk/splunk-connect-for-syslog] Juniper sourcetype (Issue #2544)

Hi @n0068702<https://urldefense.com/v3/__https:/github.com/n0068702__;!!JJ-tOIoKdBzLSfV5jA!rSlKr7RLQV2taTN75zILVPCSN3F-Ps69l7IW1-kvsQv0yPyZsjom8nuGBrKrujN5gYJxiawLZdTPnB0JwjW2FBCLAfzoINIn$>
Here are a couple of links that can help you to get the raw logs/pcap file:

  *   https://splunk.github.io/splunk-connect-for-syslog/main/create-parser/#procure-a-raw-log-message-using-tcpdump<https://urldefense.com/v3/__https:/splunk.github.io/splunk-connect-for-syslog/main/create-parser/*procure-a-raw-log-message-using-tcpdump__;Iw!!JJ-tOIoKdBzLSfV5jA!rSlKr7RLQV2taTN75zILVPCSN3F-Ps69l7IW1-kvsQv0yPyZsjom8nuGBrKrujN5gYJxiawLZdTPnB0JwjW2FBCLAZAzpfI_$>
  *   https://splunk.github.io/splunk-connect-for-syslog/main/troubleshooting/troubleshoot_resources/#obtain-raw-message-events<https://urldefense.com/v3/__https:/splunk.github.io/splunk-connect-for-syslog/main/troubleshooting/troubleshoot_resources/*obtain-raw-message-events__;Iw!!JJ-tOIoKdBzLSfV5jA!rSlKr7RLQV2taTN75zILVPCSN3F-Ps69l7IW1-kvsQv0yPyZsjom8nuGBrKrujN5gYJxiawLZdTPnB0JwjW2FBCLAQJLd2ll$>

Please feel free to reach out to support if you need any further help with the PCAP file.

**Comment by cwadhwani-splunk** [comment]
Hi @n0068702 
I have requested the support team to assist you with generating the pcap file. They will get in touch with you for the same.

**Comment by cwadhwani-splunk** [comment]
Hi @n0068702 

Could you please confirm if the call is solely for generating the pcap file, or if you need assistance with any other issues as well? This will help the support team prepare accordingly.

**Note:** For now, we just need the pcap file or sample raw logs to proceed with the case.

**Comment by Ruthieb-splunk** [comment]
Hi @cwadhwani-splunk, I'm the Splunk TSE working with the customer on the support side. SFDC case: 3533537.
We already had a call and I guided the customer on how to collect the pcap we need to create the sourcetype.
Once I have the file on the case I will share it with you.

**Comment by shihab123** [comment]
Update: we have upgraded the SC4S to 3.33.0 did not fix the parser issue.
