### ISSUE TITLE
Multiple inbound listener ports?

### ISSUE THREAD

**Issue by bicarbonate** [splunk/splunk-connect-for-syslog#2549]
Ive been through the docs but did not find anything aside from the single TLS or RFC64xx port setting. 
i have a project to hopefully replace a series of Splunk UF hosts that recieve syslog traffic with containers. The issue is, syslog on those hosts, is configured to recieve on 10 custom ports. 
The syslog configuration write the data to a port specific log file which is then ingested by the UF. 

Is it possible to define multiple inbound listener ports for the syslog-ng implementation used here?

**Comment by rjha-splunk** [comment]
we can configure multiple default listening port comma separated :
https://splunk.github.io/splunk-connect-for-syslog/main/gettingstarted/byoe-rhel8/#configure-sc4s-listening-ports 
```e.g. SC4S_LISTEN_DEFAULT_TCP_PORT=514,6504,6505,6506```
