### ISSUE TITLE
Need custom parser to filter the vcenter logs 

### ISSUE THREAD

**Issue by mpaidela** [splunk/splunk-connect-for-syslog#2553]
**What is the sc4s version?** 3.27.0

**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?**

**What the vendor name?** Vmware

**What's the product name?** vpshre

**If you're requesting support for a new vendor, do you have any preferences regarding the default index and sourcetype for their events?**

**Do you have syslog documentation or a manual for that device??**

**Feature Request description:**

**Do you want to have it for local usage or prepare a github PR?**

we have ingested vcenter logs into Splunk using sc4s, but user wants to drop some unwanted logs.

Could someone please assist us in creating a Custom parser?

**Comment by cwadhwani-splunk** [comment]
Here is what you can refer to:
https://splunk.github.io/splunk-connect-for-syslog/main/sources/#filtering-events-from-output

If you are still facing an issue with creating a parser please create a support ticket so that we can collect all the necessary information like sample logs to further assist you.

**Comment by mpaidela** [comment]
Currently, we are receiving over 100 different source types of logs into Splunk, but the user wants the logs below.

Sourcetype: vmware:vclog:vpxd
                   vmware:vclog:vpxd-main
                   vclog:applmgmt-audit
                   vmware:vclog:vmafdd
                   vmware:vclog:vpxd-svcs-access
                   vmware:esxlog:vmkernel
                   vmware:esxlog:hostd
                    vmware:esxlog:vmauthd

Can you please provide the sample parser for this?

**Comment by cwadhwani-splunk** [comment]
Hi @mpaidela 

I am closing this GitHub issue as the initial request is fulfilled.
Could you please create a support case for this and we will proceed accordingly.
Note: GitHub issues are for bugs or enhancements.
