### ISSUE TITLE
sc4s trying to open port 514 

### ISSUE THREAD

**Issue by liorbubynet** [splunk/splunk-connect-for-syslog#2572]
**Was the issue replicated by support?**
no
**What is the sc4s version ?**
30.26.1
**Which operating system (including its version) are you using for hosting SC4S?**
RHEL 9.3
**Which runtime (Docker, Podman, Docker Swarm, BYOE, MicroK8s) are you using for SC4S?**
podman
**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?**
no
**Is the issue related to the environment of the customer or Software related issue?**
we dont belive so
**Is it related to Data loss, please explain ?**
Protocol? Hardware specs?

**Last chance index/Fallback index?**

**Is the issue related to local customization?**
we are not sure
**Do we have all the default indexes created?**
yes
**Describe the bug**
we noticed that one of our sc4s was down.
We checked on the servers and the service reported active
 we looked further into it and noticed none of our configured ports were open.
We investigated the container logs and found the attached error.
![image](https://github.com/user-attachments/assets/3fcb992c-a68e-4f69-bed2-ff8b34b81ad3)

Please note the envfile don't call for port 514
But still the container trying to open it.
![image](https://github.com/user-attachments/assets/89697245-dd07-4632-b4d1-2fe31584bdf7)

As a remediation measure, we elevated the container permissions in order to keep the sc4s running.

Please let me know if you have any questions to help us investigate it further.
**To Reproduce**
(we believe this change triggered the issue but we are not sure) 
1. add the line "nix_syslog,index,it_nix" to local/context/splunk_metadata.csv
2. verify sc4s service is run on user and not root
3. restart sc4s service
4. open podman logs
5. see the error

**Comment by cwadhwani-splunk** [comment]
Hi @liorbubynet 
514 is the default port for SC4S thats why it is opened without it being mentioned in the env file.

After resolving permission issue with this elevated permission, is everything working fine?

**Comment by liorbubynet** [comment]
Hi @cwadhwani-splunk 
Yes, but we do not want sc4s to run as root.
Our other sc4s instances do not report this issue, They are not running as root and They don't have nix config on them
Is there any other option to remediate this?

**Comment by cwadhwani-splunk** [comment]
@liorbubynet 
Sure, let me look into it.
In the meantime could you please check the below things:

- What is the value of the environment variables `SC4S_LISTEN_DEFAULT_TCP_PORT` and `SC4S_LISTEN_DEFAULT_UDP_PORT`  inside the SC4S container? 
- Have you set these environment variables in the env file?
- Once you remove the "nix_syslog,index,it_nix" from local/context/splunk_metadata.csv and restart, does everything work fine?

**Comment by liorbubynet** [comment]
@cwadhwani-splunk 
Sorry for not responding sooner,
We looked at the env file and noticed that the SC4S_LISTEN_DEFAULT_TCP_PORT and SC4S_LISTEN_DEFAULT_UDP_PORT
We're missing after we added them th issue was resolved 

Thanks

**Comment by cwadhwani-splunk** [comment]
Good news. Closing this issue.
