### ISSUE TITLE
Dell Powerscale is not available in Known Vendor Sources.

### ISSUE THREAD

**Issue by dinesht77** [splunk/splunk-connect-for-syslog#2573]
**What is the sc4s version?** 
3.27.0
**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?**

**What the vendor name?**
Dell
**What's the product name?**
Dell PowerScale
**If you're requesting support for a new vendor, do you have any preferences regarding the default index and sourcetype for their events?**
No
**Do you have syslog documentation or a manual for that device??**
No
**Feature Request description:**

**Do you want to have it for local usage or prepare a github PR?**

**Comment by cwadhwani-splunk** [comment]
@dinesht77 
Please create a support ticket and attach a PCAP file there so that we can get the raw logs to work on the parser.

**Comment by cwadhwani-splunk** [comment]
Closing this GitHub issue, due to unavailability of the PCAP file. Please feel free to reopen this case once a support ticket is created with the PCAP file attached. Thanks!
