### ISSUE TITLE
sources for infoblox logs are coming up as program:$program

### ISSUE THREAD

**Issue by imsidr** [splunk/splunk-connect-for-syslog#2576]
**Was the issue replicated by support?** 

**What is the sc4s version ?** 3.27.0

**Which operating system (including its version) are you using for hosting SC4S?** ubuntu

**Which runtime (Docker, Podman, Docker Swarm, BYOE, MicroK8s) are you using for SC4S?** docker

**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?** yes on request

**Is the issue related to the environment of the customer or Software related issue?** software related

**Is it related to Data loss, please explain ?** - No
Protocol? Hardware specs?

**Last chance index/Fallback index?** sc4s

**Is the issue related to local customization?** NA

**Do we have all the default indexes created?** yes

**Describe the bug**
all sources for infoblox logs are coming as program:$program & there are two names for the vendor (infoblox & Infoblox)

**To Reproduce**
1. Go to '...' splunk SH cluster
2. Click on '....' query index=infoblox sc4s_loghost=*

**Comment by rjha-splunk** [comment]
@imsidr Please create support ticket and upload pcap please.

**Comment by imsidr** [comment]
Support ticket #3565936

**Comment by cwadhwani-splunk** [comment]
The feature for this request is now released.
```
User can set the source field value to 'sc4s' by using the `SC4S_SET_SOURCE_AS_SC4S` variable.

**Note:** If the source field value is specified in a local parser or the splunk_metadata.csv file, it will take precedence over the `SC4S_SET_SOURCE_AS_SC4S` variable and overwrite the source field value.

| Variable | Values        | Description |
|----------|---------------|-------------|
| SC4S_SET_SOURCE_AS_SC4S | yes or no(default) | Set the source field value to 'sc4s'. |
```

Hence closing this ticket.
