### ISSUE TITLE
Zscaler Private Access: User activity logs are going to Main:fallback

### ISSUE THREAD

**Issue by evslacker** [splunk/splunk-connect-for-syslog#2593]
**What is the sc4s version?**
3.30.1
**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?**
wil lbe sharing over mail

**What the vendor name?**
Zscaler

**What's the product name?**
Zscaler private Access

**If you're requesting support for a new vendor, do you have any preferences regarding the default index and sourcetype for their events?**
NA
**Do you have syslog documentation or a manual for that device??**
NA
**Feature Request description:**
ZPA is already a approved vendor for SC4S, but somehow the User Activity logs are not going to the Defined index, and they are going to Index=main  sourcetype=sc4s:falback.
**Do you want to have it for local usage or prepare a github PR?**
NA

**Comment by cwadhwani-splunk** [comment]
Hi @evslacker 
We will need pcap file to get the raws logs to work on this issue. Could you please create a support ticket and attach the PCAP file there?

**Comment by evslacker** [comment]
Hi , I have not sanitized the pcap or I would say I'm not sure how to do
that.

pcap access will be only for the Splunk internal team right? and not public?

Regards
AK

**Comment by cwadhwani-splunk** [comment]
Yes, please attach it in the support ticket. It wont be public! :)

**Comment by evslacker** [comment]
Hey Chirag,

I have uploaded the pcap over  *3577330, *Let me know if it is
accessible to you.

Regards
Ankit

**Comment by cwadhwani-splunk** [comment]
Hi Ankit,

I checked the provided pcap file and tried a few logs from both of the files, but all the logs are being classified correctly. Could you please attach a screenshot of the Splunk event in the ticket? Please make sure to expand the event and then take the screenshot.
Also, if feasible, could you please point out the log that is not being classified correctly?

**Comment by evslacker** [comment]
Hello,

Attached are the logs which are falling in the main index, as you can see
fallback are incomplete logs.
Everything is set up correctly from Zscaler Portal not sure, some logs are
falling to correct dest and rest are here.


[image: image.png]
Note- That is PRE-13, used scrubbing, let me know if you need actual logs.

Regards
Ak

**Comment by cwadhwani-splunk** [comment]
I cannot find the screenshot.

**Comment by evslacker** [comment]
Check now, I directly pasted on emai earlier.

**Comment by cwadhwani-splunk** [comment]
Hi Ankit,

I checked my email and the ticket 3577330 but couldn't locate the screenshot. It seems like the image wasn't attached properly as I only see [image: image.png].

Just for reference:
<img width="681" alt="image" src="https://github.com/user-attachments/assets/7fc8f23f-6596-4963-85fb-5d2659f380af">

Could you please resend both the raw logs causing the issues and the screenshot of the Splunk events to my email address: cwadhwani@splunk.com?

Thanks!

**Comment by evslacker** [comment]
I have shared over email, can you check now.

Regards
AK

**Comment by cwadhwani-splunk** [comment]
Hi @evslacker
I checked the screenshot and it seems like the logs coming from the ZScaler are truncated. We can check this by [obtaining the raw logs](https://splunk.github.io/splunk-connect-for-syslog/main/troubleshooting/troubleshoot_resources/#obtain-raw-message-events) coming to SC4S.
Please create a support ticket if you need any help with this, the support team can assist you here to proceed with the case. If this has something to do with SC4S, feel free to add a comment/reopen this GitHub issue.

**Comment by evslacker** [comment]
is it possible to grab a TCPDUMP of only the logs which are not going to my index?

**Comment by cwadhwani-splunk** [comment]
I dont think that would be possible, not sure, but you can use `<tcpdump command>| grep  "<search_term>"` to only get the udp packet content that contains the `search_term`. You can also try other method of obtaining raw logs, like using the `sc4s-finalfilter` and sending traffic the sc4s instance.

Please feel free to reach out to the support team for any help with this or to get the ZScaler config checked.

**Comment by cwadhwani-splunk** [comment]
Closing this GitHub issue, due to unavailability of the PCAP file. Please feel free to reopen this case once a support ticket is created with the PCAP file attached. Thanks!
