### ISSUE TITLE
Requesting a new filter for lantronix appliance

### ISSUE THREAD

**Issue by aalisher-tmx** [splunk/splunk-connect-for-syslog#2631]
**Note: If your issue is not a bug or a feature request, please raise a support ticket through our support portal (Splunk.com > Support > Support Portal). This will help us resolve your issue more efficiently and provide you with better assistance. For more information on how to work with the Splunk Support, please refer to [this guide](https://splunk.my.site.com/customer/s/article/Working-with-Support-and-the-Support-Portal).**

**What is the sc4s version?**
v3.32
**Is there a pcap available? If so, would you prefer to attach it to this issue or send it to Splunk support?**
Yes, attached pcap and raw events to splunk support case# 3604963
**What the vendor name?**
Lantronix
**What's the product name?**
ConsoleFlow
**If you're requesting support for a new vendor, do you have any preferences regarding the default index and sourcetype for their events?**

**Do you have syslog documentation or a manual for that device??**

**Feature Request description:**

**Do you want to have it for local usage or prepare a github PR?**

**Comment by cwadhwani-splunk** [comment]
Hi @aalisher-tmx 
I am closing this issue as the parser is provided, feel free to reopen the case if required. Thanks
