### ISSUE TITLE
syslog default listener port not being passed by env_file in BYOE

### ISSUE THREAD

**Issue by tangojx3** [splunk/splunk-connect-for-syslog#267]
Per Ryan's instructions on slack channel #splunk-connect-for-syslog,  I've added the following parameters into this file: /opt/sc4s/env_file
SC4S_LISTEN_DEFAULT_UDP_PORT=514
SC4S_LISTEN_DEFAULT_TCP_PORT=514

It seems that the parameters are not passed from env_file into network source files... 

...I see the template looking to build the listener port from the env_file in the following template file:
/opt/syslog-ng/etc/go_templates/source_network.t

source s_{{ .port_id}} {
    channel {
        source {
{{- if (getenv  (print "SC4S_LISTEN_" .port_id "_UDP_PORT" )) }}
            syslog (
                transport("udp")
                port({{getenv  (print "SC4S_LISTEN_" .port_id "_UDP_PORT") }})
                ip-protocol(4)
                so-rcvbuf({{getenv "SC4S_SOURCE_UDP_SO_RCVBUFF" "425984"}})
                keep-hostname(yes)
                keep-timestamp(yes)
                use-dns(no)
                use-fqdn(no)
                chain-hostnames(off)
                flags(no-parse)
            );

**Comment by mbonsack** [comment]
A couple of questions and hopefully a solution :-)
1. You have them set equivalent to the defaults already in SC4S -- so how do you know they're not being passed? 
2.  The template files get converted into regular `.conf` files; you should see the variables resolved there.
3.  The latest release contains a significant refactoring (including documentation) of SC4S listening ports.

Can you try the latest release and report back?

**Comment by tangojx3** [comment]
Hi Mark.

The syslog listener doesn't start up. I guess I'm expecting to see an SC4S
listener when the SC4S service is started. I was looking around to see
where the syslog source setups are and I don't see them.

I see that the template file looks to build the variables from the
env_file. The variables look correct. I just don't know where they pass it
too. I see that there's a network.conf file in the source folder but there
isn't any config contents in the network.conf file. Should the env_file
params be passed into this conf file for the listener?

I'll look at the update and report back. Thanks for your help!

Kit

**Comment by rfaircloth-splunk** [comment]
I believe this is fixed with the version released yesterday please re-test

**Comment by tangojx3** [comment]
steps.
1. disabled existing sc4s service. deleted all of /opt/syslog-ng and created new folder path
2. pulled down latest baremetal.tar file to /tmp and copied all of /tmp/etc/* to /opt/syslog-ng/etc/*
    version=1.6.1
    md5=fdfb513958f179f907d51cb2a62f3e8f 
3. reload daemons and started sc4s service

observations: 
preconfig.sh executes and sets up /opt/syslog-ng/etc/conf.d/local/* 

result:
still not getting the syslog listener specified by env_file.

**Comment by rfaircloth-splunk** [comment]
Resolved in 1.8
