### ISSUE TITLE
rethink of indexed fields as default config, option for opt-in

### ISSUE THREAD

**Issue by hire-vladimir** [splunk/splunk-connect-for-syslog#273]
Present template defaults generate several Splunk indexed fields; examples include: 

* `sc4s_fromhostip`
* `sc4s_log_host`
* `sc4s_syslog_facility`
* `sc4s_syslog_format`
* `sc4s_syslog_severity`
* `sc4s_syslog_product`

While the cardinality of these fields is relatively low, they do represent a sizable overhead from the disk space standpoint. For high volume syslog feeds, the overall overhead can be significant, especially in clustering scenarios with high number of searchable copies. While in specific reporting use-cases indexed fields can yield improved search performance, the overall value of the fields provided in the context of this project are questionable.

Would like to see:
* Default templates omitting generation of above indexed fields
* Provide an opt-in style template which allows the implementor to toggle the indexed fields functionality on/off
* Enhancing the Splunk `source` field to include machine that processed the event. This will better align with universal idea of Splunk use of source field, ie `set("SC4S:$LOGHOST:$SOURCE", value(".splunk.source"));`

**Comment by rfaircloth-splunk** [comment]
I think the following would be reasonable
variable control default on 
sc4s_fromhostip
sc4s_log_host
variable control default off
sc4s_syslog_facility
sc4s_syslog_format
sc4s_syslog_severity
sc4s_syslog_product

source, because we have some instances where TAs need source field we can't use that universally while we have a default source field it amounts to something so it not null.

**Comment by hire-vladimir** [comment]
Valid point on edge case use of source field.  If staying with standalone field for `$LOGHOST`, i would default to just a single field of hostname; i believe syslog-ng syntax allows for conditions, such that if hostname is null, use ip instead. There is no need in having ip and hostname, redundant information.

**Comment by rfaircloth-splunk** [comment]
We should do this in. 1.11
