### ISSUE TITLE
per sourcetype batch settings

### ISSUE THREAD

**Issue by hire-vladimir** [splunk/splunk-connect-for-syslog#274]
Not every data source is equal in overall volume throughput. Batch settings that are large are required for high throughput sources, such as firewalls, while same settings for low volume data source will present data distribution (on indexers) challenges. Proposing creating concept of small/medium/high throughput HEC destinations that can be set on per sourcetype basis.

Allowing to control batch settings will help even out data distribution to help with Splunk search performance, indexer utilization, and indexer data retention. Default batch settings would default to medium configuration.

**Comment by rfaircloth-splunk** [comment]
The config we use right now is first of time or size. Events in syslog-ng round-robin among the worker threads then the lb balances the batches. In testing the best default values regardless of throughput low/medium/high ended up being the same for batch and time, what is potentially variable is the number of workers when the number of cores is larger than 16
