### ISSUE TITLE
Please make microfocus_arcsight_source.csv user serviceable

### ISSUE THREAD

**Issue by myriadic** [splunk/splunk-connect-for-syslog#280]
This is apparently required so I can set the sourcetype/index for cyberark vault (CEF formatted) events.

**Comment by rfaircloth-splunk** [comment]
In 1.7.0 I made a change to the order of meta enrichment. Now new CEF formats can be added via splunk_indexes.csv by adding a source/sourcetype/index set of records using the value of sc4s_vendor_product as the key
