### ISSUE TITLE
Please create a way for people to set their own sourcetype/index for events that match a certain filter.

### ISSUE THREAD

**Issue by myriadic** [splunk/splunk-connect-for-syslog#281]
This would provide a workaround for customers who would like to use sc4s but have some sourcetypes which are not supported.

**Comment by mbonsack** [comment]
This is possible today using the `splunk_index.csv` file to override sourcetypes/indexes.  See
"Log Path overrides of index or metadata" here: https://splunk-connect-for-syslog.readthedocs.io/en/master/configuration/

**Comment by rfaircloth-splunk** [comment]
@myriadic What I think you are asking for is a "good enough" mapping where source ip/host is enough to set the source type and the time stamp can be take from the msg header alone?

**Comment by myriadic** [comment]
that's correct, and i realized it's already possible, so i'll just close the issue. thanks!
