### ISSUE TITLE
SC4S and HEC Indexer Acknowledgement

### ISSUE THREAD

**Issue by adriankaylor** [splunk/splunk-connect-for-syslog#309]
SC4S does not appear to support Indexer Acknowledgement.  When enabled you just get a flood of 4xx errors trying to connect.  There should be a note in the HEC config of the getting started guide as well as the suggestions under Verify Proper Operation.

**Comment by rfaircloth-splunk** [comment]
@mbonsack probably worth a mention to avoid users adding steps not indicated. 

We do not use "HEC" ack because of the performance implications

**Comment by mbonsack** [comment]
Fixed in upcoming 1.11 documentation.
