### ISSUE TITLE
Ansible role for SC4S

### ISSUE THREAD

**Issue by youngd24** [splunk/splunk-connect-for-syslog#416]
We're in the middle of deploying SC4S and was in need of an Ansible role to deploy it so I made one. Extremely early version is here if interested https://github.com/imanageops/ansible-splunk-sc4s.

**Comment by rfaircloth-splunk** [comment]
The best solution for this will be microk8s now documented

**Comment by rfaircloth-splunk** [comment]
While we don't plan to provide official ansible we are providing k8s that would have a similar result
