### ISSUE TITLE
Zscalernss keys in documentation does not match lp-zscaler_nss.conf

### ISSUE THREAD

**Issue by elee001** [splunk/splunk-connect-for-syslog#433]
Keys mentioned in the documentation for Zscaler NSS are : zscalernss_alerts, zscalernss_dns, zscalernss_fw, zscalernss_web. But in the lp-zscaler_nss.conf the keys referenced are zscaler_alerts, zscaler_dns, zscaler_fw, zscaler_web.

**Comment by mbonsack** [comment]
Fixed in PR 432.
