### ISSUE TITLE
Unclear error when processing RFC 5424 message with lots of structured data

### ISSUE THREAD

**Issue by pianohacker** [splunk/splunk-connect-for-syslog#435]
```
{ [-]
   ISODATE: 2020-05-04T21:21:59.001+00:00
   MESSAGE: Error processing log message: <14>1 2020-05-04T21:21:58.117351+00:00 arcata-pks-cluster-1 pod.log/cf-workloads/logspinner-testing-6446b8ef - - [kubernetes@47450 cloudfoundry.org/process_type="web" cloudfoundry.org/rootfs-version="v75.0.0" cloudfoundry.org/version="eae53cc3-148d-4395-985c-8fef0606b9e3" controller-revision-hash="logspinner-testing-6446b8ef05-7db777754c" cloudfoundry.org/app_guid="f71634fe-34a4-4f89-adac-3e523f61a401" cloudfoundry.org/source_type="APP" security.istio.io/tlsMode="istio" statefulset.kubernetes.io/pod-n>@<ame="logspinner-testing-6446b8ef05-0" cloudfoundry.org/guid="f71634fe-34a4-4f89-adac-3e523f61a401" namespace_name="cf-workloads" object_name="logspinner-testing-6446b8ef05-0" container_name="opi" vm_id="vm-e34452a3-771e-4994-666e-bfbc7eb77489"] Duration 10.00299412s TotalSent 10 Rate 0.999701 
   PID: 33
   PRI: <43>
   PROGRAM: syslog-ng
} 
```

How would I go about debugging this? Turning on `SC4S_SOURCE_STORE_RAWMSG` didn't add anything.

**Comment by mbonsack** [comment]
If you look really closely, your message has an indication of where the error occurred.  It is denoted by the `>@<` string in the reported log message.  In your case, it is right here:
`statefulset.kubernetes.io/pod-n>@<ame`.  Looking at the spec for RFC5424, it states that the "SD-NAME" (the left-hand side of the name=value pairs) cannot be longer than 32 printable ASCII characters.  In your message, the indicated name exceeds that.  Unfortunately, this is a spec violation on the part of the vendor, which they will need to fix.

You can work around this with an exception in the log path in sc4s, but we certainly don't want to make that universal.

**Comment by mbonsack** [comment]
Also -- the reason `SC4S_SOURCE_STORE_RAWMSG` did not return anything is because this error message is coming from syslog-ng itself -- _not_ the original log path.  When you get messages of the type `Error processing log message` with the `PROGRAM` being `syslog-ng` that is the clue your incoming message is _not_ RFC-5424 compliant (though it's often close, as is the case here).

**Comment by pianohacker** [comment]
That makes a lot of sense, thanks much for the clarifications. I figured something was probably out of spec, but couldn't figure out what. (I was also baffled by the thought that there was an `>@<` in our k8s annotations!)

For context, this is for logs coming from a log sink from VMware's TKG-I K8s infrastructure. I suspect this should be a bug on our end; please feel free to close for the time being.
