### ISSUE TITLE
Error - Unknown template function "hostname"

### ISSUE THREAD

**Issue by nandinivij** [splunk/splunk-connect-for-syslog#452]
Splunk is not receiving events from SC4S. HEC is working well for test events
Error in docker logs SC4S -
Error parsing rewrite expression, Error compiling template (Unknown template function "hostname") in /opt/syslog-ng/etc/conf.d/conflib/_splunk/splunkfields.conf:6:11-6:27:
1       #Used to set indexed fields we will always use to global defaults
2       rewrite r_set_splunk_default {
3             set("SC4S:$SOURCE", value(".splunk.source"));
4             set($FACILITY, value("fields.sc4s_syslog_facility"));
5             set($LEVEL, value("fields.sc4s_syslog_severity"));
6----->       set("$(hostname -s)", value("fields.sc4s_loghost"));
6----->           ^^^^^^^^^^^^^^^^
7             set($LOGHOST, value("fields.sc4s_container"));
8             set($SOURCEIP, value("fields.sc4s_fromhostip"));
9             set($DESTPORT, value("fields.sc4s_destport"));
10            set($PROTO, value("fields.sc4s_proto"));    
11      };
**Workaround** 
Change in file  /lib/systemd/system/sc4s.service
Replace “SC4S_CONTAINER_HOST=$(hostname -s)"
With “SC4S_CONTAINER_HOST=$(\`hostname -s\`)"

**Comment by mbonsack** [comment]
Backticks got lost in the markdown formatting :-)

**Comment by mbonsack** [comment]
See PR 457 for the final fix for the unit file.
