### ISSUE TITLE
Issues in BYOE Docs

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-connect-for-syslog#454]
* syslog-ng version in current repo is 3.25.1 not 3.27.1 which is required
* pre sh file add '' around *.tmpl i.e '*.tmpl' 
* identify the correct package for the snmpdtrap feature in docs

**Comment by rfaircloth-splunk** [comment]
When installing syslog-ng 3.27 the http modules is not installed by default also install syslog-ng-http

**Comment by mbonsack** [comment]
Fixed in https://github.com/splunk/splunk-connect-for-syslog/pull/573
