### ISSUE TITLE
Support: MongoDB system logs

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#459]
MongoDB is the most popular NoSQL database in use. It has a single flat file log that contains all system events. I propose supporting this system log which has a specific format, so that it can be parsed correctly by SC4S and delivered to Splunk.

The documentation for the log format is here:
[Log Message Format](https://docs.mongodb.com/manual/reference/log-messages/)

I took a look at our own mongodb log to see that this format is indeed correct for any version released since March 2015 (Mongodb 3.0 and above). Since only versions from 3.6 are supported at this point of time, that means that this format is correct for all supported MongoDB deployments.

I should mention one caveat I noticed with our logs that is incorrectly documented in the above URL:  there is always a double space between component and context, not a single space.  So here would be a correct log message ( two spaces between NETWORK and [initandlisten] ):

> 2014-11-03T18:28:32.450-0500 I NETWORK  [initandlisten] waiting for connections on port 27017

**Comment by rfaircloth-splunk** [comment]
Because mongo writes to file the UF is more appropriate than the SC4S project

**Comment by perditi0nspam** [comment]
The added value of using SC4S would be the improved load-balancing (SC4S HEC to load balancer rather than auto-lb), JSON formatting, and being able to index more efficiently as HEC events rather than S2S. 

Is there a strict policy of not onboarding flat files to SC4S?

**Comment by rfaircloth-splunk** [comment]
Sorry I missed the comment yes, the flat file input in syslog-ng is not very good compared to the UF. For File based sources the distributed nature of the UF and AutoLBVol should address balancing issues. When I get back from PTO (2 weeks) I can setup a zoom and look at what issue you might be having.
