### ISSUE TITLE
Support: Cisco IMC (Out of band for Cisco UCS servers)

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#460]
All Cisco UCS servers use the CIMC (Cisco Integrated Management Controller) for their out of band management. They support both UDP and TCP remote syslog servers.

I've attached a sample of some syslog messages from a CIMC.

[cimc syslog.txt](https://github.com/splunk/splunk-connect-for-syslog/files/4629345/cimc.syslog.txt)

**Comment by rfaircloth-splunk** [comment]
Thank you looking at the logs it would require a port/host/ip filter. Is there an existing add-on in Splunk base with a supporting sourcetype?

**Comment by perditi0nspam** [comment]
None that I could find.

**Comment by rfaircloth-splunk** [comment]
These messages look like they are from an embedded Linux based month sample allowing them to use the nix log path and then write any props/transfors usins source:: would be less work then duplicating the Linux TA for a new source type what do you think?

**Comment by perditi0nspam** [comment]
I'm no dev and you'd know best :)

As long as it has its own sourcetype and works correctly, it's all good. Intuitively, it does sound as though tying it up to a different TA would make it less robust and future-proof if CIMC syslog will undergo change.

**Comment by rfaircloth-splunk** [comment]
Could you look for sample messages like from this table?
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/c/sw/monitoring/guide/b_Monitoring_Cisco_IMC_Using_Syslog/b_Monitoring_Cisco_IMC_Using_Syslog_chapter_011.html

I am thinking the samples provided should source as nix:syslog but the hardware specific should get a unique source type

**Comment by rfaircloth-splunk** [comment]
Follow up, I found more message samples in cisco docs they look different than what you provided
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/ucsm_syslog/b_Monitoring_Cisco_UCSM_Using_Syslog.pdf
