### ISSUE TITLE
Readthedocs:  Download all SC4S documentation as a single PDF

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#464]
At present each page under:
[https://splunk-connect-for-syslog.readthedocs.io/en/latest/](https://splunk-connect-for-syslog.readthedocs.io/en/latest/)

Needs to be saved independantly as .PDF, and possibly merged using 3rd party software in order to keep or share offline documentation. Since this project develops rather quickly, it would be very conveniant to have a simple way to download the entire website as a single PDF.

**Comment by rfaircloth-splunk** [comment]
This will be a bit bigger than I thought we will need to build the PDF in the CI and upload to assets on the release tab as Read The Docs does not support a single PDF with mkdocs

**Comment by mkarlstrand-splunk** [comment]
@perditi0nspam Although this sounds convenient I'm not sure we should invest in the effort to implement it. As you said, the product is evolving quickly so exported docs could quickly become stale/inaccurate. Can you clarify your use case for a PDF? For example, is this needed for offline reading? Some other reason?

**Comment by perditi0nspam** [comment]
First and foremost, it's for offline reading/documentation management. This includes closed networks and project documentation where you want to refer to an offline resource which is accurate to a certain date. If you were to refer in your documentation to the readthedocs website and it's no longer accurate to your version of SC4S or your existing system design, that's unfortunate and makes that documentation obsolete. It being a single PDF also makes it much easier to reference than dozens of PDFs.

Secondly, it makes it easier for maintenance/installation navigation when it's a single PDF. Only one document to search for whatever you need.

**Comment by mkarlstrand-splunk** [comment]
@perditi0nspam good points, thank you for clarifying. I support this RFE. Now we just need to find Dev with cycles to design and implement :)

**Comment by nandinivij** [comment]
Each release has a combined sc4s pdf  #643 
https://github.com/splunk/splunk-connect-for-syslog/releases
