### ISSUE TITLE
UDP TCP TLS and HA

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-connect-for-syslog#483]
This personal blog post has the reasons choices made during implementation often have the reverse effect desired update format into docs to help in decision tree form to help customers make the best choice
https://www.rfaircloth.com/2020/05/21/performant-and-reliable-syslog-udp-is-best/

**Comment by mbonsack** [comment]
Added to docs per https://github.com/splunk/splunk-connect-for-syslog/pull/573
