### ISSUE TITLE
Support: Zscaler NSS Tunnel Logs 

### ISSUE THREAD

**Issue by elee001** [splunk/splunk-connect-for-syslog#484]
Support for parsing Zscaler NSS Tunnel Logs. Sourcetype=zscalernss-tunnel

Types of logs and their formats:

IKE PHASE 1
`%s{datetime}\tRecordtype=%s{tunnelactionname}\ttunneltype=IPSEC IKEV %d{ikeversion}\tuser=%s{vpncredentialname}\tlocation=%s{locationname}\tsourceip=%s{sourceip}\tdestinationip=%s{destvip}\tsourceport=%d{srcport}\tdestinationport=%d{dstport}\tlifetime=%d{lifetime}\tikeversion=%d{ikeversion}\tspi_in=%lu{spi_in}\tspi_out=%lu{spi_out}\talgo=%s{algo}\tauthentication=%s{authentication}\tauthtype=%s{authtype}\recordid=%d{recordid}\n`

IKE PHASE 2
`%s{datetime}\tRecordtype=%s{tunnelactionname}\ttunneltype=IPSEC IKEV %d{ikeversion}\tuser=%s{vpncredentialname}\tlocation=%s{locationname}\tsourceip=%s{sourceip}\tdestinationip=%s{destvip}\tsourceportstart=%d{srcportstart}\tdestinationportstart=%d{destportstart}\tsrcipstart=%s{srcipstart}\tsrcipend=%s{srcipend}\tdestinationipstart=%s{destipstart}\tdestinationipend=%s{destipend}\tlifetime=%d{lifetime}\tikeversion=%d{ikeversion}\tlifebytes=%d{lifebytes}\tspi=%d{spi}\talgo=%s{algo}\tauthentication=%s{authentication}\tauthtype=%s{authtype}\tprotocol=%s{protocol}\ttunnelprotocol=%s{tunnelprotocol}\tpolicydirection=%s{policydirection}\recordid=%d{recordid}\n`

TUNNEL EVENT
`%s{datetime}\tRecordtype=%s{tunnelactionname}\ttunneltype=%s{tunneltype}\tuser=%s{vpncredentialname}\tlocation=%s{locationname}\tsourceip=%s{sourceip}\tdestinationip=%s{destvip}\tsourceport=%d{srcport}\tevent=%s{event}\teventreason=%s{eventreason}\recordid=%d{recordid}\n`

SAMPLE
`%s{datetime}\tRecordtype=%s{tunnelactionname}\ttunneltype=%s{tunneltype}\tuser=%s{vpncredentialname}\tlocation=%s{locationname}\tsourceip=%s{sourceip}\tdestinationip=%s{destvip}\tsourceport=%d{srcport}\ttxbytes=%lu{txbytes}\trxbytes=%lu{rxbytes}\tdpdrec=%d{dpdrec}\recordid=%d{recordid}\n`

**Comment by satellite-no** [comment]
Hi, could you provide a pcap of the logs? The samples are nice but it's better to work with the actual events.
