### ISSUE TITLE
Documentation Configuration: Overriding Host: Potential Bad Reference (dns.csv instead of host.csv)

### ISSUE THREAD

**Issue by w3ttr3y** [splunk/splunk-connect-for-syslog#502]
In the documentation, on the configuration page, under [Fixing (overriding) the host field](https://github.com/splunk/splunk-connect-for-syslog/blob/master/docs/configuration.md#fixing-overriding-the-host-field) it states:

> [...] SC4S will first check host.csv and replace the value of host with the value specified. If a value is not found in dns.csv reverse dns lookup will be attempted.[...]

At first it references `host.csv`; it later says if not found in `dns.csv`, but it never checks `dns.csv`. 

My assumption is `dns.csv` should be `host.csv`. If you look at the commit, the [parser](https://github.com/splunk/splunk-connect-for-syslog/commit/10227402bd4c2d116bdfa8958c296b8932c27d5d#diff-0ab9dc5b1bbdabd109445404005e6305R44) references `host.csv`, there is an example for [host.csv](https://github.com/splunk/splunk-connect-for-syslog/commit/10227402bd4c2d116bdfa8958c296b8932c27d5d#diff-238f1e816230a4c27703230d03f1236bR1), etc.

If needed, I can make a pull request, but since its one word in the documentation, my assumption is its quicker for someone like @rfaircloth-splunk to just fix it then to deal with my pull request.

**Comment by rfaircloth-splunk** [comment]
I'm nothing if not inconsistent I guess.

**Comment by rfaircloth-splunk** [comment]
Fixed in push above
