### ISSUE TITLE
Filter f_proofpoint_pps_filter not capturing all events from proofpoint

### ISSUE THREAD

**Issue by jburleson** [splunk/splunk-connect-for-syslog#509]
After setting sc4s up to process proofpoint logs, I noticed that a lot of events were being sent to the osnix index with the sourcetype nix:syslog. This does not seem to happen for all events though. Some of them are going to the correct index (email) and the sourcetype is being set to pps_filter_log or pps_mail_log.

If I change the f_proofpoint_pps_filter by commenting out the line ```match('^rprt\s' value(MESSAGE) type("pcre"))```, no more events show up in the osnix index.

That line did capture the events where the message started with rprt but if does not capture events where the message starts with info, note, etc.

Is this correct or should some events be going to the osnix index?

**Comment by rfaircloth-splunk** [comment]
In the case of proofpoint the OS events should come through properly to osnix can you be more specific on proofpoint email events by example that is not being picked up ?

**Comment by jburleson** [comment]
Here are some of the events that look email related to me that are going to the osnix index.

```
queued-reinject[31146]: 059Ir0XR004181: to=<xxxx@xxxx>, delay=00:00:02, xdelay=00:00:02, mailer=esmtp, tls_verify=OK, pri=2213430, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (31g7c1fudu-1 Message accepted for delivery)
host = xxxx source = program:queued-reinject sourcetype = nix:syslog
```
```
queued-digest[22281]: 059JNdcO022281: from=<xxxx@xxxx>, size=23049, class=0, nrcpts=1, msgid=<202006091924.059JNdcO022281@pps.digest>, proto=SMTP, daemon=MTA, tls_verify=NONE, auth=NONE, relay=xxxx [127.0.0.1]
host = xxxx source = program:queued-digest sourcetype = nix:syslog
```
```
filter_instance1[1306]: warn s=31g7c1yrpa m=1 x=31g7c1yrpa-1 mod=dmarc cmd=run problematic policy str="v=DMARC1; p=none; sp=none; fo=; ri=3600; rua=mailto:xxxx@xxxx,mailto:xxxx@xxxx; ruf=mailto:xxxxx@xxxx,mailto:xxxx@xxx"
host = xxxx source = program:filter_instance1 sourcetype = nix:syslog
```
```
filter_instance1[18743]: info s=31g7c1yqhj mod=pdr ttl=60 reply="\"reject rscore=100\""
host = xxxx source = program:filter_instance1 sourcetype = nix:syslog
```
```
filter_instance1[18743]: note s=31g7c1yqgt m=1 x=31g7c1yqgt-1 mod=dmarc cmd=run result=pass result_detail= result_record="v=DMARC1; p=quarantine; rua=mailto:xxx@xxxx,mailto:xxx@xxxx,mailto:xxxx@xxxx; ruf=mailto:xxxx@xxxx; fo=1; pct=40; rf=afrf"
host = xxxx source = program:filter_instance1 sourcetype = nix:syslog
```

**Comment by rfaircloth-splunk** [comment]
Previously released failed to update issue
