### ISSUE TITLE
Docker container /entrypoint.sh error + question about splunk_metadata.csv default

### ISSUE THREAD

**Issue by adamchang2000** [splunk/splunk-connect-for-syslog#539]
awk '{print $0}' ${LEGACY_SPLUNK_INDEX_FILE} /opt/syslog-ng/etc/conf.d/local/context/splunk_metadata.csv /opt/syslog-ng/etc/context_templates/splunk_metadata.csv.example | grep -v '^#' | sort -b -t ',' -k1,2 -u > /opt/syslog-ng/etc/conf.d/local/context/splunk_metadata.csv

This line inside entrypoint.sh reads from splunk_metadata.csv as one of the sources to awk, but then pipes into splunk_metadata.csv, clearing all changes to splunk_metadata.csv before they can be read.

Also, is there a reason that the default value for splunk_metadata.csv (example file) changed from default all # commented out to no longer commented out?

**Comment by themrkeys** [comment]
The general feedback has been the comment out nature of the file has been confusing to new users and manually updating the file when new sources are added has been error prone. In order to dynamically update new entries we needed to remove the comment syntax
