### ISSUE TITLE
BYOE Documentation preconfig.sh syntax error

### ISSUE THREAD

**Issue by adamchang2000** [splunk/splunk-connect-for-syslog#540]
Hi,

https://splunk-connect-for-syslog.readthedocs.io/en/master/gettingstarted/byoe-rhel7/

In this page, an example preconfig.sh is provided, and although it notes that changes may be required for it to work, you could probably save people some headache by changing:

gomplate $(find . -name *.tmpl | sed -E 's/^(\/.*\/)*(.*)\..*$/--file=\2.tmpl --out=\2/') --template t=go_templates/

to 

gomplate $(find . -name "*.tmpl" | sed -E 's/^(\/.*\/)*(.*)\..*$/--file=\2.tmpl --out=\2/') --template t=go_templates/
(quotation marks around *.tmpl).

This prevents Linux from replacing the wildcard before being passed into find. This issue doesn't apply to the container version of SC4S as the find command is executed in a directory without any .tmpl files.

**Comment by mbonsack** [comment]
Fixed in https://github.com/splunk/splunk-connect-for-syslog/pull/573
