### ISSUE TITLE
support: modified file splunk_meta.csv is overwritten on startup

### ISSUE THREAD

**Issue by euridium** [splunk/splunk-connect-for-syslog#547]
Hello,

I am running SC4S 1.22.1 - docker image.
Image was offline created downloading the  oci_container.tar.gz file and 
```docker load <  oci_container.tar.gz```

Running on CENTOS 7.8.2003
Docker ver : docker-ce-19.03.8-3.el7

My docker maps 2 of the optional areas out to paths on my OS
```
Environment="SC4S_PERSIST_VOLUME=-v /opt/splunk_sc4s/PERSIST_VOL:/opt/syslog-ng/var"
Environment="SC4S_LOCAL_CONFIG_MOUNT=-v  /opt/splunk_sc4s/LOCAL_CONFIG:/opt/syslog-ng/etc/conf.d/local:z"
```

This all works OK and starts up clean.
When i edit the file __splunk_metadata.csv__  in my local copy of the context directory and restart the docker container.
The entry point file : 
```
/entrypoint.sh
```

has a copy command that overwrites the files in directory : /opt/syslog-ng/etc/conf.d/local/context
Which is where the local modified copies of the files live (based on the docker external mapping)

The line from the /entrypoint.sh
```
cp  /opt/syslog-ng/etc/context_templates/* /opt/syslog-ng/etc/conf.d/local/context
```
This means that on startup, any changes that i have made to my __splunk_metadata.csv__ are overwritten with the default file and lost.

If i change the cp command above to add a no-clobber switch.
```
cp -n /opt/syslog-ng/etc/context_templates/* /opt/syslog-ng/etc/conf.d/local/context
```

Then the files are only overwritten if the do not already exist. Thus my modifications are preserved and not overwritten with the default copy of the file.

Is the overwrite by design? Reading the docs it states that i can modify this file, for my own usage.
Is this a bug or am i doing something incorrectly? Where should my copy of __splunk_metadata.csv__ live so that it is read, and not overwritten?

Thanks,

Stephen.

**Comment by mbonsack** [comment]
I believe this is fixed in v1.22.2...

**Comment by euridium** [comment]
i installed and tried 1.22.2 today, and my old config was still overwritten. I tested it twice.

make change to splunk_metadata.csv, restart container, check for preservation of changes.
and then again after that.

I can test it again tomorrow and will report back.

**Comment by mbonsack** [comment]
OK -- testing on our end too...

**Comment by euridium** [comment]
i confirmed the overwrite this morning with a 1.22.2 image following the protocol.

* stop docker container using systemd : systemctl sc4s stop
* confirm docker is not runing the container : docker ps
* modify file
* start docker container using systemd : systemctl sc4s start
* check file - has reverted to default.
* modify file again (with docker container running this time)
* stop docker container with systemd
* check docker container is not running
* start docker container with systemd
* check file - has reverted to default again

with check file, i both manually check, and md5 has the file.

**Comment by euridium** [comment]
tested the 1.23.0 image it now seems to rewrite the file.  removing original file - refactoring it,  - removing comments and writing a new file, changing position of all the changed and added entries.

given my file is 99 lines long, it's hard to spot that - might be an idea to update the documentation to reflect this new behaviour. I only happened to spot it as i was specifically looking for something.

I think you can close the support request.
1.23.0 seems to have fixed it in a non expected way :)

Thanks for your help,

Stephen.

**Comment by mbonsack** [comment]
Repeating your steps above (now with version 1.23.0, but functionally the same as 1.22.2) yielded no changes to a modified `splunk_metadata.csv`.  DM me on Slack and we can set up a zoom...

**Comment by mbonsack** [comment]
All sorted; docs update needed to inform admins that the _order_ of customer's custom entries may not be preserved in the replaced file...
