### ISSUE TITLE
False success for checking index test

### ISSUE THREAD

**Issue by nandinivij** [splunk/splunk-connect-for-syslog#548]
If no index is in the selected allowed indexes list and the last chance index is not set. 
The test shows success for indexes not present in Splunk instance and data is not ingested.

**Comment by mbonsack** [comment]
Could be a HEC bug; it's just a simple curl test.  That, or we're mis-interpreting the curl exit code and claiming success when it's really a fail...

**Comment by nandinivij** [comment]
may be a HEC bug 
curl -s -S -k "http://3.12.150.32:8088/services/collector/event?index=epav" -H "Authorization: Splunk 82946703-6c7a-4aa0-95ed-53d268f9020f" -d '{"event": "HEC TEST EPAV", "sourcetype": "SC4S:PROBE"}'
{"text":"Success","code":0}"
It returns success when selected indexes are left empty for no epav index in my Splunk environment. 
But it works well if there are indexes in the selected index. 
returns - {"text":"Incorrect index","code":7,"invalid-event-number":1

**Comment by mbonsack** [comment]
Yup -- HEC bug; Jira time :-)
