### ISSUE TITLE
VMWare log path not catching all the vmware logs

### ISSUE THREAD

**Issue by euridium** [splunk/splunk-connect-for-syslog#549]
Hello,

i have the sc4s connector running with our vmaware environment which consists of vsphere, nsx, hoirzon and vsan.
I have noticed that theya re are a number of log types that are appearing in my fallback index - I think these just need to have some additional filters setup so that they can be caught and routed.

Details of the log types below.

==========================
* 1 
This message is coming from my nsx manager
```
{	[-]	
  	 DATE:	 Jun 29 10:54:02.000	
  	 HOST:	 nma01af	
  	 LEGACY_MSGHDR:	 1 	
  	 MESSAGE:	 2020-06-29T10:52:50.786+01:00 nma01af.xxx.xxxxxxxxx.xx.xx.xx NSXV 6152 - [nsxv@6876 comp="nsx-manager" level="INFO" subcomp="manager"] Start executing task: task-3308094 and running executor threads 1	
  	 PRI:	 <182>	
  	 PROGRAM:	 1	
  	 RAWMSG:	 <182>Jun 29 10:54:02 172.16.000.000 1 2020-06-29T10:52:50.786+01:00 nma01af.xxx.xxxxxxxxx.xx.xx.xx NSXV 6152 - [nsxv@6876 comp="nsx-manager" level="INFO" subcomp="manager"] Start executing task: task-3308094 and running executor threads 1	
}
```

If i run the search index="sc4s_default"| spath MESSAGE | search MESSAGE!="* NSXV *"
Then the message from the NSX manager are totally excluded. So the program type is NSXV

==========================
* 2
This is from my cluster running VSAN
```
{	[-]	
  	 DATE:	 Jun 29 10:56:38.000	
  	 HOST:	 vda04af	
  	 LEGACY_MSGHDR:	 1593424523.078212,5224e4 	
  	 MESSAGE:	 vda04af.xxxxxxxxx.xx.xx.xx cmmdsTimeMachineDump: 7-be3e-6e1e-7f7e-5b9ed11defcd,16,30842,59a6a272-e495-0c8b-2fea-246e966a4e78,2,{"capacityUsed": 0, "l2CacheUsed": 0, "l1CacheUsed": 0, "writeConsolidationRatio": 10, "avgReadsPerSecond": 1, "avgWritesPerSecond": 0, "avgThroughPutUsed": 4096, "avgReadServiceTime": 0, "avgReadQueueTime": 0, "avgWriteServiceTime": 0, "avgWriteQueueTime": 0, "avgDiskReadsPerSec": 0, "avgDiskWritesPerSec": 0, "avgSSDReadsPerSec": 0, "avgSSDWritesPerSec": 0, "estTimeToFailure": 0, "numDataComponents": 318, "logicalCapacityUsed": 0, "physDiskCapacityUsed": 0, "pendingWrite": 0, "pendingDelete": 0, "dgPendingWrite": 0, "dgPendingDelete": 0, "dgLogicalCapacityUsed": 0, "dgAvgDataDestageBytesSec": 14720322, "dgAvgZeroDestageBytesSec": 0, "dgAvgResyncReadBytesPerSec": 0, "dgAvgTotalReadBytesPe	
  	 PRI:	 <14>	
  	 PROGRAM:	 1593424523.078212,5224e4	
  	 RAWMSG:	 <14>Jun 29 10:56:38 172.16.000.000 1593424523.078212,5224e4 vda04af.vda04af.xxxxxxxxx.xx.xx.xx cmmdsTimeMachineDump: 7-be3e-6e1e-7f7e-5b9ed11defcd,16,30842,59a6a272-e495-0c8b-2fea-246e966a4e78,2,{"capacityUsed": 0, "l2CacheUsed": 0, "l1CacheUsed": 0, "writeConsolidationRatio": 10, "avgReadsPerSecond": 1, "avgWritesPerSecond": 0, "avgThroughPutUsed": 4096, "avgReadServiceTime": 0, "avgReadQueueTime": 0, "avgWriteServiceTime": 0, "avgWriteQueueTime": 0, "avgDiskReadsPerSec": 0, "avgDiskWritesPerSec": 0, "avgSSDReadsPerSec": 0, "avgSSDWritesPerSec": 0, "estTimeToFailure": 0, "numDataComponents": 318, "logicalCapacityUsed": 0, "physDiskCapacityUsed": 0, "pendingWrite": 0, "pendingDelete": 0, "dgPendingWrite": 0, "dgPendingDelete": 0, "dgLogicalCapacityUsed": 0, "dgAvgDataDestageBytesSec": 14720322, "dgAvgZeroDestageBytesSec": 0, "dgAvgResyncReadBytesPerSec": 0, "dgAvgTotalReadBytesPe	
}
```

If i run the search  index="sc4s_default" | spath MESSAGE | search MESSAGE!="* cmmdsTimeMachineDump: *"
Then the message from VSAN are totaly excluded. so the program type is cmmdsTimeMachineDump:

==========================
* 3 
This is from my cluster running VSAN
```
{	[-]	
  	 DATE:	 Jun 29 10:56:38.000	
  	 HOST:	 vda04af	
  	 LEGACY_MSGHDR:	 1593424523.078212,5224e4 	
  	 MESSAGE:	 vda04af.xxxxxxxxx.xx.xx.xx cmmdsTimeMachineDump: 7-be3e-6e1e-7f7e-5b9ed11defcd,16,30842,59a6a272-e495-0c8b-2fea-246e966a4e78,2,{"capacityUsed": 0, "l2CacheUsed": 0, "l1CacheUsed": 0, "writeConsolidationRatio": 10, "avgReadsPerSecond": 1, "avgWritesPerSecond": 0, "avgThroughPutUsed": 4096, "avgReadServiceTime": 0, "avgReadQueueTime": 0, "avgWriteServiceTime": 0, "avgWriteQueueTime": 0, "avgDiskReadsPerSec": 0, "avgDiskWritesPerSec": 0, "avgSSDReadsPerSec": 0, "avgSSDWritesPerSec": 0, "estTimeToFailure": 0, "numDataComponents": 318, "logicalCapacityUsed": 0, "physDiskCapacityUsed": 0, "pendingWrite": 0, "pendingDelete": 0, "dgPendingWrite": 0, "dgPendingDelete": 0, "dgLogicalCapacityUsed": 0, "dgAvgDataDestageBytesSec": 14720322, "dgAvgZeroDestageBytesSec": 0, "dgAvgResyncReadBytesPerSec": 0, "dgAvgTotalReadBytesPe	
  	 PRI:	 <14>	
  	 PROGRAM:	 1593424523.078212,5224e4	
  	 RAWMSG:	 <14>Jun 29 10:56:38 172.16.000.000 1593424523.078212,5224e4 vda04af.vda04af.xxxxxxxxx.xx.xx.xx cmmdsTimeMachineDump: 7-be3e-6e1e-7f7e-5b9ed11defcd,16,30842,59a6a272-e495-0c8b-2fea-246e966a4e78,2,{"capacityUsed": 0, "l2CacheUsed": 0, "l1CacheUsed": 0, "writeConsolidationRatio": 10, "avgReadsPerSecond": 1, "avgWritesPerSecond": 0, "avgThroughPutUsed": 4096, "avgReadServiceTime": 0, "avgReadQueueTime": 0, "avgWriteServiceTime": 0, "avgWriteQueueTime": 0, "avgDiskReadsPerSec": 0, "avgDiskWritesPerSec": 0, "avgSSDReadsPerSec": 0, "avgSSDWritesPerSec": 0, "estTimeToFailure": 0, "numDataComponents": 318, "logicalCapacityUsed": 0, "physDiskCapacityUsed": 0, "pendingWrite": 0, "pendingDelete": 0, "dgPendingWrite": 0, "dgPendingDelete": 0, "dgLogicalCapacityUsed": 0, "dgAvgDataDestageBytesSec": 14720322, "dgAvgZeroDestageBytesSec": 0, "dgAvgResyncReadBytesPerSec": 0, "dgAvgTotalReadBytesPe	
}
```

If i run the search  index="sc4s_default" | spath MESSAGE | search MESSAGE!="* cmmdsTimeMachineDump: *"
Then the message from VSAN are totaly excluded. so the program type is cmmdsTimeMachineDump:

==========================
* 4 
```
{	[-]	
  	 DATE:	 Jun 29 11:30:40.000	
  	 HOST:	 vda02af	
  	 LEGACY_MSGHDR:	 0, 	
  	 MESSAGE:	 'uuid': '52a340d2-1ed vda02af.xxxxxxxxx.xx.xx.xx VSANMGMTSVC: -4c87-a4f5-43405fa0b83e', 'ssdUuid': '521a4f36-7b48-3582-caec-86e100694012', 'capacity': 2000389406720, 'disk_health': {'healthReason': 0, 'timestamp': 234066772125, 'healthFlags': 0}, 'owner': '59a6ab9f-9f46-3ba5-8355-246e966a5c90', 'isSsd': 0}]	
  	 PRI:	 <12>	
  	 PROGRAM:	 0,	
  	 RAWMSG:	 <12>Jun 29 11:30:40 172.16.164.133 0, 'uuid': '52a340d2-1ed vda02af.xxxxxxxxx.xx.xx.xx VSANMGMTSVC: -4c87-a4f5-43405fa0b83e', 'ssdUuid': '521a4f36-7b48-3582-caec-86e100694012', 'capacity': 2000389406720, 'disk_health': {'healthReason': 0, 'timestamp': 234066772125, 'healthFlags': 0}, 'owner': '59a6ab9f-9f46-3ba5-8355-246e966a5c90', 'isSsd': 0}]	
}
```

If i run the search  index="sc4s_default" | spath MESSAGE | search MESSAGE!="* VSANMGMTSVC: *"

==========================
* 5 

```
 {	[-]	
  	 DATE:	 Jun 29 11:27:45.000	
  	 HOST:	 lma04af	
  	 LEGACY_MSGHDR:	 vmfs/volumes/vsan:	
  	 MESSAGE:	 520db807c2d27611-5aed8e7d8eeefdec. = 17	
  	 PRI:	 <166>	
  	 PROGRAM:	 vmfs/volumes/vsan	
  	 RAWMSG:	 <166>Jun 29 11:27:45 vmfs/volumes/vsan:520db807c2d27611-5aed8e7d8eeefdec. = 17	
}
```

==========================
* 6 

```
{	[-]	
  	 DATE:	 Jun 29 11:27:45.000	
  	 HOST:	 vmfs/volumes.	
  	 LEGACY_MSGHDR:	 = 	
  	 MESSAGE:	 17	
  	 PRI:	 <166>	
  	 PROGRAM:	 =	
  	 RAWMSG:	 <166>Jun 29 11:27:45 vmfs/volumes. = 17	
}
```

I'm happy to provide as much  log detail as you need + do testing

Thanks,

Stephen.

**Comment by rfaircloth-splunk** [comment]
In sub issue number 2 can you decode this for me I belive you are indicating the host with xxxx what is vda04af
vda04af.vda04af.xxxxxxxxx.xx.xx.xx

**Comment by rfaircloth-splunk** [comment]
In sub-issue 5 and 6 there is no hostname we would be forced to use IP or reverse DNS can you confirm there is no way to have the host sent?
 <166>Jun 29 11:27:45 vmfs/volumes. = 17

**Comment by euridium** [comment]
> In sub issue number 2 can you decode this for me I belive you are indicating the host with xxxx what is vda04af
> vda04af.vda04af.xxxxxxxxx.xx.xx.xx

Hello,

vda04af. xxx is the hostname of the device. I didn't want to disclose my full hostname on a public area so i obfuscated the domain part of it.

so the hostname would be something like vda04af.euridium.co.uk  but it could be any hostname format.
myesxserver.euridium.co.uk for instance.

Make sense?

Stephen.

**Comment by euridium** [comment]
> In sub-issue 5 and 6 there is no hostname we would be forced to use IP or reverse DNS can you confirm there is no way to have the host sent?
> <166>Jun 29 11:27:45 vmfs/volumes. = 17

Amazingly, these logs are from a ESXi server directly and are not well formatted - so i have no control over what the logs are or the format it sends.
AS you can see in the RAWMSG section - the log entries do not contain a hostname, but they are definitely from the ESXi server a source.
Unless i choose to write my own log_path for  - anything containing "vmfs/volumes/vsan"  then as you suggest i'd have to use an source IP override.
I thought there may be a clever way to custom define a filter to force it to go on the ESXi path and integrate with the exiting vmware filtering?  Rather than writing a custom log_path - i'm not able to edit your vmware log_path and filters diretly as they are overwritten at update.

Stephen.

**Comment by rfaircloth-splunk** [comment]
I was hoping for better can you re-test with the current image and see what issues remain

**Comment by rfaircloth-splunk** [comment]
Closing lack of feedback, further improvements have been made in later versions will review more data if provided
