### ISSUE TITLE
Palo Alto Host field not properly identified for all URL logs

### ISSUE THREAD

**Issue by hosom** [splunk/splunk-connect-for-syslog#554]
If a url log contains commas in the url parameter, the host field is not properly extracted from the log. This happens on a fairly consistent basis. 

Instead, the host will be identified as a value earlier in the comma separated log.

**Comment by hosom** [comment]
Adding an option for `quote-pairs('""')` at https://github.com/splunk/splunk-connect-for-syslog/blob/master/package/etc/conf.d/log_paths/lp-paloalto_panos.conf.tmpl#L68 may resolve this issue, but I don't have a convenient method to test this in my environment.

**Comment by mbonsack** [comment]
Can you set `SC4S_SOURCE_STORE_RAWMSG=yes`, restart sc4s, and post the `RAWMSG` value for an event that has an incorrect host?  If you do that, I will test your solution above -- but I need a raw sample with which to test.

**Comment by hosom** [comment]
I have an example log message here, but it needed to be redacted by necessity. 

```
1,2020/07/08 16:48:50,013201020735,THREAT,url,2049,2020/07/08 16:48:48,10.1.1.1,1.1.1.2,1.1.1.1,1.1.1.3,URLFilter_CatchAll_Internet,testuser,,arcgis,vsys1,DMZ,Outside,ae3,ae1,Panorama-Only,2020/07/08 16:48:48,357728,1,61066,80,33396,80,0x8403000,tcp,alert,"geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/reverseGeocode?distance=100&f=json&location={""x"":-33,""y"":22.3,""spatialReference"":{""wkid"":111}}",(9999),ALL-WhitelistedURLs,informational,client-to-server,6816029286804555581,0xa000000000000000,Internal,United States,0,application/json,0,,,1,,,,,,,,0,11,16,0,0,,TESTFW01,,,,get,0,,0,,N/A,unknown,AppThreat-0-0,0x0,0,4294967295,
```

**Comment by rfaircloth-splunk** [comment]
I can reproduce the issue with this data working on the fix now

**Comment by mbonsack** [comment]
PR 560 fixes
