### ISSUE TITLE
Support for Additional F5 BigIP LTM/GTM events

### ISSUE THREAD

**Issue by ananer** [splunk/splunk-connect-for-syslog#568]
There are number of messages are being set to the "Fallback" sourcetype.  When I looked at the 3 filters in the container for F5 none of them are able to identify the 5 message types.

Upon indexing the PROGRAM for 4 of them is set to "debug" and the MESSAGE starts with "sshd|mcpd|httpd|iControlPortal"
The fifth message type is PROGRAM "alert" and the MESSAGE starts with "gtmd".

**Comment by mbonsack** [comment]
Can you send us some raw messages ("on the wire") with the <PRI> string intact?  Thanks!

**Comment by ananer** [comment]
Is the raw message from Splunk adequate?  If not what what specifically do need and what is easiest way to provide it?

**Comment by mbonsack** [comment]
The quickest way to provide it is using tcpdump if you're familiar with that.  Otherwise, just do this:
1. Set `SC4S_SOURCE_STORE_RAWMSG=yes`
2. Restart sc4s
3. Post the contents of the `RAWMSG` field from Splunk for the events that land in fallback.
4. Unset `SC4S_SOURCE_STORE_RAWMSG=yes` or set to "no" to prevent excess resource usage in production from raw message capture.

**Comment by ananer** [comment]
Unfortunately I don't have samples for all of them yet.  Here's 2 to get started.

<31>Jul 14 15:35:43 F5_HOSTNAME debug iControlPortal.cgi[PID]: f5km_list_next DONE
<87>Jul 14 15:42:12 F5_HOSTNAME debug httpd[PID]: pam_bigip_authz: pam_sm_authenticate returning status SUCCESS

**Comment by mbonsack** [comment]
Great I'll look into these.  What sourcetypes/devices do the above two samples correspond to?

**Comment by ananer** [comment]
These should probably be sourcetype="f5:bigip:syslog".  

The messages debug httpd* and debug mcpd* (NO SAMPLE YET)  messages are from an F5 LTM. 
The message debug httpd*, debug iControlPortal*, debug mcpd* (NO SAMPLE YET), and  debug sshd* (NO SAMPLE YET) are from an F5 GTM.

And finally you are correct about the PID and F5_HOSTNAME.

Thank you!

**Comment by themrkeys** [comment]
httpd is simply apache if we sourcetype it as f5:bigip:syslog then we have to duplicate KOs between the TAs

**Comment by rfaircloth-splunk** [comment]
PR made for the issue iControlPortal.cgi for the httpd issue we need the F5 to use a dedicated port or we need the host name pattern added to vendor_product_by_source which should get http to the right place
