### ISSUE TITLE
Host Field Override 

### ISSUE THREAD

**Issue by TellTaleMajora** [splunk/splunk-connect-for-syslog#572]
Hi team--

**Background:**

I have SC4S running on a docker container, and am successfully ingesting syslog data over to our SIEM, Splunk. After review of the data, I am seeing Palo Alto Syslog data sometimes appends a domain name instead of just the hostname to the Host field value in Splunk. For example, firewall01.dc1, and I would like to clean up the Host field value to just be "firewall01" 

Attempted Solutions 

- Attempted to override Host field value with host.csv in SC4S, but the configuration has not produces any results. Example below
`firewall01.dc1,HOST,firewall01`

Another configuration based on IP 
`192.168.1.2,HOST,firewall01`

- Configured compliance_meta_by_source.conf, and compliance_meta_by_source.csv to attempted overriding the Host field value, but it seems that this configuration is limited to creating new fields, and overriding a couple others (Source, Sourcetype, index) 

**Issue**

- Unable to override the host field value in SC4S configuration to perform some data clean up and Host field consistency 

Feedback is appreciated, thank you! 

SC4S version is 1.21.1

**Comment by mbonsack** [comment]
- `host.csv` is used only for hostname resolution when the event does not provide the host as part of the event itself.  So your first attempt will indeed fail as noted.
- you should be able to override host in `compliance_meta_by_source.conf` and `.csv`.  Please post your configuration and we'll take a look.

**Comment by TellTaleMajora** [comment]
Hello, 

This is the configuration I currently have for `compliance_meta_by_source.conf` and `.csv`. 

compliance_meta_by_source.csv
`f_palo_host_fix,.splunk.host,"firewall01"`

compliance_meta_by_source.conf
`filter f_palo_host_fix {
   host("firewall01" type(glob))
   or host("firewall01.dc1" type(glob))
   or netmask(192.168.1.2/32)
};`

**Comment by mbonsack** [comment]
I see the problem; not sure on fix yet.  Stay tuned.

**Comment by mbonsack** [comment]
Fixed in https://github.com/splunk/splunk-connect-for-syslog/pull/575
