### ISSUE TITLE
 Cisco ACS logs are not parsing correctly and not following CIM coplinace

### ISSUE THREAD

**Issue by hetramyadav** [splunk/splunk-connect-for-syslog#639]
Hi We have implemented SC4S for integrating Cisco ACS logs.

I have also installed the TA for Cisco ACS but the logs when i checked the logs it is dropping the header part but he TA is expecting the header part in its config file.

**Actual log**

<181>Aug 16 06:38:59 ABCDE CSCOacs_Failed_Attempts 0341055990 1 0 2020-08-16 06:38:59.242 -05:00 9929587375 5401 NOTICE Failed-Attempt: Authentication failed, ACSVersion=acs-5.8.1.4-B.462.x86_64, ConfigVersionId=1087, Device IP Address=X.X.X.X, Device Port=64602, DestinationIPAddress=X.X.X.X, DestinationPort=49, Protocol=Tacacs, RequestLatency=1, Type=Authentication, Action=Login, Privilege-Level=1, Authen-Type=ASCII, Service=Login, User=, Port=tty0, Remote-Address=async, AcsSessionID=ABCDE/310319687/487315430, SelectedAccessService=Device Admin - ABC TACACS, FailureReason=13030 , Step=13013 , Step=15008 , Step=15004 , Step=15012 , Step=13015 , Step=13014 , Step=15037 , Step=13030 , Step=13015 , NetworkDeviceName=EBS-Prod-Core-Devices, NetworkDeviceGroups=Company:All Companies:ABC:TSG:EBS, NetworkDeviceGroups=Device Type:All Device Types:Network Equipment:Routers and Switches:Cisco, NetworkDeviceGroups=Location:All Locations, ServiceSelectionMatchedRule=ABC TACACS Administration, Action=Login, Privilege-Level=1, Authen-Type=ASCII, Service=Login, Port=tty0, Remote-Address=async, Response={AuthenticationMethod=PAP_ASCII; Type=Authentication; Authen-Reply-Status=Fail; }

**Log visible in splunk** 

9878903922 5401 NOTICE Failed-Attempt: Authentication failed, ACSVersion=acs-5.8.1.4-B.462.x86_64, ConfigVersionId=1084, Device IP Address=X.X.X.X, Device Port=53968, DestinationIPAddress=X.X.X.X, DestinationPort=49, Protocol=Tacacs, RequestLatency=1, Type=Authentication, Action=Login, Privilege-Level=1, Authen-Type=ASCII, Service=Login, User=, Port=tty0, Remote-Address=async, AcsSessionID=ABCDE/310319687/485526629, SelectedAccessService=Device Admin - ABC TACACS, FailureReason=13030 , Step=13013 , Step=15008 , Step=15004 , Step=15012 , Step=13015 , Step=13014 , Step=15037 , Step=13030 , Step=13015 , NetworkDeviceName=EBS-Prod-Core-Devices, NetworkDeviceGroups=Company:All Companies:ABC:TSG:EBS, NetworkDeviceGroups=Device Type:All Device Types:Network Equipment:Routers and Switches:Cisco, NetworkDeviceGroups=Location:All Locations, ServiceSelectionMatchedRule=ABC TACACS Administration, Action=Login, Privilege-Level=1, Authen-Type=ASCII, Service=Login, Port=tty0, Remote-Address=async, Response={AuthenticationMethod=PAP_ASCII; Type=Authentication; Authen-Reply-Status=Fail; }

Cisco ACS TA props.conf

EXTRACT-acs_message_header = ^\w{3}\s+\d+\s+[\d:]{8}\s+(?<dvc>\S+)\s+CisACS_(?<signature_id>\d+)_(?<signature>\S+)\s+(?<event_id>\S+)\s+(?<total_segments>\d+)\s+(?<segment_number>\d+)\s+(?<acs_message>.*)
FIELDALIAS-Message_type_vendor_action = Message_Type as vendor_action
FIELDALIAS-Caller_ID_src_mac = Caller_ID as src_mac
LOOKUP-vendor = cisco_acs_vendor sourcetype OUTPUT vendor product app

**Comment by rfaircloth-splunk** [comment]
SC4S issues are corrected in the linked PR, See documentation for specific corrections needed in the TA to work with SC4S I also notified the original ACS TA developer who will correct and release a package update soon

**Comment by hetramyadav** [comment]
Thanks for update

**Comment by rfaircloth-splunk** [comment]
The fix has been released please verify and re-open if you have further problems

**Comment by hetramyadav** [comment]
Thanks it is working in Sc4S v 1.30
