### ISSUE TITLE
Cisco FWSM log source not identified in SC4S

### ISSUE THREAD

**Issue by hetramyadav** [splunk/splunk-connect-for-syslog#648]
Log source type= Cisco FWSM logs are going under  sourcetype= sc4s:fallback in sc4s.  So need to correct the Sc4S to identify the ciso firewall service module.

**Comment by hetramyadav** [comment]
Hey after upgrading the Sc4S to 1.30 but still fwsm logs are going under sourcetype: sc4s:fallback

**Comment by hiraveomkar** [comment]
We are at version 1.30.1 now and we are not seeing FWSM events getting indexed at all. Even when they are echoed in however when the sample events are manipulated to use the %ASA instead of %FWSM, those are getting routed to ASA source type.

**Comment by themrkeys** [comment]
@hiraveomkar something is a miss, the built in log path does not alter the message if the event is being changed to ASA a custom path could be present or it could be done at index time on the Splunk side via a transform
