### ISSUE TITLE
SC4S not parsing "Host" field from RSA SecurityID log source

### ISSUE THREAD

**Issue by kailasnene** [splunk/splunk-connect-for-syslog#649]
Hello,

We are sending logs from one RSA Authentication Manger server using syslog method to SC4S. I have installed "Splunk Add-on for RSA SecurID" But its not able to parse Timestamp and Host information from syslog message.  It is picking up hostname of intermediate forwarder as "Host"  although actual source hostname in available in syslog message. 

sample payload:

X.!.&......<14>2020-08-20 13:38:39,933, <hostname>.prod.local, audit.runtim                                                                                                             e.com.rsa.ims.authn.impl.AuthenticationBrokerImpl, INFO, 0bb6fd74cdbdec0a468e20f                                                                                                             b4e040edd,0cc85ed7cdbdec0a7b3e64f332e9b9de,X.X.X.X,X.X.X.X,AUTHN_LO                                                                                                             GIN_EVENT,13002,SUCCESS,AUTHN_METHOD_SUCCESS,0b170579cdbdec0a1d5a96a8569e7277-kC                                                                                                             1JoZYTCbUl,694b0f4819b98d3f24c3ec8fd9001c01,000000000000000000001000d0011000,aea                                                                                                             32e6419b98d3f1aa6c6087db17e44,BEB_1149250_JEFFK118,<user,name>,fdb12d8c19b98d3f1                                                                                                             9eddac3049ed56f,000000000000000000001000e0011000,X.X.X.X,LRK1*****.p                                                                                                             rod.local,7,000000000000000000002000f1022000,SecurID_Native,,,AUTHN_LOGIN_EVENT,                                                                                                             5,1,,,,,f24358ae19b98d3f199b08cd28cd9bd6,000160187505,,

I can see SC4S error:

dtparse: Expected: %Y-%m-%d %H:%M:%S,%f; Actual: 13:56:50 555 |  -- | --

**Comment by kailasnene** [comment]
Any update on this?

**Comment by rfaircloth-splunk** [comment]
Looks like a slight variation of what we expected will address in the next build

**Comment by kailasnene** [comment]
Thanks Ryan!
