### ISSUE TITLE
Brocade Fabric logs going into sourcetype nix:syslog (source program:raslogd) instead of brocade:syslog

### ISSUE THREAD

**Issue by trekkiecat** [splunk/splunk-connect-for-syslog#650]

**Comment by rfaircloth-splunk** [comment]
Please re-open with supporting information for a reproduction

**Comment by trekkiecat** [comment]
[Brocade Fabric logs going into sourcetype nix syslog.docx](https://github.com/splunk/splunk-connect-for-syslog/files/5119860/Brocade.Fabric.logs.going.into.sourcetype.nix.syslog.docx)
screenshots from splunk

**Comment by trekkiecat** [comment]
[brocade sample events.txt](https://github.com/splunk/splunk-connect-for-syslog/files/5119870/brocade.sample.events.txt)
sample events
