### ISSUE TITLE
DOCS: Need a detailed log-path filter development chapter

### ISSUE THREAD

**Issue by mkarlstrand-splunk** [splunk/splunk-connect-for-syslog#658]
As an SC4S community member I need detailed directions I may follow to successfully design, build and test a new log-path filter so that I may ingest data sources not yet supported

This section should contain the following at the least...
Detailed breakdown of log-path filter functionality via walk through of an existing log-path
LP design guidance
Steps to build example
Details on testing new filter
Steps and best practices for contribution of filter to community
know gotchas

**Comment by magnuscowie** [comment]
Hi, did this happen?

**Comment by rabrahamsplunk** [comment]
+1

**Comment by rfaircloth-splunk** [comment]
Done
