### ISSUE TITLE
LEEF - Incorrect parsing/sourcetype

### ISSUE THREAD

**Issue by aberretta12** [splunk/splunk-connect-for-syslog#662]
Hello,

While reviewing LEEF logs from our Palo Alto firewall and CyberArk vault appliance we noticed discrepancy in how SC4S is forwarding into Splunk.

- CyberArk - These are tab separated LEEF logs and are being properly categorized as CyberArk, however the sourcetype is "LEEF:1" rather than the expected CyberArk sourcetype (screenshot attached). This issue of sourcetype "LEEF:1" is currently true of all LEEF log sources, see next example for Palo.
    **Example log structure:** LEEF:1.0|Cyber-Ark|Vault|9.80.0000|99|sev=6    Action=Open File    EventMessage=Open File    OSUser=    usrName=test    src=1.1.1.1    SourceUser=    TargetUser=    File=test\test    Safe=test    Location=    Category=    RequestId=    Reason=    ExtraDetails=    GatewayStation=    CAPolicy=;UserName=""

- Palo Alto - These are pipe separated logs and SC4S is stripping the entire message down to the key/value pair after all pipes ex. "Tunnel Type", likely due to the pipe separation (screenshot attached). In addition the sourcetype is set to 'LEEF1:" as above
    **Example log structure:** <14>Aug 24 14:21:59 hostname LEEF:1.0|Palo Alto Networks|PAN-OS Syslog Integration|8.1.8|allow|cat=TRAFFIC|ReceiveTime=2020/08/24 14:21:59|SerialNumber=1111111111|Type=TRAFFIC|Subtype=end|devTime=Aug 24 2020 19:21:59 GMT|src=1.1.1.1|dst=1.1.1.1|srcPostNAT=0.0.0.0|dstPostNAT=0.0.0.0|RuleName=test|usrName=|SourceUser=|DestinationUser=|Application=dns|VirtualSystem=test|SourceZone=test|DestinationZone=test|IngressInterface=test|EgressInterface=test|LogForwardingProfile=test|SessionID=test|RepeatCount=1|srcPort=37057|dstPort=53|srcPostNATPort=0|dstPostNATPort=0|Flags=0x1c|proto=tcp|action=allow|totalBytes=2651|dstBytes=2098|srcBytes=553|totalPackets=12|StartTime=2020/08/24 14:21:43|ElapsedTime=1|URLCategory=any|sequence=6694316274113274693|ActionFlags=0x8000000000000000|SourceLocation=India|DestinationLocation=United States|dstPackets=5|srcPackets=7|SessionEndReason=tcp-fin|DeviceGroupHierarchyL1=117|DeviceGroupHierarchyL2=118|DeviceGroupHierarchyL3=119|DeviceGroupHierarchyL4=146|vSrcName=vsys1|DeviceName=usarlrad-sif001-1a|ActionSource=from-policy|SrcUUID=|DstUUID=|TunnelID=0|MonitorTag=|ParentSessionID=0|ParentStartTime=|TunnelType=N/A
![Palo Alto LEEF Sample](https://user-images.githubusercontent.com/58788189/91087499-8ac82000-e61e-11ea-9f78-025d1521e37f.png)
![CyberArk LEEF Sample](https://user-images.githubusercontent.com/58788189/91087513-8e5ba700-e61e-11ea-89fa-a5a2e04afd2c.png)

**Comment by aberretta12** [comment]
Note: this is running on SC4S v1.29 with LEEF support.

**Comment by rfaircloth-splunk** [comment]
the palo message example is using | as a field separator but this is incorrect the sep for v1 leef must be \t (tab) the source should be corrected

**Comment by aberretta12** [comment]
Thanks for the reply, the pipe separated LEEF was recommended by IBM in the following document for Palo alto - see page 983 https://www.ibm.com/support/knowledgecenter/SS42VS_DSM/com.ibm.dsm.doc/b_dsm_guide.pdf?view=kc&origURL=SS42VS_DSM/b_dsm_guide.pdf

**Comment by aberretta12** [comment]
Also, please do not forget about the CyberArk example in which the log format is tab separated, however sourcetype is still "LEEF1:".

**Comment by rfaircloth-splunk** [comment]
For LEEF V1 the standard doc requires tab for LEEFV2 alternate format can be used
https://www.ibm.com/support/knowledgecenter/SS42VS_DSM/com.ibm.dsm.doc/c_LEEF_Format_Guide_LEEFeventcomps.html
The error is not surprising but its incorrect in the DSM

**Comment by rfaircloth-splunk** [comment]
For the CyberARK issue review the value of sc4s_vendor_product that is the key to add to splunk_metadata
Cyber-Ark_Vault,sourcetype,cyberark:leef

Its important to not use the sourcetype for the normally valid format as the cyberark TA Splunk supports is designed for CEF this would create a conflict. We do strongly urge using the well know/supported configuration as our experience is this is the most successful over time

**Comment by aberretta12** [comment]
Thank you that makes sense for CyberArk. We will test and let you know the result. Much appreciated!
