### ISSUE TITLE
Brocade Fabric logs going into sourcetype nix:syslog (source program:raslogd) instead of brocade:syslog

### ISSUE THREAD

**Issue by trekkiecat** [splunk/splunk-connect-for-syslog#664]
screenshots from splunk:
[Brocade Fabric logs going into sourcetype nix syslog.docx](https://github.com/splunk/splunk-connect-for-syslog/files/5119891/Brocade.Fabric.logs.going.into.sourcetype.nix.syslog.docx)

sample brocade events:
[brocade sample events.txt](https://github.com/splunk/splunk-connect-for-syslog/files/5119892/brocade.sample.events.txt)

**Comment by rfaircloth-splunk** [comment]
It looks like the existing brocade support is for network not fabric switches. That is probably similar enough however this vendors syslog does not have identifying data the input must be on a dedicated port OR use a hostname match to identify the source as brocade. Can you confirm which option is being used?

**Comment by trekkiecat** [comment]
We have approx 50 Brocade switches that are logging thru standard 514.

**Comment by trekkiecat** [comment]
I guess our only choice is to maintain a filter or have the switches reconfigured to log on a different port. Thanks.
