### ISSUE TITLE
Cisco ASA timestamps incorrect in HEC output after running for a few minutes

### ISSUE THREAD

**Issue by kwagner001** [splunk/splunk-connect-for-syslog#684]
IHAC with SC4S BYOE on RHEL 7.  With Cisco ASA logs coming in over UDP, the timestamp parsing in SC4S fails after a few minutes.  The logs are coming in with times in EDT and using the HEC debug capture on SC4S, the output timestamp in the curl commands jumps back 4 hours after a few minutes.  I have both a tcpdump pcap for the input UDP traffic as well as the HEC debug file that shows this.
[2020-08-28-hec-shortened.zip](https://github.com/splunk/splunk-connect-for-syslog/files/5163668/2020-08-28-hec-shortened.zip)
[cisco-asa-input.log-shortened.zip](https://github.com/splunk/splunk-connect-for-syslog/files/5163802/cisco-asa-input.log-shortened.zip)

In the hec log, between line 126,611 and 126,612, the time stamp jumps back 4 hours.  This corresponds to packets 126,611 and 126,612 in the pcap file.

**Comment by mbonsack** [comment]
The critical thing to ascertain here is what the incoming UDP packets' timestamps are compared to the sc4s _server's_ reality.  As soon as the incoming timestamps (at 3600 second boundaries) varies 30s plus or minus from the _server_ timestamp, the `guess-timezone` algorithm will drop out and your events will hop back four hours (as expected).

**Comment by mbonsack** [comment]
Best way to troubleshoot this is write and use a template that emits both `S_UNIXTME` and `R_UNIXTIME` and compare them.  You will undoubtedly find that when your events pop back four hours, the difference between those two integers is > 30.
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.23/administration-guide/62#TOPIC-1268641

**Comment by mbonsack** [comment]
Ensure that your VM (or wherever you are running sc4s) is sync'd and within seconds of the device time and it doesn't drift.  This looks to me like VM clock drift of some sort...

**Comment by kwagner001** [comment]
The clocks on both the appliance and SC4S VM are synchronized with NTP.  I've check the time with ntpupdate and it is not more than a few milliseconds off from NTP time.   

When I look at the times on the pcap file, there is less than a second between the UDP packets in the area where the problem occurred.  While that's the receive time of the packet, I don't see any delays in the inter-packet gap.

**Comment by themrkeys** [comment]
Please confirm fixed in current release

**Comment by bpenn-splunk** [comment]
We are seeing this problem currently where the ASA data timestamps look correct but are showing up as being 4 hours behind, any idea? I (Bruce Penn) am working with the customer and can't seem to figure it out.
