### ISSUE TITLE
Ubiquiti Firewall Logs (ACL Logs) Not Being Assigned Correct Sourcetype

### ISSUE THREAD

**Issue by drewchurch** [splunk/splunk-connect-for-syslog#705]
After following the docs instructions, Ubiquiti Firewall logs are not assigned the correct sourcetype. Changing the filter (`f_ubiquiti_unifi_fw`) did not have the intended effect.

Sample events here: [unifi_security_gateway_raw_events_20200910.txt](https://github.com/splunk/splunk-connect-for-syslog/files/5204667/unifi_security_gateway_raw_events_20200910.txt)

![image](https://user-images.githubusercontent.com/56129551/92806623-050ed900-f36f-11ea-9071-a183c286568e.png)

**Comment by rfaircloth-splunk** [comment]
resolved #1018
