### ISSUE TITLE
/opt/sc4s/local/context does not exist

### ISSUE THREAD

**Issue by haidangwa** [splunk/splunk-connect-for-syslog#714]
In v1.33.0, /opt/sc4s/local/context does not exist. Configuration is podman+redhat8. SC4S v1.32.0 under the same deployment produces this directory.

```
       [2020-09-15T00:55:16+00:00] FATAL: Chef::Exceptions::EnclosingDirectoryDoesNotExist: template[/opt/sc4s/local/context/splunk_metadata.csv] (etech_sc4s::default line 182) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /opt/sc4s/local/context does not exist.
```

**Comment by rfaircloth-splunk** [comment]
can you tell me more about how you got here, we don't specifically have context around what chef is doing here, can you reproduce using a setup created as described in our docs?

**Comment by haidangwa** [comment]
@rfaircloth-splunk this is after the deployment of sc4s in podman on redhat 8. We had previously been running v1.32.0 in this same way with no issue.

**Comment by haidangwa** [comment]
@rfaircloth-splunk 1.33.5 was not tagged in Docker Hub when I initially reported this bug, which is why I reported it under v1.33.0. This bug doesn't exist in 1.33.5 (with no changes to my chef recipe), however, there's a new bug and I reported that in #725 .
