### ISSUE TITLE
Request: Support Cisco Meeting Server (Videoconferencing solution)

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#736]
Hi,

I would like to suggest supporting Cisco's CMS as a syslog source. The syslog format is explained in this post:
[CMS Syslog examples](https://community.cisco.com/t5/collaboration-voice-and-video/cms-syslog-message-examples/ta-p/3166717)

It's one of the more prevalent video conferencing solutions. 

The link I attached is a bit old, before an external syslog server could be configured. However, in the latest versions you can configure an external server whether TCP or UDP:
[https://www.cisco.com/c/dam/en/us/td/docs/conferencing/ciscoMeetingServer/Reference_Guides/Version-3-0/Cisco-Meeting-Server-MMP-Command-Reference-3-0.pdf](url)

**Comment by rfaircloth-splunk** [comment]
Is there a TA we should be compatible with?

**Comment by perditi0nspam** [comment]
No TA as far as I can tell

**Comment by perditi0nspam** [comment]
Hello, is there any news regarding CMS support for SC4S?
