### ISSUE TITLE
Feature Request: Support timezone in contextual data 

### ISSUE THREAD

**Issue by w3ttr3y** [splunk/splunk-connect-for-syslog#741]
I honestly don't know if this is a good idea or not, but I've recently been fighting date/time parsing issues and we had some issues with rfc3164 date/times not parsing correctly due to them being in local time -- Yes that should be detected correctly, and I'll follow-up separately.  When you have a production issue, its nice to have quick fixes so when I came across this, I thought it could make a good option for a quick fix:

> If you have lots of clients that do not send timezone information in the log messages, you can create a database file that stores the timezone of the clients, and feed this data to syslog-ng OSE using the add-contextual-data() feature. For details, see  Adding metadata from an external file.

from: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.24/administration-guide/template-and-rewrite-format-modify-and-manipulate-log-messages/modifying-messages-using-rewrite-rules/rewrite-the-timezone-of-a-message/ under fix-time-zone

Again, I don't know this is a good idea, but it seemed interesting so I wanted to raise it for consideration.  If some one knows better than I and its a bad idea, than obviously please listen to them.

**Comment by rfaircloth-splunk** [comment]
Many log sources use an ambiguous shorthand with 3 letter codes cisco is one of them RFC3164 is not a standard is a memo of sorts "things we can't unsee" for RFC3164 the best practice is use UTC while RFC5424 allows for correct offset specification. There is no good answer here there just might be ways we can help make it somewhat less painful this is under strong consideration the best solution has not yet become clear

**Comment by rfaircloth-splunk** [comment]
This can be done now https://splunk-connect-for-syslog.readthedocs.io/en/latest/configuration/#change-by-host-or-subnet-match
