### ISSUE TITLE
Feature Request: "rawmsg" field in splunk (sc4s_syslog_rawmsg or just sc4s_rawmsg)

### ISSUE THREAD

**Issue by w3ttr3y** [splunk/splunk-connect-for-syslog#742]
I really appreciate the option of RAWMSG as documented on the troubleshooting resources (https://splunk-connect-for-syslog.readthedocs.io/en/master/troubleshooting/troubleshoot_resources/). 

The problem is to have that come across to Splunk, you have to change the format to JSON.  When you are running in production and have production alerts and suddenly 1% of your traffic is having parsing issues, its a hard sell to say you need to change the format coming into Splunk.  At the same time, writing it to a separate file is hard because you're looking for a needle in a haystack and that needle can be spread over a number of servers; if only we had a data aggregation system with good searching. So we could bring that data into Splunk separately, but what about logging an additional field like sc4s_syslog_rawmsg.  This would allow validation and troubleshooting.

The obvious downside is it would increase the size of a message having bandwidth and storage considerations, so it would be nice to be able to enable on a log path by log path basis.  I think having a global option would be beneficial as some places may decide the cost is worth it if it means they have an easier time troubleshooting.  For example, when something suddenly breaks, it would be nice to compare the on the wire protocol and know if it was somethign in syslog-ng and/or Splunk (which _raw should help differentiate between the two) or if it was something upstream that caused the issue.

This could also be interesting as it would make it easier for end users to supply the developers with raw data that could then be could be used for regression testing etc.

Yes, I am asking to increase overhead, but my hope is the value of helping mature data processing and being able to more quickly address issues will justify that cost.

**Comment by rfaircloth-splunk** [comment]
this is one of the broader problems of tracing vs logging we have been thinking about one possible choice would be a duplicate something like sc4s:trace that would not alter the normal log path but could go into a short retention index for diag use turned on and off as needed what do you think?

**Comment by rfaircloth-splunk** [comment]
v2 now has more effecient use of rawmsg. All non  RFC5424 events will retain rawmsg
