### ISSUE TITLE
Does SC4S support Syslog-NG Premium Edition?

### ISSUE THREAD

**Issue by lowell80** [splunk/splunk-connect-for-syslog#755]
Has anyone attempted to run syslog-ng PE on the splunk connect for syslog?  I'm looking at this as an option for a client, and they currently have a support contract for Syslog-ng and they are curious if this is possible or not.  

So I'm curious if:

1. Has anyone done this with SC4S?
2. if so, how difficult was this to setup? 
3. Would this configuration make it more difficult to support here if something goes wrong at the container configuration layer?

Thanks!

**Comment by rfaircloth-splunk** [comment]
We could not use Premium in an open-source product for license reasons, a key difference when I last looked was behaviors in the http output plugin there may be others. For our purposes, the premium doesn't offer specific advantages. 

You could use the BYOE method and make appropriate modifications (whatever those may be) for premium if something support was needed it would have to be something we could re-create with OSE alone more burden on you as the user/customer to identify what is an upstream problem, on the plus side you would have some support obligation from the developer on that not just us. Also unless you build your own container premium would need to be installed on the OS it would not be containerized

**Comment by lowell80** [comment]
Okay, thanks for the feedback, Ryan.  I figured this was not likely to be a support configuration option for SC4S.  My general feeling is that, unless you just really need to click the _I have commercial support_ checkbox, then sticking with OSE seems more likely to "just work" and be less painful than jerry-rigging SC4S to work with PE.  Is that a fair conclusion?

I just wanted to make sure I wasn't some SC4S PE fork that I was missing, or a container built-time switch, ... ;-)

Thanks again for your consideration

**Comment by rfaircloth-splunk** [comment]
If you are a Splunk Customer and using the container you can check the I have support box as this is Splunk supported
