### ISSUE TITLE
Running as non root user

### ISSUE THREAD

**Issue by rsisson-splunk** [splunk/splunk-connect-for-syslog#815]
The following contain several issues encountered when trying to run SC4S as non Root user on RHEL.  These can all be address by document updates.  Please feel free to reach out on Slack or email

- This will not work on RHEL 7.6 - this requires that the user actually log in.  sudo su sc4s is not sufficient to run podman locally.  I don't know if this is worth commenting as it is not a supported OS.

- The podman instructions say to use container tools 1.0,  you require container tools 2.0
sudo yum module enable -y container-tools:2.0
sudo yum module install -y container-tools:2.0

- Environment Variables in env_file need to be set for default listening port:
`PLUNK_HEC_URL=https://http-inputs-xxxx.splunkcloud.com:443
SPLUNK_HEC_TOKEN=A……..84292
#Uncomment the following line if using untrusted SSL certificates
#SC4S_DEST_SPLUNK_HEC_TLS_VERIFY=no
# changing default ports to allow for non-root user
SC4S_LISTEN_DEFAULT_TCP_PORT=5515
SC4S_LISTEN_DEFAULT_UDP_PORT=5515
SC4S_LISTEN_DEFAULT_6587_PORT=5601
SC4S_LISTEN_DEFAULT_TLS_PORT=6514
#change disk buffer location to /apps/sc4s
SC4S_DEST_SPLUNK_HEC_DEFAULT_DISKBUFF_DIR=/apps/sc4s/storage/volumes`

- Podman wants to store images in ~/.local  - this may not be the desired location (in my case there was only 1GB allocated /home).  I believe this can be addressed by podman --root, but I did it by modifying the storage.conf file in my home folder (/home/sc4s/.config/storage/storage.conf)   I modified the storage location to read
graphroot = "/apps/sc4s/.local/share/containers/storage"

podman created the .config folder when it first download the image.

- Make sure that sc4s has ownership of all the folders needed - chown -R sc4s:sc4s /apps/sc4s

- The sample unit file has a ExecPreStart command: 
ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment SC4SHOST=$(hostname -s)"
That will fail as non root user (cannot run systemctl). 
I commented it out and changed the ExecStart command -e line as follows:
e "SC4S_CONTAINER_HOST=myserverhostname" \

I confirmed proper operation by entering container and performing a printenv command.

**Comment by rjha-splunk** [comment]
The non root documentation is updated recently, we are working on making it better.
