### ISSUE TITLE
SC4S container is looking up "SPLUNK_HEC_URL" literally instead of the value of that variable

### ISSUE THREAD

**Issue by graememeyer** [splunk/splunk-connect-for-syslog#829]
I've been fighting with this all day - no value or modification of the "SPLUNK_HEC_URL" env variable in `/opt/sc4s/env_file` makes any difference - the container always looks up "SPLUNK_HEC_URL" as a dns name literally instead of whatever value you set.

![image](https://user-images.githubusercontent.com/3931530/98244505-7af68180-1f67-11eb-9ef4-bb028451d383.png)

If I had to guess, I would say this commit was bad: a1d3ace6f7cc1e89957b21a1f9f38538ee3c985a

**Comment by graememeyer** [comment]
Additional: I'm using Docker CE instructions on Fedora 31 host. I've tried modifying every combination of IP and DNS settings, specifying manual hosts entries etc. 

The clincher was creating this manual host entry caused it to start working (sending data to the correct machine):

```
192.168.11.143 SPLUNK_HEC_URL
```

**Comment by rfaircloth-splunk** [comment]
The incorrect DNS lookup should be resolve in v1.40.3 an unrelated issue was resolved in 1.40.10
