### ISSUE TITLE
Graylog, ELK, Others SIEM

### ISSUE THREAD

**Issue by b4b857f6ee** [splunk/splunk-connect-for-syslog#850]
Hello,

I have scroll the solution and the issue.
This solution is only made for Splunk or some people already use it to make it work with Graylog etc..?

Thank you :)

**Comment by rfaircloth-splunk** [comment]
Our primary goal is supporting Splunk users but all syslog-ng config is available you can add additional destinations and use the ALT dest constructs as we describe in docs
