### ISSUE TITLE
document changes between releases needed

### ISSUE THREAD

**Issue by haidangwa** [splunk/splunk-connect-for-syslog#855]
It's been hard to identify the changes between each stable release. It would be a great benefit to us when we're deciding what versions to bring into our environment when we know what the changes are. A simple summary of changes in a `CHANGELOG.md` in this repo would be great.

**Comment by rfaircloth-splunk** [comment]
We have recently seen some issue with the process automation for this normally speaking the release page has the changes see example here. I am testing a new solution for this challange to roll out in the near release
https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v1.40.2-alpha.1

**Comment by rfaircloth-splunk** [comment]
@haidangwa @mbonsack @mkarlstrand-splunk @nandinivij 
Feedback on the result of the enhanced release notes process please
example output
https://github.com/splunk/splunk-connect-for-syslog/releases/tag/v1.41.1

**Comment by haidangwa** [comment]
Yes, I think that's a big improvement over the previous format.
