### ISSUE TITLE
SC4S does not support customizied HEC endpoints

### ISSUE THREAD

**Issue by jovezhong** [splunk/splunk-connect-for-syslog#867]
We are building a new data service in the Splunk Cloud. The HEC URL is something like this 
`https://api.service-name.splunk.com/<tenant>/ingest/v1beta2/event `

When configuring SC4S, supplying this ingest URL to the SPLUNK_HEC_URL variable

leads to the entrypoint.sh script wrongly parsing the URL to 
`https://api.service-name.splunk.com/services/collector/event `

This causes the SC4S entrypoint script to fail when it attempts to send sample syslog events to the HEC endpoint, since the URL no longer contains a reference to the tenant.

Relevant code in SC4S that parses / manipulates the URL: https://github.com/splunk/splunk-connect-for-syslog/blob/571601465ed9c2fac39c106f90530f199d381fec/package/sbin/entrypoint.sh#L110

**Comment by rfaircloth-splunk** [comment]
The end result of this was no change required
