### ISSUE TITLE
f_nix_syslog misses programs/MSGHDR with brackets and certain characters

### ISSUE THREAD

**Issue by thamlakwis** [splunk/splunk-connect-for-syslog#878]
Sorry if this is inappropriate to report here.

From AIX hosts we get messages that fall into sc4s:fallback.

We get: "PROGRAM: run-parts(/etc/cron.hourly)" and "LEGACY_MSGHDR: run-parts(/etc/cron.hourly)[2569"

Looking at syslog-ng/conf.d/conflib/_common/f_os.conf, I think the filters for program() and LEGACY_MSGHDR are missing brackets, dots (and LEGACY_MSGHDR slashes) in the matcher-regex.

This is just an assumption. While I can edit /etc/conf.d/conflib/_common/f_os.conf in the container, it is recreated each start. I could not find a way to "override" that filter from outside the container. Is there a way?

**Comment by thamlakwis** [comment]
Here are a few RAWMSG from the failed messages (had to obscure our domain there):
<30>Dec 11 11:53:48 HMC19 sssd[nss][706970]: Starting up
<30>Dec 11 11:53:48 HMC19 sssd[be[XXXXXXX.XXXXXXX]][19835]: Shutting down (status = 0)
<30>Dec 11 11:53:48 HMC19 sssd[pam][706971]: Starting up
<30>Dec 11 11:53:48 HMC19 sssd[pam][19837]: Shutting down (status = 0)
<30>Dec 11 11:53:48 HMC19 sssd[be[XXXXXXX.XXXXXXX]][706969]: Starting up

The AIX server has received a patch, before that I also saw "run-parts(/etc/cron.hourly)[2568" and the like, but I only enabled RAWMSG after the patch, now run-parts has a parseable format...

**Comment by rfaircloth-splunk** [comment]
I retested on 1.72.0 these now parse correctly
![image](https://user-images.githubusercontent.com/35384120/114735201-f2002500-9d12-11eb-825f-49fe4d145321.png)
