### ISSUE TITLE
Feature request: Windows Event Collection (part of Syslog-ng)

### ISSUE THREAD

**Issue by perditi0nspam** [splunk/splunk-connect-for-syslog#889]
At present, centralized WEC requires each Windows node to send to a Windows server and installing a Splunk UF there to read the eventlogs. This is then sent to the indexers. It would be more resilient and require less resources if WEC could be performed directly by SC4S. See:

[Syslog-ng WEC administration guide](https://support.oneidentity.com/technical-documents/syslog-ng-premium-edition/7.0.20/windows-event-collector-administration-guide)

If there is some licensing issue of using a Syslog-ng PE feature, then maybe this can be implemented independantly for SC4S? Keep in mind that eventlogs are crucial for pretty much any Windows logging.

**Comment by rfaircloth-splunk** [comment]
I believe the Syslog agent is licensed in addition to PE not part of PE. Presently our implementation wraps OSE only as we don't have access to the PE code for testing. I will see if we can change this in the future.
