### ISSUE TITLE
fgt_event not picking up "DNS query timeout" messages

### ISSUE THREAD

**Issue by thamlakwis** [splunk/splunk-connect-for-syslog#967]
Hi there,

some of our Fortinet messages are tagged as sc4s:fallback while the other system messages are correctly detected as fgt_event.

So far, they all look like this (RAWMSG from event, just "anonymized" while keeping the format) :

<187>date=2021-02-05 time=09:21:47 devname="FW-ABC-DEF-01-FG1" devid="FGT1AB1234567898" logid="1501054200" type="dns" subtype="dns-response" level="error" vd="root" eventtime=1612513307 policyid=0 sessionid=0 srcport=0 srcintf=unknown-0 srcintfrole="undefined" dstip=111.22.3.44 dstport=53 dstintf=unknown-0 dstintfrole="undefined" proto=17 xid=0 qname="directregistration.fortinet.com" qtype="A" qtypeval=1 qclass="IN" msg="A DNS resolution error occurs" action="pass" error="DNS query timeout"

We are on sc4s V1.51.0

**Comment by mbonsack** [comment]
Can you post a raw event of a _working_ fortigate event?  It appears the DNS ones do not have the requisite syslog header (which includes a date/timestamp and host), for which we test on ingest:
`<111> Aug 17 00:00:00 fortigate date=2015-08-11 time=19:19:43 devname=Nosey...`

**Comment by thamlakwis** [comment]
Thanks for the answer! I hope this is helpful, I am just starting with SC4S:

Failed (sourcetype = sc4s:fallback):
<187>date=2021-02-08 time=07:37:02 devname="FW-ABC-DEF-01-FG1" devid="FGT1AB1234567890" logid="1501054200" type="dns" subtype="dns-response" level="error" vd="root" eventtime=1612766222 policyid=0 sessionid=0 srcport=0 srcintf=unknown-0 srcintfrole="undefined" dstip=111.22.3.44 dstport=53 dstintf=unknown-0 dstintfrole="undefined" proto=17 xid=0 qname="directregistration.fortinet.com" qtype="A" qtypeval=1 qclass="IN" msg="A DNS resolution error occurs" action="pass" error="DNS query timeout"

Working (sourcetype = fgt_event):
<189>date=2021-02-08 time=07:44:53 devname="FW-ABC-DEF-01-FG1" devid="FGT1AB1234567890" logid="0100032011" type="event" subtype="system" level="notice" vd="VD-ABC-DE01" eventtime=1612766693 logdesc="Disk log rolled" action="roll-log" reason="file-size" log="tlog" msg="Disk log has rolled."

I see a difference in severity and the "type" flag is different.

**Comment by rfaircloth-splunk** [comment]
This issue is resolved in develop by pr #1018 
![image](https://user-images.githubusercontent.com/35384120/110535342-2407e100-80ee-11eb-85ae-f25f89f290e1.png)
