### ISSUE TITLE
Ubiquiti AP Logs coming through with ':' after ever two characters. 

### ISSUE THREAD

**Issue by satellite-no** [splunk/splunk-connect-for-syslog#977]
Events for Ubiquiti AP's are coming through with a colon after every two characters. 

<img width="989" alt="Screen Shot 2021-02-12 at 10 02 52 PM" src="https://user-images.githubusercontent.com/6953914/107840117-1759cc80-6d7e-11eb-92f7-541c08c8b1c0.png">

**Comment by mbonsack** [comment]
Can you post an "on the wire" (including the leading <PRI> string) for one of these events?  This is best obtained with `tcpdump`.  Thanks!

**Comment by satellite-no** [comment]
No problem, To be specific this is an issue with the AP logs.  Below is a screenshot of how the event looks in in Splunk, how it looks in ASCII and the onthe wire log.

![image](https://user-images.githubusercontent.com/6953914/107865065-074ef500-6e31-11eb-8dd5-b468c1405fc3.png)

UnifiAP.MyBeda.com.45457 > sc4s.mybeda.com.syslog: SYSLOG, length: 273
	Facility user (1), Severity info (6)
	Msg: Feb 13 19:19:26 U7PG2,788a205c68ab,v4.3.28.11361: : stahtd[1989]: [STA-TRACKER].stahtd_dump_event(): {"message_type":"STA_ASSOC_TRACKER","vap":"ath2","mac":"ac:63:be:10:37:7a","event_type":"fixup","assoc_status":"0","auth_ts":"0.0","event_id":"1","dns_resp_seen":"yes"}

<14>Feb.13.19:19:26.U7PG2,788a205c68ab,v4.3.28.11361:.:.stahtd[1989]:.[STA-TRACKER].stahtd_dump_event():.{"message_type":"STA_ASSOC_TRACKER","vap":"ath2","mac":"ac:63:be:10:37:7a","event_type":"fixup","assoc_status":"0","auth_ts":"0.0","event_id":"1","dns_resp_seen":"yes"}

**Comment by mbonsack** [comment]
This message parse just fine for me:
![image](https://user-images.githubusercontent.com/20247946/107866211-19c23200-6e23-11eb-886c-1e62d026033b.png)

**Comment by satellite-no** [comment]
Hmm, interesting so I disabled my TA-Ubiquiti which fixed the issue, enabled and it started happening again.  So it appears SC4S is not compatible with this TA which is required for CIM compliance.  I'm guessing this is because I'm using an all-in-one instance and the TA is applying index time extracts to the events and if this was a distributed environment it would not be an issue however nonetheless this is still a bug.

Note, there is an error in the docs at the very bottom the search provided for "validation" is for a different source type. 
https://splunk-connect-for-syslog.readthedocs.io/en/master/sources/Ubiquiti/

**Comment by mbonsack** [comment]
Is it this TA?
https://splunkbase.splunk.com/app/4107/
If so, I know the author personally and we can get it sorted :-)  In general, we attempt to deliver to the TA a message that is compatible.  In this case, the parsed message in Splunk without the TA looks legitimate, so we'll need to take a look at what the TA is doing to munge that event.

**Comment by satellite-no** [comment]
Cool! Upon investigation it is just a coincidence on how SC4S delivers the message and this SED line `SEDCMD-ap_mac = s/(\w{2})(?=\w+)/\1:/g` in the TA's default props.conf for wireless.  I think altering the regex for compatibility with what is delivered from SC4S fixes the issue.  Guess there is just a slight difference between how the message looks in a traditional syslog monitor file and what SC4S sends to HEC. 

FYI, your expert 4 part blog is what finally got me to dive deeper into sc4s.

**Comment by mbonsack** [comment]
Awesome, glad it was helpful!  So -- the TA you altered -- is it the one I referenced above?

**Comment by satellite-no** [comment]
Yes, it is the TA referenced above and below.  Thanks for the help in figuring this all out. 

https://splunkbase.splunk.com/app/4107/

**Comment by mbonsack** [comment]
Working with TA author to ensure compliance with SC4S.
