### ISSUE TITLE
splunk-connect-for-syslog/docs/sources/Citrix/index.md Documentation Error

### ISSUE THREAD

**Issue by RudeDog69** [splunk/splunk-connect-for-syslog#992]
Hey all.
There is a bug in the documentation or the code, cant figure out which.
splunk-connect-for-syslog/docs/sources/Citrix/index.md

SC4S_SOURCE_CITRIX_NETSCALER_USEALT_DATE_FORMAT is what is at issue.

If you have valid date: 02/23/2021:22:02:59 GMT
and a setting of: SC4S_SOURCE_CITRIX_NETSCALER_USEALT_DATE_FORMAT=no

An error is given: sc4s_error: dtparse: Expected: %d/%m/%Y:%H:%M:%S; Actual: 02/23/2021:22:02:59

If I set SC4S_SOURCE_CITRIX_NETSCALER_USEALT_DATE_FORMAT=yes error is gone.

The documentation 

SC4S_SOURCE_CITRIX_NETSCALER_USEALT_DATE_FORMAT | no | Use "DDMMYYYY" format rather than "MMDDYYYY"

According to the doc this should mean that default is no - use MMDDYYYY and yes is use DDMMYYY
It is the opposite no appears to mean use DDMMYYY

The wording "rather" should probably be changed to default= and alternate=

Thanks,
Rudy

**Comment by rfaircloth-splunk** [comment]
this option was remove the data logic is now automatic
