### ISSUE TITLE
Feature request: Filter for Spectracom NTP logs

### ISSUE THREAD

**Issue by altusayres** [splunk/splunk-connect-for-syslog#998]
request to add Spectracom NTP logs as a source in SC4S. I have attached sample events and removed the IP address and replaced it with x.x.x.x

[Spectracom sample event.xlsx](https://github.com/splunk/splunk-connect-for-syslog/files/6065389/Spectracom.sample.event.xlsx)

**Comment by rfaircloth-splunk** [comment]
Thanks this looks easy but I do need to get a couple of samples from the wire, identifiers can be masked. Can you send a few events to sc4s as is
http://manuals.spectracom.com/SS/Content/NC_and_SS/Com/Topics/OPRTN/Logs_Remote%20Servers.htm
and include an export from splunk

**Comment by altusayres** [comment]
Hey Ryan

please see some tcpdump events below, the devices have not been pointed to a sc4s yet, still only using normal syslog-ng
[ntp tcpdump.txt](https://github.com/splunk/splunk-connect-for-syslog/files/6179252/ntp.tcpdump.txt)

I have removed sensitive ip's and replaced them with descriptions in " "

**Comment by rfaircloth-splunk** [comment]
thanks it looks like this is getting mutated by the lb, can we get the pcap in the outside of the lb. a actual pcap is best it can be attached to a support case to keep it secure

**Comment by altusayres** [comment]
Hi Ryan

thanks, so pcap before the traffic hits the LB right?
________________________________

**Comment by altusayres** [comment]
Hi Ryan

Please see attached pcap file


[pcap_ntp_elab.zip](https://github.com/splunk/splunk-connect-for-syslog/files/6268120/pcap_ntp_elab.zip)

**Comment by rfaircloth-splunk** [comment]
thanks on it
